### ISSUE TITLE
upgrade to draft-06 JSON schema

### ISSUE THREAD

**Issue by bkmartinjr** [HumanCellAtlas/metadata-schema#1]
Latest schema spec (this year) is draft-06.   Suggest upgrading to:
`"$schema": "http://json-schema.org/draft-06/schema#"`

**Comment by lauraclarke** [comment]
For more info on the differences between v4 and v6 see

http://json-schema.org/draft-06/json-schema-migration-faq.htm

**Comment by bkmartinjr** [comment]
dead link - I think you want:  http://json-schema.org/draft-06/json-schema-migration-faq.html

**Comment by dosumis** [comment]
Still using version 4 checker right now (Standard python jsonschema doesn't yet support v6).   Looks like a javascript (node js) lib might be best option for v6 at present: https://github.com/epoberezkin/ajv

**Comment by daniwelter** [comment]
This requires upgrading to the javascript schema validator that is able to cope with draft-06. Includes updating id field in all schemas to $id.

**Comment by lauraclarke** [comment]
Does this need to be retitled to draft 7

**Comment by malloryfreeberg** [comment]
We should close this issue and open a new issue about migrating to draft-07. It would be good for historical reasons to keep the topics separate. I can do that now.
