### ISSUE TITLE
Switch to using pre-commit package for running linter and doc builder

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#1006]
**Description**

 

As a DCP member who makes metadata schemas, I would like to use the
 [`pre-commit`](https://pre-commit.com/) package rather than relying on the git hooks in order to automate running the schema linter. An example could be found [here](https://github.com/HumanCellAtlas/pipeline-tools/blob/master/.pre-commit-config.yaml).

Thanks @rexwangcc !

**Acceptance Criteria**

  
- [x] schema linter running using pre-commit package
- [x] doc builder running using pre-commit package

**Comment by ESapenaVentura** [comment]
I'll take care of this!
