### ISSUE TITLE
Travis build to check if release_prepare script has been run when pushing to develop.

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#1022]
**Description**

As a member of the HCA data wrangling team, I would like to add an optional step in the travis build that checks if `prepare_release.py` script has been run before pushing from a branch into develop. This will help avoid some human error when pushing schema changes.

**This is not a replacement of the script. The script will still have to be manually run, this is just an extra automatic test.**
 

**Acceptance Criteria**

 
- [ ] Create a simple script that checks if update log is empty before pushing into develop
- [ ] Update documentation in the repository to showcase this update.

**Comment by ESapenaVentura** [comment]
@HumanCellAtlas/wranglers @daniwelter Do you think this is a good idea? Might avoid some overlooks  that could happen (Not looking at myself at all 👀 )

**Comment by daniwelter** [comment]
I know where you're coming from with this but I'm not sure this is a very practical idea. The update log file may be empty for a number of reasons, including a failed release prepare script. If you're going to do this work anyway, I would look at a more fully fledged solution.

**Comment by malloryfreeberg** [comment]
I can think of the following checks related to making sure someone ran the `release_prepare.py` script:
1. If a schema has been updated, then versions.json should be updated
1. If a schema has been updated, then changelog.md has been updated
1. If a schema has been updated, then update_log.csv should be empty

There could also be a check added to the `release_prepare.py` script itself that it exits with no errors. As @daniwelter said, the `release_prepare.py` script could fail before it finishes, and currently this type of failure doesn't produce a warning or error.

**Comment by malloryfreeberg** [comment]
Some of this work overlaps https://github.com/HumanCellAtlas/metadata-schema/issues/948

**Comment by zperova** [comment]
Need to revisit @ESapenaVentura
