### ISSUE TITLE
Bug in schema linter

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#1024]
**Give the bug a title**

`schema_linter.py` throws a KeyError if  no "DescribedBy" property is found inside a schema.

**To reproduce**

 

1. Go to any of schemas (e.g., `biomaterial_core`)
1. Change name of property `describedBy` with any other thing
1. Run `src/schema_linter.py`

**Schema versions**

This is a problem with the linter.

**Observed behavior**

The script exits due to raising "KeyError" when `describedBy` property is not found within the schema

**Expected behavior**

 
It should append the error to the `errors` list object and print it at the end, with all the errors.

**How to fix it**

Add `if "describedBy" in schema and` to line 77 of the linter.

**Comment by ESapenaVentura** [comment]
I'll proceed to make the PR if there is no objection!

**Comment by malloryfreeberg** [comment]
If it's in line with this sprint's priorities and there aren't more urgent things to do, then go ahead.
