### ISSUE TITLE
Improve metadata standard

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#1027]
This Epic will track updates to the metadata standard (schema).

Updates could be in response to data contributors (e.g. adding a new field), data consumers (e.g. standardizing a field using an ontology), or to generally improve the standard (e.g. replacing an enum with an ontology, adding examples and guidelines to fields).

Some tickets in this Epic might also be linked to specific Epics like "Support ingesting imaging data".

**Comment by malloryfreeberg** [comment]
@lauraclarke 

The following tickets linked to this Epic constitute major schema changes:

Icebox:
#367 
#382 
#386 
#389 

Product backlog:
#1001 
#1047 
#883 
#884 
#900 
#976 
#999 

Sprint backlog:
#812 (last bullet point - should probably go back into the product backlog)

**Comment by ESapenaVentura** [comment]
Closing this ticket as we really never used it. Once we have a full, approved list of metadata schema updates we may want to open a similar epic.
