### ISSUE TITLE
Capturing multiple sets of process metadata on 1 process entity

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#1029]
@malloryfreeberg commented on [Mon Apr 08 2019](https://github.com/HumanCellAtlas/hca-data-wrangling/issues/166)

**Dataset/group this task is for:**

**Description of the task:**

Process metadata needs to be entered in the biomaterial and file tabs of the metadata spreadsheet corresponding to the biomaterial/file that the process generated. There is always a single process entity between every biomaterial and file entity according to the metadata model. A process entity, though, can point to 0 or more protocol entities, each of which might have it's own process metadata.

This leads to an issue where multiple sets of process metadata (associated with implementing different protocols) might need to be represented by the single process entity in the model. How do we do this?

e.g.: The process linking a cell suspension to a sequence file points to a library preparation protocol and a sequencing protocol. The library preparation protocol was carried out by `operators` "ABC" at `location` "Smith Lab", but the sequencing protocol was carried out by `operators` "XYZ" at "Wellcome Sanger Sequencing Core". How would we capture all this metadata in 1 `process.json`?

**Acceptance criteria for the task:**

- [ ] Multiple sets of process metadata can be recorded for a single process.

**Comment by zperova** [comment]
Need to revisit @zperova
