### ISSUE TITLE
Add description check in linter for proper sentences in schema description.

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#1031]
**Description**

 

As a DCP member who works on the metadata schemas and its proper formatting, I would like to add changes in the `schema_linter` script so that it detects schema descriptions that are not well written (e.g, sentence not ending with full stop).

**Acceptance Criteria**

 
- [ ] Add a couple of lines of code to the schema-level checks so that it can identify this issue and throw a warning.

**Comment by malloryfreeberg** [comment]
Can follow the same approach as checking that field description end in a full stop: https://github.com/HumanCellAtlas/metadata-schema/blob/8752b706ac3c96a9a62b4f4d340c20845ebfebc4/src/schema_linter.py#L164-L166
