### ISSUE TITLE
Metadata developers should install pre-commit package

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#1032]
**Description**

 

Anyone who contributes to developing the metadata schema should install the pre-commit hook package ([Webpage](https://pre-commit.com/), can install with pip) on their local repo so the pre-commit hook runs.

**Acceptance Criteria**

  
Metadata developers have confirmed they have the pre-commit package installed
- [x] @daniwelter 
- [x] @malloryfreeberg 
- [x] @ESapenaVentura 
- [x] @zperova 
- [ ] @willrockout 
- [ ] @cjvillar 
- [ ] @diekhans 
- [x] @mshadbolt

**Comment by malloryfreeberg** [comment]
Example installation:
```
cd metadata-schema
pip install pre-commit
pre-commit install
```

Need to be in the top directory of your local metadata-schema repo.

**Comment by zperova** [comment]
running `pip install pre-commit`will gives the following output: 
```[ERROR] Cowardly refusing to install hooks with `core.hooksPath` set.
hint: `git config --unset-all core.hooksPath```
works after running the hint.

**Comment by daniwelter** [comment]
@zperova make sure you're also in the develop branch and your branch is up to date.

**Comment by zperova** [comment]
@willrockout @cjvillar @diekhans
