### ISSUE TITLE
Add full stop to description in schemas.

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#1035]
**For which schema is a change/update being suggested?**

I would like to request some patch changes for the schema descriptions in several schema modules. While updating the schema linter, I realized that the descriptions lack a full stop at the end. 

**What should the change/update be?**

I would like to add a full stop at the end of the schema description of the following ontology schemas:

- `length_unit_ontology.json`: update schema description
- `cell_cycle_ontology.json`: update schema description
- `library_amplification_ontology.json`: update schema description
- `ethnicity_ontology.json`: update schema description
- `cellular_component_ontology.json`: update schema description
- `library_construction_ontology.json`: update schema description
- `process_type_ontology.json`: update schema description
- `sequencing_ontology.json`: update schema description
- `species_ontology.json`: update schema description
- `disease_ontology.json`: update schema description
- `strain_ontology.json`: update schema description
- `enrichment_ontology.json`: update schema description
- `organ_part_ontology.json`: update schema description
- `microscopy_ontology.json`: update schema description
- `time_unit_ontology.json`: update schema description
- `protocol_type_ontology.json`: update schema description
- `development_stage_ontology.json`: update schema description
- `instrument_ontology.json`: update schema description
- `mass_unit_ontology.json`: update schema description
- `biological_macromolecule_ontology.json`: update schema description
- `cell_type_ontology.json`: update schema description
- `analysis_process.json`: update schema description
- `imaging_preparation_protocol.json`: update schema description
- `imaging_protocol.json`: update schema description

**What new field(s) need to be changed/added?**

No new fields needed

**Why is the change requested?**

This change is requested to adhere to the style guide.

EDIT: Added more schemas to ticket.
EDIT: Incorporated this issue to epic

**Comment by malloryfreeberg** [comment]
There are a few other schemas that don't have sentences for the schema description:
```
analysis_process.json: The `description` of the schema is not a sentence (Information about the analysis process).
imaging_preparation_protocol.json: The `description` of the schema is not a sentence (Information about the preparation protocol of the imaged specimen used in an imaging experiment).
imaging_protocol.json: The `description` of the schema is not a sentence (Information about the imaging protocol).
```

**Comment by malloryfreeberg** [comment]
@ESapenaVentura can you link this to the Epic about Improving the [metadata standard](https://github.com/HumanCellAtlas/metadata-schema/issues/1027)

**Comment by ESapenaVentura** [comment]
Added the schemas you mentioned! Also, going to link it!
