### ISSUE TITLE
Metadata design principles doesn't discuss graph being the experiment design

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/metadata-schema#1042]
[Overview of Metadata Structure](https://prod.data.humancellatlas.org/metadata/design-principles/structure) doesn't discuss graph being the experiment design.  This has lead to assumptions that the graph is fixed and a failure to appreciate the reasons for the graph.

**Comment by malloryfreeberg** [comment]
This ticket is a request to add an explanation that the graph encodes the experimental design to the Structure doc.
