### ISSUE TITLE
User documentation links to an internal google document

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/metadata-schema#1043]
[Overview of Metadata Structure](https://prod.data.humancellatlas.org/metadata/design-principles/structure) links to a google document [HCA Metadata schema structure specification
](https://docs.google.com/document/d/1pxQj7BfM8HHgD4ilm4dlvZuZATfJkNC5s_-TUoA4lYA/edit?ts=59b16455).

This is inconsistent formating with the other documentation and is not hyperlinked.  It starts with the warning (in red):

> DEVELOP - This is the current “DEVELOP” version of this specification, please use comments or “suggesting” mode only.

Which I would find very confusing and concerning as an end user.

**Comment by malloryfreeberg** [comment]
Consider removing this link or determine whether some other document should be linked to.
