### ISSUE TITLE
Improving the Required Fields document

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#1048]
# Improving the Required Fields document

**Docs Improvement**

This ticket requests some improvements to the [required fields markdown file](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/jsonBrowser/required_fields.md) which is found here and as I understand it, autogenerated at build time 

I would like the file to distinguish between fields the submitter must supply and fields which are autogenerated and fields which are always required and fields which are only required given a certain context (such as mouse, or death)

**Acceptance Criteria**
 
- [ ] A user can tell from the required fields markdown if a field is supplied by the contributor or autogenerated
- [ ] A user can tell from the required fields markdown is a field is always required or if it is only required given a certain context

**Comment by malloryfreeberg** [comment]
For the first acceptance criteria, the only required field that is not supplied by submitters (unless they are programmatic submitters) is `schema_type`. This field is required for all schemas, but the accepted value is different depending on the schema type (e.g. "project", "biomaterial"). We could put in a note every place it exists in the documentation that unless you are submitting programmatically, you don't have to supply this field.

The second acceptance criteria could possibly be met by improving the static text describing what the document contains.

**Comment by zperova** [comment]
revisit @zperova
