### ISSUE TITLE
Split development_stage_ontology into mouse and human stages

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#1054]
**What is the proposed name of the new schema?**

human_development_stage_ontology
mouse_development_stage_ontology

**What field(s) should the new schema contain?**

Same fields as current development_stage_ontology module but with appropriate class restrictions for mouse and human, respectively.

**Why is the new schema needed?**

We currently have a single development stage field in donor_organism, with non-computational rules that HsapDV stages should be used for human and EFO terms for mouse. In order to improve semantic validation, it would be more appropriate to have ontology schemas for the two species and also move the wrapper fields for the development stages into the human- and mouse-specific modules.

**Comment by mckinsel** [comment]
I'm not sure I totally understand what this is proposing. Will it still be possible to do something like `donor_organism["development_stage"]["ontology"]`?

**Comment by zperova** [comment]
@mckinsel no, the proposal here is to replace existing development_stage with human_development_stage and mouse_development_stage and move them into the human_specific and mouse_specific modules respectively. So, in this case, your request will look like:
 donor_organism["human_specific"]["human_development_stage]["ontology"]
 donor_organism["mouse_specific"]["mouse_development_stage]["ontology"]

**Comment by mckinsel** [comment]
That's going to make it kind of difficult to reliably get the development stage then. Right now you can just look it up directly, but with this, I think you need to

1. Figure out the `genus_species` of the donor organism. There is a field for that in the donor organism schema, but it's optional and it's an array, so not quite so straightforward.
2. Figure out how to map from a `species_ontology` to common names like "human" and "mouse". The `species_ontology` gives us NCBITAXON:9606 and "Homo sapiens", for example.
3. See if there's something at `${common_name}_specific.${common_name}_development_stage`
