### ISSUE TITLE
Update release SOP with instructions for when to do dev -> int release

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#1057]
**Description**

 

As a member of the metadata schema update team, I would like have instructions on when to do a develop -> integration schema release so that I am sure schema changes get incorporated into the release cycle as early as possible.

**Acceptance Criteria**

  
- [x] An added section in the release_process.md describing when to do a dev -> integration release.

**Comment by mshadbolt** [comment]
Merged PR and deleted branch so closing ticket.
