### ISSUE TITLE
Implement algorithm to determine delta between two schemas

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/metadata-schema#1067]
Given two versions of a schema of the same type, determine the delta between the two. This work will enable creating dynamic integration (DCP-wide)tests that will test the compatibility of these changes with the entirety of the DCP.

**Comment by ESapenaVentura** [comment]
Could you please elaborate on this request? Do you want all changes to be captured, or only major changes? 

Would it need to capture all changes (1.0.0 --> 1.0.1 --> 2.0.0 --> 2.0.1) or will it be ok just capturing the overall changes (1.0.0 --> 2.0.1)? There might be more than one change for a property, so this should be taken in account.

I'm more than happy to help for a script/function in the metadata library that does this, but we probably need to gather the requirements for this tool.

**Comment by maniarathi** [comment]
Sure! I don't have the exact requirements yet but I'm intending to have as input: 1) the schema, 2) the old version, and 3) the new version. The delta would capture the overall changes between the specified versions.

This is still lower priority for me for now... intending to work on it perhaps starting late next week but can chat earlier if you're interested!

**Comment by maniarathi** [comment]
Closing this. Instead of the delta, simply generate a spreadsheet based on the latest schemas. This will ease up the logic as well as ensure that unchanged items are still tested.
