### ISSUE TITLE
Make the newly populated schema_*_version fields REQUIRED

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/metadata-schema#1068]
After the `schema_major_version` and `schema_minor_version` fields are populated by Ingest and before subscriptions start making use of the fields, make the fields REQUIRED. This will ensure that all data will be accessible by the downstream components; otherwise data will be missed as we start establishing that downstream components must designate which schema versions that are compatible with.

Tasks that will accomplish this ticket:
- [ ] Ensure all future metadata is populated with the `schema_*_version` field.
- [ ] Create and run a script to back-populate all existing metadata to copy the schema versions from `described_by` to `schema_*_version`.

**Comment by maniarathi** [comment]
Since the metadata schema freeze will continue on through Barcelona, this ticket is no longer feasible to complete until October 10th. The completion of this ticket is not required to fulfill the metadata schema integration testing so I'm detaching it from the epic and assigning this to be done in Q4.

**Comment by ESapenaVentura** [comment]
Closing since we have in sight to completely remove these fields
