### ISSUE TITLE
Add two optional fields to metadata schemas

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/metadata-schema#1076]
In order to enable rapid integration of data adhering to changed metadata schemas and in accordance with the design detailed here, https://docs.google.com/document/d/1BInKossmrlpna5MV_s4MSR0Bll1wnD-3OVw-9nCLdWg/edit?ts=5d389d03#, create two additional fields in the metadata schemas: 

"schema_major_version": {
      "description": "The major version number of the schema.",
      "type": "integer",
      "pattern": "^[1-9]\d*$",
      "example": "4"
    },
"schema_minor_version": {
      "description": "The minor version number of the schema.",
      "type": "integer",
      "pattern": "^\d*$",
      "example": "6"
    }

**Comment by willrockout** [comment]
Changes have been merged. Closing this issue.
