### ISSUE TITLE
Version number pattern is too loose

### ISSUE THREAD

**Issue by mccalluc** [HumanCellAtlas/metadata-schema#1090]
**To reproduce**

1. Look at [biomaterial_core.json](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/core/biomaterial/biomaterial_core.json#L21)
1. `[0-9]{1,}.[0-9]{1,}.[0-9]{1,}` is better written as `\d+\.\d+\.\d+`: Most critically, `.` is a wildcard: `\.` is needed.

**Schema versions**

All?

**Observed behavior**

As written, `1X2X3` or `1*2*3` would also match.

**Expected behavior**

only `1.2.3`

**Comment by ESapenaVentura** [comment]
**Schema update**

For `biomaterial_core.json`:
- Change in version number pattern as described above.
- Delete `|` in `indsc_sample_accession` property pattern match
