### ISSUE TITLE
automatically validate that patch version changes conform to SOP

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/metadata-schema#1092]
A patch version change should only be to documentation fields and not impact code.  

Patch changes that impact code could have adverse impacts.

At to appropriate code.

**Comment by ESapenaVentura** [comment]
Hi @diekhans , how could we automatically validate that patch version changes does not impact code?

By definition in our documents, a patch change is `Any change to auxiliary information that does not affect the structure or semantics of the schema itself. Also, any bug fixes to the schema` (Detailed list of what patch changes are [here](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/evolution.md)). 

Also, could you please clarify what do you mean by "documentation fields"? Do you mean fields like "examples" or "guidelines"?
