### ISSUE TITLE
Duplicate "Homo sapiens" and "homo sapiens" tag appears in browser

### ISSUE THREAD

**Issue by adriennes** [HumanCellAtlas/metadata-schema#1098]
In the Data Browser Donor facet, both "Homo sapiens" and "homo sapiens" appear as options

**Comment by claymfischer** [comment]
Thanks @adriennes, good catch!

@ESapenaVentura is assigned this in ticket 279 of the wrangling repo.

**Comment by adriennes** [comment]
Got it, I'll close this one then.
