### ISSUE TITLE
Need a field that indicates tissue, as opposed to patient, is diseased.

### ISSUE THREAD

**Issue by dosumis** [HumanCellAtlas/metadata-schema#11]
This example shows why:

```json
{ "short_label" : "U2OS Cells", 
"long_label" : "Osteosarcoma from the tibia of a 15 year old", 
"uuid" : "5f16b743defc4b5c8717f023f9921069", 
"body_part" : 
	{ "name" : "tibia" }, 
"donor" : 
	{ "id": "U2", 
	"uuid": "a1ef5009045f42e88a0e3db1d1f2b050", 
	"life_stage" : "child", "age": 15, "species": "Homo sapiens" } }
```

Formal metadata makes this sample look like normal body part, rather than a tumor sample!
Asserting that a sample exhibits a disease is distinct from asserting that a patient does.  A sample may come from a normal bone from a patient with osteosarcoma.

This is an action item from the DCP meeting at CZI:
https://docs.google.com/document/d/1w-OKngEuIC0oYEdg_QtaIZFQ8BSAZQIJR3qumSBL_ho/edit#

**Comment by JimKent** [comment]
This is a good idea.  This particular merfish metadata example is not well threshed out though.  In the bits that were better wrangled there would have been a donor.disease at least.  However it is a valid distinction to draw between a person with a disease and a diseased part of a person.

**Comment by dosumis** [comment]
We now have a test dataset that requires this:   a mouse with a tumor originating from an injected cell line.  There are two types of sample from this:  
  1. tumor (requires disease field on sample)
  2. lymph nodes from mouse with tumour

**Comment by JimKent** [comment]
I have to ask - is the cell_line derived from human or mouse?  They do inject human tumor cells into mice sometimes (and for that matter human IPS cells as part of the teratoma assay).  Ah, the life of a SCID mouse.

**Comment by malloryfreeberg** [comment]
Closing this issue. Opened a new issue #168 to address the last two comments in this thread (which are a different topic).
