### ISSUE TITLE
ErrorType URIs do not resolve

### ISSUE THREAD

**Issue by MightyAx** [HumanCellAtlas/metadata-schema#1100]
#Acceptance Criteria
- Have ErrorType URIs resolve to web pages with more information about the error.

#More Info
Current errors have these URIs for error types:
- `http://ingest.data.humancellatlas.org/Error`
- `http://importer.ingest.data.humancellatlas.org/Error`
- `http://submission.importer.ingest.data.humancellatlas.org/Error`
- `http://exporter.ingest.data.humancellatlas.org/Error`

These uri's don't go anywhere. We could change the ErrorTypes to go to a webpage that contains info about the error and how to resolve it. This will probably require us to change to types to be:
`http://<component-name>.ingest.dev.data.humancellatlas.org/<ErrorType>`

**Comment by zperova** [comment]
@MightyAx i believe this one does not belong here?

**Comment by MightyAx** [comment]
Apologies, My zenhub client has been making issues against the wrong repository. I'll use GitHub directly in future.
