### ISSUE TITLE
 Remediate Critical lodash vulnerability

### ISSUE THREAD

**Issue by stahiri** [HumanCellAtlas/metadata-schema#1104]
GitHub reports the following **Critical** severity vulnerability in HumanCellAtlas/metadata-schema and HumanCellAtlas/metadata-schema-publisher. Please remediate by the end of Q3 Milestone 3.

### Description
lodash

### Suggested Remediation
Upgrade lodash to version 4.17.13 or later

### Details
Affected versions of lodash are vulnerable to Prototype Pollution. The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload.

**Comment by diekhans** [comment]
@ESapenaVentura,  can you knock out upgrades to get the snyxbot off our back?

**Comment by ESapenaVentura** [comment]
This was already done on August 28th ([PR change](https://github.com/HumanCellAtlas/metadata-schema/pull/1112/files#diff-7b49bc3553619baa6047e85285771321R16)

**Comment by ESapenaVentura** [comment]
This was promoted on metadata-schema on [August 28th](https://github.com/HumanCellAtlas/metadata-schema/pull/1112/files#diff-7b49bc3553619baa6047e85285771321R16). I can't take care of it because I don't have permits to see if the changes break the component but @aaclan-ebi will take care of this.

**Comment by diekhans** [comment]
@aaclan-ebi doesn't appear to be a member of this repo, so I can't assign it to her.

**Comment by Lilalamar** [comment]
@aaclan-ebi Hi Alegria, just checking in-- any update on this?

**Comment by brianraymor** [comment]
Per conversation with @stahiri, this is Q4M3. Updating from Q3M3 which is long past.
