### ISSUE TITLE
Remediate High js-yaml vulnerability

### ISSUE THREAD

**Issue by stahiri** [HumanCellAtlas/metadata-schema#1105]
GitHub reports the following **High** severity vulnerability in HumanCellAtlast/metadata-schema-publisher. Please remediate by the end of Q3 Milestone 3.

### Description
js-yaml

### Suggested Remediation
Upgrade js-yaml to version 3.13.1 or later

### Details
Js-yaml prior to 3.13.1 are vulnerable to Code Injection. The load() function may execute arbitrary code injected through a malicious YAML file.

**Comment by ESapenaVentura** [comment]
I will take on this one for this time but [metadata-schema-publisher](https://github.com/HumanCellAtlas/metadata-schema-publisher)repo is not responsability of the wrangling team. (Also, please create the tickets on the appropriate repo). Thanks!

**Comment by stahiri** [comment]
Hey @ESapenaVentura - sorry about that! Please advise if you'd like me to move this ticket to metadata-schema-publisher now or leave it here given your one-time willingness to take on this ticket (which is much appreciated!).

**Comment by ESapenaVentura** [comment]
No worries! It's hard to keep track of all the repositories and who's responsible for what. I don't think that for this time it would be necessary to duplicate tickets, just keep it in mind if a ticket like this is necessary in the future!

**Comment by ESapenaVentura** [comment]
@aaclan-ebi is going to take over this for me because I have no permits to test if the new version of js-yaml breaks the schema publisher

**Comment by brianraymor** [comment]
Per conversation with @stahiri, this is Q4M3. Updating from Q3M3 which is long past.

**Comment by diekhans** [comment]
@ESapenaVentura , does upgrading the version cause any problems?

**Comment by ESapenaVentura** [comment]
https://github.com/HumanCellAtlas/metadata-schema-publisher/pull/5/files#diff-32607347f8126e6534ebc7ebaec4853dR1659

It's being upgraded, in the process of code review with some other changes

**Comment by ESapenaVentura** [comment]
I think this is already sorted, so I'll proceed to close the issue!
