### ISSUE TITLE
Confirm smartseq 2 fluidgm metadata meets the pipeline teams needs

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#1116]
This ticket is a placeholder to reminder the metadata team to confirm with the pipelines team that our smartseq 2 fluidgm metadata meets their needs

- [x] Contact pipelines team to ask about their perspective
- [x] Confirmed with pipelines team that fluidgm ss2 metadata is sufficient for their pipelines

**Comment by zperova** [comment]
Pipelines team have referenced this in the following PR: https://github.com/HumanCellAtlas/skylab/pull/201

Waiting to hear back on whether any metadata changes are needed.

**Comment by zperova** [comment]
Confirmed by Kylee via Slack.
