### ISSUE TITLE
Explicitly record cDNA metadata

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#1127]
The SCEA tertiary portal has a flexible secondary analysis pipeline that can potentially analyse non 10x/SS2 by feeding cDNA parameters.

These are:

cDNA_read
cDNA_read_offset
cDNA_read_size

HCA does not take these parameters as they can be inferred by hard coded mappings based on the library prep technology e.g. 10x V2 has set values for these fields.

However, as this metadata is not recorded, datasets that the HCA does not yet have pipelines for require some manual inspection prior to secondary analysis. In the future, the HCA may want to use these parameters to guide their analysis or analyse datasets that do not as yet have a pipeline.

P.S.
The same argument can be made for sample fields:

sample_barcode_read
sample_barcode_size
sample_barcode_offset

However since both the SCEA and the HCA only take sample demultiplexed data files these fields may not be needed.

**Comment by lauraclarke** [comment]
@hewgreen it isn't entirely clear to me when these details would be needed? for scRNAseq technologies where it wasn't standard?

What are they used for.

I know there is no plans to start taking fastq files before they are been de'muxed by sample. There are other pooling techniques that the DCP might ultimately need to handle such as sample separation by genetic variation but I don't think we will ever accept non de'muxed by sample fastq

What are the other circumstances this is needed for?
