### ISSUE TITLE
Assessing the tissue fields in the HCA metadata schema

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#1129]
Discussions spurred by the CZI HCA Seed network meetings mean we must assess what fields we use to capture information about human tissue and how it is collected and stored in our metadata standards.

- [x] Compare HCA fields to John Hopkins document (@lauraclarke can email) and provide a summary of present and absent fields to @lauraclarke 
- [x] Create list of currently collected fields and if they are required or optional that we can share with other people looking into best practice around tissue collection and metadata tracking

**Comment by zperova** [comment]
I started the mapping here: https://docs.google.com/spreadsheets/d/1vPKVitrzUlQo6OShaStzSprgJlMzzw9gJ4Wm052El4g/edit#gid=0

**Comment by lauraclarke** [comment]
Thanks for this, before I send it to Marc I have a couple of questions

Was there a reason you suggested the description field for comments and supplementary files for notes? Could they both use the description field?

Is there a reason that autopsy date is not collection date on the autopsy process?

For the rows where you are uncertain, can you add a bit of detail about your uncertainty in the notes field?

I was wondering if it would be good to also send an explanation about protocol/process to make it clear why we have generic fields for things like times, dates and operators

I made clearly correct fields are green and fields where we don't have a mapping at all red

**Comment by zperova** [comment]
@lauraclarke 


> Was there a reason you suggested the description field for comments and supplementary files for notes? Could they both use the description field?

they can both use description field. l understood that "notes" might be longer than "comments" - supplementary files is an option for longer strings of information.

> Is there a reason that autopsy date is not collection date on the autopsy process?

No. Since our relevant metadata fields refer to time, I initially put it in the Time Autopsy completed. In practice they capture both date and time. I updated it in the spreadsheet. 

> For the rows where you are uncertain, can you add a bit of detail about your uncertainty in the notes field?

I added notes. 

> I was wondering if it would be good to also send an explanation about protocol/process to make it clear why we have generic fields for things like times, dates and operators

I added a note to process to have it in the spreadsheet as well.

> I made clearly correct fields are green and fields where we don't have a mapping at all red

Thank you

**Comment by mhalushka** [comment]
[Meta data lists.xlsx](https://github.com/HumanCellAtlas/metadata-schema/files/3633672/Meta.data.lists.xlsx)
I combined data from in house protocols, GTEx's data types, and Anna Maria Storniolo Breast Tissue Repository.  I split the data types into specimen and subject metadata. There are 29 data points for specimen metadata and 59 for subject metadata.  Obviously that is too many for a given project.  However, this list (or a similar list) would be good to get the community's thoughts on with the goal of finding consensus on which of these are A, B, or C level data points.

**Comment by lauraclarke** [comment]
Thanks for the list @mhalushka this is a great list of terms. You can see the work @zperova with your original document here  https://docs.google.com/spreadsheets/d/1vPKVitrzUlQo6OShaStzSprgJlMzzw9gJ4Wm052El4g/edit#gid=0

@zperova Would you be able to do a similar workup with respect to the original autopsy worksheet for this list? I guess adding a new sheet to the spreadsheet above might work?

We should sit down and talk about how to best assess how many of these fields that we currently record do we already information for on our primary tissue samples. There is probably a way to automate that check and get the numbers but not sure what the best way to do that.

**Comment by zperova** [comment]
@lauraclarke I added a new sheet for the other Metadata lists. @mhalushka I would appreciate if you could provide clarifications of some terms for both the Autopsy worksheet and the Metadata lists - these are marked in blue.

**Comment by mhalushka** [comment]
Importantly, not all of these data fields will be useful and some are study-specific. So if something doesn't make sense, it's likely it just won't make sense :).
Research Staff Present: Designed just to keep track of who was in the (autopsy) room when the case was done.  So if anything was forgotten, one might be able to ask someone who was present.  There are no chaperone issues with this particular item.
Charge Resident...:  Same answer as above.  Just to keep track of who was there if questions arise.
Modifiers:  Here are a list of modifiers we used to comment on the sampled pieces of tissue that came from an autopsy.  A lot of this relates to cancer and will not be applicable to the HCA studies.
[Modifiers.xlsx](https://github.com/HumanCellAtlas/metadata-schema/files/3637849/Modifiers.xlsx)

**Comment by zperova** [comment]
@mhalushka thank you for details. We can add Research Staff and Charge Resident in the Contributors tab and indicate their role. Please let me know if anything in the following list matches these roles, if not we can add a term(s): https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009736
For modifiers I can see that some of them relate to organ parts, which we capture, and the other modifiers could be captured in the specimen description field.

**Comment by zperova** [comment]
@mhalushka Thank . you for the info. We can capture the Research Staff present and Charge resident in the Contributors tab. Could you please have a look and chose a term that would best match these roles, if not there we can add a term(s): https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0002012

Contributor's name but not contact details will appear on the Data Browser in the Contributor's secion.

For the Modifiers - I can see that some of them are organ parts which we capture, for the others we can include them in the specimen description field which is a free text.

**Comment by lauraclarke** [comment]
@zperova happy to turn this into another ticket if that is helpful but I now have details from Peter Harrison about how to get the FAANG metadata so we can assess how much the recommended fields are given compared to the optional ones

The rules themselves are here

https://github.com/FAANG/dcc-metadata/tree/master/rulesets

The commands to get the raw metadata are

You can get the FAANG metadata from the API, using the following commands to get all data in one chunk:

Animals: 
curl https://data.faang.org/api/organism/_search/?size=1000000
	
Specimens:
curl -X GET "https://data.faang.org/api/specimen/_search/?size=1000000" -H 'Content-Type: application/json' -d'{"query":{"bool":{ "filter":[{"term":{"standardMet":"FAANG"}}]}}}'

Experiments:
curl -X GET "https://data.faang.org/api/experiment/_search/?size=1000000”

and

[faang_api.txt](https://github.com/HumanCellAtlas/metadata-schema/files/3657435/faang_api.txt)

Can we do a comparision for number of non null values for the different fields (say value, structured null and completely missing) for the three rule types

thanks

**Comment by mhalushka** [comment]
For those positions (Research Staff, Charge Resident), I would drop "Charge Resident" and just add "technician" from the drop down list.  Thanks!  The goal with all of this is to create a set of reasonable datapoints to be collected that the community can decide which ones have value or not.  So if there are things that I have provided that are unlikely to be globally of value, it is easiest enough just to drop those data types.  It would be great if we can get a list out to the community to have them give some opinions on the importance of different data fields.

**Comment by zperova** [comment]
@mhalushka thanks for your comment. I am working on making the list more user-friendly and will have it ready next week.

**Comment by zperova** [comment]
@lauraclarke happy to hear comments on this document. I tried to condense it to be understandable from the data contributor's perspective to clearly indicate the required fields we collect: https://docs.google.com/spreadsheets/d/1fZJsN3vpN7vGb9xhRNdj4nrtorJgPXMUXvAS0l5qPZM/edit#gid=828284694

**Comment by mshadbolt** [comment]
@zperova is it ok to share this doc with other contributors?

**Comment by zperova** [comment]
yes @mshadbolt

**Comment by zperova** [comment]
closing as this issue is done and related tickets linked.
