### ISSUE TITLE
New JSON schema version assessment

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#1130]
The newest version of JSON schema has been released

https://json-schema.org/ 2019-09
https://json-schema.org/draft/2019-09/release-notes.html

These schema changes need to be assessed so we can understand if we should move and on what timeline

**Comment by ESapenaVentura** [comment]
So, I'm doing a deep dive into this. I'm currently reading all the documents, but it will take a while. As far as over-reading the main pages, I get the feeling that there should be no problem moving forward to this version of the schema, aside from the fact that we would have to change the "$schema" to reference the new draft and talk to the ingest devs (Probably @rolando-ebi) about the schema validator (And the whole validation process, as I've realized today I don't have the slightest idea of where it is done and against what or how).

Aside from that, no other component should be affected.

**Comment by ESapenaVentura** [comment]
So, major points to take into consideration before moving:

- Validator will become deprecated, so we will need to make sure that we can create/update/use a validator that is compatible with this version of the schema.
- `definitions` keyword has now become `$defs`, so we need to update this fields:
```
  "definitions": {
               "$ref": "system/links.json#/definitions/protocol_links"
        "$ref": "system/links.json#/definitions/bundle_links"
    "definitions": {
                "$ref": "type/process/analysis/analysis_process.json#/definitions/parameter"
                "$ref": "type/process/analysis/analysis_process.json#/definitions/task"
```
- `$schema` should point out to the new version on every schema


Minor things:
- I think we can implement some of the keywords to make for a better schema. I haven't finished assimilating all the concepts yet but I will be more than glad to look further into it.

**Comment by ESapenaVentura** [comment]
@javfg Since you know about the validator now, do you think we can meet next week to discuss moving to the new JSON schema version?

**Comment by javfg** [comment]
Certainly. We can talk about it whenever you have some spare time!

**Comment by ESapenaVentura** [comment]
@javfg and I have talked about it today. Over the course of this sprint we will assess its cost/value to decide whether if it's a good idea to upgrade or it will be more valuable to stay in draft-07.
