### ISSUE TITLE
Update barcode module fields from string to array.

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/metadata-schema#1131]
**For which schema is a change/update being suggested?**

I would like to request an update to the `barcode.json` schema.

**What should the change/update be?**

I would like to change `barcode_read`, `barcode_offset` and `barcode_length` to accept multiple values. 

**What new field(s) need to be changed/added?**

Field type: Needs to be changed to an array for all fields.

**Why is the change requested?**

Data contributor has a number of library preparations with multiple values for the above fields.

**Comment by willrockout** [comment]
This is for a CZI incentive dataset so were trying to move this through relatively quickly but I know this may affect other components. This change will have an effect on both cell barcode and umi barcode fields as they both import the barcode.json module. @hannes-ucsc @samanehsan @kbergin would the above changes cause any major problems?

**Comment by cjvillar** [comment]
<img width="999" alt="Screen Shot 2019-09-19 at 11 34 22 AM" src="https://user-images.githubusercontent.com/20974239/65271194-866fba80-dad1-11e9-9834-5b33acf01ad4.png">

**Comment by cjvillar** [comment]
Above is an example of the fields in the spreadsheet we received.

**Comment by samanehsan** [comment]
It looks like the metadata-api library is not parsing those fields from the `library_preparation_protocol` json so it should not cause any issues there: https://github.com/HumanCellAtlas/metadata-api/blob/develop/src/humancellatlas/data/metadata/api.py#L485

This is a major schema version change since it affects the type of the field right? If so, we will need to update our subscription queries to pin to the new version.

**Comment by lauraclarke** [comment]
Quick question, is there any way to associate these details with the specific library that used them if we simply add an array. 

If there isn't this might need a deeper change than adding an array. 

If there is no way to reverse engineer which library used which settings making this change isn't useful

**Comment by willrockout** [comment]
@lauraclarke The library preparation protocol id in the sequence file tab connects the sequencing file to the library preparation protocol that made it.

**Comment by lauraclarke** [comment]
So a for this dataset a single library preparation uses multiple different barcode offsets and lengths?

If there are multiple different library preparations which use different protocols surely there need to be multiple protocols each with its own barcode details

**Comment by willrockout** [comment]
No it’s that the cell barcode is in multiple files example read 1, i7 index and i5 index and we need to capture the length/offset of the barcode in each of those places.

**Comment by lauraclarke** [comment]
Okay, just to confirm I have understood

for one library preparation protocol, different fastq files will have different barcode offsets and lengths

I am assuming the convention will be the order of the barcode containing read array will match the order barcode offset and barcode length arrays 

That isn't entirely foolproof but the right balance of minimal change to schemas for the usability of data

**Comment by zperova** [comment]
@willrockout Since the dataset has been submitted without this schema update, could you please comment on:
1.  what was the solution that enable submission of the dataset?
2. is this ticket is relevant?

**Comment by lauraclarke** [comment]
@willrockout @claymfischer we are trying to schedule all the schema updates and metadata changes they produce. Can you confirm what the solution was in the end here and if the proposed update is still the right one?

**Comment by willrockout** [comment]
@lauraclarke @zperova It was determined that this update was not needed and the metadata was changed.

**Comment by zperova** [comment]
Closing this ticket as this update is not needed.
