### ISSUE TITLE
Assess the value of specifying recommended to optional fields in metadata collection.

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1137]
From @lauraclarke :
I now have details from Peter Harrison about how to get the FAANG metadata so we can assess how much the recommended fields are given compared to the optional ones

The rules themselves are here

https://github.com/FAANG/dcc-metadata/tree/master/rulesets

The commands to get the raw metadata are

You can get the FAANG metadata from the API, using the following commands to get all data in one chunk:

Animals:
curl https://data.faang.org/api/organism/_search/?size=1000000

Specimens:
curl -X GET "https://data.faang.org/api/specimen/_search/?size=1000000" -H 'Content-Type: application/json' -d'{"query":{"bool":{ "filter":[{"term":{"standardMet":"FAANG"}}]}}}'

Experiments:
curl -X GET "https://data.faang.org/api/experiment/_search/?size=1000000”

and

faang_api.txt

Can we do a comparison for number of non-null values for the different fields (say value, structured null and completely missing) for the three rule types

thanks

**Comment by zperova** [comment]
@lauraclarke could you please specify what is meant by `structured null`?

**Comment by lauraclarke** [comment]
See missing data section in here https://github.com/FAANG/dcc-metadata/blob/026c13e9dc2b8eb1cd791217d239fe70ba91fb8a/docs/faang_sample_metadata.md

**Comment by zperova** [comment]
thanks @lauraclarke

**Comment by zperova** [comment]
Missing data section from FAANG:

Missing data
Where data cannot be included in a submission, submit one of these text values instead

- 'not applicable' (i.e. does no apply to this sample)
- 'not collected' (i.e. will always be missing)
- 'not provided' (i.e. may be added later)
- 'restricted access' (i.e. it isn't missing, we just can't include it in a public document)

The use of these values will interact with the metadata validation system as follows:

- attribute is required
  - not applicable, not collected, not provided - validation will regard these as an error
  - restricted access - validation will generate a warning
- attribute is recommended
  - not collected, not provided - validation will generate a warning
  - restricted access, not applicable - pass
- attribute is optional
  - validation will pass with any of missing values terms

**Comment by zperova** [comment]
@ESapenaVentura

**Comment by ESapenaVentura** [comment]
I am assuming "sample" and "specimen" is the same in this context? I don't see rulesets for sample

**Comment by diekhans** [comment]
I would much rather have the missing reason be a separate field instead of part the value.  This allows the value to keep its type and NULL be specified for simple filtering and actually having an explanation if one cares.

**Comment by lauraclarke** [comment]
@diekhans this particular thread isn't about how we might store the reason for why a field is null but providing @zperova and @ESapenaVentura with information to help with assessing the FAANG metadata which already uses three categories of fields, required, recommended and optional to see if we can observe a positive impact of recommended vs optional fields.

It is good to think about the value associated with capturing structured null information and if we do how it is best to do it balancing value to the consumer with effort to the contributor (two fields needing to be filled in seems like a lot more effort) but this isn't the place for that. We do have a ticket about this issue which hasn't been considered much recently https://github.com/HumanCellAtlas/metadata-schema/issues/315, any feedback you have would be great there.
