### ISSUE TITLE
Review DCP Arch Doc

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1138]
@mshadbolt commented on [Mon Sep 30 2019](https://github.com/HumanCellAtlas/hca-data-wrangling/issues/322)

**Description of the task:**

As a data wrangler and as part of the metadata team I was requested by Madison to review the DCP Arch document and fill in metadata sections and review diagrams. Direct quote from slack:

> I know metadata is a little different than the other components so let me know if you think any of the sections arent applicable. Also would you take a look at the diagrams in the system overview section and let me know if anything is inaccurate or missing?

Document link: https://docs.google.com/document/d/11a-0In72pg28vVBdMSz0G_y4JYm7nE5Gr3LwtLi6GLU/edit?usp=sharing

**Acceptance criteria for the task:**

- [ ] document reviewed
- [ ] metadata section completed 
- [ ] digrams reviewed

**Comment by mshadbolt** [comment]
@MDunitz I made this ticket based on your request. Is there a particular deadline you had in mind to complete the document?

Am waiting on @lauraclarke or @morrisonnorman to assign someone and add to a sprint based on our other current priorities.

**Comment by MDunitz** [comment]
I'm hoping to present the doc at the tech arch meeting at the end of the week and then use it to create a dcp arch RFC. I'd really appreciate if you could prioritize this. @tburdett might be able to help

**Comment by diekhans** [comment]
@MDunitz I think it would be good to discuss the goals.  I see the architecture doc as something more expansive and more incrementally written than an RFC.    A system architecture would be the canonical description of how the components fit together.

A wiki would be a good way of writing and maintain it.

**Comment by lauraclarke** [comment]
@MDunitz I have made a first pass at answering those questions. I don't quite know what you are expecting in lucid chart form but I have left a question in that respect. I agree with @diekhans that an RFC seems like the wrong place to publish this documentation

**Comment by zperova** [comment]
Finished.
