### ISSUE TITLE
Discuss viability of overall metadata schema versioning

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/metadata-schema#1151]
The current proposed design of being able to query DSS for bundles using a particular metadata schema version requires that subscriptions specify a set of versions per schema that they are dependent on. Here we'd like to discuss the viability of having an overall schema set version that represents the state of the entire set of schemas over time such that a downstream component would be able to query DSS using one overall schema instead of a particular set of versions for each dependent schema.

**Comment by diekhans** [comment]
I added myself as a second assignee, as there should be at least one metadata person owning this.

However, I don't have any great ideas on how to do this in a useful way.

**Comment by hannes-ucsc** [comment]
Combined with the tight coupling between schema files in this repository, the individual versioning has proven to be unwieldy. It cause the addition of the `schema_{major,minor}_version` fields to have been implemented incorrectly (core schema was rev'ed, concrete schemas were not) resulting in schema-invalid documents in the production data store.

Obviously, hat could have been prevented but the lesson is that individual versioning makes things unwieldy and harder to reason about and ultimately get right.

**Comment by hannes-ucsc** [comment]
Obsolete in DCP/2.
