### ISSUE TITLE
Add metadata to identify fluidigm-based assays

### ISSUE THREAD

**Issue by samanehsan** [HumanCellAtlas/metadata-schema#1153]
**For which schema is a change/update being suggested?**

I am not sure which metadata file would be most appropriate to change here, so I'd appreciate input from the metadata team! 

**What should the change/update be?**

I would like to add a new field so that we can easily determine whether or not an assay is using a fluidigm-based protocol. Or perhaps add more specific SmartSeq2 ontologies such as "SmartSeq2_plate_based" and "SmartSeq2_fluidigm".

**What new field(s) need to be changed/added?**
Open to discussion/suggestions 

**Why is the change requested?**

Currently, the SmartSeq2 pipeline in production was made with non-fludigm data in mind. The one SS2 fluidigm dataset that we do have has a different library preparation protocol ontology (“SmartSeq” instead of “SmartSeq2") so it does not match our subscription query (which is intended). However, it is not clear from the metadata that the experiment is using a fluidigm-based assay and this has caused a lot of confusion.

We want to distinguish between standard and beta analysis results in the HCA. One specific case is that we will need a way to tell if a dataset was created with a fluidigm-based SS2 protocol (vs. plate-based) so that we can indicate it is a “beta” analysis. As well, this will open development for fluidigm specific analysis if users give this feedback (which would not be currently possible with a shared subscription).

**Comment by kbergin** [comment]
We've decided to postpone implementing beta pipelines, and intend to get our fluidigm compatible SS2 pipeline approved as a standard pipeline. I think this feature may no longer be needed.

**Comment by ESapenaVentura** [comment]
I'll put it in the icebox, then. When will you know for sure? We are trying to clean the backlog and, while it's not an issue to have this ticket hanging in the icebox, it will be nice to know for sure if we need to make this change or not.

**Comment by ESapenaVentura** [comment]
Closing the ticket due to inactivity

Please re-open if deemed necessary!
