### ISSUE TITLE
schema_linter.py should have a configurable ontology service URL

### ISSUE THREAD

**Issue by rolando-ebi** [HumanCellAtlas/metadata-schema#1156]
**Description**

The schema_linter script, which runs as part of travis tests, looks for the ontology service in the dev environment when checking schemas. The dev environment isn't guaranteed to be available and so the integration/stg/prod schema environments can fail to pass tests in this scenario.

**Acceptance Criteria**

- the schema_linter has a configurable ontology service URL
- the appropriate environment-specific ontology service URL is used in travis test runs of the schema_linter

**Comment by willrockout** [comment]
@rolando-ebi Are you thinking to have this pull statically from a more stable environment or be dynamic?

**Comment by ESapenaVentura** [comment]
@rolando-ebi Would it work for your requirements if we were to add a parameter to the linter (let's say default is dev but if specified `--environment` we could specify dev, integration, staging and prod) and update the `.travis.yml` config to detect the base branch and pass the parameter accordingly?

**Comment by rolando-ebi** [comment]
@willrockout Ideally dynamic

@ESapenaVentura That would work. Btw ingest infrastructure doesn't require the work in this ticket, this work is required to ensure consistency in the results of the schema_linter and travis tests.

**Comment by ESapenaVentura** [comment]
In dev right now!
