### ISSUE TITLE
Provide clear instructions on where to find HCA Metadata from the HCA main webpage

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1157]
As a data contributor interested in submitting data to the HCA with no prior knowledge about the HCA, I would like to know where I can find information about HCA Metadata from the humancellatlas.org website.

Currently, there is no link to the HCA-DCP website from the main HCA website. Data contributors who are not familiar with the HCA can not find any information on where to look for required metadata or instructions on how to submit data. The only contact information given on the website refers to general enquiries or press enquiries.

Acceptance criteria:
- [x] email Tracey to add a link to the HCA-DCP from the https://www.humancellatlas.org/data-sharing

- [ ]  <s> provide recommendations on improvement of the Data Coordination section of the website including replacing outdated content <s>

**Comment by claymfischer** [comment]
Something a lot of folks have asked about (both as generators and consumers) is where metadata is added at different steps, and what's available from different sources. For instance, if someone downloads the metadata TSV (manifest), they would be unaware that's only a subset of the metadata.

I drew a _very_ rudimentary metadata chart here recently when explaining this to someone:
https://docs.google.com/drawings/d/1O-96-vIkFBVkJrR64GcEmyNtto-DEbVQXYlJaAMcJhY/edit

Any thoughts about having a [much better version of a] chart like this?

**Comment by lauraclarke** [comment]
Thanks @claymfischer 

@morrisonnorman can you link Clay's doc to the epic around improving how we present metadata so we can make it clear the lifecycle of metadata acquisition

**Comment by zperova** [comment]
@claymfischer thanks for the chart. it would be important to facet metadata transformations for the data contributors/consumers on the Data Portal.

**Comment by zperova** [comment]
emailed Tracey about the link

**Comment by zperova** [comment]
The second point should be addressed at a later time. Closing this issue as finished.
