### ISSUE TITLE
Make example spreadsheets and their graphs for the Metadata section of the Data Portal

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1165]
**Description**

We need to provide Dave with the content for the Metadata sections on the Data Portal in order to improve user's experience of finding relevant information about HCA metadata. 

As a data contributor, I would like to see an empty template and an example template to understand how to fill in my metadata for submission to the HCA-DCP.

Example and empty templates should be stored in metadata-schema/examples/spreadsheets/current/

**Acceptance criteria:**

- [x] empty template for 10x project is ready 
- [x] example template for 10x project is ready
- [x] graph corresponding to the example template for 10x is ready
- [x] emplty template for SS2 project is ready
- [x] example template for SS2 project is ready
- [ ] graph corresponding to the example template for SS2 is ready

**Comment by mshadbolt** [comment]
@zperova do you want empty spreadsheets for this or filled with some dummy data or both?

**Comment by zperova** [comment]
These should be real spreadsheets - similar to the example spreadsheets we occasionally send to the contributors when they request them.

**Comment by lauraclarke** [comment]
I like in the faang portal you can get both examples and templates https://data.faang.org/ruleset/samples#standard

**Comment by zperova** [comment]
@ESapenaVentura will take a real published dataset and simplify it to have 1 donor - 2 specimen and 2 cell suspensions and a set of fastq files each.

**Comment by ESapenaVentura** [comment]
Done it for 10x - I'm also generating a graph with the sample to visually show the experiment.

**Comment by ESapenaVentura** [comment]
![Graph_model_10x](https://user-images.githubusercontent.com/38617863/69538951-59c99a80-0f7b-11ea-9fd9-a805374c92e1.png)

Whenever @HumanCellAtlas/wranglers can please tell me if you like this graph for the example. I can change everything (From colour of the arrows to fonts, size of the circles, etc).

Thanks!

**Comment by lauraclarke** [comment]
@ESapenaVentura I like the example but I wonder if you can make the text bigger/shorter so it is easier to read?

**Comment by ESapenaVentura** [comment]
@lauraclarke I can rename the protocols for them to be shorter and then I could make the text bigger!

**Comment by ESapenaVentura** [comment]
New version of the graph: 

![Graph_model_10x](https://user-images.githubusercontent.com/38617863/69560091-16832200-0fa3-11ea-8a95-e0c80d93fe68.png)

**Comment by mshadbolt** [comment]
@ESapenaVentura are you able to share with me the link for the empty 10X spreadsheet, I'd like to use it for explaining the spreadsheet quick guide.

**Comment by gabsie** [comment]
Guys, please tell me when we can chat about the graphs and how they're used?

**Comment by ESapenaVentura** [comment]
More than happy to do so! Anything in particular you want to talk about?

I am open to any suggestion!

**Comment by pnejad** [comment]
@ESapenaVentura could we also think about making graphs of more complicated experiments? Cell lines, organoids, xenografts etc. From my experience, people struggle most with those.

**Comment by ESapenaVentura** [comment]
@pnejad I could make a better version of the graph I made for the dendritic reprogrammed cells dataset:

![graph](https://user-images.githubusercontent.com/38617863/69243345-ca973e00-0b9a-11ea-8b55-2b41a60b3f37.png)

For the rest, I need datasets where we actually captured this, as this is generated by the graph-validator tool and "tidied" by me

**Comment by gabsie** [comment]
I just want to learn about them - understand how they work, look and what needs they address.

**Comment by lauraclarke** [comment]
The HipSci project has ipscs to organoids https://data.humancellatlas.org/explore/projects/005d611a-14d5-4fbf-846e-571a1f874f70 might be interesting

**Comment by lauraclarke** [comment]
@gabsie Propose some times and we can all discuss our current goals and a possible direction of travel. I know @javfg has thought a lot about this while at the Elixir Hackathon so his presence at such a meeting would be useful

**Comment by gabsie** [comment]
cool. I will suggest something for next week.

**Comment by javfg** [comment]
Perfect, next week we will probably able to show you more, as the graph validator development will be more advanced.

**Comment by gabsie** [comment]
Just as a heads up - these are my current explorations for the Example template spreadsheets page. So that's why I am curious about what is being developed.
https://chanzuckerberg.invisionapp.com/share/N2V0HOKWUTX#/395180543_4-3_Contribute__-_Data_-_Metadata_Templates

**Comment by ESapenaVentura** [comment]
Seeing that template spreadsheets page, I would like to raise 3 things (That we can talk about in the meeting):
- Seems like the first 2 options "align" with what we have thought about: examples from 10x and SS2, with an option to see the experimental design (The graph). The difference is that we also thought about providing an empty template.
- What is the tissue collection for? I thought that this section was directed towards researchers that wanted to contribute to the DCP (But I couldn't attend to the last meeting, so this might be new)
- Love the overall aesthetic!

**Comment by ESapenaVentura** [comment]
For the SS2 experiment, I would suggest to leave it in only 1 donor --> 1 specimen --> 3 cell suspensions with 1 cell each, as making it with 2 donors will make the graph unreadable.

**Comment by ESapenaVentura** [comment]
Partially done as explained in the pull request linked - When we're ready to finish this task for SS2 we'll continue.
