### ISSUE TITLE
Fix INSDC accessions for project and study in the project.json schema

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1167]
**For which schema is a change/update being suggested?**

I would like to request an update to the `project.json` schema.

**What should the change/update be?**

I would like to fix the following two fields: 

`insdc_project_accessions` and `insdc_study_accessions`

**What new field(s) need to be changed/added?**

For the field `insdc_project_accessions` the following should be changed to:

"pattern": "^PRJ[E|N|D][a-zA-Z][0-9]+$"
"example": "PRJNA000000"
"guidelines": "Enter accession if project has been archived. Accession can be from the DDBJ, NCBI, or EMBL-EBI and must start with PRJD, PRJN, or PRJE, respectively."

For the field `insdc_study_accessions` the following should be changed to:

"pattern": "^[D|E|S]RP[0-9]+$"
"example": "SRP000000"
"guidelines": "Enter accession if study has been archived. Accession can be from the DDBJ, NCBI, or EMBL-EBI and must start with DRP, SRP, or ERP, respectively."

**Why is the change requested?**

This information is incorrect as it is currently mixed up. 

This is a major change as breaks compatibility of data currently in the system.

**Comment by ESapenaVentura** [comment]
Adressed in the corresponding PR and merged.
