### ISSUE TITLE
Make cell_type an ontology

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1172]
**For which schema is a change/update being suggested?**

I would like to request an update to the `cell_line.json` schema.

**What should the change/update be?**

I would like to change to `cell_type` from an enum to an official ontology. 

**What new field(s) need to be changed/added?**

no new fields. Cell)type ontology already exists in the schema.

**Why is the change requested?**

Having the cell_type field as an ontology instead of an enum is more robust to future updates.

**Comment by ESapenaVentura** [comment]
cell type is an ontology
