### ISSUE TITLE
Establish reliable means of communication with the Metadata community

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1173]
We need a reliable means of communication with the Metadata Community for the upcoming calls and a central location to keep agenda and notes.

**Acceptance criteria:**

- [x] get a list of RSVPs for the first Metadata community call from Fiona @zperova 
- [x] ask to create metadata-community mailing list @lauraclarke 
- [x] metadata-community mailing list is created and populated
- [x] decide on what is the best/preferred way of communication with the community
- [x] preferred way of communication is implemented
- [x] decide on where the Agenda for the Metadata community lives
- [x] location is set up and first agenda and notes are moved there

**Comment by zperova** [comment]
@javfg do you have any update on the mailing list population?

**Comment by javfg** [comment]
53 people requested access so far, and all of them were provided with invitations or added to the group straight await.

Right now there is a total of 70 people in the list.

**Comment by javfg** [comment]
The group has 78 members now.
