### ISSUE TITLE
Prepare content for the Contribute: Metadata requirements for the Data Portal

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1180]
**Description**

 

We need to provide Dave with the content for the Metadata sections on the Data Portal in order to improve user's experience of finding relevant information about HCA metadata. 

As an HCA contributor, I would like to know what are minimum metadata requirements to submit data to the HCA.
As an HCA contributor, I would like to know how to submit data to the HCA.

**Acceptance Criteria**

 
 
- [ ] content for the Metadata requirements landing page
- [ ] downloadable spreadsheet with required fields and descriptions
- [ ] content for How to upload your data

**Comment by zperova** [comment]
Metadata fields required/metadata dictionary.

Here you can find a list of user-facing HCA metadata fields with descriptions for required fields: https://docs.google.com/spreadsheets/d/1fZJsN3vpN7vGb9xhRNdj4nrtorJgPXMUXvAS0l5qPZM/edit#gid=828284694

**Comment by gabsie** [comment]
Hey Zina, 
I would propose (to be discussed) that there is an extra layer of **Recommended fields** instead of saying Other
and then we have the last layer of **Other optional fields**

At the moment if the list just says Other makes me not look at it at all, while it actually has got attributes in it... Breaking down other in two groups makes it more digestible for people, and additionally they can differentiate the next level of what they can strive for. 
Recommended will also make it clear there's some sort of a higher standard, and research has shown us this is something they expect from HCA?

Gabs


This would he

**Comment by lauraclarke** [comment]
@gabsie I would like to see the outcome of https://github.com/HumanCellAtlas/metadata-schema/issues/1137 and understand if having recommended fields has significantly impacted how often they are filled out in the FAANG metadata given they have been run this way for about 5 years.

Once we have this assessment, we then can make a decision if having our validation know about recommended fields is a good idea or if a better approach might be to highlight high-value optional fields in the templates/documentation but not have validation do anything, or even not make any changes.

**Comment by gabsie** [comment]
@lauraclarke On this occasion I was not suggesting at all the involvement of validation or any system actions, so rather your second scenario.
We know that different tissue teams have mentioned about the higher standard expectations of HCA, and we can demonstrate this, hopefully also explaining to people why they are recommended.

The first reason I mentioned, though, is mostly about visibility. The word Other makes the fields invisible now, as if they should be discarded.

**Comment by lauraclarke** [comment]
What is the difference in how required vs optional fields look like now in the spreadsheets @zperova ?

**Comment by zperova** [comment]
@lauraclarke Required fields have "(REQUIRED)" following the field name in the spreadsheet. 

@gabsie I agree with you that we should communicate what metadata fields will make submitted data complete and we should think of a better way to communicate it. This also touches on the FAIRness of submitted data, that I would love to incorporate into the website as well. The current list represents our response to the community's request to be able to check that they are collecting the necessary fields that we require in order to submit to the HCA - and nothing more. No one in the scientific community will go off with this list in hands and only collect the following metadata and nothing else. There is an understanding of the difference between minimal requirements and Metadata standard in the community, and we should also have an explanation on the website. As well an explanation for the work with the community that we are doing for the evolution of the Standard. I don't particularly like the label "Recommended fields" until we do a proper assessment and have something to base our recommendations on - which will result from our work with the community. What I envision in the future is having some metrics of which metadata fields make a dataset more complete - however, this is not an MVP we are working on now.
We could use something like "Most of the datasets in HCA also have the following fields ..." 
"The following fields make the data more complete..." or think of some better wording.

**Comment by lauraclarke** [comment]
@gabsie do you already have any designs for this?

@zperova how easy/difficult would it be to get stats on how many of our fields get values? so we can see if what we think are high-value fields are frequently being filled out or not?

**Comment by zperova** [comment]
@lauraclarke I am working on it and will update once I have the results.

**Comment by zperova** [comment]
V1of the attributes list: https://docs.google.com/spreadsheets/d/1sfFWM1VH4j7TJmLHizia6NC7jO9s_Q5BPuPeG0cs0nI/edit?folder=1dq-PWs0iDWs5kjFHypzaILWuKzbHvVez#gid=0

Currently only showing the field and number of datasets (out of 28) it was filled in.
