### ISSUE TITLE
Prepare content for the FAQ section of the Contribute section of the Data Portal

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1182]
**Description**
We need to provide Dave with the content for the Metadata sections on the Data Portal in order to improve user's experience of finding relevant information about HCA metadata. 

As someone interested in HCA, I would like to find answers to my questions regarding HCA and data submissions. 
**Acceptance Criteria**

- [x] content for the FAQ section

**Comment by ESapenaVentura** [comment]
After the talk today with @gabsie and @mshadbolt I will look through the email from the wrangling team + ZenDesk to come up with a list. A point to take into consideration is that we are going to be focused in the **data contributor**, not consumer, for this point.

**Comment by ESapenaVentura** [comment]
I have prepared a document with what I've gathered as frequently-asked questions [here](https://docs.google.com/document/d/1Qp1V7YsjfoV2ccxKoaOH-PtI3mxBkYYcYA_dFUgpkLc/edit). Please feel free to review it @HumanCellAtlas/wranglers , keeping in mind that this is for a data contributor and not a data consumer (e.g. scientist wanting to submit vs expression portal wanting to export data).
