### ISSUE TITLE
Prepare Metadata lifecycle chart for the Metadata section of the Data portal

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1183]
**Description**

We need to provide Dave with the content for the Metadata sections on the Data Portal in order to improve user's experience of finding relevant information about HCA metadata. 

As an HCA member, I would like to know at what stages is metadata added to a project submitted to the HCA-DCP.

**Acceptance Criteria**

- [ ] chart for Metadata lifecycle 
- [ ] content to describe at which stages of the project the metadata is added to the project

**Comment by ESapenaVentura** [comment]
I think if we need to come back to this we can reopen/create a new ticket
