### ISSUE TITLE
Replace update_date with version in provenance schema

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/metadata-schema#1191]
**For which schema is a change/update being suggested?**
https://schema.humancellatlas.org/system/1.1.0/provenance
**What should the change/update be?**
Rename `update_date` with `version`
**What new field(s) need to be changed/added?**
`update_date` -> `version`
* Field name: Version
* Field description: Data Store version of the metadata
* Field type:
 "type": "string",
"format": "date-time",
* Required: yes
* Examples: "2019-12-02T13:40:50.520Z"

**Why is the change requested?**
From last DCP Oct 2019 F2F meeting, it was requested that update_date should contain the DSS file version. Change to the exporter to populate the value was already done. But it would be nice to also rename the field to `version`.

**Comment by ESapenaVentura** [comment]
@clairerye I think this is no longer needed
