### ISSUE TITLE
Investigate inconsistencies in input_nucleic_acid_molecule

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1199]
@zperova commented on [Tue Dec 17 2019](https://github.com/HumanCellAtlas/hca-data-wrangling/issues/393)

**Dataset/group this task is for:**

Multiple

**Wrangler responsible for this dataset/lab:**

Multiple

**Description of the task:**

The datasets in the HCA-DCP have 2 values for the `library_preparation_protocol.input_nucleic_acid_molecule`:

OBI:0000869 | polyA RNA extract
CHEBI:33699 | messenger RNA

Most likely the difference is because of our vague description of the field and guidelines. 

**Acceptance criteria for the task:**

- [ ] all spreadsheets are checked for the presence of oligo-dT primer in `library_preparation_protocol.primer` for `library_preparation_protocol.input_nucleic_acid_molecule`: OBI:0000869 | polyA RNA extract

- [ ] if absent in the spreadsheet checked with the data contributors which primer was used for DNA synthesis from RNA.

- [ ] update all spreadsheets where needed accordingly

**Comment by ESapenaVentura** [comment]
Projects that contain polyA RNA/oligo-dT combinations:

- 1M Immune Cells
- snRNA-seq_for_human_retina
- Multiplexed scRNA-seq with barcoded antibodies
- KidneySingleCellAtlas
- HPSI human cerebral organoids
- WongAdultRetina
- Fetal/Maternal Interface
- 1M Neurons
- TissueStability
- SingleCellLiverLandscape
- Mouse Melanoma
- Healthy and type 2 diabetes pancreas
- CD4+ cytotoxic T lymphocytes
- Mouse Endoderm Project
- HumanColonicMesenchymeIBD
- Single cell RNAseq characterization of cell types produced over time in an in vitro model of human inhibitory interneuron differentiation.
- MouseGastrulationAtlas

Projects that contain messenger RNA/oligo-dT combinations:
- Reprogrammed_Dendritic_Cells

Projects that do not have poly-dT field filled:
- HDCA-Sweden-10x
- HumanTissueTcellActivation
- Kidney biopsy scRNA-seq
- Drop-seq, DroNc-seq, Fluidigm C1 Comparison
- BM_PC
- Diabetic Nephropathy snRNA-seq
- HumanMousePancreas
- TissueStability
- Tabula Muris

**Comment by lauraclarke** [comment]
What is this field used for? What is the impact of increasing consistency here?

**Comment by zperova** [comment]
@lauraclarke this field is used by the Matrix service and they have asked our opinion on why there are such differences between the datasets

**Comment by ESapenaVentura** [comment]
This may be an interesting research to do with the new datasets but I guess it will be brought up to our attention if there's an issue again @clairerye
