### ISSUE TITLE
Remediate High Tree-kill vulnerability

### ISSUE THREAD

**Issue by Lilalamar** [HumanCellAtlas/metadata-schema#1202]
Snyk reports the following **High** severity vulnerability in HumanCellAtlas/metadata-schema. Please remediate by the end of Q1 Milestone 1.

### **Description**
tree-kill

### **Suggested Remediation**
Upgrade tree-kill to version 1.2.2 or higher.

### **Details**
Affected versions of this package are vulnerable to Command Injection. User input is concatenated with a command within tree-kill and treekill that will be executed without any check.

**Comment by ESapenaVentura** [comment]
Looking into it. It seems that the severity is only applicable to windows systems, which we don't use. 

```
tree-kill is a package to kill all processes in the process tree, including the root process.

Affected versions of this package are vulnerable to Command Injection. User input is concatenated with a command within tree-kill and treekill that will be executed without any check.

Note: This vulnerability is only applicable if the package is used on a Windows operating system.
```

I think it's reasonable to merge into develop and let it propagate?

**Comment by ESapenaVentura** [comment]
Will close the ticket and delete the branch once I get confirmation of only merging into develop and let it propagate.

**Comment by Lilalamar** [comment]
@ESapenaVentura thanks for the update!

**Comment by ESapenaVentura** [comment]
@Lilalamar since we are in maintenance mode I assume there will be no releases and, therefore, no propagation through the system "naturally" (from dev to integration, etc). 

Should I merge the branch that fixes the vulnerability to all environments?

**Comment by Lilalamar** [comment]
@ESapenaVentura the resolution of security vulnerabilities fits the maintenance mode so please work within your teams to address these findings. If any resolutions require significant engineering effort, please let us know - we can work with you and DCP leadership to determine whether or not the resolution is necessary under maintenance mode.

**Comment by ESapenaVentura** [comment]
Remediated in all environments - Closing issue

**Comment by Lilalamar** [comment]
@ESapenaVentura thank you!
