### ISSUE TITLE
Assessing how well the HCA metadata standard reflects published data

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#1204]
As discussed on a meeting on Wednesday, January 8th, while the DCP remains in maintenance mode we would like to dedicate some capacity to assess how well the HCA metadata standard reflects published data. 

The chosen organs for this iteration will be **Kidney** and **Lung**. We expect at least 5-10 datasets for each organ and therefore, if not enough datasets can be found for any of these organs, a new one will be selected.

Specific tickets with the tasks will be written and associated to this epic:

1. Create a non-overlapping, curated list of available datasets from:
   - [GEO](https://www.ncbi.nlm.nih.gov/geo/)
   - [DCP](https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22genusSpecies%22%2C%22terms%22%3A%5B%22Homo+sapiens%22%5D%7D%5D)
   - Valentine's single cell human compilation spreadsheet (Reflected in the [Q3 data harvesting spreadsheet](https://docs.google.com/spreadsheets/d/1gY--ckT04Jc3xJ9atvNbm0KVty86CwKtR3cz_aau0L4/edit#gid=0))
   - CellTypist [spreadsheet](https://docs.google.com/spreadsheets/d/1ewZtKEZj5OAkkXvEpsadsqCe4QQ3Fh64EVluynV1NGI/edit#gid=0)
   - [Single Cell Expression Atlas](https://www.ebi.ac.uk/gxa/sc/experiments?species=homo%20sapiens)

1. Get metadata in native format for all the datasets.

1. Compare the metadata fields collected by the other resources to the fields the HCA collects in its metadata schema. 

1. Assess use of fields.

1. Prioritise fields based on usability into required/recommended/optional

1. Seek community feedback by contacting expert scientists.

**Acceptance criteria for the task:**
- [ ] High value fields defined
- [ ] Community feedback process completed and recommendations defined

**Comment by lauraclarke** [comment]
I would say 5 - 10 rather than 10-15

**Comment by ESapenaVentura** [comment]
Do we still need this?

It feels like we are not prioritising this for now, should we close the ticket @lauraclarke @clairerye ?
