### ISSUE TITLE
Create a list of available datasets for kidney and lung

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#1205]
**Description**

As a member of the DCP Metadata team, I would like to assess the community needs for metadata, focused first on lung and kidney, creating a list of available datasets from the following resources:

 - [GEO](https://www.ncbi.nlm.nih.gov/gds/?term=(((%22high+throughput+sequencing%22%5BPlatform+Technology+Type%5D)+AND+%22expression+profiling+by+high+throughput+sequencing%22%5BDataSet+Type%5D)+AND+%22gse%22%5BEntry+Type%5D)+AND+%22Homo+sapiens%22%5BOrganism%5D+AND+%22Single+cell%22)
  - [DCP](https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22genusSpecies%22%2C%22terms%22%3A%5B%22Homo+sapiens%22%5D%7D%5D)
  - Valentine's single cell human compilation spreadsheet (Reflected in the [Q3 data harvesting spreadsheet](https://docs.google.com/spreadsheets/d/1gY--ckT04Jc3xJ9atvNbm0KVty86CwKtR3cz_aau0L4/edit#gid=0))
  - CellTypist [spreadsheet](https://docs.google.com/spreadsheets/d/1ewZtKEZj5OAkkXvEpsadsqCe4QQ3Fh64EVluynV1NGI/edit#gid=0)
  - [Single Cell Expression Atlas](https://www.ebi.ac.uk/gxa/sc/experiments?species=homo%20sapiens)

**Acceptance Criteria**

 
- [x] A list of 5-10 datasets from different resources has been retrieved for **kidney** 
- [x] A list of 5-10 datasets from different resources has been retrieved for **lung**

**Comment by lauraclarke** [comment]
For GEO, I would stick to the UCSC identified studies in https://docs.google.com/spreadsheets/d/1gY--ckT04Jc3xJ9atvNbm0KVty86CwKtR3cz_aau0L4/edit#gid=0 rather than trying to trawl all the GEO. I know ArrayExpress indexes GEO so that might also help

**Comment by zperova** [comment]
This will become one source of truth: https://docs.google.com/spreadsheets/d/1gY--ckT04Jc3xJ9atvNbm0KVty86CwKtR3cz_aau0L4/edit#gid=0
once this ticket is done: https://github.com/HumanCellAtlas/metadata-schema/issues/1207
However, it doesn't block this ticket.

**Comment by zperova** [comment]
List of available datasets for kidney: https://docs.google.com/spreadsheets/d/1gY--ckT04Jc3xJ9atvNbm0KVty86CwKtR3cz_aau0L4/edit#gid=2049210213
List of available datasets for lung: https://docs.google.com/spreadsheets/d/1gY--ckT04Jc3xJ9atvNbm0KVty86CwKtR3cz_aau0L4/edit#gid=1706095752

**Comment by lauraclarke** [comment]
This is great, How is the ranking reflected? is it just to top to bottom?

**Comment by zperova** [comment]
@lauraclarke yes top to bottom based on the provided information. I am checking some details in the papers now.

**Comment by lauraclarke** [comment]
Thanks, it would be good to add the additional factor of cell count and down prioritize studies with fewer than 1000 cells as they tend to be less useful in the current world.

Do have a plan for how to divide this work up between yourself and the other wranglers?

**Comment by zperova** [comment]
I am working through the cell numbers now, some of the numbers in the spreadsheet do not correspond to what is in the papers. I plan to divide the work based on our capacity this sprint.

**Comment by zperova** [comment]
Datasets have been ranked now.
