### ISSUE TITLE
Get metadata in native format for the kidney datasets

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#1206]
**Description of the task**

As a member of the HCA DCP Metadata team, I would like to gather the metadata for the identified [kidney datasets](https://docs.google.com/spreadsheets/d/1gY--ckT04Jc3xJ9atvNbm0KVty86CwKtR3cz_aau0L4/edit#gid=2049210213) 
in a native format to compare with the HCA metadata.

**Acceptance Criteria**

- [x] Get all the metadata in native format for **kidney** and deposit in the [google drive folder](https://drive.google.com/drive/folders/11-4mbMmZD_WOMzewgFdbGOUClQux6YjW)

**Comment by lauraclarke** [comment]
@zperova @ESapenaVentura @rays22 @ami-day it would be good to see this split up between all four of you rather than just Enrique and Ray.

**Comment by zperova** [comment]
Closing as this is now finished. Follow up ticket for assessment is here: https://github.com/HumanCellAtlas/metadata-schema/issues/1210
