### ISSUE TITLE
Create a non-overlapping, curated list of available datasets 

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1207]
**Description**
As a DCP data wrangler working on the Metadata Standard, I would like to have all available single cell datasets that are suitable for HCA in one list to asses their metadata.

Add non-overlapping datasets from the following resources to the [Q3 data harvesting spreadsheet](https://docs.google.com/spreadsheets/d/1gY--ckT04Jc3xJ9atvNbm0KVty86CwKtR3cz_aau0L4/edit#gid=0):

 - [GEO](https://www.ncbi.nlm.nih.gov/gds/?term=(((%22high+throughput+sequencing%22%5BPlatform+Technology+Type%5D)+AND+%22expression+profiling+by+high+throughput+sequencing%22%5BDataSet+Type%5D)+AND+%22gse%22%5BEntry+Type%5D)+AND+%22Homo+sapiens%22%5BOrganism%5D+AND+%22Single+cell%22)
  - [DCP](https://data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22%3A%22genusSpecies%22%2C%22terms%22%3A%5B%22Homo+sapiens%22%5D%7D%5D)
  - CellTypist [spreadsheet](https://docs.google.com/spreadsheets/d/1ewZtKEZj5OAkkXvEpsadsqCe4QQ3Fh64EVluynV1NGI/edit#gid=0)
  - [Single Cell Expression Atlas](https://www.ebi.ac.uk/gxa/sc/experiments?species=homo%20sapiens)

**Acceptance Criteria**

- [ ] All the datasets have been added to the [Q3 data harvesting spreadsheet](https://docs.google.com/spreadsheets/d/1gY--ckT04Jc3xJ9atvNbm0KVty86CwKtR3cz_aau0L4/edit#gid=0)

**Comment by jahilton** [comment]
Also worth looking at:
- Valentine's database: http://www.nxn.se/single-cell-studies
- HCA publications: https://www.humancellatlas.org/publications/

**Comment by lauraclarke** [comment]
> Also worth looking at:
> 
> * Valentine's database: http://www.nxn.se/single-cell-studies
> * HCA publications: https://www.humancellatlas.org/publications/

Thanks @jahilton, we have already used Valentine's database. I don't know if anyone checked the publications list

**Comment by jahilton** [comment]
Valentine's database is updated daily, so may need to grab the recent additions, depending on when it was last checked.

**Comment by zperova** [comment]
@jahilton @lauraclarke we have assessed the HCA publication list

**Comment by zperova** [comment]
One list is no longer needed. Closing.
