### ISSUE TITLE
Get metadata in native format for the lung datasets

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1209]
**Description of the task**

As a member of the HCA DCP Metadata team, I would like to gather the metadata for the identified [lung datasets](https://docs.google.com/spreadsheets/d/1gY--ckT04Jc3xJ9atvNbm0KVty86CwKtR3cz_aau0L4/edit#gid=1706095752) in the native format

**Acceptance Criteria**

- [ ] Get all the metadata in native format for **lung** and deposit to the [google drive folder](https://drive.google.com/drive/folders/1HMuDWWYwdBIa89oJtYnlHA2cba0iAQ6i)

**Comment by JoshuaFortriede** [comment]
I am a curator on the LungMap Initiative and can work with you on metadata for lung datasets if you are interested.
