### ISSUE TITLE
Set up a reliable location for the Metadata Community calls materials

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1211]
**Description**

 

As an HCA member who would like to be involved in HCA Metadata calls, I would like to have a reliable location for the Metadata call agenda, recordings and meeting minutes.

**Acceptance Criteria**

 
- [ ] Set up reliable location for Community Metadata call materials
- [ ] Move existing materials to the new location
- [ ] Check that everyone has access to this new location.

**Comment by zperova** [comment]
@lauraclarke These are currently hosted on my private Gdrive, which is not the best location long term.

**Comment by mshadbolt** [comment]
I have contacted the HCA exec office about potentially hosting on the HCA youtube channel. Tracey will consult with management to see if this is possible.

If it is we will also need to confirm with speakers and the general list to ensure they would be happy for the recordings to be shared on this platform.

**Comment by mshadbolt** [comment]
HCA exec office have given the go ahead to upload metadata community call videos to the HCA youtube channel. We will need to liaise with Tim Tickle about uploading as he has permissions to upload on behalf of DCP.

**Comment by lauraclarke** [comment]
Great, I think for the meeting minutes we should resurrect the plans to add static content to schema.humancellatlas.org as that seems like a good home. @clairerye we need to discuss the prioritization of this

**Comment by mshadbolt** [comment]
After some feedback from laura I will send an email to all the presenters today informing them of our intention to upload to youtube and give them the option to object.

**Comment by mshadbolt** [comment]
All emails sent.

Martijn already gave consent.

**Comment by mshadbolt** [comment]
The following have replied giving consent:
- Martijn
- Tommaso
- Anna
- Marc
- Michela & Sara - assuming the new censored ppt is used, I might double confirm if the information that they are concerned about is too visible on the video and potentially blur it out in the video
- Lisa

**Comment by mshadbolt** [comment]
I created this sheet to give to Tim for how we want the videos to be uploaded, can I please get a review on the titles and descriptive text? 
https://docs.google.com/spreadsheets/d/1apsSFNgrRzJWMD9FR1rLvRbJltalyXHTHkRwWgD9YNg/edit#gid=0

**Comment by zperova** [comment]
If it's SCEA EMBL-EBI should not it be HCA EMBL-EBI?

**Comment by zperova** [comment]
I made some corrections. Thank you @mshadbolt

**Comment by mshadbolt** [comment]
Thanks @zperova I will email to Tim today by lunchtimeish so if @lauraclarke has any other comments please let me know by then.

**Comment by lauraclarke** [comment]
Looks good to me, brief but descriptive and nice to tag the community list membership in each.

This does mean we will need to be more aware of spam and spam members on the list as it becomes more broadly advertised but I don't think the risk is massive given the google form

**Comment by mshadbolt** [comment]
sent to Tim this afternoon

**Comment by mshadbolt** [comment]
Do we have any ideas for where the minutes should go? Are they also in @zperova 's personal google drive?

**Comment by lauraclarke** [comment]
There are options, a different google drive, using documents or markdown files attached to the website, using some sort of wiki associated with github?

What do you think the important features of the minutes are?

**Comment by mshadbolt** [comment]
I had started putting the calls on the community website in a more structured format because I think the current mega minutes document is not very useful for people to try to parse, e.g. https://ebi-ait.github.io/hca-metadata-community/community_calls/2019-11_metadata_fields.html

The main requirements are that is accessible to all and the community can find the information they want easily. Also that the location is stable and not in a drive that might move, disappear or result in broken links.

If we want to keep the google docs way I would suggest having a doc for each call as well as the rolling one. I think @zperova had started making individual docs but not sure how far through this she got or where they ended up.

**Comment by ESapenaVentura** [comment]
@clairerye I don't think we are continuing this work?
