### ISSUE TITLE
Harmonization of cell-type annotations for the March release

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#1221]
**Description**

 

As an HCA data wrangler who ensures that data consumers are provided with correct and harmonized data and metadata on the Portal, I would like to collect all the publically available cell-type annotations to create a curated list of ontologized high-level cell-types.

**Deadline: 28 Feb 2020**

**Acceptance Criteria**
 
- [x] All publicly available annotations are collected in the tracking spreadsheet

- [x] All annotations are collected from the contributors - except Immune Cell Atlas

- [x] All avaialble annotations are collated into one deduplicated master list - except Immune Cell Atlas

- [x] All cell-types are mapped in Zooma for ontology term - except Immune Cell Atlas

- [x] Annotations for the Immune Cell Atlas are received and added to the rest

- [x] Cell type annotations collected from multiple sources are harmonized

- [x] A list of high-level cell-types with ontology terms is created

- [x] Ontologized cell type annotations are sent to the selected annotation experts

- [x] Ontologized cell type annotations are confirmed by experts

**Comment by lauraclarke** [comment]
I think there is a missing step about resolving ontology mapping which has multiple options? Does that need to be made explicit?

**Comment by zperova** [comment]
@lauraclarke it doesn't have to be from my viewpoint. @ami-day please make the change in the ticket description if you think otherwise.

**Comment by zperova** [comment]
De-duplicated list of cell type annotations: https://docs.google.com/spreadsheets/d/1iLvKklYiW1qQSNSLfSPWHNg_-fgEhNONmqvNAXPhZDA/edit#gid=892667147

**Comment by zperova** [comment]
Annotations for the Immune Cell Atlas are promised by Monday Feb 17. If not received by then, ping Bo again.

**Comment by mshadbolt** [comment]
from email from Zina:

> I have finished cell type annotation normalisation. Here is the link to the deduplicated and harmonised list of cell types per dataset: https://docs.google.com/spreadsheets/d/1WikuK2mlFhAqCfWuPJIwBAGsevTO156cRkFXur6LkCs/edit#gid=231487397
Column A - is the contributor’s term
Column B is harmonised term
Column C - ontology label
Column E - ontology id

> We should use “Inferred cell identity” rather than “inferred cell type” as many of these are not cell types, and that is very obvious from the label (e.g. “glycolysis state”).

**Comment by zperova** [comment]
Working sheet on the non-perfect match ontologies: https://docs.google.com/spreadsheets/d/1bnRxUzO53pIC1YrHidELnjBdI4Ox1OMrKjk4Cz3h4P4/edit#gid=1736731387

**Comment by zperova** [comment]
Tickets related to new terms:
https://github.com/obophenotype/cell-ontology/issues/627
https://github.com/obophenotype/cell-ontology/issues/625
https://github.com/obophenotype/cell-ontology/issues/628
https://github.com/obophenotype/cell-ontology/issues/626
https://github.com/obophenotype/cell-ontology/issues/629
https://github.com/obophenotype/cell-ontology/issues/630

**Comment by zperova** [comment]
All the emails sent out to authors for confirmation.

**Comment by zperova** [comment]
Emails to the authors sent for the contributor's, some responses already for more specific terms. Going through on the dataset-by-dataset basis.

**Comment by zperova** [comment]
Response from Zhisong He from Barbara's lab - annotations in the paper that were used for March release are not the final. Received the file to redo the annotations.
Also received replies on:
Tissue sensitivity
SingleCellLiver
Pancreas
HaematopoieticProfiling
ICA

**Comment by lauraclarke** [comment]
How many are we left to get responses from?

**Comment by mshadbolt** [comment]
@zperova I have noticed an issue with the annotation of `erythroid` cells

For some projects, like the Census of Immune cells erythroid cell has been annotated as `erythrocyte:CL_0000232` whereas in the kidney dataset the `Erythroid` cell type has two separate terms `erythroid lineage cell:CL_0000764` and `primitive erythroid lineage cell:CL_0002417`

I think that all cells that have the 'harmonized cell identity' as `erythroid cell` should have the same ontology associated with it. Let me know what you think.

**Comment by mshadbolt** [comment]
I decided to remove the `erythroid lineage cell` and `primitive erythroid lineage cell` and made them `erythrocyte` to be consistent and because the ontology specifies that `erythrocyte` is equivalent to `erythroid lineage cell`

**Comment by mshadbolt** [comment]
I found another duplicate for Myeloid progenitors, I decided to keep the `common myeloid progenitor:CL_0000049` annotation

**Comment by ami-day** [comment]
I am un-assigning myself as I am not working on this
