### ISSUE TITLE
Introduce UUIDs in spreadsheets with UUID missing

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#1225]
**Description**

 

As a DCP Data wrangler, I would like to update the older spreadsheets with the corresponding UUIDs in order to be able to AUDR the datasets in the future.

**Acceptance Criteria**

 
- [ ] Spreadsheets without UUIDs are listed here
- [ ] Submission UUIDs for those spreadsheets are listed here
- [ ] All spreadsheets are updated with the UUIDs for each entity
- [ ] all spreadsheets are updated to the latest schema

**Comment by ESapenaVentura** [comment]
@mshadbolt Think we are gonna need this in moving forward? Trying to close outdated tickets

**Comment by mshadbolt** [comment]
We might need something similar depending on how it is decided we will be editing projects that end up in the exchange format for TDR... but it probably shouldn't be in this schema. Maybe close for now and we can open a new ticket in wrangler central when / if it comes up again
