### ISSUE TITLE
Remediate High url-parse vulnerability

### ISSUE THREAD

**Issue by Lilalamar** [HumanCellAtlas/metadata-schema#1228]
Snyk reports the following **High** severity vulnerability in HumanCellAtlas/metadata-schema-publisher. Please remediate by the end of Q1 Milestone 2.

**Description**
url-parse

**Suggested Remediation**
Upgrade url-parse to version 1.4.5 or higher.

**Details**
url-parse is a Small footprint URL parser that works seamlessly across Node.js and browser environments. Affected versions of this package are vulnerable to Improper Input Validation. When using url-parse in the browser the protocol of the URL returned by the parser is not validated correctly. In the Node.js environment strings like, javascript: return empty strings on the resulting URL object, but in the browser document.location.protocol is used when the provided URL doesn't match the validation expression /^([a-z][a-z0-9.+-]*:)?(\/\/)?([\S\s]*)/i.

**Comment by ESapenaVentura** [comment]
@Lilalamar Please next time open this issue in the [metadata-schema-publisher repo](https://github.com/HumanCellAtlas/metadata-schema-publisher/issues)

@javfg Can you take a look at the change and see if it breaks the publisher?

**Comment by Lilalamar** [comment]
Thanks @ESapenaVentura will do!

**Comment by ESapenaVentura** [comment]
I have commented on the pull request in the proper repo https://github.com/HumanCellAtlas/metadata-schema-publisher/pull/8 and @javfg will take care of it. Closing this ticket!

**Comment by Lilalamar** [comment]
Thanks @ESapenaVentura !
