### ISSUE TITLE
Define an initial process for FAIRification of single-cell datasets that meet HCA data suitability criteria

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#1236]
The goal of this epic to create an initial process to take data from sources such as those below and produce HCA compliant data and metadata which can be provided to other resources.

- Valentine Svennson’s database http://www.nxn.se/single-cell-studies,
- Papers used for the CellTypist development efforts https://docs.google.com/spreadsheets/d/1ewZtKEZj5OAkkXvEpsadsqCe4QQ3Fh64EVluynV1NGI/edit#gid=0
- HCA publications https://www.humancellatlas.org/publications/

Here is also a link to a GEO/AE dataset tracker that Zina created previously, with accessions split by organ: https://docs.google.com/spreadsheets/d/1gY--ckT04Jc3xJ9atvNbm0KVty86CwKtR3cz_aau0L4/edit#gid=2049210213

This is the first milestone of the AIT HCA 2020 Roadmap
https://docs.google.com/document/d/10fGP8WEK0ZRfbIeed61bdDeMY4nhn9AOEXFvTsD1wQE/edit

This epic will complete when there is a repeatable process for collecting and transforming such datasets.

**Comment by ami-day** [comment]
@laura could the process of identifying published datasets for conversion be considered a part of this epic? I am interested in how single cell datasets might be identified as they are released/published, and the extent to which Valentine Svennson is actively uploading new datasets to his database. Even if we do not have the bandwidth to convert them all, I thought it might be interesting and useful to have some kind of measure of the number of datasets out there and basic info. about the tissue/organ studied for example

**Comment by lauraclarke** [comment]
A task that I hadn't added yet was something for myself and @clairerye to produce a burndown chart of the existing datasets from Valentine and the other sources so we can start to track progress. 

The forward-looking capture of prospective datasets is something that it is worth considering but this feels like a lower priority. Certainly think about what approaches might be but it would be good to focus on if we can capture stuff we already know about before worrying about how to find more

**Comment by ami-day** [comment]
Hello, these 2 datasets that are listed above have already been converted. However, they have not yet been reviewed and may require edits.

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE114156 (reviewed by @Enrique, edited, awaiting final review)
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE131685 (awaiting review)

**Comment by ami-day** [comment]
GSE114156 & GSE169564 belong to the same publication/project

**Comment by lauraclarke** [comment]
@ami-day Probably best to add these sorts of comments to https://github.com/humancellatlas/metadata-schema/issues/1242 rather than the epic level. I will redraft the epic description to make that clearer

**Comment by ESapenaVentura** [comment]
I think this was somewhat achieved and we are not working on this anymore. Closing @clairerye !
