### ISSUE TITLE
Add a biomaterial module containing pregnancy-related fields

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#124]
Fields like gestational_age, gestational_age_unit, and other neonate/pregnancy related fields should go in their own module. Currently, gestational_age and gestational_age_unit are in the organism.json schema, but as these fields will likely only be used in a small percentage of cases, it makes more sense to put them in their own module.

**Comment by ESapenaVentura** [comment]
@HumanCellAtlas/wranglers Since one of the next future step is to de-modularize the schema, is the aggregation of these fields necessary anymore?

**Comment by mshadbolt** [comment]
Is the de-modularisation a definite thing or still be discussed? I haven't heard anything official that we are going ahead with it?

**Comment by ESapenaVentura** [comment]
Is not official, but I think it's mostly because we don't know how to exactly do it. The person who had the the most idea was Mallory, so after the incentive we might want to discuss if we are going to do it/how/who

**Comment by lauraclarke** [comment]
I agree we should recover the discussions about schema demodularization once everyone in the office is done with their incentivisation submissions
