### ISSUE TITLE
Define prioritized list of datasets to be put through the FAIRification process

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#1243]
## Background

This initial issue of this goal was to produce a burndown chart of datasets from sources such as:

- Valentine Svennson’s database http://www.nxn.se/single-cell-studies,
- Papers used for the CellTypist development efforts https://docs.google.com/spreadsheets/d/1ewZtKEZj5OAkkXvEpsadsqCe4QQ3Fh64EVluynV1NGI/edit#gid=0
- HCA publications https://www.humancellatlas.org/publications/
- GEO https://www.ncbi.nlm.nih.gov/geo/
- ArrayExpress https://www.ebi.ac.uk/arrayexpress/

This is now complete; the list contains human and mouse scRNAseq datasets which are likely to fit the HCA and SCEA dataset suitability criteria and enough information that they can be fed into the FAIRification process being defined for this epic.

## Description of this issue

The goal of this issue was to take the above mentioned first pass list and create a dataset backlog tracking sheet which can be shared between the HCA and SCEA teams to track progress made on the above suitable datasets and to store all required information for the FAIRification process defined for this epic. Documents describing the tracking sheet and a first pass of the tracking sheet itself can be found here:

**Google doc:**
https://docs.google.com/document/d/1JPXQdY7fE6N9WR2ac0_nyj1yxeIMX3d3B1JMsYBIMgk/edit

**Tracking sheet:**
https://drive.google.com/drive/folders/1Ja2NKtHkDh2YIvUhNa1mpivL-UjCsmbR

## Acceptance criteria

- [ ] List the questions people need to answer with the tracking sheet, and add these to the shared google doc.
- [ ] Review these questions and if needed, update the sheet appropriately
- [ ] Clarify appropriate terminology for conversion status and prioritisation using feedback from the team (drop-down lists)
- [ ] Add drop-down lists for: status, prioritisation, sample type, technology, organism
- [ ] Circulate the updated tracking sheet with the team and ask for feedback
- [ ] Establish a prototype process to automatically retrieve the required information listed in the table above, where automatic retrieval is indicated.
- [ ] Apply prototype process to the list of 14 GEO datasets that are listed in tracking sheet
- [ ] Enter all unfilled values in the tracking sheet: datasets which have already been uploaded or are currently being converted.

**Comment by lauraclarke** [comment]
First past

https://docs.google.com/spreadsheets/d/1N1MmQKe8b7DvIHSybLKvxeGzuv3M_QvhzDfPkotXy8s/edit#gid=1003433101

**Comment by ami-day** [comment]
HCA/SCEA datatset tracker - second pass:

https://drive.google.com/drive/folders/1Ja2NKtHkDh2YIvUhNa1mpivL-UjCsmbR

**Comment by lauraclarke** [comment]
@ami-day This feels like it was superceeded by your work. Can you review and see if there is anything that isn't done. If it is finished, please close it

**Comment by ami-day** [comment]
@lauraclarke Together with what has been done already by the wranglers and I, and also your addition of new datasets from Valentine's DB, I think we can close this now.
