### ISSUE TITLE
Create a map of GEO field names -> HCA field names

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/metadata-schema#1244]
**Description**

This issue was created in relation to epic ticket #1236: "Define an initial process for FAIRification of single-cell datasets that meet HCA data suitability criteria".

7 datasets have been identified to help with the piloting of this process:

https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-5060/
https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-6149/
https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-6653/
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE114156
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE109564
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE131685
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE136103

The goal of this issue is to identify the list of field names which are common to all GEO datasets above and identify the HCA field names which map to these, if applicable.

**Acceptance criteria**

- [x] Create a list of GEO specific field names common to all GEO datasets.
- [x] Map GEO field names list to HCA field names, where applicable.

**Comment by ami-day** [comment]
@rays22 I created this task previously, will you be working on the Array Express specific fields?

**Comment by rays22** [comment]
> @rays22 I created this task previously, will you be working on the Array Express specific fields?

Yes, I will be working on the ArrayExpress specific fields. Thanks for creating the ticket.
