### ISSUE TITLE
Modify existing use of openpyxl to convert HCA JSON formated metadata to excel spreadsheet

### ISSUE THREAD

**Issue by ami-day** [HumanCellAtlas/metadata-schema#1249]
**Description**

The goal of this ticket is to write a function/script which takes HCA metadata in JSON format and converts it into the HCA excel spreadsheet format. The aim is to enable us to manually add empty fields directly into the automatically converted file.

**Acceptance Criteria**

- [x] Identify an existing HCA script which uses openpyxl to read/write xlsx files
- [x] Make modifications if necessary to convert HCA JSON formatted metadata to HCA excel spreadsheet 

Please feel welcome to provide feedback on the criteria for this process, it may not be the most efficient or useful method for the intended outcome.

**Comment by ESapenaVentura** [comment]
`ingest.importer` module reads xlsx HCA spreadsheets.

Concretely, the class used to do this is `XlsImporter`, inside `ingest.importer.importer`

**Comment by lauraclarke** [comment]
@ami-day It would be good to understand why we need this? where is the HCA json coming from?

**Comment by ami-day** [comment]
@lauraclarke i think we already resolved this, but just in case: we need to be able to add extra metadata to the automatically pre-filled spreadsheet. Ideally in future, we won't need to work with a spreadsheet at all but for now, i think we need it. We are not at the stage of implementing it yet though.

**Comment by ami-day** [comment]
this has now been incorporated into the geo -> hca prototype.
