### ISSUE TITLE
Determine metadata requirements for scMethylation experiments

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1252]
**Description**

 

As a contributor with single cell methylation data I want to accurately capture the relevant information about my experiment using the HCA metadata standard.

This was sparked an incoming dataset that uses plate-based single cell methylation data.

Wranglers to review and discuss literature to determine important fields to capture. Once we have put together some literature we can have a meeting to discuss. Tagging @ami-day as this was her idea.

**Publications**
Decent looking review article: _Single-Cell DNA Methylation Profiling: Technologies and Biological Applications_ https://www.sciencedirect.com/science/article/pii/S016777991830115X (need to be on VPN for full text)

**Acceptance Criteria**

 
- [ ] Requirements for capturing single cell methylation experiments determined
- [ ] Any required ontology updates requested in the ontology repo
- [ ] Any required schema updates filed as new ticket/s

**Comment by ESapenaVentura** [comment]
I propose we create a new ticket / reopen this one when we focus on new omic techs
