### ISSUE TITLE
Propose schema to capture cell type annotations

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1253]
**What is the proposed name of the new schema?**

A biomaterial type schema, possibly called `cell`

**What field(s) should the new schema contain?**

Will import `biomaterial_core`

To be filled in

* Field name: 
* Field description: 
* Required: 
* Example: 
* CV or enum: 

**Why is the new schema needed?**

To capture per cell cell type annotations for single cell sequencing experiments

**Comment by ESapenaVentura** [comment]
We took other route to capture cell type annotation, closing this @clairerye
