### ISSUE TITLE
Summarise needs and learnings from Metadata Community Calls

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1261]
To date there have been 6 Metadata Community calls. As part of #1265 Zina and I will summarise the learnings from these.

They are:
- November - Valuable fields to collect @zperova 
- December - Lung @zperova 
- January - Kidney @mshadbolt 
- February - Heart @mshadbolt 
- March - Common Coordinate Framework @mshadbolt 
- April - Metadata acquisition in smFISH @zperova 

Document for collecting summaries:
https://drive.google.com/open?id=1LsPk11PtETM5FvxZ51rnQcVK604E0Bi-BAbpyH3JjQo

working directory: Brokering>Metadata Community Call>20200504-May Call Preparation

## Acceptance criteria:
Summaries exist for:
- [x] November - Valuable fields to collect
- [x] December - Lung
- [x] January - Kidney
- [x] February - Heart
- [x] March - Common Coordinate Framework
- [x] April - Metadata acquisition in smFISH

**Comment by mshadbolt** [comment]
@zperova feel free to take which one suits you. I thought it made sense for you to do the first one because you were heavily involved in the preparation. 

I took Kidney first up as I don't think you attended this one. I can't remember which other ones you did/didn't attend but let me know if there is any that you think would make more sense for me to do.

**Comment by zperova** [comment]
Done: Nov, Dec, and April ones

**Comment by mshadbolt** [comment]
Closing as done
