### ISSUE TITLE
Plan to address the needs raised in metadata community calls

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1262]
Once we have summarised key needs and learnings we will need to come up with a plan on how to meet these needs.

This ticket will be expanded once we have completed #1261

**Comment by zperova** [comment]
Collect per call, focus on those needs that came up in different calls, choose top x number to follow-up on

**Comment by zperova** [comment]
This has been followed up with a call (Tony, Laura, Marion and Zina attending). FUrther planning needed.

**Comment by ESapenaVentura** [comment]
@claire I think this is outdated
