### ISSUE TITLE
Create slides for May metadata community call

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1263]
As data wranglers, Zina and I will be presenting at the metadata community call. 

Blank slide deck to work on once we are ready to work on this: https://docs.google.com/presentation/d/1RuTI8w7mt48S-YVZ2QCZxbs7oyFjp9k_RTotiUaqKjQ/edit#slide=id.p

**working directory:** Brokering>Metadata Community Call>20200504-May Call Preparation

**Comment by zperova** [comment]
The slides are in the Metadata Community Calls > Presentations/Materials from previous calls > 20200504: https://docs.google.com/presentation/d/1fSRwbWfZX0BRAmUopSp3vzCbB9qxBF8yeWM452SURYY/edit
