### ISSUE TITLE
Schemas for the HCA metadata BigQuery tables in the Terra Data Repo which match the defined HCA TDR data model

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#1269]
# Schemas for the HCA metadata BigQuery tables in the Terra Data Repo which match the defined HCA TDR data model

We need a home for the very first big query HCA schema in the metadata-repo so we can track the TDR HCA schema as they evolve

~~The goal for this is to have the first iterations of the schema defined for HCA data/metadata deposition in the TDR~~

~~This "Using the Terra Data Repository" document is likely to be a good starting point for this. https://docs.google.com/document/d/1jCPVEapjJcJ3SMBd5ZNXcYkbD11nIoi5atsugcgCKWs/edit#heading=h.qolnuwor7cru~~

~~### Tasks~~
~- [ ] Read the Using TDR document and investigate example schema https://docs.google.com/document/d/1jCPVEapjJcJ3SMBd5ZNXcYkbD11nIoi5atsugcgCKWs/edit#heading=h.qolnuwor7cru e.g  https://drive.google.com/file/d/1T6VvgwX9RNm1PPnKa5wz8PlOycWh17Us/view?usp=drive_web~
~- [ ] Meet with TDR schema team to understand how TDR schemas work @kreinold to facilitate~
~- [ ] Decide where the HCA metadata TDR schema will live and how it will be versioned~

~### Acceptance criteria
~ - [ ] Mapping of the existing schema to TDR big query schema in a suitable format~

**Comment by zperova** [comment]
https://cloud.google.com/bigquery/docs

**Comment by mshadbolt** [comment]
@rays22 to take lead on working through tasks.

**Comment by lauraclarke** [comment]
This task is being closed  as in the light of the data model proposal it isn't needed. The learning aspects of this task have been moved to https://github.com/HumanCellAtlas/metadata-schema/issues/1267

**Comment by danxmoran** [comment]
@lauraclarke now that we've reached consensus on the TDR/BigQuery MVP schema, I'd like to write out the JSON definition for a more concrete review. Would it make sense to track that JSON in this repo, even though this issue was closed?

**Comment by lauraclarke** [comment]
@danxmoran This seems like a great plan, @ESapenaVentura @mshadbolt can you coordinate with @danxmoran to specify the best location for the initial TDR big query schema for the HCA data.

**Comment by lauraclarke** [comment]
I will reopen this issue and edit the main task

**Comment by mshadbolt** [comment]
Hi @danxmoran, we think it might be better to create a fresh repo for the TDR/BigQuery schemas. The `metadata-schema` repo is a bit more complicated to add to due to its history within the DCP with a lot of rules set up in regards to pull requests, Travis checks, schema linter etc, which we haven't decoupled as yet. It will also be a bit more simple in the future if the schema are evolving at different rates.

Let us know if you need any help with setting up the repo.

**Comment by danxmoran** [comment]
@mshadbolt works for me! I'll set up a repo in the DataBiosphere org for now (same org that hosts the TDR codebase) for now, we can move it to the HCA org later if we want.

**Comment by ESapenaVentura** [comment]
Thanks for the quick answer @danxmoran! 

Please post the link to the repo here once it's done and let us know when you would like us to review it.

Also, would you like us to give you feedback in a ticket, commenting on the PRs, with a google doc...?

**Comment by lauraclarke** [comment]
@ESapenaVentura as this will be the basic schema as described in https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit?ts=5eabf976# I don't think our feedback will be needed in the first iteration

Once the outcomes of https://github.com/HumanCellAtlas/metadata-schema/issues/1267 are defined we should work on what the next steps are and what we can do in parallel with the establishment of the MVP

**Comment by danxmoran** [comment]
One clarifying question: We decided to create one table per concrete entity JSON under the json_schema/type directory. The "process" and "protocol" subdirectories there include what look like catch-all JSON schemas (i.e. "protocol.json" and "process.json") as well as specialized schemas (i.e. "enrichment_protocol.json" and "analysis_process.json"). Should the schema include "protocol" and "process" tables for the catch-all cases?

**Comment by hannes-ucsc** [comment]
@danxmoran Could you ask this on the [document](https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit#)?

**Comment by danxmoran** [comment]
@hannes-ucsc done: https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit?disco=AAAAJgrBW_o

**Comment by mshadbolt** [comment]
For those that are interested the MVP json schema for bigquery tables is here: https://github.com/DataBiosphere/hca-ingest/blob/master/schema/mvp.json

**Comment by lauraclarke** [comment]
I am closing this ticket now as I think everything is resolved. @danxmoran if you have any other questions or process matters to discuss, please do feel free to create an issue or email us if you have any questions
