### ISSUE TITLE
Assessment of how many suitable AE datasets are available for DCP2 and process definition for AE->HCA metadata conversion

### ISSUE THREAD

**Issue by rays22** [HumanCellAtlas/metadata-schema#1272]
**Description**
These are the remaining tasks of [Prototype process to FAIRify datasets in ArrayExpress and GEO #1242](https://github.com/HumanCellAtlas/metadata-schema/issues/1242) related to the documentation of AE -> HCA data flow.

 

The goal is to incorporate suitable AE datasets into HCA DCP2 to help build the Human Cell Atlas.

**Acceptance Criteria**

- [ ] Document the AE -> HCA data/metadata flow.
    - [ ] 1. Process definition for the conversion of AE metadata to HCA standards.
    - [ ] 2. Process definition for uploading converted metadata and data to HCA.
- [ ] Assessment of how many datasets suitable for DCP2 are in AE

**Comment by lauraclarke** [comment]
@rays22 Can you copy this ticket to https://github.com/ebi-ait/hca-ebi-wrangler-central/ and close it here

**Comment by rays22** [comment]
> @rays22 Can you copy this ticket to https://github.com/ebi-ait/hca-ebi-wrangler-central/ and close it here
I have copied this ticket to
<https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/9>.
