### ISSUE TITLE
Update links schema to express concrete types for process, inputs and outputs

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-schema#1274]
https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit#heading=h.6h4eqvm2zreu

**Comment by ESapenaVentura** [comment]
This was addressed in PR [1279](https://github.com/HumanCellAtlas/metadata-schema/pull/1279)
