### ISSUE TITLE
Remove `input_bundles` from `analysis_process`

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-schema#1275]
As specified in the [DCP2 MVP Schema doc](https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit#heading=h.eeyjdjt197l9)

**For which schema is a change/update being suggested?**
`type/process/analysis_process.json`

**What should the change/update be?**

remove the field `input_bundles` ~and replace it with `input_files`~

* ~Field name: input_files~
* ~Field description: A list of references to the metadata entities that describe the individual input data files~
* ~Field type: array~
* ~item type: string~
* ~Required: yes~
* ~user_friendly: Input files~
* ~Examples: b816d2d6-5f10-4447-4194-3d0a804454d6~
* ~CV or enum: no~

**Comment by mshadbolt** [comment]
@hannes-ucsc I tried to fill out this ticket to describe what you wanted. To check that I have understood correctly, in an example with a sequencing experiment with for example 3 fastq files that are analysed, the `input_files` list would contain the three `sequence_file.provenance.document_id`s ?

**Comment by hannes-ucsc** [comment]
Yes, that's right. Thank you!

**Comment by hannes-ucsc** [comment]
I edited the description to reflect the decisions made in today's call. The spec document has been updated, too.
