### ISSUE TITLE
modify links.json to allow for explicit supplementary file linking

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1285]
**For which schema is a change/update being suggested?**

`system/links.json`

As part of work for DCP2 MVP we need a way of explicitly linking supplemental files to a project. The suggestion is to modify the links.json file to include both `experimental_graph_link` and `supplementary_file_link`.

Supplementary files should be able to be linked to any metadata entity whether that is the project, protocol or biomaterial.

**What should the change/update be?**

change the current `link` definition to `experimental_graph_link`, i.e. line 83-91 to read

```
"experimental_graph_link": {
      "type": "object",
      "required": [
        "process_type",
        "process_id",
        "inputs",
        "outputs",
        "protocols"
      ]
...
```

add a new type of `link` object, `supplementary_file_link`

```
"supplementary_file_link": {
      "type": "object",
      "required": [
        "inputs",
        "file_entity_id"
      ],
      "properties": {
        "inputs": {
          "description": "An array of inputs for this link",
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/input"
          },
          "file_entity_id": {
            "description": "A link to a supplementary file uuid"
            "type": "string"
        }
```

modify the "links" definition to allow objects of both the new link types e.g.

```
"links": {
      "description": "An array of linking objects.",
      "type": "array",
      "items": {
        "type": "object",
        oneOf:
          - "$ref": "#/definitions/experimental_graph_link"
          - "$ref": "#/definitions/supplementary_file_link"
      }
```
tag @ESapenaVentura @rolando-ebi

**Comment by ESapenaVentura** [comment]
Looks good to me, may I suggest `experimental_link` and `supplementary_file_link` instead?

**Comment by mshadbolt** [comment]
definitely agree on the supplementary instead of supplemental, good catch. 

To me experimental_link makes it sound like the link is not stable. I could deal with changing it to `experiment_link`

**Comment by ESapenaVentura** [comment]
I like `experiment_link`!

Making the changes and appending it to PR [1284](https://github.com/HumanCellAtlas/metadata-schema/pull/1284)

**Comment by mshadbolt** [comment]
ok, I am really not sure if I have specified the syntax correctly for allowing multiple refs for the link objects so please double check it is correct!

**Comment by ESapenaVentura** [comment]
The syntax is a mix of yaml and json but I'm fixing it, thanks for the reminder!

**Comment by rolando-ebi** [comment]
I think we shouldn't use "input" for this, the word doesn't make sense in the context of supplementary files. 

Also, the ingest model has an entity (only Project entities at the moment) referring to a set of supplementary files so we'd want something that captures `entity -> [array of supplementary file IDs]`. Suggestion below: 



```
"supplementary_file": {
    "type": "object",
      "required": [
        "inputs",
        "file_entity_id"
      ],
      "properties": {
         "file_id": {
            "description": "ID for this supplementary file entity",
            "type": "string",
            "pattern": <the UUID regex>
          },
         "file_type": {
           "description" : "concrete type of this supplementary file entity",
           "type": <enum type, only allowed value for now is "supplementary_file" i.e schema_type of the "supplementary_file" schema>
         }
      }
}
...
...
...
"supplementary_file_link": {
      "type": "object",
      "required": [
        "inputs",
        "file_entity_id"
      ],
      "properties": {
        "supplementary_files": {
          "description": "An array of supplementary files",
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/supplementary_file"
          },
          "entity_id": {
            "description": "ID of the entity that has these supplemtary files"
            "type": "string",
            "pattern": <the UUID regex>
        }
```

**Comment by mshadbolt** [comment]
@rolando-ebi I was trying to kill two birds with one stone because we typically thing ok supplementary files as linked to an entity. e.g. a protocol pdf should be linked to the relevant protocol, a tissue specimen image should link to that specimen. Is this possible or would it break other things in ingest?

**Comment by rolando-ebi** [comment]
@mshadbolt Regarding making this generic enough to support linking to any entity type, I think that's a good addition. I've updated my suggestion above to include this

**Comment by ESapenaVentura** [comment]
```
"supplementary_file": {
    "type": "object",
      "required": [
        "inputs",
        "file_entity_id"
      ],
      "properties": {
         "file_id": {
            "description": "ID for this supplementary file entity",
            "type": "string",
            "pattern": <the UUID regex>
          },
         "file_type": {
           "description" : "concrete type of this supplementary file entity",
           "type": <enum type, only allowed value for now is "supplementary_file" i.e schema_type of the "supplementary_file" schema>
         }
      }
},
...
```
@rolando-ebi This doesn't seem right, none of the properties match the required

**Comment by mshadbolt** [comment]
one other edit for your code @rolando-ebi is to change the required fields to 

```
"supplementary_file": {
    "type": "object",
      "required": [
        "file_id",
        "file_type"
      ],
      "properties": {
         "file_id": {
            "description": "ID for this supplementary file entity",
            "type": "string",
            "pattern": <the UUID regex>
          },
         "file_type": {
           "description" : "concrete type of this supplementary file entity",
           "type": <enum type, only allowed value for now is "supplementary_file" i.e schema_type of the "supplementary_file" schema>
         }
      }
}
```

**Comment by rolando-ebi** [comment]
@ESapenaVentura yep that was copy-pasted, fixed now. Thanks @mshadbolt

**Comment by mshadbolt** [comment]
Cool so this would allow us to link supp files either to a project or to actual entities. If in the MVP they are all linked to project by default that is okay but it would be great to see the proper linking incorporated. 

Currently we do this by specifying a document file name against an entity in the spreadsheet but the link here is never formalised so I guess implementing this might need further work both in the way the spreadsheet is imported as well as how it is exported (when the `links.json` is created)
