### ISSUE TITLE
Update pullapprove.yaml config notification/requests lists

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#1287]
**Description**

As a DCP wrangler from the metadata team, I would like to update pullapprove's yaml config file to notify the proper people for updates.

The lists indicated in [the current file](https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml) are outdated as we move into DCP2/ There has been on and off-boardings.

Previous discussion can be found in #1280 

Current people in each list:

- [Major updates notification list](https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml#L30-L36):
   - [x] ~~maniarathi~~
   - [x] aaclan-ebi
   - [x] ~~MDunitz~~
   - [x] NoopDog
   - [x] ~~brianraymor~~
   - [x] ~~jahilton~~
   - [x] ~~jychien~~
   - [x] ~~jlzamanian~~
   - [x] ~~samanehsan~~
   - [x] hannes-ucsc
   - [x] ~~kislyuk~~
   - [x] danxmoran
- [Security group](https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml#L45-L49):
   - [x] ESapenaVentura
   - [x] ~~simonjupp~~
   - [x] ~~diekhans~~
   - [x] ~~willrockout~~
   - [x] rolando-ebi
- [Metadata major-minor updates group](https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml#L62-L69) and [patch](https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml#L82-L89):
   - [x] mshadbolt
   - [x] ESapenaVentura
   - [x] zperova
   - [x] rays22
   - [x] ami-day  
   - [x] willrockout
   - [x] pnejad
   - [x] claymfischer
   - [x] ~~cjvillar~~

- [x] [Code review group](https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml#L101-L104):
   - [x] mshadbolt
   - [x] ESapenaVentura
   - [x] ~~willrockout~~
   - [x] ~~cjvillar~~
   - [x] rays22
   - [x] ami-day 

 

**Acceptance Criteria**

The following lists have been updated:
- [x] [Major updates notification list](https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml#L30-L36).
- [x] [Security group](https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml#L45-L49)
- [x] [Metadata major-minor updates group](https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml#L62-L69) and [patch](https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml#L82-L89)
- [x] [Code review group](https://github.com/HumanCellAtlas/metadata-schema/blob/master/.pullapprove.yml#L101-L104)

**Comment by ESapenaVentura** [comment]
I wrote the lists to cross out people that shouldn't be kept, tick people that should be kept and add new people in

**Comment by lauraclarke** [comment]
I have crossed out those people from CZI and Stanford who are no longer playing an active role in the DCP and staff I know who have moved on.

@kbergin who is the right person from the pipelines team to be on the major updates notification list?
@hannes-ucsc @theathorn who are the right people from UCSC to be on the major updates notification list?
@kreinold @danxmoran Who from the Terra import team should be added to this list?

@claymfischer what role do you and the UCSC side of the wrangling team want to play in this? which lists do you want to be on?

@clairerye I suspect we need to review the membership of the security list so @ESapenaVentura has slightly more backup

**Comment by claymfischer** [comment]
@lauraclarke we (UCSC wrangling) would like to continue being apprised of all changes.

**Comment by lauraclarke** [comment]
Thanks @claymfischer 

So who should be listed on the Metadata major-minor updates group and patch list? @willrockout or someone else?

**Comment by theathorn** [comment]
@hannes-ucsc and @NoopDog (Dave Rogers) are the correct UCSC contacts for  the major updates list.

**Comment by danxmoran** [comment]
For Terra, you can add me to the major updates list and remove @samanehsan as she's working on other systems now

**Comment by claymfischer** [comment]
Add @pnejad and @claymfischer to the lists, too.

**Comment by lauraclarke** [comment]
@ESapenaVentura could this get resolved?

**Comment by ESapenaVentura** [comment]
It has been updated in dev.

I don't think this change will affect much until we are able to evolve the schema normally, so I think it's ok there for now.

Happy to hotfix it to all environments if preferred
