### ISSUE TITLE
links 2.0.0 schema has broken $ref URLs to definitions in same doc

### ISSUE THREAD

**Issue by danielsotirhos** [HumanCellAtlas/metadata-schema#1303]
**To reproduce**

See https://schema.humancellatlas.org/system/2.0.0/links 
I believe this schema has `$ref` URL values that are incomplete.

**Schema versions**

`links.json` schema v2.0.0 (and 2.1.0)

**Observed values**

```
"inputs": {
    "description": "An array of inputs for this link",
    "type": "array",
    "items": {
        "type": "object",
        "$ref": "https://schema.humancellatlas.org/2.0.0/#/definitions/input"
    }
},
"outputs": {
    "description": "An array of outputs for this link.",
    "type": "array",
    "items": {
        "type": "object",
        "$ref": "https://schema.humancellatlas.org/2.0.0/#/definitions/output"
    }
},
"protocols": {
    "description": "An array of protocols for this link.",
    "type": "array",
    "items": {
        "type": "object",
        "$ref": "https://schema.humancellatlas.org/2.0.0/#/definitions/protocol"
    }
}
```

```
links": {
    "description": "An array of linking objects.",
    "type": "array",
    "items": {
         "type": "object",
         "$ref": "https://schema.humancellatlas.org/2.0.0/#/definitions/link"
    }
}
```

**Expected values**

```
"inputs": {
    ...
        "$ref": "https://schema.humancellatlas.org/system/2.0.0/links#/definitions/input"
    }
},
"outputs": {
     ...
        "$ref": "https://schema.humancellatlas.org/system/2.0.0/links#/definitions/output"
    }
},
"protocols": {
    ...
        "$ref": "https://schema.humancellatlas.org/system/2.0.0/links#/definitions/protocol"
    }
}
```

```
links": {
    ...
         "$ref": "https://schema.humancellatlas.org/system/2.0.0/links#/definitions/link"
    }
}
```

**Comment by rolando-ebi** [comment]
@mshadbolt @ESapenaVentura it looks like the release script assumed that the local $ref's in the original commit referenced external modules. These $refs can work as they were in the original commit, and don't require prefixing with the schema.humancellatlas.org URL

**Comment by mshadbolt** [comment]
@rolando-ebi so you are saying we should change something to make it consistent with what @danielsotirhos expects or the ones that are currently generated are correct?

**Comment by rolando-ebi** [comment]
Either will work. @danielsotirhos 's suggestion looks more consistent with the rest of the schemas and would be future-proof if we decided to move input/output/protocol into their own schema file. I'd say go for whichever is easiest

**Comment by mshadbolt** [comment]
Like if we changes the `$ref` for the fields that are defined in the links.json to it would give the expected result?

```
"$ref": "system/links/#/definitions/protocol"
```

**Comment by rolando-ebi** [comment]
That looks like it would work (I don't know how the schema publish script is set up, so I'm not 100% sure if it will)

**Comment by mshadbolt** [comment]
ok i'll try investigating to see if it would work

**Comment by mshadbolt** [comment]
I pushed a fix for this to develop and looks like it worked, see: https://schema.dev.data.humancellatlas.org/system/2.1.1/links#/definitions/process_link

I can hotfix to the other environments on Monday if everything looks good
