### ISSUE TITLE
Remove `schema_major_version` and `schema_minor_version` from file_descriptor

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-schema#1317]
We should not have added these to file_descriptor in the first place. We've already agreed to phase them out and they are absent from other system schemas like `links.json`.

From [DCP v2 spec, section Schema validation](https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit#heading=h.oatkw4xqqy0o):

> There is one known existing schema violation in documents in the DCP v1 production instance of DSS. The `provenance.schema_major_version` and `provenance.schema_minor_version` properties are present in metadata files submitted to the DSS from around Oct 2019 onwards. The addition of these fields was proposed in [RFC 11](https://github.com/HumanCellAtlas/dcp-community/blob/master/rfcs/text/0011-query-by-metadata-schema-versions.md). After that RFC was accepted, the `provenance` schema was revised and the Ingest component was modified to add those fields to documents but the schema reference in those documents still points at an old schema, not the revised one. This is further complicated by the fact that the `provenance` schema is referenced indirectly via the main document schema ([example document](http://dss.data.humancellatlas.org/v1/files/003d3dda-6906-4943-9f12-331b963e2f55?replica=aws)). The `analysis_file` schema in that document is at version 6.0.0 while the new fields were introduced in version 6.2.0 (via the `provenance` schema version 1.1.0). The problem affects all metadata documents submitted after October of 2019, not just `analysis_file` documents.

> To address this issue, the DSS adapter removes those two fields and the Ingest adapter is modified to not emit them. Luckily, the fields are not required so removing them from documents that do happen to carry an updated schema declaration does not invalidate those documents. The `provenance` schema will be revised to remove the fields again.

These two properties need to be removed from the schema:

https://github.com/HumanCellAtlas/metadata-schema/blob/c2ab8a5115a2fabd4fcbb57fda89022be12cd939/json_schema/system/file_descriptor.json#L38

https://github.com/HumanCellAtlas/metadata-schema/blob/c2ab8a5115a2fabd4fcbb57fda89022be12cd939/json_schema/system/file_descriptor.json#L45

**Comment by mshadbolt** [comment]
I wasn't aware of the plan to phase them out and equally they are present in other system schemas like provenance.json
