### ISSUE TITLE
`protocol_type` in links schema should be an enum

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-schema#1333]
… with an entry for each of the valid schema types for protocols.

https://github.com/HumanCellAtlas/metadata-schema/blob/90b0ac22def50d35538891c6d145d07077a8f93a/json_schema/system/links.json#L71

Would have prevented https://humancellatlas.slack.com/archives/C01360XN04S/p1603433805210700

**Comment by ESapenaVentura** [comment]
Closing as this has been merged to develop
