### ISSUE TITLE
Add project level organ/assay type/cell count to project_core

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1337]
**For which schema is a change/update being suggested?**

project_core.json

**What should the change/update be?**

I would like to add project level organ, organ_part and assay/technology fields to the schema that provide a convenient way of understanding summary aspects of the project at a glance. This field could be filled in manually or automatically filled when a project is imported into ingest from the metadata available in the spreadsheet.

This update constitutes a minor change to the project schema

**What new field(s) need to be changed/added?**

#### project organs
* Field name: organs
* Field description: A list of organs that were studied in this project
* Field type: List of `organ_ontology` objects
* Required: no
* Examples: NA
* CV or enum: no

#### project organ parts
* Field name: organ_parts
* Field description: A list of specific organ parts that were studied in this project.
* Field type: list of `organ_part_ontology` objects
* Required: no
* Examples: NA
* CV or enum: no

#### project assays
* Field name: assays
* Field description: A list of the assays that were used in this project
* Field type: list of `process_type_ontology` objects
* Required: no
* Examples: NA
* CV or enum: no

#### project cell_counts
* Field name: estimated_cell_count
* Field description: An estimated number of cells in this project
* Field type: int
* Required: no
* Examples: 10000;2000000
* CV or enum: no

**Why is the change requested?**

To allow users an easy way to see key information about the project at the project level

**Comment by ESapenaVentura** [comment]
Modifying this issue to also include cell count! we're going to prioritise this for the next iteration

**Comment by ESapenaVentura** [comment]
https://github.com/HumanCellAtlas/metadata-schema/pull/1388
