### ISSUE TITLE
add cell_count to analysis_file schema

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/metadata-schema#1344]
**For which schema is a change/update being suggested?**

analysis_file.json

**What should the change/update be?**

Add new field, cell_count, so that the number of cells in matrix files can be stored in the metadata

This update constitutes a minor change to the schema(s) it affects.

**What new field(s) need to be changed/added?**

* Field name: cell_count
* Field description: The number of analysed cells present in the analysis file.
* Field type: integer
* Required: no
* Examples: 2473
* Guidelines: Should be the exact number of detected cells in the file.

**Why is the change requested?**

So that the number of cells in an analysis file can be stored in the metadata.

**Comment by ESapenaVentura** [comment]
Already in prod!
