### ISSUE TITLE
How to cite the metadata-schema discussions?

### ISSUE THREAD

**Issue by lubianat** [HumanCellAtlas/metadata-schema#1385]
Hello all, 

I've noticed there is not a "how to cite" session in the repository. Some of the discussions and recommendations are quite useful, and I wanted to be able to say in future writings thins like "the HCA Metadata Standards team recommends x, y, and z  regarding the use of ontology vs. enum vs. free text (reference).."

I can always cite the GitHub URL, but it would be good to have a stable (even if temporary) reference to cite. Is there a white paper or a preprint anywhere that I could specifically cite?

**Comment by ESapenaVentura** [comment]
Hi!

That is a great suggestion. We still don't have an official "HCA Metadata Paper", but you could use [this paper](https://www.nature.com/articles/s41587-020-00744-z) on the guidelines for reporting scRNA-Seq data. It is not specific to the HCA but it does encompass the HCA standards and was written as a collaboration between many single cell resources.

If you would like to cite the white paper, you can find it [here](https://www.humancellatlas.org/wp-content/uploads/2019/11/HCA_WhitePaper_18Oct2017-copyright.pdf) as well

Let me know if you have other queries!

**Comment by ESapenaVentura** [comment]
I am going to assume the previous comment answered your query.

Closing this issue, feel free to reopen or create a new ticket if you have further queries.
