### ISSUE TITLE
analysis.json is not a valid json schema

### ISSUE THREAD

**Issue by dosumis** [HumanCellAtlas/metadata-schema#14]
Tested using python jsonschema:

```
SchemaError: 'string' is not of type 'object'
Failed validating 'type' in schema['properties']['definitions']['additionalProperties']['properties']['properties']['additionalProperties']
On instance['definitions']['parameter']['properties']['name']:
    'string'
```

Looks like there may be a nesting problem with definitions.

**Comment by dosumis** [comment]
Hi @TimothyTickle  - from what I can gather, you might be the best person to fix this.  So have assigned for now.  Cheers, David

**Comment by daniwelter** [comment]
This passes in v4

**Comment by daniwelter** [comment]
analysis.json has been renamed analysis_process.json in v5 and now fully passes validation.
