### ISSUE TITLE
Change sequence_file.read_index enum to include Read3/Read4.

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/metadata-schema#1401]
**For which schema is a change/update being suggested?**

I would like to request an update to the `sequence_file.json` and `barcode.json` schema.

**What should the change/update be?**

I would like to add enum values - `read3, read4` - to this the sequence file schema and `Read 3, Read 4` to the barcode schema to allow sequence file data from ATAC-seq and inDrop assays.

This update constitutes a patch change to the schema(s) it affects.

**Why is the change requested?**

Data needs to be accurately described for these two assays. This also is holding up submission of two datasets linked below:

1. GSE117498
2. GSE102580

**Comment by Wkt8** [comment]
@willrockout could you please link the PR for this schema change to this ticket? It'll be the schema change to the staging branch of the metadata-schema repo. 

Quick question: Will we need to change the enum values in the barcode module (https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/module/process/sequencing/barcode.json) to allow 'Read 3/Read4' as enum values there as well?

**Comment by Wkt8** [comment]
I think so, because that change will also be required for accurately describing the assays - I think individually the PRs won't unblock the datasets so they should be made together.
