### ISSUE TITLE
Wrong "Apostrophe" used in matrix.json enum values

### ISSUE THREAD

**Issue by JoshuaFortriede** [HumanCellAtlas/metadata-schema#1410]
**Give the bug a title**

Two values in the data_normalization_methods field in matrix.json utilize a "Right single quote" character, rather than an apostrophe.

**To reproduce**

 

1. Copy the apostrophe looking character in "DESeq2’s median of ratios" enum entry into the following website: https://www.babelstone.co.uk/Unicode/whatisit.html
2. Observe that the character is a "Right single quotation mark" and not an apostrophe

**Schema versions**

 
matrix.json schema v1.0.0

**Observed behavior**

When viewing the values on a website/interface without UTF-8 encoding, the "Apostrophe" is displayed as "â€™". For instance, "DESeq2â€™s median of ratios"

**Expected behavior**

 When viewing on an interface, I am expecting a true apostrophe character.

**Screenshots or Messages**

**Comment by ESapenaVentura** [comment]
Hi Joshua,

Thanks for looking into this! I will bring it to attention so we can solve it ASAP

Many thanks

Best,

Enrique

**Comment by ESapenaVentura** [comment]
I have created a PR solving this issue https://github.com/HumanCellAtlas/metadata-schema/pull/1411

We will work to merge this ASAP! thanks again for noticing this
