### ISSUE TITLE
`ega_accessions` and `dbgap_accessions` patterns are missing anchors

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/metadata-schema#1425]
Patterns for `project.ega_accessions` and `project.dbgap_accessions` are missing  line anchors (^$)
https://schema.humancellatlas.org/type/project/15.0.0/project

**To reproduce**

 

Observed inconsistency between accession values in the project index within Azul. Saw the missing anchors within the field pattern.

**Schema versions**

 
project.json schema v15.0.0

**Observed behavior**

Pattern matches the whole string `"EGAS00001003779; EGAS00001003769"`

**Expected behavior**

I expect the pattern to do a full match including line anchors.
`"EGAS00001003779", "EGAS00001003769"`

**Screenshots or Messages**

**Comment by ESapenaVentura** [comment]
Currently in staging, closing issue!
