### ISSUE TITLE
Make imaging_protocol 'channel' and 'probe' optional 

### ISSUE THREAD

**Issue by Wkt8** [HumanCellAtlas/metadata-schema#1430]
**For which schema is a change/update being suggested?**
I would like to request an update to the 'type/protocol/imaging/imaging_protocol.json' schema

**What should the change/update be?**
Removing the two module fields 'channel' and 'probe' which are part of the 'imaging_protocol' schema from the 'required' array. 

This update constitutes a Minor change to the schema(s) it affects.

**Why is the change requested?**
The 'channel' and 'probe' imaging modules are not applicable for some imaging technologies (such as Visium). Currently,  Visium datasets are blocked as they fail validation. Making the two module fields optional would allow datasets to be unblocked and pass validation.

*e.g.*: Data contributors need to be able to assign a random integer to a cell line in order to keep track of it.

Datasets being blocked: 
AdultLungElo
E-MTAB-10386
Spatial multi-omic map of human myocardial infarction

**Comment by ESapenaVentura** [comment]
Currently in staging, closing issue!
