### ISSUE TITLE
Replace file definition with $ref to file.json

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#144]
In analysis_process.json, output files are defined with a file definition. Now that we have a core entity file in v5.0.0, we can replace this definition with a $ref to the file type. We will need to make a new file type called something like analysis_file.json to differentiate from sequence_file.json (currently the only file type entity we have).

**Comment by daniwelter** [comment]
Is there an update on this?

**Comment by malloryfreeberg** [comment]
Asked Mint Team about this via email and the response was: 

> Q: I'd like to replace the current file definition to referencing our file entity, which shouldn't change the file fields but will change the schema.
> 
> A (@dshiga): I'd be happy to see improvements to the schema. Changing it to use the file entity doesn't sound difficult to accommodate. As long as we have some lead time to deal with the changes, they shouldn't be a problem. 
> 

So, I think we can go ahead and replace the file definition with a ref to a file type entity, but we need to make a new file type entity because we cna't use `sequencing_file.json` for analysis files. How does `analysis_file.json` sound?

I think the resulting JSON that the secondary analysis team will have to build will look essentially the same (both definitions and $refs are written as objects), but there will be some slight changes to the field names:

`v4.6.1` -> `v5.0.0`
- `format` -> `file_format`
- `name` -> `file_name`
- `file_path` -> removed - should be part of `file_name`
- `checksum` field is unchanged

I'm happy to help with updating the code to point to the new v5.0.0 field names.

Thoughts @daniwelter @lauraclarke @TimothyTickle @dshiga ?

**Comment by TimothyTickle** [comment]
These seem like technical changes and do not change the composition of the
json, so I differ to Dave here (so sounds good to me :-)).
