### ISSUE TITLE
Record Genome version used to generate analysis file

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#1508]
**For which schema is a change/update being suggested?**

I would like to update the `analysis_file` schema

**What should the change/update be?**

I would like to add 2 new fields:
1. `genome_version`: mandatory enum field with the following values:
    ```
    Not applicable
    GRCh38
    ```
3. `patch_version`: optional free string to indicate the patch version of the genome (e.g. p14)

This update constitutes a major change to the schema(s) it affects.

**What new field(s) need to be changed/added?**

```
* Field name: genome_version
* Field description: Version of the genome used to generate this file
* Field type: string
* Required: yes
* Examples: GRCh38, Not Applicable
* CV or enum: enum
```

```
* Field name: patch_version
* Field description: Version of the patch within the genome version
* Field type: string
* Required: no
* Examples: p14, p11
* CV or enum: no
```
**Why is the change requested?**

Data consumers need the genome version so that the data can be re-usable. Understanding what version of the genome was used for certain tasks (e.g. alignment) helps them re-use the data.

**Comment by anu-shiva** [comment]
In this workbook, the sheet *GenomeReference examples* lists assemblies for Human and mouse
[genomeAssemblyversion_examples.xlsx](https://github.com/HumanCellAtlas/metadata-schema/files/10409744/genomeAssemblyversion_examples.xlsx)
