### ISSUE TITLE
Schema types in core and module entities

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#152]
Should core and module entities have the schema_type property, or should this only be found in type entities? Core and module should never be submitted at stand-alones but rather always as part of a type entity. The only consideration is whether the schema_type could be used for some form of validation of the right core/module being used in the right type. 

If schema_type isn't present in core and module entities, should it be required in types?

**Comment by malloryfreeberg** [comment]
If no one else has strong arguments for making schema_type not required in type entities, I would argue it should be required now. It will be easier to switch it back to not required in the future than to switch it from not required --> required.

**Comment by daniwelter** [comment]
Ok, I will make the change now.

**Comment by daniwelter** [comment]
After discussion with @lauraclarke and @malloryfreeberg, we decided that schema_type should be a required property on all type and bundle entities and that it should not be present at all in core and module entities as these are not stand-alone. Validation of inclusion is done more easily by other means.
