### ISSUE TITLE
add data access details to project

### ISSUE THREAD

**Issue by amnonkhen** [HumanCellAtlas/metadata-schema#1535]
**For which schema is a change/update being suggested?**

I would like to request an update to the [`project.json`](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/type/project/project.json) schema.

**What should the change/update be?**

I would like to add a new field - `dataAccess` - to this schema to allow data contributors to state how the dataset can be accessed. E.g. Open, Managed

This update constitutes a minor change to the schema(s) it affects.

**What new field(s) need to be changed/added?**
example value
```json
{ 
   "dataAccess": { 
      "type": "All managed access",
      "notes": "data available on GSA databases with accession number HRA000nnn"
   }
}
```

* Field name: dataAccess
  * Field description: data access type
  * Field type: object
  * sub fields: type and notes

* Field name: type
  * Field description: data access type
  * Field type: string
  * Required: yes
  * Examples: All fully open;All managed access;A mixture of open and managed;It's complicated
  * CV or enum: enum

* Field name: notes
  * Field description: notes clarifying the data access type
  * Field type: string
  * Required: no
  * Examples: data available on GSA databases with accession number HRA000nnn
  * CV or enum: no

**Why is the change requested?**

Part of the Managed Access effort for HCA ingest.
See ebi-ait/dcp-ingest-central#967

Additional tasks:
_should be linked to the relevant development tasks for the ingest backend_
- [ ] @idazucchi to make a report of what is currently recorded in the data access notes - do we want this information published or moved to the admin notes?
- [ ] Once the field is added, existing data, which currently resides in the ingest db and accessible via the API in the `dataAccess` field, should be migrated to the new location.
- [ ] ingest ui should be change to read and write this new field in the correct location of the project json.

FYI @gabsie

**Comment by ESapenaVentura** [comment]
Currently in PR review: https://github.com/HumanCellAtlas/metadata-schema/pull/1537

**Comment by idazucchi** [comment]
After some discussion in the biweekly managed access implementation calls we've redefined the metadatata needed to label a dataset's access type.
We've agreed that we're going to use 3 specific DUO codes, as outlined in the Data Contributor Agreement:
- `DUO:0000004` - Open Access data is labelled “No Restrictions (NRES)”. This data use permission indicates that there is no restriction on use.
- `DUO:0000042` - Managed Access data is labelled as “General Research Use (GRU)”. This data use permission indicates that use is allowed for general research use for any research purpose.  This includes but is not limited to: health/medical/biomedical purposes, fundamental biology research, the study of population origins or ancestry, statistical methods and algorithms development, and social-sciences research.
- `DUO:0000046` - Managed Access data may additionally be labelled as “Non-Commercial Use (NCU)”. This data use modifier indicates that use of the data is limited to not-for-profit use.This indicates that data can be used by commercial organisations for research purposes, but not commercial purposes.
