### ISSUE TITLE
Capturing data from a tumor/cell of different organism origin than host

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#168]
Copying thread from issue #11 because this is a new issue.

"We now have a test dataset that requires this: a mouse with a tumor originating from an injected cell line. There are two types of sample from this:

tumor (requires disease field on sample)
lymph nodes from mouse with tumour"

"I have to ask - is the cell_line derived from human or mouse? They do inject human tumor cells into mice sometimes (and for that matter human IPS cells as part of the teratoma assay). Ah, the life of a SCID mouse."

**Comment by ESapenaVentura** [comment]
The [xenograft](https://github.com/HumanCellAtlas/hca-data-wrangling/issues/252) conversation would fill this need as well, so I'm closing this issue
