### ISSUE TITLE
Update developmental & life stage ontology subschemas

### ISSUE THREAD

**Issue by dosumis** [HumanCellAtlas/metadata-schema#169]
@simonjupp and I decided to incorporate the [human developmental stage ontology](https://www.ebi.ac.uk/ols/ontologies/hsapdv) (hsapdv). It's pretty comprehensive and well structured.  It also links up to Uberon stage terms if we need to bridge to other organisms (makes sense for mice).  

We have not (yet) added general Uberon parents & the equivalent mouse stage terms. If we do so, it might be best to have separate, species specific subschemas.

The human developmental stage ontology includes explicit terms for ages, including binned age terms (e.g. third decade) and developmental timings (eighth month, 27th week).

This potentially makes the age fields we have redundant: 'organism age'; 'gestational age'.

TBD: 
* ditch explicit age fields in favour of using ontology term
OR
* Find a way to exclude specific age terms from stage fields
    * This should be straightforward to do, but may involve some hsapdv edits*

The fromer makes us better aligned with other projects I think.  It also provides a way to express binned ages, which may be required for anonymization (CC @lauraclarke )

\* I've already start doing some edits and pull requests on hsapdv so should be easy to get any sensible changes we want in.

CC @daniwelter @malloryfreeberg

**Comment by lauraclarke** [comment]
While I like the idea from a computationally understandably age/development stage perspective, I am concerned about changing age to an ontology field rather than a field with an ontologized unit what the impact would be on user input

@malloryfreeberg are binned ages allowed in the current schema? are they expressed differently?

**Comment by malloryfreeberg** [comment]
Yes, the age field can accept either a strict number (integer or decimal) or a range of numbers. The pattern for this in the schema is: `^[0-9]+\\.?[0-9]*-?[0-9]*\\.?[0-9]*$`

**Comment by malloryfreeberg** [comment]
@dosumis @daniwelter @simonjupp 

We have made the `development_stage` field required for donors, and have kept the `organism_age` field but it is optional. 

The `development_stage` field uses the following:
```
                "ontologies" : ["obo:efo", "obo:hcao"],
                "classes": ["EFO:0000399", "HsapDv:0000000", "UBERON:0000105"],
                "relations": ["rdfs:subClassOf"],
```

Does this sufficiently address this issue? If so, let's close it.
