### ISSUE TITLE
Naming of field that indicates how biomaterials relate to one another

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#180]
Currently, biomaterials are linked to each other using a field called "derived_from" in the schema. This field is used to indicate that a certain biomaterial - e.g. a cell suspension - came from another biomaterial - e.g. a tissue specimen - by way of a particular process/protocol. There is some discussion about whether the term "derived_from" is the best term to indicate this relationship. 

Relationships indicated by dotted lines in this [diagram](https://docs.google.com/drawings/d/1IMQr94cKuiviWXt2LWJwrc40gh6cvJqsvYWMxXA4XQE/edit).

It has been suggested that a possible confusion of meaning could arise, e.g., when capturing metadata about iPSC-derived cells.

@pnejad: "Any chance we could change 'derived_from' to something with 'source' in the name? Sample_source_id?

I see this being a potential problem when we have iPSC samples in the future. The way we use the term 'derived_from' in lab is to link differentiated cell types to their origin source.

For example: iPSC-derived neural stem cells or iPSC-derived cardiomyocytes

I think we will see derived-from in project titles, project descriptions, cell line info, sample info and organoid descriptions (and more!) when we start receiving stem cell data. It would be nice to separate them early on."

@claymfischer: "After some thought towards future compatibility, "derived_from" in field names can be a contentious issue. It's likely something that would be best suited to restrict to stem cells."

@lauraclarke: "While I appreciate that deriving mature cells from iPSCs has a more specific meaning than the general usage of the world, I am struggling to think of an alternative unambiguous term that means the same thing. Very happy to hear alternative suggestions, though."

**Comment by malloryfreeberg** [comment]
> For example: iPSC-derived neural stem cells or iPSC-derived cardiomyocytes

I actually see the `derived_from` field being a perfect fit for this scenario. If someone is submitting data for iPSC-derived neural stem cells, they should be submitting metadata both about the iPSCs (likely as a cell_suspension type) and about the neural stem cells (cell_suspension or cell_line type). In that case, their neural stem cells would have the ID for their iPSCs in the `derived_from` field indicating that their cells were literally "derived from" the iPSCs.

**Comment by lschriml** [comment]
@lschriml 
  Hello Mallory, 
  adding in some thoughts. 
the relation, derives_from (see description in Ontobee: http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0001000) 
Definition: A relation between two distinct material entities, the new entity and the old entity, in which the new entity begins to exist when the old entity ceases to exist, and the new entity inherits the significant portion of the matter of the old entity

Since derives_from is a more general relation, I would suggest identifying some more specific options to specify the to 'material entities'. 

The Cell Line ontology has some more specific relations that may useful here: 
derived from anatomic part
derived from cell
derived from cell line
derived from organism
derives from patient having disease

http://www.ontobee.org/ontology/catalog/CLO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty

Cheers,
Lynn

**Comment by tburdett** [comment]
I think we might be stuck between a desire to model the relationship between two samples specifically - in which case, @lschriml's suggestion to go more specific and reuse relations that have been coined in ontologies elsewhere here is great - vs. a desire to stay more generic - in which case `derived_from` is probably a contentious choice, especially if used in an inconsistent way with the definition from RO.  MIABIS uses `parent sample id` (https://github.com/MIABIS/miabis/wiki/Data-describing-Sample) and the ISA model (http://isa-specs.readthedocs.io/en/latest/isamodel.html#isa-abstract-model) doesn't explicitly type edges but instead the specification talks about inputs and outputs so for example: 

> Process nodes represent the application of a protocol to some input material (e.g. a Source) to produce some output (e.g. a Sample)

We could certainly try to be consistent and use e.g. `has_input_material`

**Comment by lauraclarke** [comment]
I think has_input_material has the advantage of not adding specific fields for this general relationship to every possible pair.

The ontology terms that @lschriml mention could be useful if we get better at specialising the interface for specific use cases.

In all these cases though we need to make sure the schema documentation is sufficient as API users won't get the UI quiz drive specialization

**Comment by malloryfreeberg** [comment]
Thanks for the comments everyone!

I'm inclined to favor a generic way to define relationships and consistency. Therefore, `derived_from` will be replaced with `has_input_biomaterial` in the biomaterial_core.json schema.
