### ISSUE TITLE
Include cell_type in the ontology restriction for organ_part

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#181]
At the moment, organ_part can only hold a child term of UBERON:0000465. We have come across a couple of scenarios where it would be more useful to specify a cell type rather than an organ sub-part. In a glioblastoma sample for example, the organ would be brain but beyond that, glioblastomas can occur anywhere in the brain. They specifically affect glial cells/astrocyotes though, so this would be a more useful subdivision in this case.

**Comment by malloryfreeberg** [comment]
@daniwelter Is this issue still relevant given the recent updates to HCAO?

**Comment by daniwelter** [comment]
No, I think this is sorted by using the partonomy tree - cell type part of some organ looks like it's a child of organ, so it should validate. Close and if there's a problem with validation, we can fix it later.
