### ISSUE TITLE
Clarifying values for "end_bias" in library_preparation_process.json

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#184]
Suggest changing the following accepted enums for `end_bias` field:
- `three_prime_end` to `3 prime tag`
- `five_prime_end` to `5 prime tag`
- `three_prime_bias` to `3 prime end bias`
- `five_prime_bias` to `5 prime end bias`
- Adding `full length` value

Suggestions based on feedback from secondary analysis team:

> Q: Why is the `end_bias` field required for library preparation? What specifically is meant by the valid values which are "three_prime_end", "three_prime_bias", "five_prime_end", "five_prime_bias", "none"? Are there any other potential values that someone might but here?
> 
> A (@jishuxu): I think "three_prime_end" and "five_prime_end" really mean the 3' tag or 5' tag libraries, such as 10X. As for "three_prime_bias" and "five_prime_bias, I would not say they are protocol types (at least from what I know). I guess they mean some libraries are prone to have 3' end bias or 5' end bias. It is more like to describe the quality of library. I would add 'full length' for SmartSeq2 library. 

I suggest writing out "prime" instead of using the single apostrophe as this character can be troublesome during parsing. Thoughts? @TimothyTickle @dshiga @kbergin @samanehsan

**Comment by kbergin** [comment]
Tagging in @ambrosejcarr as well. One of the people tagged should be able to answer while I'm out :) Thanks for the tag Mallory! I love the increase in communication on metadata!
