### ISSUE TITLE
move ontology.json into individual ontology specific schemas

### ISSUE THREAD

**Issue by simonjupp** [HumanCellAtlas/metadata-schema#19]
The proposal is to have an ontology schema that encapsulate the validation info. e.g. body_part_ontology.json would define the ontology validation for body parts, which would contain a custom syntax extension to json schema that specify the ontology used, the root class and the type of restriction (e.g. subclassOf, , parts, ancestors etc..)

**Comment by daniwelter** [comment]
Addressed in v5 prototype, various commits incl a4eceb96c6d9641cce3c8866f43cb9c05869b3f3
