### ISSUE TITLE
Add $id

### ISSUE THREAD

**Issue by bkmartinjr** [HumanCellAtlas/metadata-schema#2]
Schema should have an $id key.

For an excellent discussion on reuse and $id, see https://spacetelescope.github.io/understanding-json-schema/structuring.html

**Comment by daniwelter** [comment]
This is starting to be implemented in the v5 prototype

**Comment by malloryfreeberg** [comment]
Addressed in v5.0.0 updates e4137d7cf3a6eee53fc7854805e3627fc94e8b94

**Comment by daniwelter** [comment]
v5 still used id rather $id as $id is not compatible with json schema draft #4. As soon as we upgrade to json schema draft #6, we can also upgrade from id to $id

**Comment by daniwelter** [comment]
Closing this ticket as the change to $id will happen automatically as part of the upgrade to draft-06 of Json schema
