### ISSUE TITLE
remove project_id

### ISSUE THREAD

**Issue by simonjupp** [HumanCellAtlas/metadata-schema#20]
not clear what project id value should be (uuid, accession?). Projects will be created through ingest and entities can be associated to a project through ingest so there is no need for an explicit project_id field in any of the core entity objects

**Comment by lauraclarke** [comment]
Is there an entity accession field somewhere that all entities will have?

That should remove the need for any entity specific ids aside for those we import from other systems possibly

**Comment by simonjupp** [comment]
Yes, but as it is supplied by ingest it has been moved to the ingest.json schema.

**Comment by daniwelter** [comment]
This is now done

**Comment by daniwelter** [comment]
Reopening pending full schema review
