### ISSUE TITLE
$schema does not point to json schema.

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/metadata-schema#209]
The url provided for `$schema` in biomaterial_bundle.json does not lead to the JSON schema.
https://github.com/HumanCellAtlas/metadata-schema/blob/92b2ce5a882571cc144dbe3fd1c552ad27e21c9f/json_schema/bundle/biomaterial_bundle.json#L3 In order for the anything in this file to be indexed, `$schema` must lead to a json schema. This currently blocks bluebox from supporting V5.

**Comment by daniwelter** [comment]
@Bento007 The v5 bundles aren't officially released yet, which is why they aren't available on schema.humancellatlas.org yet. We're working on finalising them at the moment and they should be out in the next couple of days, incl resolving to schema.humancellatlas.org

**Comment by daniwelter** [comment]
@Bento007 we re-released v5.0.0 today including bundle schemas. Please note that in the new release, $schema has been replaced by describedBy, in line with json schema best practice. v5 bundles no longer contain the word "bundle" in the entity name, eg https://schema.humancellatlas.org/bundle/5.0.0/biomaterial
