### ISSUE TITLE
name, description and comment as optional fields on all core entity types

### ISSUE THREAD

**Issue by simonjupp** [HumanCellAtlas/metadata-schema#21]
the difference between supplying a name and title on a sample is not clear. We propose moving name, description and comment as optional attribute on all core entities:

name: short name for the entity (e.g. sample or assay) that should be unique at least within a project
description: A longer description of the entity
comment: A free text field for any additional information

**Comment by daniwelter** [comment]
Also added user_supplied_identifer to allow users to enter their local identifier for entities

**Comment by maximilianh** [comment]
For practical purposes, name and title may be immensely useful. Title is a
short description that can be shown in a user interface, when someone wants
to list samples. Name could be a longer description that is shown when a
user mouse-overs or wants to get some better idea what a sample is.

I agree that it should be made more clear what name and title are exactly,
maybe with examples.

But without name and title, how do you imagine users browsing samples? I'd
vote for making title at least mandatory.

**Comment by lauraclarke** [comment]
I would strongly advocate for two fields, one is a user supplied short label (that can be name, title, label or similar, I personally prefer name) and should be encouraged to be what ever the submitter refers to the entity as internally and the other is a longer field called description. I would recommend the user supplied label is required but the description is option.

The browser use case of wanting nice labels should be fulfillable with some combination of the accession and the descriptive ontology labels, a submitter shouldn't be required to provide something else which is informative in the browser context. 

I strongly discourage more than one descriptive field especially if they are optional it will likely confuse the submitter as to what information to but in which optional free text field and an annoy them because they have to provide the same or overlapping info in more than one place

**Comment by simonjupp** [comment]
Name and title were defined the other way round in v3. If title is defined as a short description we felt it was clearer to simply call the property description. 

Looking at sample.json there is an id and a name property where both are required. This can be confusing/annoying especially when both are the same. We were proposing having a "user supplied id" on sample, and make it clear that this should uniquely identify the sample within a project (or at least a submission). This kind of id can be useful to broker interfaces to help link up user supplied content before submitting it to the ingest service (the current spreadsheet broker requires this). The name should be optional (personally I prefer label) and used for display purposes with a description similar to what Laura provided.

We don't need a name/label for ingest to work and in cases where it isn't provided we would just fallback to the HCA accession for display, which all samples will always have.

**Comment by lauraclarke** [comment]
There are advantages from a user support perspective for insisting on a user-supplied internal label for all entities especially if the submission comes via a LIMS system as then the name a user might refer to an entity by internally is known to us and can be used to help find a particular entity which might need updating or be causing problems

The user supplied label also helps when people are submitting more than one type of entity at once which needs to be lined together as then those user supplied labels can be used by the user to refer between different entities before they have an accession

I would strongly advocate for a more user friendly name for the field than user_supplied_label like name, title or alias as I think it will be clearer to most people what is meant by that than user supplied label which seems very formal and might confuse users as to what is meant to contain, what sort of label, you could always stick local in front of the field name but that risks the confusion of what is meant to be local in this context

**Comment by maximilianh** [comment]
Totally agree with Laura. Samples have names, in every lab. There is
something that you wrote on the tube when shipping it to sequencing. It's
the name in the lab notebook and in the Excel spreadsheets. It's used to
name files on harddisks. At some point of a project in a lab, every one in
the lab knows what "IPSCpostDiff/lateNeural/sample3" is. Machine-readable
(sometimes generated by the LIMS) names are a somewhat different thing,
like CR-1-234-32154, they sometimes include the lab, the technician and the
original freezer where stored.

Humans like human-readable names.

**Comment by simonjupp** [comment]
I get that it is nice to have. The question here is, must they provide it to submit data to HCA? this ticket relates to the json schema validation specifically.

**Comment by lauraclarke** [comment]
I am not sure I understand why it is a problem to insist we get one? I know both ENA and ArrayExpress require them but will autogenerate them for the submitter if they can't supply it

**Comment by simonjupp** [comment]
If they can be autogenerated by the system when not supplied, then it is not required from a submitters point of view. I also expect that a users/application should be able to validate any json against this schema before submitting it to the ingest service. 

Our current bundles already contain donors, that inherit from sample, yet don't have any value for the name property and currently fail validation. 

We already require a submitter to provide us with a local id for the sample (which has a clear purpose in the current ingest system), so forcing them to supply a name seems unnecessary.

**Comment by lauraclarke** [comment]
It wasn't clear that you were already asking for a local id in this issue

In which case my question is what is the field name for the local id and why isn't it name (or title)?

and is there a reason this is specific to sample rather than general to all entities?

**Comment by lauraclarke** [comment]
@maximilianh @simonjupp and I had a face to face discussion today and we think the best way forward is

All user supplied name/id/title fields currently in the schema are collapsed into a single field required field (currently in v4 this is user_supplied_label) and we need some combination of a vote and UX work to figure out the correct label, possible field names are name, title, alias, id and user_supplied_labels

We will also add an alternative_names/synonyms field which is optional but users can use to supply any other identifiers which they use for these entities

All long-form free text fields will be collapsed into a single long-form free text field called description which is optional

Would that suit your use cases too?

**Comment by lauraclarke** [comment]
I am not sure having a second optional single name field is useful, surely we just want one required field and then the array of other alternative names?

**Comment by dosumis** [comment]
Here's what we have right now:

```json
       "type": {
            "description": "The name of the core metadata entity type.", 
            "enum": [
		      "assay",
		      "project",
		      "protocol",
		      "sample",
		      "file",
		      "analysis"
            ]
        },
       "user_supplied_id":{
            "description": "A local identifier for the entity (e.g. sample, assay, protocol, file, analysis).",
            "type": "string"
        },
        "name": {
            "description": "A short descriptive name for the entity (e.g. sample, assay, protocol, file, analysis).  Should be enough to distinguish it from other samples in the project.", 
            "type": "string"
        },
        "comment": {
            "description": "A free text commment capturing any relevant information not captured by other fields.",
            "type": "string"
        },
        "description": { 
            "description": "A general description of the item being submitted (e.g. sample, assay, protocol, file, analysis).",
            "type": "string"           
        }
    },
    "required": [
        "type"
    ]  
```

Note these are all in core.json - which is imported by *all* the core entity types (sample, assay, protocol, file, analysis, project).    None is currently compulsory, but the consensus here seems to be that user_supplied_id should be.  I'm leaning towards agreeing but have a couple of questions.

(a) do we expect users to have their own identifiers for all these types of entity (this might be an argument against pushing these fields up.
(b) Do we expect some of those entering data to start relying on HCA provided accessions.  If so, how would this field be used?

@maximilianh - I'm sympathetic to your case for short descriptions to be used in browsing, but would also like an outlet for longer free text description for data that doesn't fit into the current schema. I'd prefer that to allowing users to come up with arbitrary, uncurated key-value pairs to extend metadata - in my experience these just tend to cause confusion in both human and computational consumption of metadata where a clear piece of free text may enlighten and can at least be mined by NLP.  Not sure how to balance needs here.  Perhaps we could switch name to 'short summary' and put a tweet-like character limit on it, making it compulsory?

**Comment by lauraclarke** [comment]
It would be good to talk about this in person/on a metadata call

This feels like unnecessary inflation of fields which will create confusion rather than solve problems

user_supplied_id and name feel like they overlap a lot.

I like the idea of giving users a space for alternative names as well as the first one but two singular fields seems like it will cause confusion

I believe (but I am happy to be proved wrong) that users do give their own samples and experiments names either in their own spreadsheets or in their LIMS systems and these are likely to be the names that the submitters know when asking us for their data back. I think for anyone else the accessions are likely to be as if not more useful but it is difficult to say what people will use until the system goes live

I should really test my assertion about sample and experiment names by asking the ENA and ArrayExpress support teams and find out what users use to refer to their samples when emailing in questions

Is there a reason for description and comment, don't both of those fields serve the same purpose? how does a user know what to put in the comment and what to put in the description and why take it in two different fields?

**Comment by malloryfreeberg** [comment]
@daniwelter and I have added name, description, comment, and user_supplied_id to the core.json schema (reflected in [core.json](https://github.com/HumanCellAtlas/metadata-schema/blob/version_4/json_schema/core.json) file and in metadata [spreadsheet](https://docs.google.com/spreadsheets/d/1L0-7JoOPiukqqKzmx_hh7u1EP9-2VSKN5Zld3DXlz7o/edit#gid=75895669)). Leaving this issue open in case there is more discussion on this topic.

**Comment by lauraclarke** [comment]
Can I ask again what the use case is for two free text fields comment and description? 

I am very concerned that users will find it odd there are two places for this sort of information and how they are used from submission to submission will be very inconsistent 

Is there a reason not to just have one?

**Comment by dosumis** [comment]
I think we all felt that a description of a sample or assay is distinct from a comment about it.  Although I don't *think* the suggestion for this field came from me, I've certainly found this distinction to be quite useful in a number of other contexts.   But I don't want to be too dogmatic on this.   We could just have a single description field if you think that would be better.

At the risk of field inflation again: what is you opinion on @maximilianh 's case for a summary field to be used in browsing display?  This was, apparently, the aim of the 'title' field.  I think title is the wrong name for this.  

short_summary_description:
    type: string
    description: A tweet-length (140 character) summary description.

Also TBD:  Have we done the right thing in pushing all these fields up into core.json.  The result of this is that the same set of general fields are present for all core object types (sample; assay; protocol; project etc).    I think most of the discussion here has assumed this is only about samples.  Would it make more sense to push some of these fields down to gross-type level and provide type more specific descriptions of what is expected?  This would also allow us to control which fields are required at the type level.

**Comment by lauraclarke** [comment]
Having all these fields in core.json is the right thing as we will need them in the different entities

I am concerned that two optional free text fields will be used very inconsistently by users and different people will have different views on what is a description and what is a comment. 

This will make it even more difficult to find information which has been provided by this route. 

I don't care what it is called but in the first instance at least I would strongly advise only one long form free text field so at least it is all held in the same place and you don't have to check two fields to see if the submitter has provided useful ancillary information in there.

On @maximilianh suggestion, I would rather browsers used the standard fields such as assay or sample type, disease, organ, technology (note these aren't necessarily the correct field names) to produce those descriptions than assume different submitters will provide any short consistent short description which is useful in a browser context.

I don't think submitter supplied descriptions (short or long) will ever be terribly useful in the browser display context
