### ISSUE TITLE
"title" should be "publication_title"

### ISSUE THREAD

**Issue by Bento007** [HumanCellAtlas/metadata-schema#217]
It looks like a bug, please correct me if i'm wrong. This https://github.com/HumanCellAtlas/metadata-schema/blob/290696a0fa77a777b085f94d534f19c79de4d628/json_schema/module/project/publication.json#L9 should be https://github.com/HumanCellAtlas/metadata-schema/blob/290696a0fa77a777b085f94d534f19c79de4d628/json_schema/module/project/publication.json#L34

**Comment by malloryfreeberg** [comment]
Thanks for the catch, @Bento007 ! A bug fix patch has been released.
