### ISSUE TITLE
Change target cell type to predicted cell type

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/metadata-schema#233]
3/8/18 discussion outcome = predicted_cell_type

Target is a strong word, predicted is neutral!

**Comment by lauraclarke** [comment]
predicted isn't appropriate though

predicted implied it has been asserted on the basis of analysis

This means the cell type targetted by the sorted technique

**Comment by pnejad** [comment]
Target sounds like you are starting with a cell and changing it to a different type. Is there a different neutral field?

**Comment by jishuxu** [comment]
`target` and `predicted` probably both confusing. Can we just leave this field as 'cell type'? At GEO, there is only `cell type` field for cell line or cells extracted from tissue. it is clear and no confusing.

**Comment by lauraclarke** [comment]
I think the problem with just using cell type is because at some point the HCA will do analysis which potentially assigned different cell types to results from a cluster.

We are trying to find a term that indicates this is the cell type which was aimed to be collected not the definitive cell type

**Comment by jishuxu** [comment]
`target cell type` makes me think it is a cell has specific reaction to drug, virus. `predicted` probably is not good choice  either as @lauraclarke  described.

**Comment by pnejad** [comment]
How about 'selected_cell_type'?
