### ISSUE TITLE
Add culture properties to cell_line schema. 

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/metadata-schema#234]
**Which schema needs be changed?**
growth_conditions.json

**What field(s) in that schema need to be changed/added?**
add culture_properties _(other suggested field names below)_

**What should the change/addition be?**
New field

**Field name (required)**
culture_properties, culture_method, culture_conditions or culture_environment? 

**Field description (required)**
Cell culture environment (conditions?) in which cells are grown in.

**Whether the field should be optional or required (required)**
no

**An example valid value for this field (optional)**
Examples: adherent culture, monolayer culture, multi-layer culture, spinner flask culture, suspension culture, 3D scaffold based culture, 3D non-scaffold based culture, co-culture ...

**Why is the change requested?**
This field is being requested because the growth_conditions schema does not have a field that captures the culture environment the cells are grown in.

**Note**: I've listed several different field names that could be used. I'm not sure which would work best. Please leave suggestions!

**Comment by malloryfreeberg** [comment]
@pnejad Can you update this issue to reflect the template we are using for requesting changes to the schema? Copy/paste/answer the following bit in the original comment:

1. Which schema needs be changed?
1. What field(s) in that schema need to be changed/added?
1. What should the change/addition be?
1. Why is the change requested?

**Comment by malloryfreeberg** [comment]
@pnejad Can you clarify what schema changes you are requesting for this issue? It sounds like there are 2 changes you are requesting: 1 to add a new field and 1 to change the description of the `growth_medium` field. 

Please either clarify this ticket with the information asked for above, or work with @willrockout to make a new branch and make the changes you want. Since the two changes are related and are in the same schema, feel free to make one branch/PR for the requested 2 changes.

**Comment by pnejad** [comment]
@malloryfreeberg Will and I are working on new fields that would be added to the growth_conditions section, which would also address the issues I listed above. Once that is done, this issue can be closed.

**Comment by malloryfreeberg** [comment]
@pnejad @willrockout Is this issue addressed to your satisfaction? If so, please close it. If you can reference the PR that addressed it as well, please enter in the comments (so we can track when it was addressed).
