### ISSUE TITLE
Add 'tissue' field to cell_line schema.

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/metadata-schema#235]
1. Which schema needs be changed?
**cell line**
2. What field(s) in that schema need to be changed/added?
**tissue (or organ/organ part) should be added**
3. What should the change/addition be?
**A new field that captures the cell line tissue source.**
4. Why is the change requested? 
**The addition of the 'tissue' field is being requested to capture the tissue the cell line was made from.**

**Comment by lauraclarke** [comment]
A quick question, do we use tissue in the specimen_from_organism type, if we don't but use an equivalent we should use the same term here otherwise it will get confusing if they are different field names

**Comment by pnejad** [comment]
specimen_from_organism has the term **organ_part**: A term for a specific part of the organ that the biomaterial came from.

**Comment by lauraclarke** [comment]
So what is the use case for tissue on cell line and can we find a single term which fits both needs. If we can, it will be less confusing for submitters?

**Comment by pnejad** [comment]
So instead of tissue, add organ and organ_part to the cell line schema? 

Examples of what manufacturers call it:
ATCC = [tissue](https://www.lgcstandards-atcc.org/Products/Cells_and_Microorganisms/Cell_Lines/Human/Alphanumeric.aspx?dsNav=Ns:P_Product_Name%7c101%7c1%7c,N:4294963741) 
Sigma-Aldrich = [biological source](https://www.sigmaaldrich.com/catalog/product/sigma/93005a?lang=en&region=GB) 
ThermoFisher  Scientific= [tissue](https://www.thermofisher.com/us/en/home/technical-resources/cell-lines.html)

**Comment by malloryfreeberg** [comment]
@pnejad Can you update this issue to reflect the template we are using for requesting changes to the schema? Copy/paste/answer the following bit in the original comment:

1. Which schema needs be changed?
1. What field(s) in that schema need to be changed/added?
1. What should the change/addition be?
1. Why is the change requested?

**Comment by malloryfreeberg** [comment]
I'm happy to call the field `tissue` in the cell line entity. I'd rather use a term that is understandable by the users actually ordering the cell lines from somewhere else (or growing them in the case of primary cell lines). We might get some push back for liquid tissues (which I believe was the original reasoning behind using `organ` in specimen_from_organism schema), but ATCC actually includes "blood" as one of their tissue types.

For fun, I checked out all the "tissue" categories ATCC has, and they are:
Adipose
Aorta
Artery
Blood
Bone
Bone Marrow
Brain
Breast
Cervix
Colon
Eye
Heart
Intestine, Small
Kidney
Liver
Lung
Lymph Node
Muscle
Other Tissues
Ovary
Pancreas
Pituitary
Prostate
Retina
Skin
Spleen
Vein

**Comment by malloryfreeberg** [comment]
@pnejad Since you are requesting a new field, can you also supply the following information as per the contributing.md documentation:
```
To request any new fields or changes to fields, the following information needs to be supplied:

1. Field name (required)
2. Field description (required)
3. Whether the field should be optional or required (required)
4. An example valid value for this field (optional)
5. If this field needs a controlled vocabulary or ontology, what those values should be (optional)
```
I showed @claymfischer @cjvillar and @willrockout examples of how to request this info this week, so perhaps they could sit down and walk you through the process :) Thanks!

**Comment by pnejad** [comment]
@malloryfreeberg 

I want to follow up on this GH issue. Does everything above look ok?

**Comment by daniwelter** [comment]
Change done in branch and committed. PR to be done post-metadata release 11/6/18
