### ISSUE TITLE
organ_part should not be a required field for specimen

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#239]
### 1. Which schema needs be changed?
specimen_from_organism
### 1. What field(s) in that schema need to be changed/added?
organ_part
### 1. What should the change/addition be?
Make it not required
### 1. Why is the change requested? 
In some cases, the sub-section or part of the organ sampled may not be known, so making this field optional allows it to be filled in if the information is available and blank otherwise.

**Comment by lauraclarke** [comment]
Just to confirm, the organ is required?

**Comment by daniwelter** [comment]
Yes. They are currently both required and this is causing us issues, for example for Mike's spleen data, where we know it's spleen but no further sub-division

**Comment by lauraclarke** [comment]
Sounds good.

This does seem like the sort of field where it needs to be recommended rather than required but I don't think JSON schema allows that middle tier

**Comment by daniwelter** [comment]
Agreed! There are quite a few fields that we'd like to somehow flag as "strongly recommended" but as you say, json schema only has required and optional. We might be able to look at a custom flag that we roll into our non-JSON schema validation that allows the json to validate but flags these fields to the user if they are empty.

**Comment by lauraclarke** [comment]
Sorry, just added an upate

**Comment by daniwelter** [comment]
If we remove the field altogether, this is a major schema update and we've done all our UX with both fields up until now. I think we should leave it in as optional in the short term and review once we're starting to get data.

**Comment by lauraclarke** [comment]
Sure, I think a review is a good idea after it has been running for a while. I am just concerned that the more general term being the required one might lead us to missing specific info

Do we have anywhere to keep open questions about metadata fields so we can review say when we have 10's of submission rather than the current situation

**Comment by danielvaughan** [comment]
+1 to having recommended fields. ENA has mandatory, recommended and optional fields. This could even help with an idea of having gold, silver and bronze submissions. Perhaps gold means all required and recommended fields?

**Comment by lauraclarke** [comment]
I have made two JIRA tickets about this

https://www.ebi.ac.uk/panda/jira/browse/HCA-593

and this one

https://www.ebi.ac.uk/panda/jira/browse/HCA-594

which is more about relationships.
