### ISSUE TITLE
Add field for expected file sizes

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/metadata-schema#260]
As a user I would like to have some way to validate that the files I have downloaded are of the correct size (no truncations). Ideally there would also be an md5 checksum.

Can I get some help filling in these fields from someone well versed in the schema? 
 
**Which schema needs be changed?** 

- `sequence_file.json`

**What field(s) in that schema need to be changed/added?**

- <s>new field for file size in bytes</s>
- optionally add a field for the md5 checksum

**What should the change/addition be?**

- see above

**Why is the change requested?**

- end user (Max Haussler) commented that he had no way to know if his downloads were correct, and that he would like to have at least a file size, but an md5 checksum would be great too. The checksum is less useful for large files because of the time it takes to run it can be impractical.

**Comment by lauraclarke** [comment]
Two important issue to consider for this is: when is this added to the metadata. This won't be supplied by the user and wherein the metadata does it belong? files.json makes the most sense from my perspective

**Comment by malloryfreeberg** [comment]
To note: there is already a `checksum` field in `file_core.json` that allows users to include a checksum value when they upload metadata. We don't specify what type of hash function to use to make the checksum, so we might consider either specifying a function or maybe adding a `checksum_function` field. Checksums submitted by users are required for GEO submissions, so it's not unprecedented to require this. 

We need to distinguish between validating successful upload of data from the user -> ingest and then from data store -> user download. Both are necessary but will happen at different stages.

**Comment by lauraclarke** [comment]
We will need to specify checksum type. otherwise, people won't know how to compare it. Differentiating between user supplied values and DCP written values is also important

I think anyone who is using the hca cli to download should't need to do their own checksum tests as I believe the program does it for them, this is something else we need to make clear in the documentation/FAQ

**Comment by kozbo** [comment]
The HCA CLI does not currently validate the checksums on the download. We
are hoping to implement this by go-live, see
https://github.com/HumanCellAtlas/data-store/issues/1144

**Comment by lauraclarke** [comment]
So in the first instance, we need a FAQ about how to get the checksums right now, it sounds like it is an extra command on top of the script

@kislyuk can you provide those instructions or point to someone who can

**Comment by malloryfreeberg** [comment]
@kozbo I see that Issue HumanCellAtlas/data-store#1144 is closed. Is your use case addressed? If so, let's close this ticket. If not, I would suggest moving this ticket to ingest-central as calculating file sizes should be something ingest does, not something users record in the metadata.

**Comment by kozbo** [comment]
HumanCellAtlas/data-store#1144 covers part of the data path, but leaves the final step off. 1144 validates that the network transfer was correct, but it doesn't verify the write to local storage. That step would have to be done by the end user. They would need a checksum for the data such that they could run a check on after the data was written to disk. The check will take a long time but they may want to run it anyway. Is there already a checksum for the data itself? It looks like we might already have it (just missing a checksum type field). If we have the checksum then we don't need a size field. The size field provides a quick check to see if the data was truncated.
What we need is a data integrity diagram that shows where the data validity is being checked as it is moved through the system.

**Comment by malloryfreeberg** [comment]
Thanks for the update. I've updated the original issue to note that a file size field is not needed anymore. 

Currently, the metadata schema support an (optional) user-supplied checksum value (although it doesn't specify what hash function the contributor should use), but this value isn't used anywhere as far as I'm aware. 
1. Do we want to do a check between the user-supplied checksum in the metadata schema and a system (DCP)-generated checksum?
  - If yes, this ticket needs to be moved to ingest-central repo
1. Does the metadata schema need to store a system (DCP)-generated checksum value anywhere?
  - If yes, then we need to figure out where it goes.
  - If no, then this ticket can be closed in the schema-repo

**Comment by diekhans** [comment]
We believe file integrity is the responsibility of the DDS.  The checksum field has been removed from the experiment metadata.   Checksums are available in the bundle manifest.  If would be good to have DSS API endpoints that can take a file fqid or uuid and return the informattion.

@kozbo if you agree, please close this ticket.

**Comment by kislyuk** [comment]
File size is returned by DSS both in the `GET bundle` response (as part of the bundle manifest entry for each file) and in the `GET file` response (in the `X-DSS-SIZE` header). The full instructions for retrieving the file checksums and sizes are available in the Swagger API specification on https://dss.dev.data.humancellatlas.org/.

**Comment by diekhans** [comment]
This is the responsibility of DSS; closing.
