### ISSUE TITLE
Rename technical_replicate_group_id to library_preparation_id

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/metadata-schema#262]
Not sure what this would go under but the issue is confusing labeling for library_preparation_process which leads to misunderstandings in library grouping. This should be an easy fix as its more of a current way we do it rather than a structure or content change to my understanding. We would just need to have a library_preparation_process for each library created. @malloryfreeberg would that work?

**Comment by malloryfreeberg** [comment]
I think this issue will be addressed with the new rearrangement of process and protocol fields, and the new way to link biomaterials and files in the spreadsheet. When we have examples of how this has been fixed, we will link them here.

**Comment by daniwelter** [comment]
@malloryfreeberg bumping this for comment

**Comment by hewgreen** [comment]
This will be resolved with https://github.com/HumanCellAtlas/metadata-schema/pull/425

**Comment by lauraclarke** [comment]
@hewgreen how will it be resolved. As we can see from the most recent zendesk ticket, library names and technical replicate labels are a concern for people

**Comment by hewgreen** [comment]
Maybe we could change the name of technical replicate id to library prep id?

**Comment by lauraclarke** [comment]
Is this a sequencing specific field?

**Comment by hewgreen** [comment]
I think it is given our definition of technical replicate. It only sits on sequencing file at the moment too.

**Comment by lauraclarke** [comment]
If it is sequencing specific, then renaming it to library prep id seems reasonable.

This does mean that people can make their own assessment about technical replication too as two sequencing runs of the same library on different sequencing machine models (hi-seq and next-seq for example) may or may not be considered technical replicates

**Comment by hewgreen** [comment]
PR https://github.com/HumanCellAtlas/metadata-schema/pull/633
