### ISSUE TITLE
Metadata release process specification

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#266]
The new metadata release process specification can now be reviewed in Google docs (https://docs.google.com/document/d/1RBmq-AbKwqm2ElYXx2Iyxt54xyAsH5jn1stPzePmIao/edit). The spec is also available here: https://github.com/HumanCellAtlas/metadata-schema/blob/dw-HCA-634_MetadataReleaseProcessSpec/docs/Metadata_schema_release_process.md.

We would invite comments and questions from other boxes on the specification as soon as possible (ideally by 4 May 2018) so we can modify the spec if necessary or move forward with the implementation of the release process.

**Comment by hannes-ucsc** [comment]
As people are probably aware from previous discussions, my approach to metadata versioning would be radically different. However, I think the train for radical changes has left. I did review the document and I think the approach it describes is functional and well-thought through.

**Comment by kbergin** [comment]
LGTM thank you!

**Comment by malloryfreeberg** [comment]
Closing this issue as the release SOP document has been circulated and put into practice. Feedback still welcome!
