### ISSUE TITLE
Add fields that HipSci uses for cell lines

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#275]
[HPSI0214i-wibj_2.CofA.20160227.pdf](https://github.com/HumanCellAtlas/metadata-schema/files/1993637/HPSI0214i-wibj_2.CofA.20160227.pdf)

Attached file is an example Certificate of Analysis for an iPSC cell line from HipSci - specifically [this](http://www.hipsci.org/lines/#/lines/HPSI0214i-wibj_2) line.

The CoA has some extra fields that we might consider capturing, in general, for other iPSC cell lines.
- **lot_number** (or **batch_number**; different from `catalog_number`, which we have)
- **cell_line_identity_test** and **cell_line_identity_test_result** (e.g. Fluidigm, pass)
- **cell_viability_result** - we have `cell_viability_method` and `percent_cell_viability`, but HipSci also has whether the method test passed/failed

There are a few more tests that HipSci lines undergo, but the ones listed above I think are probably the most useful.

Thoughts @pnejad ?

**Comment by pnejad** [comment]
Hi Mallory,

- **lot_number** is included in the ipsc induction schema we submitted ("**induced_pluripotent_cell_induction_kit_lot_number**"). 
- **cell_line_identity_test** and **cell_line_identity_test_result**: are they testing whether the cells are pluripotent? If yes, we have the "pluripotency_test" field. 
- We do need to capture information about **cell_viability**. What are their standards for "passed" vs "failed"?
-  Fields we should add are **"clearance_of_reprogramming_factors_test"** and **"clearance_of_reprogramming_factors_test_results"**. I used the field "subcellular_localization" in the spreadsheet I shared with you, but received feedback that the field name was unclear.

What do you think?

Tagging @willrockout so he is aware of possible changes.

**Comment by malloryfreeberg** [comment]
Thanks for the quick feedback!

- **lot_number** for the cell line is different from **induced_pluripotent_cell_induction_kit_lot_number** which I believe you meant to be for the kit. In the HipSci CoA, the lot number is specifically indicating the cell line for when someone purchases the cells from HipSci. So, we'll need both fields - **induced_pluripotent_cell_induction_kit_lot_number** on the process schema and **lot_number** (maybe **cell_line_lot_number**) on the biomaterial schema.
- Not sure what "identity test" is. Will have to investigate.
- I'm not sure what HipSci's standards are. Ideally it would be great to get % viability from submitters, but for banked lines like from HipSci, we might not have access to actual test values, only whether the test passed or failed.
- How does `subcellular_localization` relate to `clearance_of_reprogramming_factors_*`?

We have to be careful about what fields go on the iPSC *process* and what fields go on the iPSC *biomaterial*. I suspect the `pluripotency_test` fields will actually need to be moved to the cell_line biomaterial schema, as I think this is a test done on the cells post-induction process.

**Comment by lauraclarke** [comment]
I just want to confirm what Mallory is saying about the lot number. There is the kit which was used to produce the ipscs which people will know if they made them themselves but probably not if they were bought from a cell respository

Then there is the individual batch of ipscs used (and hopefully passage number) which indicated which batch was grown up and frozen at the same time from a particular ipsc clone. I suspect more people will have the latter

**Comment by pnejad** [comment]
I misread Mallory's first comment. Cell line lot # and induction kit lot # should be separate fields.

**Comment by malloryfreeberg** [comment]
I am proposing the following new field to capture cell line information, partially motivated by what HipSci reports:

1. Which schema needs be changed?
`cell_line.json`

1. What field(s) in that schema need to be changed/added?
New field: `lot_number`

1. What should the change/addition be?
Field name: `lot_number`
Field description: The supplier lot or batch number for the cell line.
Required: no
Example: 24.10.14
CV or enum: no

1. Why is the change requested?
Purchased cell lines - in addition to having a catalog number from a specific manufacturer/provider - will also come with a lot or batch number. This lot/batch number should be recorded.

**Comment by malloryfreeberg** [comment]
I am proposing the following new field and field update to extend cell morphology module, partially motivated by what HipSci reports:

1. Which schema needs be changed?
`cell_morphology.json`

1. What field(s) in that schema need to be changed/added?
New field: `cell_viability_result`
Updated field: `cell_viability` -> `percent_cell_viability`

1. What should the change/addition be?
**New field**
Field name: `cell_viability_result`
Field description: Whether the result of the cell viability test is pass or fail.
Required: no
Example: pass
CV or enum: yes: pass, fail
**Updated field**
Field name: Change `cell_viability` to `percent_cell_viability`
Field description: Percent of cells determined to be viable. (Unchanged)
Required: no
Type: string pattern, but a number range should be acceptable so follow the regex: "^[0-9]+\\.?[0-9]*-?[0-9]*\\.?[0-9]*$"
Example: 98.7
CV or enum: no

1. Why is the change requested?
Reporting cell viability is important. Current schema only captures the test method and the reported % viability. For purchased biomaterials, only a "pass" or "fail" for the test method is reported so we need a way to capture this. To differentiated between reporting a pass/fail on a test and reporting the actual % viability, we also need to update the `cell_viability` to specifically capture `percent_cell_viability` results.
