### ISSUE TITLE
nutritional_state missing type=string in medical_history schema 

### ISSUE THREAD

**Issue by simonjupp** [HumanCellAtlas/metadata-schema#277]
### 1. On which version of the code did the bug occur? (git hash, date, branch, be specific)

https://schema.humancellatlas.org/module/biomaterial/5.1.0/medical_history

### 1. Expected behavior

nutritional_state should have a `"type" : "string"`

### 1. Actual behavior

type is missing

**Comment by malloryfreeberg** [comment]
Thanks @simonjupp. This bug has been fixed in the `develop` branch and will be merged into `master` in the next few days as part of the schema release process.
