### ISSUE TITLE
single nuclei sequencing module required

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#298]
### Which schema needs be changed?
add new fields to existing lib prep module
or
add new module for single nuclei seq fields

The latter may be favoured if the number of fields is >3.

### What field(s) in that schema need to be changed/added?
We need to find out what metadata fields we need to capture for single nuclei experiments. I think this will likely be fields related to alternative sample preparation rather than changing the sequencing protocol itself.

### What should the change/addition be?
Specifics to be determined through feedback.

### Why is the change requested?
Several CZI awardees will have single nuclei sequencing data that will be ready to submit within the next few months. This technique somewhat overcomes cell sorting issues when a tissue has a diverse range of cell sizes and is being implemented to produce better representative datasets. Therefore, it is likely to be a key technique for the future.

**Comment by lauraclarke** [comment]
@jishuxu that sounds like we might need modules at both the biomaterial and protocol level then. Could you get example data

**Comment by hewgreen** [comment]
Although there are clearly protocol differences (mainly buffers) the metadata doesn't look too different to me. The key question we need help with is, **are any fields relevant to single nuclear sequencing that aren't relevant to single cell sequencing?**

**Comment by saralinker** [comment]
Hi @hewgreen, I'm a scientist in the Gage lab and am one of the leads on our single-nucleus RNA-seq project. Rusty forwarded your email to me to help out with some of these questions. 

**1. Are there any metadata fields that apply to single nuclei sequencing that don’t apply to single cell sequencing?**

We don't have metadata fields that are only for nuclei at this time. I might be saying things you already know, but if you're comparing cells and nuclei to one another in a large project like the Cell Atlas it would be useful to track variables like the exact amount of time whole cells were on heat / enzyme as this may change from batch to batch and multiple groups have shown that heat and enzymatic digestion can influence gene expression estimates.  

You may also want to include a field for %aligned to exons and %aligned to introns. While this would be done for both cells and nuclei, the estimates should be different (and discrepancies can offer a clue to the relative size of the nucleus compared to the cytoplasm - https://www.biorxiv.org/content/early/2018/01/19/239749)

**2. Would any fields that are relevant to both cells and nuclei (e.g. size), ever both be measured for the same original sample? For example, would a protocol measure cell size and then also nuclear size on the same cell after lysis?**

Great question, I haven't seen anyone do this, but it would be interesting to try. I’ve only seen the size comparison performed post hoc. The study linked above had identified a cell type which had an obvious increase in the proportion of nuclear transcripts compared to whole cell (nuclei and whole cell preps were done separately) and they then went back and examined the ratio of nucleus to cytoplasm with staining. 

Also, I was reading through the conversation above and there are multiple differences between whole cell and nuclei depending on which protocol you use (other than buffers). I'd be happy to chat on that topic as well if you want to discuss further.

**Comment by hewgreen** [comment]
Hi @saralinker,

Your comments are very useful. Thanks for replying to my email.

Can I clarify, when you say time on heat/enz, are your referring to a specific step?

If there are significant differences it may be more appropriate to model this as a separate protocol type in our schema. So I’d be very interested to hear what these multiple differences are you refer to. If you have time it to elaborate on this from your perspective it would be very useful to the community.

**Comment by pnejad** [comment]
@lauraclarke @hewgreen 
Below is a list of fields I've pulled out from a metadata template sheet used by a lab that does single nuclei sequencing.

- Nuclei Sample Tissue Weight
- Nuclei Sample Tissue Weight Unit
- Nuclei Sample Tissue RIN
- Nuclei Cell Concentration
- Nuclei Technique
- Nuclei Cell Size
- Nuclei Cell Size Unit
- Nuclei Cell Count
- Nuclei Cell Viability Count
- Nuclei Cell Dead Count
- Nuclei Debri Estimate
- Nuclei Clumping Estimate
- Nuclei Dilution Factor
- Nuclei Dilution Volume Used
- Nuclei Cell Initial Concentration
- Nuclei Cell Final Concentration
- Nuclei Post Dilution Technique
- Nuclei Post Dilution Cell Size
- Nuclei Post Dilution Cell Size Unit
- Nuclei Post Dilution Cell Count
- Nuclei Post Dilution Cell Viability Count
- Nuclei Post Dilution Cell Dead Count
- Nuclei Cell Suspension Interphase Time. Max time is 30 mins.
- Nuclei Suspension Interphase Time Unit
- Nuclei Recovered Cell Count
- Nuclei Recovered Cell Suspension Volume
- Nuclei cDNA PCR Cycle Number
- Nuclei cDNA Yield.
- Nuclei cDNA Fragment Size (Expected: 200-9,000)
- Nuclei Library QC Amount
- Nuclei Library QC Fragment Size  (Expected: 200-700)

Any input would be appreciated!

**Comment by saralinker** [comment]
Hi @hewgreen, for the heat/enz step, yes I'm referring to the tissue dissociation step that's often performed for whole cell sequencing. I've also included the manuscripts for more complete info about some different nuclear methods as well as a whole-cell method that reduces aberrant gene activation during dissociation. Of course there are more protocols than these, but they hit some of the main points. Hope this helps!

Main points: 
whole cell / papain digestion:  Enzymatic digestion at temperature to disrupt tissue
nuclei / dounce protocol: No enzymatic digestion, whole protocol performed on ice, mortar and pestle disruption of tissue (we also sorted by FACS, but this is not required)
nuclei / dronc-seq: cell lysis with buffer, myelin removal step

[CG000124_SamplePrepDemonstratedProtocol_-_Nuclei_RevD.pdf](https://github.com/HumanCellAtlas/metadata-schema/files/2037457/CG000124_SamplePrepDemonstratedProtocol_-_Nuclei_RevD.pdf)

[nihms799122.pdf](https://github.com/HumanCellAtlas/metadata-schema/files/2037460/nihms799122.pdf)

https://www.cell.com/neuron/fulltext/S0896-6273(17)30868-1

**Comment by malloryfreeberg** [comment]
Thank you so much for the useful info @saralinker ! We have a metadata field called `dissociation_method` that takes a generic value like "enzymatic", "mechanical", or "FACS", so this field could address part of the distinction you outlined in "Main points". We will take a look at the protocols you linked to and see where else we might be able to improve.

**Comment by malloryfreeberg** [comment]
We will need to make sure that the specific single nucleus sequencing approaches (e.g. sNuc-seq, Div-seq, DroNc-seq) are added to the HCAO for library preparation approach @daniwelter

**Comment by malloryfreeberg** [comment]
@daniwelter has confirmed/added the above snRNA-seq approaches into EFO. This ticket is on ice until we get further snRNA-seq datasets and can reassess whether additional new fields/module are required.

**Comment by malloryfreeberg** [comment]
I'm closing this issue. I think we've determined that we likely have the metadata fields required to capture single nuclei sequencing data. We ingest a DroNc-seq dataset as part of beta without any issues. In the future, if we come across something specific for snRNA-seq that we need, then a specific ticket can be created for that update.
