### ISSUE TITLE
migrate to HCA namespace

### ISSUE THREAD

**Issue by bkmartinjr** [HumanCellAtlas/metadata-schema#3]
Both schema $id and internal $ref's should use an HCA namespace.

Suggest migrating to something like http://schema.humancellatlas.org/ (which we could set up to point at github.io/humancellatlas/metadata-schema)

**Comment by bkmartinjr** [comment]
yes, approximately that (subject to a final decision about what base URL we use).

There are really three things we should do in concert (I've filed separate issues):
- pick a top-level official namespace for HCA schema (this issue)
- declare the canonical $id for each schema (this issue and issue #2)
- convert all the $ref's to point to canonical location (this issue)

And optional, but I think good form, use relative $ref URIs where it makes sense.   Style issue, but I think it makes things far more usable when you are working on a local file system.   I will file this.

**Comment by dosumis** [comment]
In order to progress on v4 (currently taking shape in a branch ), I have switched all $ref to local paths - following #4.  It should be relatively trivial to switch to an absolute URL once we have a namespace.

**Comment by daniwelter** [comment]
This is being implemented in the v5 prototype at the moment
