### ISSUE TITLE
Changes in requirement of fields for pilot launch

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#307]
The following fields are proposed to become **required** fields in preparation for the pilot launch. Please comment on a specific field(s) if you have thoughts. Making any field required in a schema will be a *major* version change for that schema.

### Protocol ontologies

1. `analysis_protocol.protocol_type`: An ontology term describing an analysis protocol.
1. `biomaterial_collection_protocol.protocol_type`: An ontology term describing a biomaterial collection protocol.
1. `dissociation_protocol.protocol_type`: An ontology term describing a dissociation protocol.
1. `enrichment_protocol.protocol_type`: An ontology term describing an enrichment protocol.
1. `imaging_protocol.protocol_type`: An ontology term describing an imaging protocol.
1. `library_preparation_protocol.protocol_type`: An ontology term describing a lib prep protocol.
1. `sequencing_protocol.protocol_type`: An ontology term describing a sequencing protocol.

### Process/protocol fields

1. `collection_protocol.collection_method`: A string field describing how the biomaterial was collected. Analogous `_method` field is already required in all other `biomaterial_collection` protocols.
1. `dissociation_protocol.nucleic_acid_source`: Source cells or organelles from which nucleic acid molecules were collected. Must be one of: bulk cell, single cell, single nucleus, bulk nuclei, mitochondria. Could potentially be required by secondary analysis group to know whether to launch pipelines using cell-, nuclei-, or mitochondria-based references.

### Biomaterial fields

1. `cell_line.cell_line_type`: The type of cell line. Must be one of primary, immortalized, stem cell-derived, iPSC, or synthetic.

### Analysis fields

1. `reference_file.ncbi_taxon_id`: A taxonomy ID (taxonID) from NCBI.
1. `reference_file.genus_species`: The scientific binomial name for the species of this reference.
1. `reference_file.assembly_type`: The assembly type of this reference. This applies to reference genome sequences.
1. `reference_file.reference_type`: The type of the genome reference. Must be one of: genome sequence, transcriptome sequence, annotation reference, transcriptome index, genome sequence index.
1. `reference_file.reference_version`: The genome version of the reference.

**Comment by malloryfreeberg** [comment]
@kbergin @jishuxu @samanehsan  If you have any feedback about the proposed required `reference_file` fields, I would much appreciate it!

**Comment by kbergin** [comment]
It seems good to me, the only thing I worry about is that we are using two references for our SS2 pipeline (transcriptomic for one analysis and genomic for another). Would the metadata be able to handle that information? @jishuxu am I saying this correctly?

**Comment by malloryfreeberg** [comment]
@kbergin RE 2 references: The `reference.json` bundle ([schema](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/bundle/reference.json)) - which will contain the reference files submitted by green box to ingest - takes an array of `reference_file.json` reference files. So, there is no technical barrier to green box submitting two reference files.
