### ISSUE TITLE
Shorten 12 metadata schema field names

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#311]
Changes to the following 12 metadata schema field names are requested:

1. <file_format>
**Which schema needs to be changed?**
Change to file_core.json
**What field in that schema need to be changed?**
file_format field
**What should the new field name be?**
Change to format
**Why is the change requested?**
Just to shorten things.

New ticket https://github.com/HumanCellAtlas/metadata-schema/issues/375

1. <process_location>
**Which schema needs to be changed?**
Change to process_core.json
**What field in that schema need to be changed?**
process_location field
**What should the new field name be?**
Change to location
**Why is the change requested?**
Shortening.

New ticket https://github.com/HumanCellAtlas/metadata-schema/issues/376

1. <operator_identity>
**Which schema needs to be changed?**
Change to process_core.json
**What field in that schema need to be changed?**
operator_identity
**What should the new field name be?**
Change to operator
**Why is the change requested?**
Shortening

New ticket https://github.com/HumanCellAtlas/metadata-schema/issues/377

1. <project_shortname>
**Which schema needs to be changed?**
Change to project_core.json
**What field in that schema need to be changed?**
project_shortname field
**What should the new field name be?**
Change to project_short_name
**Why is the change requested?**
Keeping consistent with underbar separation of words.

New ticket https://github.com/HumanCellAtlas/metadata-schema/issues/378

1. <is_child_of>
**Which schema needs to be changed?**
Change to familial_relationship.json
**What field in that schema need to be changed?**
is_child_of field
**What should the new field name be?**
Change to parent
**Why is the change requested?**
Shortening. 
1. <is_parent_of>
**Which schema needs to be changed?**
Change to familial_relationship.json
**What field in that schema need to be changed?**
is_parent_of field
**What should the new field name be?**
Change to child
**Why is the change requested?**
Shortening.
1. <is_sibling_of>
**Which schema needs to be changed?**
Change to familial_relationship.json
**What field in that schema need to be changed?**
is_sibling_of field
**What should the new field name be?**
Change to sibling
**Why is the change requested?**
Shortening

New ticket https://github.com/HumanCellAtlas/metadata-schema/issues/380
These three are in the same ticket as they are all the same basic change with the same proposed outcome.

1. <orgnaism_age>
**Which schema needs to be changed?**
Change to donor_organism.json
**What field in that schema need to be changed?**
organism_age field
**What should the new field name be?**
Change to age
**Why is the change requested?**
Shortening
1. <organism_age_unit>
**Which schema needs to be changed?**
Change to donor_organism.json
**What field in that schema need to be changed?**
organism_age_unit field
**What should the new field name be?**
Change to age_unit
Shortening
**Why is the change requested?**

New ticket: https://github.com/HumanCellAtlas/metadata-schema/issues/382
These two are in the same ticket as they are all the same basic change with the same proposed outcome.

1. <biological_sex>
**Which schema needs to be changed?**
Change to donor_organism.json
**What field in that schema need to be changed?**
biological_sex field
**What should the new field name be?**
Change to sex
**Why is the change requested?**
Shortening

New ticket:https://github.com/HumanCellAtlas/metadata-schema/issues/384

1. <nucleic_acid_source>
**Which schema needs to be changed?**
Change to dissociation_protocol.json
**What field in that schema need to be changed?**
nucliec_acid_source field
**What should the new field name be?**
Change to dissociation_contents
Clarification.  The biosample may be used for other purposes than nucleic acid extraction as well.
**Why is the change requested?**

New ticket:https://github.com/HumanCellAtlas/metadata-schema/issues/385

1. <donor_organism>
**Which schema needs to be changed?**
Change to donor_organism.json
**What field in that schema need to be changed?**
Name of schema
**What should the new field name be?**
Either donor.json or individual.json
**Why is the change requested?**
Shortening and clarification.  donor_organism reads very much like it should have values like "human" 
or "mouse."

New ticket: https://github.com/HumanCellAtlas/metadata-schema/issues/386

1. <specimen_from_organism>
**Which schema needs to be changed?**
Chane to specimen_from_organism.json
**What field in that schema need to be changed?**
Name of schema
**What should the new field name be?**
Change to body_part.json
**Why is the change requested?**
Shortening and clarification.  

https://github.com/HumanCellAtlas/metadata-schema/issues/389

1. <mus_musculus_specific>
**Which schema needs to be changed?**
Change to mus_musculus_specific.json
**What field in that schema need to be changed?**
Name of module
**What should the new field name be?**
Change to mouse_specific.json
**Why is the change requested?**
Keeps consistent with the human_specific module name

New ticket: https://github.com/HumanCellAtlas/metadata-schema/issues/387

1. <reference_file>
**Which schema needs to be changed?**
Change to reference_file.json
**What field in that schema need to be changed?**
Name of the schema
**What should the new field name be?**
Change to mapping_reference_file.json
**Why is the change requested?**
Clarification - refererence_file reads like it might be the PDF of an associated publication among other things.

https://github.com/HumanCellAtlas/metadata-schema/issues/388

**Comment by willrockout** [comment]
@malloryfreeberg @daniwelter @lauraclarke These are the fields/modules/schemas that Jim requested name changes too.

**Comment by lauraclarke** [comment]
@willrockout We have created independent tickets for most of these as it allows us to review and accept the proposals on their own merits without getting confused.

There is one remaining proposed change which does not yet have a ticket as I am seeking internal clarification on a point before I create the ticket.

specimen_from_organism to body_part

Once that is up I will comment again and it would be great for you or someone else from the UCSC to confirm these new individual tickets are fine and then we can close this one and proceed from the individual tickets.

**Comment by lauraclarke** [comment]
@willrockout all the issues now have their own ticket so if you are happy with the new tickets we can close this issue and work on the individual proposals.
