### ISSUE TITLE
New supplemental_file.json schema

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#313]
In order to attach supplemental files to a project/submission, we might need a new `supplemental_file.json` schema. It would import `file_core.json` and would potentially need additional field(s) to allow it to be linked to the biomaterial/protocol/project that it is associated with.

**Comment by hewgreen** [comment]
We may need this ASAP for MVP. We need 'file_core.file_name', 'biomaterial_core.biomaterial_id' (deprived from project or biomaterial at any level) and 'file_core.file_format'. We may also want to create a free text 'file_core.file_description'. 

On reflection I think scoping expected unsupported supplementary and orthogonal data types is a fools errand but we need the ability to understand and report what we have ingested post hoc. Therefore, file type should be enum and have text and also potentially ontology. This is important to clarify what users are giving us so we can later report what data types we have to inform (GG, analysis etc) what we should build in the future.

We need to understand what the 'derived from' should semantically mean. We may not necessarily want to create a process for each of these files and we may not want to create separate bundles for them. What do you think @simonjupp ?

**Comment by diekhans** [comment]
I think it's tragic to encourage labs to throw away data that
doesn't fit into the data model by restricting the types of
files.  I would agree that it is foolish to try to model every
odd bit of data or build quires on top of it.  However,
supplemental data can be very valuable when a human being
is trying to understand an experiment,

Also, file format doesn't dictate file content, only how the
bytes are laid out.  I have seen very interesting collection of
sequences in FASTA files.

**Comment by hewgreen** [comment]
@diekhans Referring to the enum suggestion. We definitely don't want to discourage submitters providing extra information. Currently this wouldn't discourage anything though (with the current UI). The files would be ingested anyway, validation would fail and a wrangler would be prompted to either add to the controlled vocabulary or seek further clarification if the type already existed in a different form. Later when moving to a less wrangler lead process relaxing the enum validation would be a non breaking minor change. Although, it may be too risky to do this now as we would be reliant on changing this when the UI evolves to become more self service.

Having said that, you are completely right about file type. The file_type is not the most important thing at all. Its much more useful to capture what technique/technology was used to create the file. My use case here is in a few years time I want to be able to say what percentage of projects uploaded CyTOF data (as one example of data that is not currently processed past ingest). This is useful to inform which metadata and pipelines to develop. Manually we could eek this out if we don't have many projects but I'd like to think of a way to capture this so we have better than a free text free for all to analyse at a later date.

**Comment by hewgreen** [comment]
Other than the fields in file_core, I have proposed three additional fields:

**supplementary_type** (required) is a enum for one of "Supplementary analysis", "Supplementary data" and "Supplementary metadata". This broad categorisation along with the link to the biomaterial helps users to understand what the file contains. The data viewer could group files based on this field.

**source_method_name** (optional) this field is ontology linked and should contain the method or technique that was used to derive the supplementary data/analysis. this will allow us to investigate types supplementary information across multiple datasets to scope further ingest use cases.

**data_source** (optional) this should be a URL to a database record. For example this is useful to link to health records or data records.

Please add feedback.

**Comment by lauraclarke** [comment]
Is the supplementary_type file actually useful? who are you expecting to use this field? people will just pick which ever is first in the dropdown list I would imaging

**Comment by lauraclarke** [comment]
@hewgreen Can you write up what we agreed when talking in person and then modify the schemas to reflect that

**Comment by hewgreen** [comment]
Yep. I'm on it.
