### ISSUE TITLE
Capturing "missing" data in structured way

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#315]
There should be a more structured and consistent way to represent missing **required** metadata. FAANG has a decent setup that seems to work for them: https://github.com/FAANG/faang-metadata/blob/master/docs/faang_sample_metadata.md

The following points should be considered:

- Where data cannot be included in a submission, submit one of these text values instead
  - 'not applicable' (i.e. does no apply to this sample)
  - 'not collected' (i.e. will always be missing)
  - 'not provided' (i.e. may be added later)
  - 'restricted access' (i.e. it isn't missing, we just can't include it in a public document)
- The use of these values will interact with the metadata validation system as follows:
  - attribute is required
    - not applicable, not collected, not provided - validation will regard these as an error
    - restricted access - validation will generate a warning
  - attribute is recommended (**HCA currently does not have this designation**)
    - not collected, not provided - validation will generate a warning
    - restricted access, not applicable - pass
  - attribute is optional
      - validation will pass with any of missing values terms

---

- [x] Make proposal for this as RFC
- [x] Announce RFC on #hca-metadata

**Comment by lauraclarke** [comment]
This is a standard FAANG borrowed from INSDC (the sequencing archives)

**Comment by daniwelter** [comment]
See https://www.ebi.ac.uk/ols/ontologies/genepio/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGENEPIO_0001850 for structured capture of terms in ontology

**Comment by malloryfreeberg** [comment]
The current terms in the ontology Dani linked to:

- **missing**: "When a measurement value was known to be recorded in the past but the observed value cannot be located or retrieved for some reason."
    - **in process**: "While the data for a given measurable datum has not finished being collected, is awaiting a conclusion, or has not yet been communicated."
    - **not collected**: "When a datum was not measured with respect to some entity during some process."
    - **not provided**: (The description is missing but I imagine it's something like "When a datum is potentially available but not recorded here.")
    - **restricted access**: "When the data for a given measurable datum is available but not shared publicly because of information privacy concerns."
- **not applicable**: "When a measurable datum does not apply to a given context, as for example the measure of femur length for a patient with a missing limb."
- **recorded**: "When a recorded datum is known to be available for retrieval."

I think that for our purposes, the **recorded** value should not be acceptable (if it's recorded it should be the recorded value.

The **not applicable** value should only be acceptable for required fields for which the metadata field truly isn't applicable. I can't think of any instances at the moment where this might occur. And if it does occur, we should rethink where the metadata field lives (maybe it belongs in a module).

The **restricted access** value should not be allowed as all the data and metadata must be open access.

**Comment by malloryfreeberg** [comment]
We will likely need to convert this issue into an Epic (post phase 1) and identify specific actions to take to achieve this goal. I think addressing this issue/epic will take more work in infrastructure/validation than in the schema itself.

**Comment by malloryfreeberg** [comment]
Also to think about: how to use these terms for fields that are type integer, ontology, or anything else that isn't a free text string. Do we modify the validator to allow "missing" text strings for fields expecting integers, e.g.?

**Comment by hewgreen** [comment]
Just to note, a consequence of adding these values will be a large increase in size of metadata JSON. We will go from files that only contain the provided information to potentially having metadata files with all the fields. We may still want to define what empty means. If a field is completely missing we could state that this means 'not provided' to save some churn.

**Comment by daniwelter** [comment]
Structured capturing of missing information is in no way intended to be used for every single field for which no information was provided. The intention is rather to provide a more well-defined means of capturing why information wasn't provided for required fields. This strategy will also allow us to use required fields more extensively for information that should reasonably be expected to be available but may be missing occasionally.

**Comment by hewgreen** [comment]
That sounds fair but these points need to be communicated carefully to the contributors as other views on this will exist. Good metadata is complete metadata. Previously we have received sheets full fields such as NA, 'impossible to collect', 'cannot disclose due to privacy legislation' etc. Consumers have also asked if we have specific missing metadata fields via Zendesk.

So another use case for this metadata is to describe why certain fields are missing and this could apply to non-required fields. If this is firmly out of scope here we should discuss why.

**Comment by malloryfreeberg** [comment]
Should we make a formal RFC (via the GitHub RFC mechanism) for this? Or should we just keep this change in the metadata-schema repo? Wondering if, for now, we can implement this using our shiny new (almost) linter instead of trying to hack at the js validator.

**Comment by daniwelter** [comment]
RFC now open for comments https://docs.google.com/document/d/1-HSIwZKOabjk9Ziee8WD_67tbdyFzIVfDQESzqVqm3k/edit#heading=h.xe1eqwz3nqmr

**Comment by malloryfreeberg** [comment]
@daniwelter is there a deadline for when you want comments by?

**Comment by daniwelter** [comment]
I'd settle for any comments at all but I guess in the interest of sticking to the sprint, by the end of the week?

**Comment by daniwelter** [comment]
Based on comments received in the doc and on the Metadata call on 25/02/2019, this proposal is likely no longer relevant.

**Comment by ESapenaVentura** [comment]
Is this issue still a thing, or should we close it?

**Comment by malloryfreeberg** [comment]
We still need to do this. The implementation is unclear.

**Comment by diekhans** [comment]
I would much rather have the missing reason be a separate field instead of part the value. This allows the value to keep its type and NULL be specified for simple filtering and actually having an explanation if one cares.

**Comment by lauraclarke** [comment]
It is good to think about the value associated with capturing structured null information.

If there is clear evidence of value then we should balance contributor and consumer needs and effort for a controlled vocab in the field vs an ancillary field to capture the reason for both user groups. 

I could envision a reason why people might want to filter on type of null too as people might want to avoid datasets where a particular value is not collected but might be happy to request restricted access fields if they valued having that information for the context they wanted to use the field in.

To provide some background, the original list was taken from INSDC standards, in the FAANG context which inspired the idea in the HCA context these values are only required to be filled out for the middle context of recommended fields. Mandatory fields aren't allowed to be null and optional fields can be empty.

If we don't go down that route it might be that this isn't needed anyway as the effort for contributors even with only one field is quite high.

Another context which might require one of these values is if for donor and maybe specimen fields once we understand how to best comply with GDPR and other privacy legislation for alive donors. 

I know the compliance working group has already floated the idea of at least coarsening if not redacting some fields for donors who are subject to GDPR to ensure we are compliant with the legislation, that might mean that restricted access is a good way to provide transparency for fields where we have data but can't publicly distribute it.

**Comment by zperova** [comment]
Having an analysis of FAANG metadata fields will be helpful for this ticket: https://github.com/HumanCellAtlas/metadata-schema/issues/1137
