### ISSUE TITLE
Ability to submit array of external IDs for datasets

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#324]
~1. Which schema needs be changed?~
~`project.json`~

~1. What field(s) in that schema need to be changed/added?~
~`insdc_project`, `geo_series`, `array_express_investigation`, and `insdc_study`~

~1. What should the change/addition be?~
~These fields should be changed from a single string matching a pattern to an array of strings each matching the pattern. ~

~1. Why is the change requested?~
~We are brokering a Single Cell Expression Atlas dataset in which a single project has both SS2 and 10x data that were submitted to archives separately with their own accessions. This means that this single HCA project will reference 2 GEO, 2 INSDC project, and 2 INSDC study accessions.~

**For which schema is a change/update being suggested?**

I would like to request an update the the `project.json` schema.

**What should the change/update be?**

- [x] change `insdc_project` to `insdc_project_accessions` and make the field type: array
- [x] change `geo_series` to `geo_series_accessions` and make the field type: array
- [x] change `array_express_investigation` to `array_express_accessions` and make the field type: array
- [x] change `insdc_study` to `insdc_study_accessions` and make the field type: array

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

I would like to change all the accession fields to arrays to support users entering multiple accessions if their data were deposited into an archive in more than one batch. I would also like to change the field names to be internally consistent and to be plural, in order to adhere to the Style Guide.

**Comment by lauraclarke** [comment]
@malloryfreeberg Is this something which needs to be actioned before the end of phase1?

**Comment by malloryfreeberg** [comment]
No, this is not required for phase 1. The dataset mentioned in the original issue will only be ingested with the SS2 data, so we don't need these fields to be arrays at the moment. 

I think there was a suggestion (can't remember who from) about not modelling different external references explicitly, but just having a single `external_database_id` field that is an array of any IDs. We can revisit this issue after phase 1.
