### ISSUE TITLE
Add "feeder_layer" field to iPSC schema

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#327]
**For which schema is a change/update being suggested?**

I would like to request an update the the `ipsc_induction_process.json` schema.

**What should the change/update be?**

I would like to add a new field to this schema called `feeder_layer`.

**What new field(s) need to be changed/added?**

* Field name: `feeder_layer`
* Field description: **TBD**
* Required: No
* Example: "feeder-free"
* CV or enum: Yes, an enum. Accepted values should be: "feeder-free" and "feeder-dependent"

**Why is the change requested?**

**TBD**

**Comment by malloryfreeberg** [comment]
@pnejad please fill out the **TBD** sections of this issue so that we can add the new field to the schemas.

**Comment by pnejad** [comment]
**For which schema is a change/update being suggested?**

I would like to request an update to the growth_conditions.json schema.

**What should the change/update be?**

I would like to add a new field to this schema called feeder_layer.

**What new field(s) need to be changed/added?**

**Field name**: feeder_layer
**Field description**: Feeder-free if biomaterial is not grown on a feeder layer. Feeder-dependent if biomaterial is grown on a feeder layer. 
**Required**: No
**Example**: "feeder-free"
**CV or enum**: Yes, an enum. Accepted values should be: "feeder-free" and "feeder-dependent"

**Why is the change requested?**

We received feedback from researchers that this field is important for their experiments.

**Comment by pnejad** [comment]
@malloryfreeberg Thoughts on moving this to growth_conditions.json instead?

Feeder layer info should be captured for both iPSC's and stem cell lines (before they are differentiated).
