### ISSUE TITLE
Add "feeder_layer_type" to growth_conditions schema

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/metadata-schema#329]
**For which schema is a change/update being suggested?**
I would like to request an update to the growth_conditions.json schema.

**What should the change/update be?**
I would like to add a new field to this schema called feeder_layer_type.

**What new field(s) need to be changed/added?**

* Field name: feeder_layer_type
* Field description: Type of feeder layer cells biomaterial was grown on.
* Required: No
* Example: "MEF Feeder Cells", "JK1 Feeder Cells", "SNL 76/7 Feeder Cells", "Human Marrow Stromal Cells"
* CV or enum: No

**Why is the change requested?**

This change is requested to capture the type of feeder layer cells biomaterial is grown on. The type of feeder layer used may have different effects on biomaterial growth/proliferation.

**Comment by malloryfreeberg** [comment]
Combine with PR #327
