### ISSUE TITLE
Add smoking_history, alcohol_history and feeding_status to donor, and change submitted_id to submitter_id

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#33]

**Comment by lauraclarke** [comment]
Where is submitter_id being stored and who is responsible for filling it in?

**Comment by daniwelter** [comment]
You can ignore that, we just realised the field is redundant as it is captured at sample level

**Comment by lauraclarke** [comment]
Don't we need that for all entities, surely the person who submitted a sample might be different from person who submitted a project or an assay

Happy to be told if I am missing context

**Comment by daniwelter** [comment]
At the moment, the json schema only tracks one submitter or updater at ingest.json level, but not at the time when the individual files are added. I think this may need a wider discussion about tracking and metadata, and the appropriate level of granularity.

**Comment by daniwelter** [comment]
Completed for v4
