### ISSUE TITLE
Make project_description required

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#330]
**For which schema is a change/update being suggested?**

I would like to request an update the the `project.json` schema.

**What should the change/update be?**

Make the field `project_description` required.

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

The data portal and data browser would like to be able to display summary information about projects.

**Comment by malloryfreeberg** [comment]
Currently the `project_shortname` and `project_title` are required for all projects, and this request is to make the `project_description` also required. The description is requested to be required as it typically contains more information about the motivation behind and general approach for the project. This would mean that all 3 fields are now required. In most cases (preview and pilot), we've gotten all 3, so I don't think it would be much of a stretch to make these required. Thoughts @lauraclarke ?

```
"project_shortname": "A unique label for the project."
"project_title": "A summary of the project in a sentence."
"project_description": "A longer description of the project which can include research goals and experimental approach."
```

**Comment by lauraclarke** [comment]
I think requiring a description is fine. The worse is someone just cut and pastes their long title
