### ISSUE TITLE
Add purchased_reagent module to specimen_from organism

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#333]
**For which schema is a change/update being suggested?**

I would like to request an update the the `specimen_from_organism.json` schema.

**What should the change/update be?**

I would like to add the purchased_reagents module to this schema as a new field called something like `purchased_specimen` which points to the puchased_reagents module.

**What new field(s) need to be changed/added?**

* Field name: `purchased_specimen`
* Field description: Information about a purchased specimen.
* Required: No
* Example: none needed (this field should import the` purchased_reagents` module)
* CV or enum: No

**Why is the change requested?**

Specimen_from_organism is sometimes a blood sample. Blood samples can be purchased from companies, so we need to capture information about where the sample came from.

**NB** Specifically, we need this for the ICA preview dataset.

**Comment by daniwelter** [comment]
Change done in branch and committed. PR to be done post-metadata release 11/6/18
