### ISSUE TITLE
Roles for contributors

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#352]
Change for contact.json

New field addition Role and orcid id

role - we might want an ENUM here something like (project_member, external_curator, dcp_wrangler) We should consult on what the best labels might people as people might want to differentiate between bioinformatician, maybe free text is best in the first instance

orcid id - the orcid id of an individual

This is to help provide credit to everyone including those who prepared the datasets for submission and evetually link back to orcid records

**Comment by lauraclarke** [comment]
@malloryfreeberg @hewgreen has anything been done about this?

**Comment by hewgreen** [comment]
I talked to the wranglers about this at UCSC and they thought it was a good idea. I don't think we have done the work yet though. Let me know if it should be highly prioritised.

**Comment by lauraclarke** [comment]
As the next data release will contain data which was curated by the expression atlas having it in the system before they are ingested would be good if possible but it isn't a showstopper.

**Comment by hewgreen** [comment]
created PR https://github.com/HumanCellAtlas/metadata-schema/pull/408
