### ISSUE TITLE
Do we have sufficient and appropriate plate metadata for smart-seq 2 experiments

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#355]
This thread aims to establish if we have the correct plate metadata for smartseq 2 experiments

https://github.com/HumanCellAtlas/metadata-schema/blob/develop/json_schema/module/process/sequencing/smartseq2.json

Property name | Description | Type | Required? | Object reference? | User friendly name | Allowed values | Example
-- | -- | -- | -- | -- | -- | -- | --
plate_id | An ID for the plate that the well is located on. | string | no |   | Well plate ID |   |  
well_name | A name for the well. Should be unique for the plate | string | no |   | Well name |   |  
well_row | Well row in plate. | string | no |   | Well row |   |  
well_column | Well column in plate. | string | no |   | Well column |   |  
cell_quality | Note on how good cell looks if imaged in well before sequencing. | string | no |   | Cell quality | OK, control, 2-cell well, control, empty well, low quality cell

We are thinking about removing either well_name or well_row/well_column as we don't think they will record different info not sure what is best

We want to make plate_id required

We need a way of specifying different wells have different lysis buffer, this might be most easily done with different protocols rather than here

@mckinsel @ambrosejcarr @dshiga @TimothyTickle Your thoughts would be appreciated

**Comment by lauraclarke** [comment]
@jishuxu could you take a look here for plate based metadata

**Comment by malloryfreeberg** [comment]
Specifying different lysis buffers can be done at the protocol level, I believe. For plate-based sequencing, each cell/well is a row in the cell suspension tab, so we can have the lysis buffer at this level of granularity.

**Comment by jishuxu** [comment]
1. I would like to see well_ID(such as A12, B39...) and plate_ID as required field. we will use plate_ID to identify batch. the well_ID is also crucial. Some of the technical failure are associated with well_id. 
2. Is there any meta data just for plate, such as Illumina HiSeq plate(96 wells) or NovaSeq plate (384 wells)
3. Sometimes, the samples/cells in one plate are mixed from different experiments so the data uploaded to HCA/DCP probably just partial of one plate. Is there meta to address this yet?

**Comment by malloryfreeberg** [comment]
Following-up: @jishuxu Do you required an accurate `well_id` (e.g. as you said, A12, B39) to assess quality? If a group doesn't have the well IDs recorded, and just supply us with integers (e.g. 1-96 for a 96-well plate), would that suffice your use case? If we make `well_id` required, but a group doesn't have this info, they will likely just make something up. Would that be a problem for your use case?

**Comment by TimothyTickle** [comment]
Would 1 always start at a specific space and would this always go by column
or row? Otherwise, it will not be possible to understand how the numbers
relate spatially.

**Comment by lauraclarke** [comment]
I think the challenge here is different groups will address their plates and wells in their plates in different ways. We can't guarantee that well id will be interpretable to give you positional information. 

https://preview.data.humancellatlas.org/datasets/melanoma/hca-metadata-melanoma.xlsx
Looking at the melanoma dataset in the preview release we have well names which look like 

22421_6#272

I suspect the first part is the plate name and the second part is the well id but where on the plate 272 was there is no clue.

I suspect insisting on accurate well location information may well lead to submitters who don't know just making up and then providing misleading information to your QC pipelines which we don't want to happen.

@malloryfreeberg @hewgreen can you look at all the SS2 data we have got directly from labs and see how much information is provided on a well basis, that should give us a good idea of how likely we are to get that info

**Comment by jishuxu** [comment]
Here is what I am thinking.
1. The unambiguous well_id or well_map will be crucial for downstream data normalization and analysis but not necessary for secondary-analysis.  
2. I would like to see a consistent formatting conventions for well_id.  it is also easier for data browsing, filtering service.

**Comment by jishuxu** [comment]
@malloryfreeberg, `partial plate sample` or . `full plate` can be confounding factors with final gene expression. Such fields probably will be in the plate meta data but not in cell meta data.

**Comment by daniwelter** [comment]
@lauraclarke In the latest iteration of the plate_based_sequencing module, this hangs off cell suspension rather than file https://github.com/HumanCellAtlas/metadata-schema/pull/398/files

**Comment by lauraclarke** [comment]
So we are duplicating plate wide information for each cell suspension then

Are there any other fields which are duplicated? 

I suspect as much as I would like plate and well based information to be separate there is probably no way to do that yes?

**Comment by malloryfreeberg** [comment]
@lauraclarke There is 1 process per cell/pair of fastq files. For SS2 datasets we've seen, the cell suspension tab has been filled in with 1 cell/well per row. Each of these rows is then connected to it's pair of fastq files by 1 process. A per-cell separation is required in cases where FACS sorting is used because any given cell on the plate could be sorted from a unique set of markers.

**Comment by lauraclarke** [comment]
Yeah, I was just wondering there would be a way to minimize duplication of the general plate information to minimize risk of typos.

I guess this might need to be a summary state in a future version which says

This submission contains X plates
Plate1 has 95 entries
late1 has 1 entry

So people can spot if they have made a typos

**Comment by lauraclarke** [comment]
This is true but I suspect we are a distance from having a UI which checks for those sorts of typos. We aren't even exposing users to a UI at all yet.

In the short term summaries are likely to be easier to implement

**Comment by ambrosejcarr** [comment]
Sorry for the late comment. Mostly I'm posting in support of the existing discussion: 

> We are thinking about removing either well_name or well_row/well_column as we don't think they will record different info not sure what is best

I support whichever approach can be unambiguously decoded to extract the following information: 
1. Which column is a cell contained in? 
2. Which row is a cell contained in? 
3. Is this well on the edge of a plate?

Basically, I want to be able to determine the spatial localization of the cell. I don't care how it's implemented in metadata. 

> We want to make plate_id required 

👍
