### ISSUE TITLE
New organ_donation_death_type field 

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#361]
**For which schema is a change/update being suggested?**

I would like to request an update to the `death.json` schema.

**What should the change/update be?**

I am requesting an addition field called `organ_donation_death_type` to capture the type of death experienced by an organ donor.

**What new field(s) need to be changed/added?**

* Field name: `organ_donation_death_type`
* Field description: For organ donors only, donor type (DCD / DBD)
* Required: no
* Example: Donation after circulatory death (DCD)
* CV or enum: Yes. Valid values should be: "Donation after circulatory death ([DCD](https://www.odt.nhs.uk/deceased-donation/best-practice-guidance/donation-after-circulatory-death/))", "Donation after brainstem death ([DBD](https://www.odt.nhs.uk/deceased-donation/best-practice-guidance/donation-after-brainstem-death/))"

**Why is the change requested?**

Discussions with scientists/teams working with Addenbrooks and other hospitals that provide organs for donation have identified that indicating the type of death that donors experienced is important. Although important, it is not always available so this field shouldn't be required. One of the preview/pilot datasets uses this field. Open to alternate names, making this an ontologized field, or expanding the enum.

**Comment by malloryfreeberg** [comment]
@lauraclarke @claymfischer what do you think about this field? It is requested from one of the pilot submitters. Is there a third party you think we could ask about this?

**Comment by lauraclarke** [comment]
This seems like a good idea as they are different
