### ISSUE TITLE
New NRP field to donor_organism.json

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#362]
**For which schema is a change/update being suggested?**

I would like to request an update to the `donor_organism.json` schema.

**What should the change/update be?**

I would like to add a new field - `normothermic_regional_perfusion`.

**What new field(s) need to be changed/added?**

* Field name: `normothermic_regional_perfusion`
* Field description: Yes if donor's body (but not limbs) was perfused with warm oxygenated blood from the donor. No otherwise.
* Required: No
* Example: Yes
* Enum: Yes, No, Unknown
* User-friendly name: "Normothermic regional perfusion?"

**Why is the change requested?**

One of the pilot datasets has data from different donors that either were or were not treated with normothermic regional perfusion. This field is different from the `cold_perfused` field, which is perfusion of body/tissue with cold organ preservation solution (not oxygenated).

**Comment by malloryfreeberg** [comment]
@lauraclarke @claymfischer what do you think about this field? It is requested from one of the pilot submitters. Is there a third party you think we could ask about this?

**Comment by lauraclarke** [comment]
Is there a circumstance where this term would be used for perfusing a region which was different from the core body? then we might want a yes and a region tag

Otherwise it seems fine.

**Comment by lauraclarke** [comment]
I would post it on slack and tag Deanne maybe? or ask the Addenbrookes folks
