### ISSUE TITLE
Change describedBy to snake_case to maintain consistency with field names

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#367]
**For which schema is a change/update being suggested?**

I would like to request an update to all schemas.

**What should the change/update be?**

Change `describedBy` to `described_by` to be consistent with other field names.

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

To keep metadata field cases consistent.

**Comment by malloryfreeberg** [comment]
This has been postponed indefinitely due to the complexity of downstream dependencies. There has been some discussion on calls ([here](https://docs.google.com/document/d/1jmYXKi_mxW8IXNwhlYK_e13kUwjAA-uDomjttSY0S30/edit)) and on some Slack channels.

**Comment by lauraclarke** [comment]
@malloryfreeberg I guess putting this on ice for now makes sense?
