### ISSUE TITLE
Rename field file_format to format

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#375]
Ping Hannes, Dave

### Original request

1. <file_format>
**Which schema needs to be changed?**
Change to file_core.json
**What field in that schema need to be changed?**
file_format field
**What should the new field name be?**
Change to format
**Why is the change requested?**
Just to shorten things.

### Consequences

1. “format” is a reserved keyword in JSON schema. While keywords can be overloaded, this should be avoided if at all possible to prevent confusion over usage. “format” could also be used in other contexts, eg submission format, which would further overload the label.

1. From a usability point of view, this doesn’t comply with the principles for: “recognition rather than recall”, “visibility of system status”, “error prevention” [https://www.nngroup.com/articles/ten-usability-heuristics/](https://www.nngroup.com/articles/ten-usability-heuristics/) , as it might be ambiguous if not carrying the specific context (i.e. format could be for time, date, etc)

1. Will break analysis pipelines (writing analysis results to ingest; querying on input fastq files) and data portal filters.

**Comment by lauraclarke** [comment]
I do not recommend this proposal is taken forward. It reduced the specificity of the term making it less clear and also created issues from a JSON schema keyword perspective

**Comment by malloryfreeberg** [comment]
Format is a JSON schema reserved word. We shouldn't shorten `file_format` to `format` as otherwise it might cause issues with use of standard JSON parsing code in future. The user-friendly name for this field can certainly just be "Format" without causing confusion to people filling out the spreadsheet (it usually appears just after "File name", giving it context).

**Comment by diekhans** [comment]
Notes, this is in responses to a discussion in the metadata meeting.

`format` is an attribute in JSON schema, but its context is different than the context where a field name is declared.  There is no chance of there being a name collision.   JSON schema imposes no reserved words on JSON documents.   Example farther below.

JSON types are fundamentally programming data structures.  While there is a strong relationship between the names in the metadata data structure objects, those in spreadsheets, and those in GUIs, they are better bound by a level of indirection.  By attempting to foresee the future in creating a single name that works for all of these environments, the data structures are both cumbersome to use and the system very complex.

Any change to the requires for a GUI component necessitates a breaking change to the data structure.

Example of how metadata format does not collide:
`{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "A file entity contains information about a file produced from any process.",
    "additionalProperties": false,
    "required": [
	"name",
	"format",
        "creation_date"
    ],
    "title": "file",
    "type": "object",
    "properties": {
        "name": {
            "description": "The filename of the file.",
            "type": "string"
        },
        "format": {
            "description": "The format of the file.",
            "type": "string"
        }, 
        "creation_date": {
            "description": "Date the file was created",
            "format": "date-time"
        }, 
    }
}
`
and the corresponding object would be:
`{
    "name": "mystuff.fastq.gz",
    "format": "fastq",
    "creation_date": "1985-04-12T23:20:50.52Z"
}
`

There is no collision between the symbol `format` for the programmer as these are in different scope and even data structures.  This is obvious to any programmer who understands JSON.

It is up to the GUI designer to look up and properly format the names in a way that is clear and unambiguous for non-programmers.  The way to do this will even vary between different GUI designed.  It would greatly constrain the GUI developer to couple the data structure name to the GUI or spreadsheet name.

**Comment by diekhans** [comment]
BTW, the above comment is neutral on changing the field name at this time.

From my observations, the metadata has gone down a path were ut needs stop moving as much as possiblele, get out the first HCA release. Then revisit in based on leasons learned with clear separation of needs of programmers and GUI developers.

**Comment by lauraclarke** [comment]
@diekhans I am going to put this on ice for now and we can come back to it after the MVP is out and consider all the angles.

**Comment by malloryfreeberg** [comment]
I want to maybe bring this out the icebox as we are actively working to adhere to our Style Guide now. Currently, a JSON instance of a sequencing file, e.g., would be:

```
{
    "describedBy": "https://schema.humancellatlas.org/type/file/6.5.2/sequence_file",
    "schema_type": "file",
    "file_core": {
        "file_name": "S1_L001_I1_001.fastq.gz",
        "file_format": "fastq.gz",
        "checksum": "e09a986c2e530130b1849d4bf9a94c06"
    },
    "read_index": "index1",
    "lane_index": 1,
    "provenance": {...}
}
```

And the corresponding fully qualified name would be `file_core.file_format`.

If we change the field name to `format`, we would have:
```
{
    "describedBy": "https://schema.humancellatlas.org/type/file/6.5.2/sequence_file",
    "schema_type": "file",
    "file_core": {
        "file_name": "S1_L001_I1_001.fastq.gz",
        "format": "fastq.gz",
        "checksum": "e09a986c2e530130b1849d4bf9a94c06"
    },
    "read_index": "index1",
    "lane_index": 1,
    "provenance": {...}
}
```

And the corresponding fully qualified name would be `file_core.format`.

I think this change is clear and as @diekhans said, having a field named "format" doesn't actually cause any technical JSON issues. What do people think? @hewgreen @daniwelter @zperova @willrockout @cjvillar @pnejad 

We can discuss `file_name` in another ticket :)

**Comment by malloryfreeberg** [comment]
@hannes-ucsc @NoopDog This change has been merged into our develop environment. The aim would be to merge it into integration as soon as everyone is ready for the change.

**Comment by malloryfreeberg** [comment]
@samanehsan @rexwangcc This change has been merged into our develop environment. I think it might affect how the analysis_file metadata are written. The aim would be to merge this change into integration as soon as everyone is ready for the change.

**Comment by samanehsan** [comment]
Hi @malloryfreeberg! We are currently using [analysis file schema 5.3.6 ](https://schema.humancellatlas.org/type/file/5.3.6/analysis_file). When this change goes into the file core schema, will the schema version of the analysis file increase as well? And will ingest only validate the latest version in this case too? @justincc

**Comment by justincc** [comment]
@samanehsan Yes we will only validate against the latest schema version, you'll need to use `format`
