### ISSUE TITLE
Rename field process_location to location

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#376]
### Original request
1. <process_location>
**Which schema needs to be changed?**
Change to process_core.json
**What field in that schema need to be changed?**
process_location field
**What should the new field name be?**
Change to location
**Why is the change requested?**
Shortening.

### Consequences:

1. Location could be used in other contexts, e.g. contact or preservation_storage, which would overload the term
2. From a usability point of view, this doesn’t comply with the principles for: “recognition rather than recall”, “visibility of system status”, “error prevention” [https://www.nngroup.com/articles/ten-usability-heuristics/](https://www.nngroup.com/articles/ten-usability-heuristics/)  , as it might be ambiguous if not carrying the specific context (i.e. location could be for institute, sequencing centre, operator etc)
3. Breaking change for all downstream components

**Comment by lauraclarke** [comment]
I do not recommend proposal as it reduced the specificity of the term without any technical argument as to why the shorter term is better.

**Comment by malloryfreeberg** [comment]
While we don't have any other location fields yet, as we start to acquire more experiments which support building the 3D atlas, other location fields arising seems very likely. Removing this context will make it more difficult in future to add other types of location unambiguously.

Currently, this field can appear in the spreadsheet tab for a biomaterial (e.g. Donor organism). We need to be clear that this is the location at which a process/protocol took place, and not a location, for example, where a donor lives.

**Comment by lauraclarke** [comment]
This should be reviewed in the light of qualified/unqualified field names
