### ISSUE TITLE
Rename field operator_identity to operator

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#377]
### Original request
1. <operator_identity>
**Which schema needs to be changed?**
Change to process_core.json
**What field in that schema need to be changed?**
operator_identity
**What should the new field name be?**
Change to operator
**Why is the change requested?**
Shortening

### Consequences: 

1. Breaking change for all downstream components
2. From a usability point of view, this doesn’t comply with the principles for: “recognition rather than recall”, “visibility of system status”, “error prevention” [https://www.nngroup.com/articles/ten-usability-heuristics/](https://www.nngroup.com/articles/ten-usability-heuristics/) , as it might be ambiguous if not carrying the specific context

**Comment by lauraclarke** [comment]
I do not recommend this change to the schema. It decreases the specificity of the term and the longer name has no clear significant technical consequence

**Comment by malloryfreeberg** [comment]
We should accept this change. The shortening doesn't alter how easy it is to understand this field given the rest of the context. The "_identity" part is unneeded extra precision.
