### ISSUE TITLE
Rename field is_parent_of to child and other relationship fields

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#380]
### Original request
1. <is_child_of>
**Which schema needs to be changed?**
Change to familial_relationship.json
**What field in that schema need to be changed?**
is_child_of field
**What should the new field name be?**
Change to parent
**Why is the change requested?**
Shortening. 
1. <is_parent_of>
**Which schema needs to be changed?**
Change to familial_relationship.json
**What field in that schema need to be changed?**
is_parent_of field
**What should the new field name be?**
Change to child
**Why is the change requested?**
Shortening.
1. <is_sibling_of>
**Which schema needs to be changed?**
Change to familial_relationship.json
**What field in that schema need to be changed?**
is_sibling_of field
**What should the new field name be?**
Change to sibling
**Why is the change requested?**
Shortening

### Consequences: 

1. Loss of explicit relationship directionality
2. Could be interpreted as a “yes/no” question, ie “is the individual a child?”
3. Breaking change for all downstream components

### Consequences: 

1. Loss of explicit relationship directionality
2. Could be interpreted as a “yes/no” question, ie “is the individual a parent?”
3. Breaking change for all downstream components

### Consequences: 

1. Loss of explicit relationship directionality
2. Could be interpreted as a “yes/no” question, ie “is/has the individual a sibling?”
3. Breaking change for all downstream components

**Comment by lauraclarke** [comment]
I do not recommend this change is accepted as it reduces the specificity of the direction of the relationship and what the contents of the field should be.

I would like to know what the description of the field as I am not entirely clear on the field

**Comment by lauraclarke** [comment]
@daniwelter can you close/delete this issue. I am merging it with the other similar issues

**Comment by lauraclarke** [comment]
@daniwelter ignore my previous comment, this is now the merged ticket.

**Comment by JimKent** [comment]
How does this lose the functionality?   If you have
   donor.child
then it is pretty apparent that it is referring to the child of the donor.   
That the contents of the field is a reference to another donor makes it obvious that it is not a boolean property.

**Comment by JimKent** [comment]
Especially if this can have multiple values,  using the plural,  "children" would further disambiguate things.

**Comment by dosumis** [comment]
If the aim is to relate two entities, I much prefer something that sounds unambiguously relational.  This is standard practise in semantic modelling.

`Jane is_parent_of Yasmin` is clear

child, otoh, could be misinterpreted as boolean referring to the (yes/no)
children is worse:  it could easily be interpreted as a question about whether a donor has children

is_parent_of also works for non-human subjects.

**Comment by JimKent** [comment]
In particular, consider the query use case:

select where donor.child.city != donor.city

to track movement within a family vs.

select where donor.is_parent_of.city != donor.city

I'm not seeing how child is human specific.  Isn't there an is_child_of
field in your formulation to which the same argument would apply if it were
human-specific?

**Comment by dosumis** [comment]
> In particular, consider the query use case:
> select where donor.child.city != donor.city
> to track movement within a family vs.
> select where donor.is_parent_of.city != donor.city

I agree that this would be confusing, but don't see how it's possible with the current schema - where the value of is_parent_of is a of string:  https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/module/biomaterial/familial_relationship.json#L26

I assume this is meant to be a relationship between donors. In that case wouldn't the query require two legs - one to find an ID for the related donor, another to look up metadata about that related donor.  Assuming this is possible with elastic search, it couldn't be specified with a single json_path. 

> I'm not seeing how child is human specific.  Isn't there an is_child_of
field in your formulation to which the same argument would apply if it were
human-specific?

Yep. Sorry. My bad.

**Comment by lauraclarke** [comment]
I have been chatting about this via email with @diekhans and thinking again. Looking at schemas.org they use parent/child rather than is_parent_of and is_child_of. 

I suspect unless we are expecting AIs top reason about these field names (which I don't think is on the cards) humans will always have context so the semantic precision isn't really needed and using child and parent tends to be what everyone does 

This is the schemas.org specification for person https://schema.org/Person

I change my mind and support @JimKent's request to switch to the more straightforward and simple parent, child and sibling

**Comment by JimKent** [comment]
Thanks.   The "is_parent_of" and "is_child_of" syntax makes since as a
field within a link, but as a field within an object I think the
directionality is already implied.
