### ISSUE TITLE
Rename field organism_age to age (and same change to unit)

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#382]
### Original request
1. <orgnaism_age>
**Which schema needs to be changed?**
Change to donor_organism.json
**What field in that schema need to be changed?**
organism_age field
**What should the new field name be?**
Change to age
**Why is the change requested?**
Shortening
1. <organism_age_unit>
**Which schema needs to be changed?**
Change to donor_organism.json
**What field in that schema need to be changed?**
organism_age_unit field
**What should the new field name be?**
Change to age_unit
Shortening
**Why is the change requested?**

### Consequences: 

1. “Age” is used in other contexts (gestational_age, organoid_age, etc.) so a loss of contextualising compound name may cause confusion
2. From a usability point of view, this doesn’t comply with the principles for: “recognition rather than recall”, “visibility of system status”, “error prevention” [https://www.nngroup.com/articles/ten-usability-heuristics/] (https://www.nngroup.com/articles/ten-usability-heuristics/), as it might be ambiguous if not carrying the specific context (as provided above)
3. Breaking change for all downstream components

### Consequences: 

1. “age_unit” is used in other contexts (gestational_age_unit, organoid_age_unit etc) so loss of contextualising compound name may cause confusion
2. Breaking change for all downstream components

**Comment by lauraclarke** [comment]
I do not recommend this change is accepted. As the ticket suggests this loses important context from the field name making it more difficult to interpret.

**Comment by JimKent** [comment]
Just as you need to look at age_unit to fully make sense of this field, you also need to look at a bit of context.  Adding organism as a prefix does not disambiguate gestation since an embryo is by most points of view already an organism.   Since there are still breaking changes, the time to simplify it is now.  Simplifying it will make queries much cleaner looking, avoiding such redundancy as organism.organism_age.  I recommend we move forward with this now.

**Comment by lauraclarke** [comment]
The specific use case we are targetted was one recommended by Deanne Taylor at the Boston Metadata meeting January 2018 and puts gestational age and organismal age in the same json schema, donor_organism

If sampling from a born but premature baby you will have both an actual age, say 5 days and a time since fertilization, say 26 weeks and you can't record both of them if you only have one age field.
