### ISSUE TITLE
Add ontology_label field to all ontology schemas

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#383]
**For which schema is a change/update being suggested?**

All ontology modules

**What should the change/update be?**

* New schemas or fields

Each ontology module needs a separate field to capture the label of the ontology term that the user-supplied value is mapped to.

**What new field(s) need to be changed/added?**

* Field name: ontology_label
* Field description: The preferred label for the ontology field. This can be the same as but may also differ from the user-supplied value in the "text" field.
* Required: no
* Example: An example value that would satisfy this field.
* CV or enum: n/a

**Why is the change requested?**

User supplied values in the "text" field can be inconsistent, eg y, year, years, Year, Y are values that could supplied by the user for a time unit field. In this case, the ontology_label should contain "year", the preferred label for UO:0000036. Inconsistent field values were flagged as a problem for orange box faceting.

**Comment by malloryfreeberg** [comment]
Fixed with commit 8c068ca
