### ISSUE TITLE
Rename field biological_sex to sex

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#384]
### Original request
1. <biological_sex>
**Which schema needs to be changed?**
Change to donor_organism.json
**What field in that schema need to be changed?**
biological_sex field
**What should the new field name be?**
Change to sex
**Why is the change requested?**
Shortening

### Consequences: 

1. “Sex” has a subtly different meaning to biological sex, including conflation with gender or self-identified sex. This may lead to submitters providing non-biological sex information that conflicts with the biological sex of the sample 
2. Breaking change for all downstream components

**Comment by JimKent** [comment]
Biological sex is also ambiguous to a degree.  People are born biologically intersex.  People with androgen receptor deficiencies can be by all outwards appearances female, but genetically XY.   Further, since there are many other breaking changes still going in,  now is the time to do it.  I recommend this go in.

**Comment by malloryfreeberg** [comment]
We should probably shorten `biological_sex` to `sex`. We don't use sex anywhere else and it is sufficiently specific given the acceptable values are male, female, mixed, and unknown. This change won't have important functional consequences.

Sex will be based on what a donor self-reports or seqnom assay results at the sequencing centre, so I think it is sufficient.

If at a later date anyone consistently does karyotyping, we can always add `chromosomal_sex` (valid values: XX, XY, XXY, etc.) and then have the UI autofill sex based on the karyotype and check with the submitter, but I suspect in this project that will be unlikely.

We need to make the description clear that this field should not be a self-identified _gender_.
