### ISSUE TITLE
Rename field nucleic_acid_source to dissociation_contents

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#385]
### Original request
1. <nucleic_acid_source>
**Which schema needs to be changed?**
Change to dissociation_protocol.json
**What field in that schema need to be changed?**
nucliec_acid_source field
**What should the new field name be?**
Change to dissociation_contents
Clarification.  The biosample may be used for other purposes than nucleic acid extraction as well.
**Why is the change requested?**

### Consequences: 

1. Change to a required field means all existing data will have to be re-ingested to fix failing metadata
2. Breaking change for all downstream components

**Comment by lauraclarke** [comment]
While I agree that nucleic acid source is too specific and we will see other molecules in this field for experiments such as proteomics or metabolomics I think dissociation content is too non-specific and could create confusion.

Would molecule_source be better?

Are there any other middle ground suggestions be better where the meaning is clearer from the attribute name without needing to read help

**Comment by lauraclarke** [comment]
@JimKent I have been discussing this with @malloryfreeberg and I have come to the conclusion that I am not sure this field is appropriate for dissociation protocol at all so it would be great if you could check my reasoning.

As I understand it, the use case for this field is so a protocol is labelled with the type of biomaterial (bulk, single cell etc) that was the source of the molecule used in an assay.

For dissociation protocol, the output should always be another biomaterial rather than a molecule to be assayed so it isn't clear why such a field is needed on dissociation protocol because the molecule isn't produced using this protocol.

We already have input_nucleic_acid_molecule on the library_prepartion_protocol. If we match this with nucleic_acid_source on library_preparation then if someone doesn't provide us with the full hierarchy of samples before the library prep, everyone will still be able to tell what the source of the nucleic acid was for the library prep

Then when we have the philosophical equivalent of the library prep exists for spatial transcriptomics, proteomics or metabolomics we can ensure there is another appropriate source field in those protocol schemas.

It would also let us do an assessment in future if the provided field is always identical to the biomaterial type (@daniwelter @malloryfreeberg can we tell what type of sample something was from the biomaterial?) then we can move to auto-populate it rather than asking the user to provide it.

Does this make sense?

**Comment by JimKent** [comment]
Yes, I think we could trim this one as well.

**Comment by malloryfreeberg** [comment]
To summarize, the output of this issue is:

1. Remove `nucleic_acid_source` field from `dissociation_protocol` schema (major change).
2. Add optional `nucleic_acid_source` field to the `library_preparation_protocol` schema to complement `nucleic_acid_molecule` field (minor change).

If we are all agreed, I can start this change.
