### ISSUE TITLE
Rename entity donor_organism to donor or individual

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#386]
### Original request
1. <donor_organism>
**Which schema needs to be changed?**
Change to donor_organism.json
**What field in that schema need to be changed?**
Name of schema
**What should the new field name be?**
Either donor.json or individual.json
**Why is the change requested?**
Shortening and clarification.  donor_organism reads very much like it should have values like "human" or "mouse."

### Consequences:
Breaking change requiring widespread code adaptations in all components, in particular ingest and orange box.
Community consensus established that “donor” implies active consent, which is incompatible with mouse and other animals, and fetal tissue samples.
This issue was already addressed in GitHub issue https://github.com/HumanCellAtlas/metadata-schema/issues/83

**Comment by lauraclarke** [comment]
This is going to be put on ice. The entity names should be discussed again but there will be no capacity to change this across the DCP in the near future

**Comment by malloryfreeberg** [comment]
Comment from @hannes-ucsc 

> There currently is only one entity type with donor in its name. Unless we expect another type of donor, say donor_cell, it would make sense to shorten the name because it turns out that we frequently need to qualify metadata properties fully—in TSV headers, for example. These fully-qualified metadata property references tend to be long.

> It may also be worth noting that we colloquially use the shortened term.
