### ISSUE TITLE
Rename module mus_musculus_species to mouse_specific

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#387]
### Original request
1. <mus_musculus_specific>
**Which schema needs to be changed?**
Change to mus_musculus_specific.json
**What field in that schema need to be changed?**
Name of module
**What should the new field name be?**
Change to mouse_specific.json
**Why is the change requested?**
Keeps consistent with the human_specific module name

**Comment by lauraclarke** [comment]
I suggest we accept this change. I would like to confirm that latin to common name is the correct direction rather than changing human_specific to homo_sapiens_specific perhaps our UX people can comment here.

**Comment by JimKent** [comment]
THanks for accepting one.

**Comment by lauraclarke** [comment]
Gabs has said that mus_musculus to mouse is the best direction. The only thing to consider would be if other animals HCA might adopt data from would follow the same form but I think zebrafish and most mammals have clear and unambiguous common names so this should work from a style point of view @daniwelter @hewgreen can one of you produce a suitable PR for this

**Comment by JimKent** [comment]
Historically the zebrafish common name has been more stable than it's
scientific binomial name.  I would slightly lean towards mouse_specific
rather than mus_musculis specific but my feelings are not particularly
strong.
