### ISSUE TITLE
Rename entity reference_file to mapping_reference_file

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#388]
### Original request

1. <reference_file>
**Which schema needs to be changed?**
Change to reference_file.json
**What field in that schema need to be changed?**
Name of the schema
**What should the new field name be?**
Change to mapping_reference_file.json
**Why is the change requested?**
Clarification - refererence_file reads like it might be the PDF of an associated publication among other things.

### Consequences: 

1. Breaking change for all downstream components, in particular analysis pipelines, who are the primary users for this entity
2. Not all reference files are mapping reference files (e.g. some are gene annotation files) so alternative types of reference files such as annotation references would require their own file type, causing schema bloat.

**Comment by lauraclarke** [comment]
I do not recommend this change is accepted. As described above not all reference files are mapping files. Documentation and help text can make it clear what this field is for. There are a lot of publication specific fields already in the schema such as 

publications and supplementary_files in project

The context of this field along with its description makes its purpose very clear.

**Comment by JimKent** [comment]
It would be nice if in the spirit of an actual collaboration you accepted one of our changes now and again....

The gene annotations that I'm aware of at least are used for mapping.  Could you give me an example of a use of a gene annotation that does not involve mapping?

**Comment by daniwelter** [comment]
Tagging @jishuxu @samanehsan @kbergin for comment as all reference_* elements were defined primarily by green box.

**Comment by lauraclarke** [comment]
You are correct at the moment that this is setup to contain genome assemblies and gene annotation and mapping is a reasonable label in the specific use case currently being used. I think assemblies are clearly mapping, the gene annotation file is less clear-cut.

By relabelling this file to mapping you are assuming this will never be needed for reference variants for association experiments, reference images for any imaging experiments, reference spectra or molecules for proteomics or metabolomics experiments or reference cell type identities if the annotation of cell identities ever moves within the DCP.

That feels like a short-sighted view and will mean when we do get a different class of reference file we will have to not only extend this schema but either change its name again or create another schema for a different type of reference file. This sounds like it will create more work rather than clarify things for everyone.

**Comment by JimKent** [comment]
It would mean a schema change (of a non-breaking sort) to add in a new
field for a new type of reference file.  On the other hand this would also
give us the opportunity to clarify what that new type of reference is.....

**Comment by daniwelter** [comment]
Agreed, it is much easier to add a new (optional) field to an existing type entity than to create an entirely new entity.

**Comment by daniwelter** [comment]
In fact, reference_file already has a reference_type field, which is an enum, so it will only be a patch update to add additional values to this to capture other types of reference file.

**Comment by JimKent** [comment]
Ok, reference_file with a reference_type subfield is good enough for me.
