### ISSUE TITLE
 Rename entity specimen_from_organism to body_part

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#389]
### Original proposal

1. <specimen_from_organism>
**Which schema needs to be changed?**
Chane to specimen_from_organism.json
**What field in that schema need to be changed?**
Name of schema
**What should the new field name be?**
Change to body_part.json
**Why is the change requested?**
Shortening and clarification.  

### Consequences:

1. Breaking change requiring widespread code adaptations in all components, in particular, ingest and orange box.
2. This change would mean this entity would be difficult to reuse in any experiment which takes a cross-section of potentially multiple body parts which do not share a name such as imaging experiments. This would then the require the invention of a new entity and the additional work that entails for no technical reason just a stylistic one.

**Comment by lauraclarke** [comment]
I do not recommend this change is accepted. As said above it makes the term more specific and therefore less flexible in experiments which might be using cross-sections of a body as opposed to samples from a specific organ or body part

**Comment by JimKent** [comment]
A specimen is in common biological usage as a whole dead organism.
We have not as I write this settled on use of "organism" as opposed to "donor" or "individual."
Specimen, being singular, also implies that it is just from one place.
In many case we are limited by screen width in presenting things to users.  Having to scroll through something rather than being able to see it all in one screen places a burden on user memory and slows comprehension.  Since "body_part" is less than half the size of "specimen_from_organism" this is an important consideration.

**Comment by lauraclarke** [comment]
This is going to be put on ice. The entity names should be discussed again but there will be no capacity to change this across the DCP in the near future

**Comment by malloryfreeberg** [comment]
From @hannes-ucsc 

> There currently is only one kind of specimen mentioned the schema. Unless we expect another type of specimen, it would make sense to shorten the name because it turns out that we frequently need to qualify metadata properties fully—in TSV headers, for example. These fully-qualified metadata property references tend to be long.

> It may also be worth noting that we colloquially use the shortened term in conversation.

**Comment by hannes-ucsc** [comment]
-1 on body_part. Do all organisms have bodies and are those made up of parts? Even if they do, isn't a specimen a removed section of the tissue in a body part?

+0 on tissue 

+1 on specimen

Also worth considering: biospecimen.

**Comment by lauraclarke** [comment]
So specimen actually means a whole organism rather than a bit of one according to a dictionary, not sure if that is commonly understood

https://en.oxforddictionaries.com/definition/specimen
An individual animal, plant, piece of a mineral, etc. used as an example of its species or type for scientific study or display.

One of tissues meanings is a distinct material which is a bit larger than we are thinking
https://en.oxforddictionaries.com/definition/tissue
Any of the distinct types of material of which animals or plants are made, consisting of specialized cells and their products.

There is no precise word which means what we do which is a part of a specific piece of an animal. I am ambivalent to which is better tissue or specimen but either works

**Comment by hannes-ucsc** [comment]
Wikipedia gives a slightly different definition for *biological specimen* but I guess Oxford wins:

https://en.wikipedia.org/wiki/Biological_specimen

Hence my `biospecimen` proposal. Throwing `tissue_sample` in there, as well.

The existing `specimen_from_organism` is going to be one of the types that Azul is currently working on exposing in the new Samples tab which is to replace the Specimens tab. The other ones are organoid and cell line.

**Comment by lauraclarke** [comment]
Interesting looks like the dictionary definition is closer to zoological specimen from a wikipedia perspective 

https://en.wikipedia.org/wiki/Zoological_specimen

I think @gabsie has UX evidence to support tissue being slightly preferable but as I said before I am happy with either
