### ISSUE TITLE
Update smartseq2 module to plate_based_sequencing

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#397]
**For which schema is a change/update being suggested?**

smartseq2 module

**What should the change/update be?**

1. rename smartseq2 > plate_based_sequencing
2. remove well row/column from module
3. rename well_name to well_id and make it mandatory
4. make plate_id mandatory
5. move plate_based_sequencing module import from sequencing_file to cell_suspension

**What new field(s) need to be changed/added?**

Remove well_row and well_column, rename well_name to well_id

**Why is the change requested?**

The field changes are necessary as we need to make a well identifier mandatory and current evidence suggests that we are more likely to get a well name/id than row/column coordinates. Renaming the module will make it more easily reusable for non-smartseq plate-based technologies. Finally, moving the import location of the module from sequence_file to cell_suspension is necessary as the plate information otherwise has to be duplicated for each file pair, whereas there should only ever be one cell suspension (sequencing library) per well.

**Comment by dshiga** [comment]
The plate_based_sequencing move definitely makes more sense. I'm less sure about removing row/column. It sounds like from what @jishuxu was saying that it's really critical for qc / correcting plate artifacts. If that's the case, maybe it should be required. If there are overriding reasons why we still want to accept data without row/column, would it make sense to at least make it optional, so that submitters who have it can include it?

**Comment by lauraclarke** [comment]
@dshiga I think the theory behind removing row and column and keeping name is people who have row and column but not name can merge it to produce the name (and we can add a note) but by having both it is more inconsistent and more difficult for people to interpret

As I mentioned earlier I don't think we can make anything well based required as not everyone will have this information especially if a third party has done the sequencing for them so I think it would be too big a barrier to submission and as I understand it while it is useful for analysis it isn't essential

**Comment by dshiga** [comment]
Thanks for the clarification, @lauraclarke. I understand it may be too big a barrier to require row/column. Do I understand correctly that we're going to suggest that people who have row and column just put that info into the name field, following some convention like [row]_[column]? Might that lead to  ambiguity where we're not sure if someone intended a name to be interpreted as row and column?

**Comment by lauraclarke** [comment]
@hewgreen made this proposal, I believe that was his idea

We previously had both name and row/column, it was decided to remove row/column and keep the name to reduce confusion as to whether to fill out either of them. 

You are correct that could lead to ambiguity @hewgreen do you want to comment

**Comment by TimothyTickle** [comment]
I am not sure I understand the change of name from smartseq2 to plate_based_sequencing. They are not equivalent and plate_based_sequencing actually does not comment on a specific assay or chemistry; it is not as specific as smartseq2. Is there metadata that points to the specific assay? Where would one look to find this is smartseq2?

**Comment by malloryfreeberg** [comment]
@TimothyTickle, the intention *was* to make the original `smartseq2.json` module more generic (thus renaming it to `plate_based_sequencing.json`) so that it could be used for other plate-based assays, not just SmartSeq2. Inclusion or exclusion of this module doesn't define whether an experiment is SmartSeq2 or otherwise. Definition of the experiment is done by directly indicating it in the field `library_construction_approach` in the `library_preparation_protocol.json` schema. This field takes values such as "Smartseq2", which is where one would look to identify the specific experiment type.

**Comment by TimothyTickle** [comment]
That makes sense and the current attributes in the json make sense in that context. I like the seperation between library prep and cell handling. Are you going to do this with 10X as well? being a microfluidics cell handling (of the type 10X) with a certain library prep (in our case v2 chemistry)? Or something close to that :-).

**Comment by malloryfreeberg** [comment]
@TimothyTickle that's a great idea. We just pre-released a 10x module today with fields that @willrockout has discussed with 10X representatives directly and, I believe, with @ambrosejcarr . If we find that these fields can be generalized to other microfluidics-based techniques, perhaps we can do something similar.

**Comment by TimothyTickle** [comment]
Awesome, thanks for the conversation. Closing my comment, no concerns.

**Comment by hewgreen** [comment]
@dshiga regarding the well id, row and column information. The thought behind removing row and column was quite simplistic and you may be right to question it. We don't want both for the reasons Laura pointed out. So given the choice of which one to keep we went with well id thinking that the row and column can be put there anyway. Most people do this anyway (A2, B2 etc). I have only seen one dataset (MARS seq) with where all three were provided and the well ID was not of the format row/column.

That being said you have a good point that this may be ambiguous if you are trying to programatically understand the coordinates of a well on a plate. Laura is also right in saying that this information may not be available. Maybe we should just stick with all three for now until we have more examples.

**Comment by daniwelter** [comment]
@hewgreen The concern with having all three is that it makes difficult to make one concept required, and it was agreed a few weeks ago that one had to be required. While I agree that a row/column coordinate makes it much easier to unambiguously define a single well, a single well ID is easier to supply from a pair of values than to extrapolate row and column coordinates if only one is available. I would strongly advise against retaining all three variables.

**Comment by ambrosejcarr** [comment]
> if we find that these fields can be generalized to other microfluidics-based techniques, perhaps we can do something similar.

I bet they will be, but the module as it stands does a good job of capturing the information required for 10x.

**Comment by jishuxu** [comment]
Illumina sequencer has standard plate map and well map. The well ID or plate map per  sample/library is in a manifest file.  User should have the access to this file.

**Comment by lauraclarke** [comment]
@daniwelter I will reiterate that I don't think we can require those fields. While they are great information to improve QC they are not essential to the process full stop and there will be enough people who are sufficiently distanced from the sequencing that it will be difficult for them to retrieve it. I strongly recommend we leave them as optional

@jishuxu I agree in a facility like the Broad it will be easy to get this but where a small lab has paid a third party to do the sequencing it might be a lot more difficult as I would be very surprised if it comes as part of the standard output which is returned to them. I really don't think we can require this information

**Comment by ambrosejcarr** [comment]
Smartseq2 uses the indices to demultiplex. It may also be possible for us to calculate row and column information using our pipeline if that index information is embedded in the files somewhere. 

@jishuxu, is the index data present in, for example, the queryname of the fastq?

**Comment by ambrosejcarr** [comment]
@jishuxu My point was more that the cells that populate the same row of a plate will always have the same forward sequencing adapter, while the cells populating the same column of a plate will have the same reverse sequencing adapter. So, we might be able to reconstruct the data if the _sequencing core_ has access to that data. 

Am I wrong about that?
