### ISSUE TITLE
use relative URLs in $ref

### ISSUE THREAD

**Issue by bkmartinjr** [HumanCellAtlas/metadata-schema#4]
Where modules are referenced, use relative URLs.  This makes it easier to use/validate the schema from a local copy.

Eg, instead of 
`"$ref": "http://hgwdev.soe.ucsc.edu/~kent/hca/schema/core.json"`
use:
`"$ref": "core.json"`

**Comment by daniwelter** [comment]
We expanded the ref URLs to the full V4 tag github URL. There is a script in the src directory called ref-updater.py, which given a URL, a target input and an output directory, can go through and change all URLs to and from relative.

**Comment by malloryfreeberg** [comment]
With the hierarchical structure of the schemas now, can we still use relative URLs? If I take out the $ref path for a module, e.g.
```
        "genus_species": {
            "description": "The scientific binomial name for the species of the biomaterial.",
            "type" : "array",
            "items":{
                "$ref": "module/ontology/species_ontology.json"
            }
        },
```
From a .json schema with the following header
```
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://schema.humancellatlas.org/type/biomaterial/organism/4.0.0/organism.json",
```
I get the error
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='schema.humancellatlas.org', port=80): Max retries exceeded with url: /type/biomaterial/organism/4.0.0/module/ontology/species_ontology.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a65aeb8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```
So it looks like the URL trying to be resolved is
`/type/biomaterial/organism/4.0.0/module/ontology/species_ontology.json`

When the URL should look like
`http://schema.humancellatlas.org/module/ontology/4.0.0/species_ontology.json`

I'm not sure how to deal with this.

**Comment by bkmartinjr** [comment]
I haven't had time to verify this, but have you tried:   "$ref": "/module/ontology/species_ontology.json"?   Or alternatively, "../../../../module/ontology/species_ontology.json"?

**Comment by malloryfreeberg** [comment]
I did try `../../../../module/ontology/species_ontology.json` and `/module/ontology/species_ontology.json` and I get the same error for both:

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='schema.humancellatlas.org', port=80): Max retries exceeded with url: /module/ontology/species_ontology.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a65aeb8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

**Comment by malloryfreeberg** [comment]
I guess I'm unsure what is being interpreted as the base URI if a relative URL is used. I'm running the scripts used in the Travis test locally, and when I ask it to print to screen the base URI I get:
```
base_uri = subprocess.check_output('pwd').decode("utf-8").rstrip()
print('base URI: %s' % base_uri)

base URI: /Users/mfreeberg/git/metadata-schema/json_schema
```
But this doesn't seem to be used based on the error message.

**Comment by mckinsel** [comment]
Hey @malloryfreeberg , I believe jsonschema is going to use the `id` as the resolution scope for any `$ref`s, and when the `id` is absolute, that will override any `base_uri` you've set elsewhere.

I can get the local `json_examples_validate_against_schema.py` script to work if I set the `id` to `type/biomaterial/organism/organism.json` and the `$ref` to `../../../module/ontology/species_ontology.json`.

**Comment by daniwelter** [comment]
If we need to use relative URIs everywhere (id & ref), then this negates the need for an HCA-specific namespace. I think there needs to a reference to absolute URIs somewhere and id is the obvious place for it. We also have the added issue that the version number in the absolute URI lives between the semantic path and the entity name (eg type/biomaterial/5.0.0/organism) but there is no version number folder in the directory structure, so this would also causes clashes in validation.

**Comment by malloryfreeberg** [comment]
Validation doesn't work with relative URLs. The base URI gets reset after traversing more than 1 level deep, which happens with some of the module/ontology schemas. We have chosen to expand out full URLs as part of the release process to enable validation to happen during testing.
