### ISSUE TITLE
New corresponding_author field to contact schema

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#409]
**For which schema is a change/update being suggested?**

I would like to request an update the the `contact.json` schema.

**What should the change/update be?**

I would like to request a `corresponding_author` field to the `contact.json` schema to indicate to a downstream user of the data who they should contact with specific biological questions or other questions about datasets that Zendesk can't answer.

**What new field(s) need to be changed/added?**

* Field name: `corresponding_author`
* Field description: Whether the individual is a corresponding author for this project.
* Required: No
* Example: Yes
* CV or enum: Field should be a boolean such that the schema renders true or false, but "yes" and "no" are appropriate entries, too.

**Why is the change requested?**

As with publications, it would be useful to know which of the contacts associated with a project can be contacted for various questions. This field is analogous to a corresponding author on a publication.

**Comment by malloryfreeberg** [comment]
@gabsie @hewgreen How does this field look to you?

**Comment by hewgreen** [comment]
I like it. For clarity, are these authors that have formally indicated to us that they are happy to be contacted in relation to the work? i.e. a GDPResque declaration or are these just the corresponding authors on the paper. Maybe we should state this in the description. Also the 'There should be at least one corresponding author per project.' may be helpful in the description for now to help us wranglers.

**Comment by malloryfreeberg** [comment]
They are all the people in the contacts tab for the project, no not necessarily related to a publication. Maybe we should change it to `corresponding_contributor` to distinguish between a contributor of the project and an author on a paper? Thoughts @lauraclarke ?

**Comment by malloryfreeberg** [comment]
Thoughts @claymfischer @pnejad @willrockout @cjvillar ?

**Comment by lauraclarke** [comment]
I like corresponding_contributor these aren't authors in the journal sense though I do hope eventually people will be able to claim these datasets to their orcid profiles

**Comment by pnejad** [comment]
@malloryfreeberg  I think **corresponding_contributor** is more appropriate. Should we capture the preferred method of contact? Some labs may prefer having questions emailed to an admin who then forwards it to the appropriate person.

**Comment by malloryfreeberg** [comment]
I'm now having second thoughts about whether to make the `corresponding_contributor` field required or not. Having it required means that, in most cases, this field will be "no", and only 1 or a few will be "yes". Alternatively, if we make this field optional, we would just have "yes" marked next to the contacts who should receive correspondences. Thoughts @gabsie ?

**Comment by malloryfreeberg** [comment]
Made this field optional as we are likely to only get "yes" from individuals who are comfortable with being corresponded with about the project. Updating the original ticket to say "Required: no".
