### ISSUE TITLE
Implement new compositional strategy for sample.json, allowing flattening.

### ISSUE THREAD

**Issue by dosumis** [HumanCellAtlas/metadata-schema#42]
@simonjupp has identified better compositional strategy for structuring sample.json which allows some flattening:

```.js
{
    "$schema": "http://json-schema.org/draft-04/schema#", 
    "description": "Information about a biosample." ,
    "additionalProperties" : false,
    "properties": {
        "core": {
            "$ref": "core.json",
            "description": "type and schema for this object"
             },
        "donor" : {
          "$ref": "donor.json"
        },
        "sample_from_organism" : {
          "$ref": "sample_from_organsim.json"
        },
    "allOf" : [{"required" : ["core"]}],
    "oneOf" : [{"required" : ["donor"]}, {"required" : ["sample_from_organsim"]}]
}
```
(Example only show fields needed to illustrate the composition pattern)

I've tested this locally with both positive and negative tests.  It appears to work well, and gives much clearer error reports than the current v4 strategy.

**Comment by dosumis** [comment]
Implementing this requires changing sample.json and removing the sample_type property from all sample subschemas.

**Comment by lauraclarke** [comment]
Happy for this to be explained tomorrow during our meeting but how does this allow samples to be chained into a hierarchy like our example

kate -> blood -> monocytes -> macrophages 

My quick scan of 
https://github.com/HumanCellAtlas/metadata-schema/blob/v4-sample/json_schema/sample_from_organism.json
and
https://github.com/HumanCellAtlas/metadata-schema/blob/v4-sample/json_schema/donor.json

doesn't show any obvious fields for between non-donor sample linking?

**Comment by simonjupp** [comment]
Asserting relationships between entities is done with the ingest API so lives in the ingest schema. You can see this already in the current system in the "links" section of the json. 

http://api.ingest.dev.data.humancellatlas.org/samples/59e084f913a592000691dfef

I have a new proposal for the bundles where essentially sample.json contains a list of all samples. A derived_from link is added to link them up e.g. https://github.com/HumanCellAtlas/metadata-schema/blob/v4-sample/schema_test_files/10x_pbmc8k_sample_bundle.json

**Comment by lauraclarke** [comment]
OKay, fair enough for leaving them out of v4  given this.

That being said I think we need to look who uses those relationships downstream of ingest. My current understanding is that if the metadata doesn't contain the relationships the document store the DSS indexes will also not contain those relationships and this might make it very difficult for any downstream users to know that different assay or samples come from the same donor or biopsy

**Comment by dosumis** [comment]
Now feeling less positive about this change.

We now have two different visions of how this compositional scheme will work:

Here's my attempt:
https://github.com/HumanCellAtlas/metadata-schema/commit/a4586e96101cfdccc70291926bc5b3d75b42d6e4
Here's Simon's:
https://github.com/HumanCellAtlas/metadata-schema/blob/v4-sample/json_schema/sample.json
(sample.json only) 

A major difference is that Simon's has an additional sample_type enum.  This is in addition to having properties named for each sample type.  There's no way to use a schema checker to make sure these match, e.g. this would be valid

sample.type = 'organoid', donor : { smoking_history = ...} 

But if we consider how this might be used to make a UI, perhaps the additional type field makes some sense.   The problem is that there is nothing in the schema to indicate which properties refer to sample types.  But if these property names match with sample_type names in the enum, we could use this to drive construction of valid schemas.  We could also use it to work from spreadsheets to JSON.

(One more note: this change doesn't really flatten the schema much - sample_type fields still get nested one level down).

**Comment by simonjupp** [comment]
@dosumis can we push the type down into the subschemas with enum of 1 like you had before? think this just fell out of removing core

**Comment by simonjupp** [comment]
or you can do this in sample.json to enforce the correct type 

```    "allOf" : [{"required" : ["id", "type"]}],
    "oneOf" : [
      {"required" : ["donor"], "properties" : {"type" : {"enum" : ["donor"]}}},
      {"required" : ["sample_from_organism"], "properties" : {"type" : {"enum" : ["sample_from_organism"]}}}
    ],```

**Comment by dosumis** [comment]
```    "allOf" : [{"required" : ["id", "type"]}],
    "oneOf" : [
      {"required" : ["donor"], "properties" : {"type" : {"enum" : ["donor"]}}},
      {"required" : ["sample_from_organism"], "properties" : {"type" : {"enum" : ["sample_from_organism"]}}}
    ]
```

In the json instance files this translates to

type: donor
donor:  {  < some set of more specific fields> }

* You still have to, confusingly, state donor twice: once as a key and once as a value.    Presumably you want it as a value because that make auto-conversion to spreadsheet easier?
* We still have nesting of fields.
* Keys named for sample type might make more sense if they could exist in the same instance, but in this case they can't (and we don't want them to).

Compare this to what we had before:

core: { type: sample ... }
details:  { sample_type: donor ...}

We have the same amount of nesting of fields, but we only state once that this is a donor sample, and we do so in a value field.  I agree that 'details' is not a great name for the grouping field here. Suggest changing to 'content' ( or more explicit 'sample type specific content' ).

As far as I can see, the only advantage of the new scheme is that it gives clearer error reports with our current python schema checker.

**Comment by daniwelter** [comment]
This is no longer relevant in the updated hierarchical structure in v5.
