### ISSUE TITLE
Usage of library_construction_approach to trigger analysis pipelines for different 10X prep versions

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#426]
The following field library_preparation_protocol.library_construction_approach.text, is an ontology field. However, I just realised for the ICA dataset the value entered is '10x_v2' but should presumably be 10X sequencing (EFO_0008995).

Does this change break the analysis box's trigger? (I presume yes)
Do our analysis pipelines require knowledge of the version 'v2' to run? (presuming yes)

If so we should either:
1. add to the ontology
2. capture the 10X version in a different metadata field (in the 10X module).

**Comment by malloryfreeberg** [comment]
@jishuxu @ambrosejcarr can confirm, but I do believe the pipelines need to know that a 10x dataset is specifically from the v2 version of 10x. As such, I would recommend expanding the ontology being used here.

**Comment by daniwelter** [comment]
There are now 3 ontology fields - a free text field, the ontology ID and the actual ontology label. The free text field can contain anything you like, although for consistency, I would suggest indexing the ontology label. Unfortunately, I have yet to find a satisfactory definition of 10x v2 compared to 10x to warrant creating distinct ontology terms for them. Any suggestions would be appreciated.

**Comment by jishuxu** [comment]
I guess it should be something like
{'reagent':"10X",
"chemistry":"V2"
}

**Comment by ambrosejcarr** [comment]
> [snip] but I do believe the pipelines need to know that a 10x dataset is specifically from the v2 version of 10x. As such, I would recommend expanding the ontology being used here.

Correct.

**Comment by malloryfreeberg** [comment]
@daniwelter wouldn't the definition of the different 10x techs be something like:

10x v2 sequencing: "10X is a "synthetic long-read" technology and works by capturing a barcoded oligo-coated gel-bead and 0.3x genome copies into a single emulsion droplet, processing the equivalent of 1 million pipetting steps. **This is version 2 of the 10x sequencing technology.**"

10x v1 sequencing "10X is a "synthetic long-read" technology and works by capturing a barcoded oligo-coated gel-bead and 0.3x genome copies into a single emulsion droplet, processing the equivalent of 1 million pipetting steps. **This is version 1 of the 10x sequencing technology.**"
