### ISSUE TITLE
Adding supplementary_link to project.json

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#438]
Adding a supplementary_link field to project.json

Add a new field called supplementary_link, it should be an array and each element should be a URL

* Field name: supplementary_link
* Field description: An external link hosting code or supplementary data associated with a project which won't be hosted by the Human Cell Atlas Data Coordination Platform
* Required: no
* Example: A url such as https://github.com/czbiohub/tabula-muris
* CV or enum: no

**Why is the change requested?**
The aim of this field is to enable data contributors to provide links to third party resources hosted by them or other people which contain data associated with their project. The Tabula Muris project uses a github to do this

https://github.com/czbiohub/tabula-muris

You could imagine people also using GEO, BioStudies, Figshare or Zenodo to do this too

**Comment by lauraclarke** [comment]
@claymfischer @cjvillar This is my proposal for a possible solution on providing access to a group's own analysis results

**Comment by claymfischer** [comment]
I think this is a valuable addition and in line with what Mark Diekhans suggested. Can be a reasonable compromise for right now.
