### ISSUE TITLE
Updates to induced_pluripotent_cell_induction_produced_in_house field.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#459]
**For which schema is a change/update being suggested?**

I would like to request an update to the `ipsc_induction_protocol.json` schema.

**What should the change/update be?**

1. Change the field name `induced_pluripotent_cell_induction_produced_in_house` to something like: `ipsc_purchased_produced`.
1. Change the description for this field to "Were iPSCs purchased from an external source or produced in-house?".
1. Change the user_friendly name for this field to "iPSCs purchased or produced?".
1. Change the example for this field to "Should be one of: purchased, or produced.".
1. Change this field from a boolean to a string and enforce an enum, possibly with "unknown" as an acceptable value: `["purchased","produced"(,"unknown")]`.

**What new field(s) need to be changed/added?**

No new fields

**Why is the change requested?**

1. The field name should be changed because it is needlessly long and is partially redundant with the name of the schema (`induced_pluripotent_cell_induction` == `ipsc_induction`).
1. The point of the field is to ascertain whether iPSCs were purchased from an outside source or produced "in-house" i.e. in the lab doing the experiments. Instead of having this field simply state yes or no that iPSCs were produced "in-house", it will be more clear to directly ask users to state whether iPSCs were purchased from an external source or produced in-house.
1. The user-friendly change reflects a change in the field name, description, and change to an enum.
1. The example change reflects a change in the field name, description, and change to an enum.
1. The enum change reflects a change in the field name and description.

**Proposed changes as a whole**

From:
```
        "induced_pluripotent_cell_induction_produced_in_house": {
            "description": "Whether the induced pluripotent stem cell was prepared in-house.",
            "type": "boolean",
            "user_friendly": "iPSC prepared in-house?",
            "example": "Should be one of: yes, no."
        },
```
To:
```
        "ipsc_purchased_produced": {
            "description": "Were iPSCs purchased from an external source or produced in-house?",
            "type": "string",
            "user_friendly": "iPSCs purchased or produced?",
            "enum": [
                "purchased",
                "produced"
            ],
            "example": "Should be one of: purchased, or produced."
        },
```

**Comment by malloryfreeberg** [comment]
Actually, now that I've written this all out, this field seems a bit misplaced. The field is in a protocol schema, not a biomaterial (cell line) schema, and so maybe would be better off reflecting whether the _induction protocol_ was done externally or in-house, not whether the _iPSCs_ were produced in-house. 

Interestingly, we don't make the distinction for any other protocols of whether they were done externally or internally to the people submitting the experiments. Is it necessary that we capture it here? What are the use cases for data consumers knowing/searching for the value in this field? @pnejad can you comment here?

**Comment by lauraclarke** [comment]
People should be able to infer this from process_location (if reported). 

It does seem like an odd thing to specifically record and what does it mean? 

Does it mean ipscs were actually transformed from primary cell culture by the lab rather than being bought from a catalogue (again should be inferable as a bought one should have a catalogue record) or if the colony was cultured in-house or by someone else?

**Comment by pnejad** [comment]
@malloryfreeberg  @lauraclarke  This field was suggested by a lab that does not purchase their iPSCs, but instead gets them from another lab at the institution. They said that they would be interested in this information when looking at public datasets. This is also the case for one of our pilot datasets.

**Comment by malloryfreeberg** [comment]
@pnejad the question isn't whether or not this kind of information is relevant, but where it should live in the schema. We have the ability to identify the `location` (formerly `process_location`) for any protocol - this field lives in the `process_core.json` schema. The question is whether it is redundant to have the specific `induced_pluripotent_cell_induction_produced_in_house` field in the `ipsc_induction_protocol.json` schema when we could have the same information represented by the `location` field in the `process_core.json` schema.

In the spreadsheet, it would look something like:

| Protocol ID | Protocol name | Location |
|--|--|--|
| `protocol_core.protocol_id` | `protocol_core.protocol_name` | `process_core.location` |
| ipsc_induction_protocol_1 | iPSC induction by Sendai virus | Smith Lab, UCSC |

We want to avoid having duplicate ways for the same metadata to be represented, which makes it harder for both querying and displaying information as the code has to look it up in more than 1 place.

In this case, I think I vote for removing the `induced_pluripotent_cell_induction_produced_in_house` field and using the already-in-use `location` field to represent this metadata.

**Comment by lauraclarke** [comment]
I agree with @malloryfreeberg it would be good to understand why this couldn't be recorded by process.location

**Comment by pnejad** [comment]
@malloryfreeberg @lauraclarke 

I think this field would be redundant in 2 cases:
1. if the process.location is *always* filled out in the iPSC protocol
2. both lab name and university name are mentioned in process.location

If a lab gets their iPSCs from another lab at the same university, they would have to mention "Smith Lab, UCSC". If only UCSC is mentioned, it would defeat the purpose of capturing whether the lab reprogrammed the cells themselves.

I also think more people would fill out this field (with a "yes", "no" or "unknown") instead of providing process.location information. 

A lab suggested we add this field because some labs get their iPSCs from other labs that specialize in generating iPSC lines.

**Comment by lauraclarke** [comment]
@pnejad Did you explain to the group who requested this field about the option to provide process location? 

If this is about providing information about who produced the ipscs surely a free text field which allows people to name the lab is better than a enum with yes/no/unknown in it.

**Comment by pnejad** [comment]
@malloryfreeberg This field is not worth so much back and forth discussion. Please change it as you see fit.

**Comment by lauraclarke** [comment]
Hi @pnejad 

We would like to understand why you think the lab wouldn't be happy with process location as if not taking your field means they don't provide this information that is definitely a problem.

That being said both me and @malloryfreeberg are pushing back as this seems like unnecessary duplication. If it is isn't unnecessary then we should include it.

Did you discuss process.location as an option with this lab? did they give a reason why they didn't like it?

thanks

**Comment by malloryfreeberg** [comment]
I would like to resolve this issue. Given the conversations here, I am proposing to remove the `ipsc_induction_produced_in_house` field from the `ipsc_induction_protocol.json` schema. 

In the current dataset using this field, this change would mean that instead of contributors providing "yes" in the `ipsc_induction_protocol.ipsc_induction_produced_in_house` field, they would provide an exact location (e.g. "University of Chicago" or wherever the iPSCs were produced) in the `process.location` field.

The resulting JSON would look like this:
```
{
...
    "location": "University of Chicago",
...
}
```

instead of this:

```
{
...
    "ipsc_induction_produced_in_house": false,
...
}
```

Unless there are any strong objections or alternative suggestions, we can make this change next week (week of Feb 18).

@pnejad @lauraclarke @diekhans @claymfischer @morrisonnorman

**Comment by malloryfreeberg** [comment]
Closing as this is now being tracked in #926.
