### ISSUE TITLE
Determine where schema_url and schema_version should live

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#46]
`schema_url` and `schema_version` can live either in `core.json` (if we keep this), in the core entity schemas (e.g. `sample.json`), or in a bundle (managed by Ingest).

**Comment by malloryfreeberg** [comment]
In v5_prototype, these fields live in `sample/core.json`, etc.

**Comment by daniwelter** [comment]
In v5, schema_url has been replaced by $schema in line with json schema best practice. Each json entity (core, type, module and bundle) has its own $schema and schema_version properties in order to allow fully independent schema evolution.
