### ISSUE TITLE
Final date for schema changes to be released to master for phase 1

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#461]
Define new final date for all metadata schema changes (not including updates to documentation, example sheets/JSON, or code) to be promoted to master for phase 1 release.

**Comment by daniwelter** [comment]
Make it August 31st and then we can yell at people on Sept 3rd.

**Comment by malloryfreeberg** [comment]
Done! Friday 31st August it is.

**Comment by lauraclarke** [comment]
Presumably, it would be good to check with UCSC folks?

**Comment by malloryfreeberg** [comment]
@claymfischer @pnejad @cjvillar @willrockout Thoughts?

**Comment by cjvillar** [comment]
You have my support for August 31st. 1/4!

**Comment by willrockout** [comment]
August 31st!
