### ISSUE TITLE
Incorporate timecourse module into entity schemas.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#462]
**For which schema is a change/update being suggested?**

Not sure which type schemas should include the `timecourse.json` module: all biomaterial types? all protocol types? both?

**What should the change/update be?**

We have the `timecourse.json` module, but it's not included in any schemas. We need to add it as a field (probably an array) to one or more type schemas.

**What new field(s) need to be changed/added?**

* Field name: `timecourse`
* Field description: "Information relating to a timecourse associated with this [biomaterial/protocol]."
* Required: no
* Example (examples will be in the timecourse module schema): `{"timecourse_value": "2", "timecourse_unit": "day", "timecourse_relevance": "Collection after tumor cells injected into the mammary gland."}`
* CV or enum: This field will be a `$ref` to the `timecourse.json` module

**Why is the change requested?**

We need a way to capture timecourse information, and we have the module made, but the module isn't imported by any type entities.

**Comment by lauraclarke** [comment]
@malloryfreeberg is this needed for phase 1?

**Comment by malloryfreeberg** [comment]
No, not needed for phase 1, as far as I'm aware of the phase 1 datasets. Hence, it's not tagged with the phase 1 milestone.

**Comment by malloryfreeberg** [comment]
The mouse melanoma dataset can implement this schema.

**Comment by hewgreen** [comment]
PR: https://github.com/HumanCellAtlas/metadata-schema/pull/634
