### ISSUE TITLE
Change paired_ends to paired_end

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#467]
**For which schema is a change/update being suggested?**

I would like to request an update the the `sequencing_protocol.json` schema.

**What should the change/update be?**

The field `paired_ends` should be changed to `paired_end`. The singular form of this phrase is what is used for sequencing experiments, and this field does not take multiple values. The user-friendly term should be updated accordingly.

**Why is the change requested?**

We would like to adhere closer to the HCA metadata style guide which states that plural field names should only be used when the field can take multiple values. Also, "paired-ends" is not used for sequencing experiments. The correct term is "paired-end".

**Comment by lauraclarke** [comment]
I agree with this change. In the sequencing archives they use library_layout and have values of PAIRED or SINGLE so this matched that too

**Comment by malloryfreeberg** [comment]
This isn't a high-priority change, but it's a pretty straightforward one and might be better to change now before we ingest data for phase 1. Thoughts?

**Comment by lauraclarke** [comment]
Is there are other changes already going it, it would seem like a good idea to move it with

@pnejad @willrockout @cjvillar what do you think of the proposed change?

**Comment by cjvillar** [comment]
I'll find something or just push for practice, Thanks!
