### ISSUE TITLE
Branch naming for imaging branch

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#470]
@dosumis please rename this branch to include your initials

https://github.com/humancellatlas/metadata-schema/tree/imaging

The instructions on how to name branches are listed here
https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/committers.md#specific-steps-for-making-changes

Google'd instructions on how to rename
https://www.w3docs.com/snippets/git/how-to-rename-git-local-and-remote-branches.html

**Comment by malloryfreeberg** [comment]
@dosumis If you no longer need this branch, let us know and we can just delete it. Thanks!

**Comment by dosumis** [comment]
Done
