### ISSUE TITLE
Please rename the induction branch

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#471]
@hewgreen please rename the induction branch

https://github.com/humancellatlas/metadata-schema/tree/induction

The instructions on how to name branches are listed here
https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/committers.md#specific-steps-for-making-changes

Google'd instructions on how to rename
https://www.w3docs.com/snippets/git/how-to-rename-git-local-and-remote-branches.html

**Comment by hewgreen** [comment]
I didn't create this branch (or at least didn't do so intentionally), I was the last commit in master when it was created. As nothing happened in it I will just delete it.
