### ISSUE TITLE
Missing plate_id for SS2 study

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#475]
I currently have a published SS2 dataset that I'm working on the metadata for. I know they used 96-well plates, and there are 2,244 cells, but there is no direct indication of which cells were on which plates (also no `well_id` info). I think I can infer some of the plates (there are 96 cells from a single library prep - so these were likely all from the same plate), but I can only infer this info for about half of the cells. As the `plate_id` is currently a required field, I was wondering what you would recommend I do for this dataset moving forward. Options are:

1. Assign all 2,244 cells to the same plate using a made-up plate ID
1. Assign each cell to its own plate using 2,244 made-up plate IDs
1. Attempt to assign the correct plate IDs to all cells, knowing that for half of them the ID may be wrong
1. <s>Make the `plate_id` field optional</s>

For options 1-3, I would indicate in the project description that the plate IDs are hacked/potentially incorrect. @ambrosejcarr @jishuxu @kylee do you have a preference for which option I choose from the perspective of secondary analyses?

**Comment by lauraclarke** [comment]
I want to veto option 4. We can't make plate id optional otherwise it makes any sort of plate-based grouping or analysis impossible.

We need a policy for cases like this and to document it.

**Comment by malloryfreeberg** [comment]
@ambrosejcarr I like your proposal. This proposal is related to an open ticket we have to represent "missing" or "unknown" metadata in a structured way ([link](https://github.com/HumanCellAtlas/metadata-schema/issues/315)).

I will go ahead and update the metadata using the approach of inferring correct plate ID when I can, and entering NULL for the rest.

What do you think of this plan @pnejad @willrockout @cjvillar @hewgreen ?
