### ISSUE TITLE
User-friendly term for biomaterial linking fields

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#477]
The metadata spreadsheet contains "biomaterial linking" fields which are used to indicate the order of biomaterial derivation throughout an experiment. For example, a specimen is collected from a donor, then a cell suspension is made from the specimen, and then files are derived from the cell suspension. This example path is outlined in the following toy example (each table is a tab in the metadata spreadsheet):

_Donor_ tab:

| Donor ID | Sex |
|--|--|
| donor_1 | male |
| donor_2 | female |

_Specimen from organism_ tab:

| Specimen ID | Organ | **Input Donor ID** |
|--|--|--|
| specimen_1 | heart | donor_1|

_Cell suspension_ tab:

| Cell suspension ID | Selected cell type | **Input Specimen ID** |
|--|--|--|
| cell_suspension_1 | cardiomyocyte | specimen_1|

_Sequence file_ tab:

| File name | File format | **Input Cell suspension ID** |
|--|--|--|
| R1.fastq.gz | fastq.gz | cell_suspension_1|
| R2.fastq.gz | fastq.gz | cell_suspension_1|

The "Input * ID" headers above indicate fields that are not encoded in the metadata schema, but rather are used to link a biomaterial/file to the biomaterial it was derived from. This ticket is to determine what the naming of this field should be, as we have gone through a few iterations of term usage without deciding on one way. A complication for deciding naming is that we won't know _a priori_ what the upstream/input biomaterial will be in all cases. In the above toy example, the path is Donor --> Specimen --> Cell suspension --> Sequence file, but this is not the only possible path. Therefore, we cannot hard-code the linking fields in the code used to generate these column headers; however, we can make best guesses for now and propose those with some agreed-upon wording for the rest of the field. 

Some proposed columns headers are:
1. **Input <biomaterial_type> ID**
1. **Derived from <biomaterial_type> ID**
1. **Source <biomaterial_type> ID**
1. **<biomaterial_type> Biomaterial ID** where the biomaterial_type here doesn't match the tab

Where <biomaterial_type> is replaced by an upstream type such as "Donor", "Specimen", etc.

This ticket is to open the discussion for what the wording should be in the next iteration of spreadsheet UX tests.

**Comment by malloryfreeberg** [comment]
Pinging @gabsie @pnejad @cjvillar @willrockout @hewgreen who have experience with users filling out this field.

**Comment by hewgreen** [comment]
I only have mild preference. 'Input <biomaterial_type> ID' would make most sense if this was entered at the process level but isn't as nice for us because we enter this at the entity level. It seems slightly wrong to say 'input cell suspension' on a file especially when the stoichiometry there can be vague well/plate/tube etc. Option 2 is most common in ontology wording but I also like option 3.

**Comment by pnejad** [comment]
We should not use option 2, there was a github issue for [derived_from](https://github.com/HumanCellAtlas/metadata-schema/issues/180).

I've switched over to using "Donor Biomaterial ID", "Specimen Biomaterial ID" etc. with the labs I'm working with since there was still a bit of confusion with "has_input_biomaterial".

**Comment by hewgreen** [comment]
The git issue's main point was that using derived_from on its own is too generic but here we would have 'derived from donor ID' so it wouldn't be generic. Though I'm not advocating this is the clearest option.

@pnejad suggestion is what I have been doing naturally too. '<biomaterial type> Biomaterial ID' practically seems to work well in the context of the tab.

**Comment by lauraclarke** [comment]
As we can now chain the same biomaterial type together (at least for cell suspensions) I would advocate for either input_cell_suspension_id or source_cell_suspension_id (replace the cell suspension with the appropriate other biomaterial type as appropriate)

The help text and guidance will also need to be clear and UX reviewed.
