### ISSUE TITLE
Remove "organoid" from field names in organoid schema

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#480]
**For which schema is a change/update being suggested?**

I would like to request an update to 8 fields in the `organoid.json` schema.

**What should the change/update be?**

`organoid_age` -> `age`
`organoid_age_unit` -> `age_unit`
`organoid_size` -> `size`
`organoid_size_unit` -> `size_unit`
`organoid_morphology` -> `morphology`
`organoid_growth_environment` -> `growth_environment`
`organoid_stored_oxygen_levels` -> `stored_oxygen_levels`
`organoid_type` -> `type`**
`model_for_organ` -> `model_organ`***

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

Having "organoid" at the start of the indicated field names (A) is redundant with the schema name and (B) does not improve clarity of the field names. The word should be removed.

\***  Remove extra word ("for") and be consistent with related term model_organ_part

\** A field named "type" is not a good idea. "Type" is an overloaded term. We have a similar field - `cell_line_type` - in the `cell_line.json` schema that should be updated in parallel with this field, once we decide on what it should be called.

**Comment by malloryfreeberg** [comment]
@pnejad @daniwelter 

We need a solution for what to name the old `organoid_type` field:

```
        "organoid_type": {
            "description": "The type of organoid.",
            "type": "string",
            "enum": [
                "primary",
                "immortalized",
                "stem cell-derived",
                "synthetic"
            ],
            "example": "Should be one of: primary, immortalized, stem cell-derived, or synthetic.",
            "user_friendly": "Organoid type"
        },
```

Given that we need to remove the word "organoid" from the field name in order to avoid duplicating it in the fully qualified field name. But having a field just called "type" is not ideal either.

**Comment by zperova** [comment]
@malloryfreeberg what about `origin`? I wrote the same comment in the PR.

**Comment by pnejad** [comment]
@malloryfreeberg 

I would keep organoid_age and organoid_age_unit as they are. Organoid age/age_unit should be treated differently from age/age_unit. We changed the fields to include 'organoid' in them after issues were brought up at the Hinxton metadata meeting in March.  The main concern was that people may have different perceptions of when day 0 of organoid aging begins. 

The current organoid_age field has the following description: 'Age of the organoid in Organoid age unit. **Measured from when cell aggregates started differentiating to desired organoid model.**'

Would this description be carried over if we change organoid_age to age?


Are we also changing organism_age to age?

**Comment by malloryfreeberg** [comment]
> I would keep organoid_age and organoid_age_unit as they are

Keeping "organoid" contradicts the style guide which values easily understandable, fully qualified names over duplicated information. For example:

`organoid.age` is preferred over `organoid.organoid_age`

Given there is no other age field in the organoid schema, I think it is ok to remove "organoid" from this and the unit field. Also, the user-friendly name is still "Organoid age" for user-facing clarity.

> Would this description be carried over if we change organoid_age to age?

Yes. The field name can change independently of the description. In the [PR](https://github.com/HumanCellAtlas/metadata-schema/pull/655/files) you can see the changed field name and the same description:

```
        "age": {
            "description": "Age of the organoid in Organoid age unit. Measured from when cell aggregates started differentiating to desired organoid model.",
            "type": "number",
            "example": 55,
            "user_friendly": "Organoid age"
        },
```

> Are we also changing organism_age to age?

I don't know if there is a consensus for this. This [ticket](https://github.com/HumanCellAtlas/metadata-schema/issues/382) is still outstanding.

**Comment by diekhans** [comment]
If age is considered confusion, I would suggest something that specifies the type of age, like differention_age.  organoid_age really doesn't say anything more about age actually means in my mind.

**Comment by hannes-ucsc** [comment]
https://github.com/HumanCellAtlas/metadata-api/issues/40 has been promoted all the way through staging to production.
