### ISSUE TITLE
Guide for filling out metadata spreadsheet

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#485]
As a data contributor for phase 2, I would like some guidance on filling out the metadata spreadsheet so I can submit data.

Acceptance criteria
- Draft document for filling out metadata spreadsheet for phase 2 submitters
- Document reviewed by all wranglers
- Final markdown document hosted on metadata-schema repo

**Comment by hewgreen** [comment]
duplicated by https://app.zenhub.com/workspace/o/humancellatlas/ingest-central/issues/174
