### ISSUE TITLE
Convert ontology metaschema into jsonschema spec extension

### ISSUE THREAD

**Issue by dosumis** [HumanCellAtlas/metadata-schema#49]
JSON schema is intended to be extensible: 

"Implementations MAY define additional keywords to JSON Schema. Save for explicit agreement, schema authors SHALL NOT expect these additional keywords to be supported by peer implementations. Implementations SHOULD ignore keywords they do not support.

Authors of extensions to JSON Schema are encouraged to write their own meta-schemas, which extend the existing meta-schemas* using "allOf". This extended meta-schema SHOULD be referenced using the "$schema" keyword, to allow tools to follow the correct behaviour." 
[JSON schema v6 core, section 6.4](http://json-schema.org/latest/json-schema-core.html#rfc.section.6.4)

The core of an ontology field specification for recording graph restrictions is here:
https://github.com/HumanCellAtlas/metadata-schema/tree/version_4/json_meta_schema

(for background, see doc: [Embedding ontology validation in JSON Schema](https://docs.google.com/document/d/1qs2RP_0B1T5tVFuYJ7bneVTUgNqqjnyc1GoIKsXUWb0/edit?usp=sharing)) 

 - [ ] TODO:  add required context to make this a formal extension to jsonschema.

**Comment by daniwelter** [comment]
Nothing has been done on this for v5 so this is an ongoing issue.

**Comment by lauraclarke** [comment]
Is there an item about this in our JIRA backlog, this being here means it probably wont ever get prioritized

**Comment by lauraclarke** [comment]
@daniwelter is this something which is likely to be done in the next couple of phases, if not it should move into the icebox

**Comment by daniwelter** [comment]
This can put on ice for now

**Comment by ESapenaVentura** [comment]
Was this ever done?

**Comment by zperova** [comment]
@ESapenaVentura No
