### ISSUE TITLE
Deprecate attributes that can be expressed as supplementary and protocol files

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#490]
**For which schema is a change/update being suggested?**

`biomaterial_core`, `protocol_core`, `project`, `specimen_from_organism`, `barcode`

**What should the change/update be?**

Remove the following fields: 

- `biomaterial_core.supplementary_files`
- `protocol_core.document`
- `project.supplementary_files`
- `specimen_from_organism.state_of_specimen.microscopic_image`
- `specimen_from_organism.state_of_specimen.gross_image`
- `barcode.white_list_file`

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

Following the introduction of supplementary_file.json we no longer need to store the filenames of supplementary files in these attributes.

Please review this list and see if there are any missing attributes to deprecate for this reason or if we need to keep any (I'm particularly thinking about project.supplementary_files)

**Comment by malloryfreeberg** [comment]
> -biomaterial_core.supplementary_files
> -protocol_core.document

Are we going to eventually want to have these fields here for when ingest is able to link supplementary files to individual protocols and biomaterials? How will _e.g._ a document of a patient's medical history be linked to an individual donor in this future case? I want to avoid removing fields that we just need to add back in later.

> - project.supplementary_files

I already replaced this field with a `supplementary_links` field in [PR 476](https://github.com/HumanCellAtlas/metadata-schema/pull/476)

> - specimen_from_organism.state_of_specimen.microscopic_image
> - specimen_from_organism.state_of_specimen.gross_image
> - barcode.white_list_file

Same comment from the `biomaterial_core.supplementary_files` and `protocol_core.document` fields above. I want to avoid removing fields that we just need to add back in later. What is the plan?

**Comment by lauraclarke** [comment]
I would also like to know how we plan to indicate specific file types in the absence of these fields? and how anyone be able to use the metadata to link from a supplementary file to a specific entity?

**Comment by hewgreen** [comment]
This change requires the ability to link supplementary file entities to specific biological/file entities using the internal spreadsheet IDs. This as this isn't built yet we should leave these fields as they are until it is. Later we will need to remove these fields and rewrangle/curate all the phase 1 datasets to comply with this change.

**Comment by malloryfreeberg** [comment]
Closing this issue for now as `project.supplementary_files` has been addressed, and the other supplementary* fields will be addressed with a new issue ().
