### ISSUE TITLE
Missing dot notation for Process_id in Sequence file tab in 10x spreadsheet

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#491]
**Give the bug a title**

Missing dot notation for Process_id in Sequence file tab in 10x spreadsheet in the infrastructure integration test files

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to /metadata-schema/infrastructure_testing_files/current/dcp_integration_test_metadata_1_10X_bundle.xlsx
2. Click on Sequence tab
3. See error in Process ID field (row4)

**Expected behavior**

To have a dot notation for the Process ID: process.process_core.process_id

**Actual behavior**

No dot notation for the Process ID

**Comment by malloryfreeberg** [comment]
@zperova Can you clarify this bug? I can see the `process.process_core.process_id` programmatic name in row 4 of the Sequence file tab.

![Screen Shot 2018-08-13 at 15.37.55.png](https://images.zenhubusercontent.com/5b0ea149348b7966b4341398/c1dc54b7-d94e-4697-88ec-effdfcd09ff3)

**Comment by zperova** [comment]
Fixed the bug right after creating the issue as a practice with @hewgreen 
The commit should be "Added missing dot notation. Fixes #491".
