### ISSUE TITLE
Establish and maintain unit tests on the HCA metadata-schema repo

### ISSUE THREAD

**Issue by ofanobilbao** [HumanCellAtlas/metadata-schema#494]
The metadata-schema repo on GitHub needs comprehensive unit tests and mechanisms for automated updates/releases. This is a larger epic that will likely span the whole quarter and will require many tasks.

**Comment by ofanobilbao** [comment]
Replaces HCA-525

**Comment by ambrosejcarr** [comment]
Tagging this out of shared interest. We've started to implement a few basic unit tests for the spaceTx  image data schema and I would be interested in following/discussing json-schema with the team that ends up implementing this.

**Comment by ESapenaVentura** [comment]
@ofanobilbao is this still needed? Closing the ticket but if it's not needed just re-open it please
