### ISSUE TITLE
Add 'stem cell' to the list of enums for cell_line_type

### ISSUE THREAD

**Issue by pnejad** [HumanCellAtlas/metadata-schema#498]
**For which schema is a change/update being suggested?**
cell_line.json

**What should the change/update be?**
Add a new field to list of enums for cell_line_type

**What new field(s) need to be changed/added?**
new enum = stem cell 

**Why is the change requested?**
The current enums for cell_line_type are:

- primary

- induced pluripotent

- synthetic

- stem cell-derived

- immortalized

Embryonic and adult stem cell lines do not fall into any of the above categories. Adding 'stem cell' to the list would allow correct labeling of stem cell lines such as H1, H9 and [more](https://grants.nih.gov/stem_cells/registry/current.htm).  I have come across this issue with one of the pilot datasets.

*We may also want to consider keeping embryonic and adult stem cells separate by adding 2 new fields to the list of enums.

**Comment by malloryfreeberg** [comment]
I believe we can infer whether a stem cell is embryonic or adult from fields in the donor (`developmental_stage`) or specimen (`organ`, `organ_part`) schemas. I will add "stem cell" to the enum.
