### ISSUE TITLE
Using json schema format rather than defined patterns

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#5]
JSON schema has a tag called format which allows you to specify a string field should match a given format

It would be good for date, email and URI files to use this for validation rather than patterns as is currently the case.

Looking at contact.json

  "email": {
            "description": "Email of contact for contributingauthors", 
            "pattern": "^.*@.*..*$", 
            "type": "string"
        }, 

would be expressed as

  "email": {
            "description": "Email of contact for contributingauthors", 
            "type": "string"
            "format": "email"
        }, 

The full list of formats can be found here
http://json-schema.org/latest/json-schema-validation.html#rfc.section.8.3

This would seem much more in keeping with the idea of using JSON schema to valid content

**Comment by daniwelter** [comment]
@malloryfreeberg This may be of interest to what you're currently reviewing.

**Comment by lauraclarke** [comment]
Have we used this now? @daniwelter @malloryfreeberg Can this issue be closed?

**Comment by malloryfreeberg** [comment]
@daniwelter added date-time format to many fields. We didn't change the email field, but I will make that change now and tag this issue so that it closes when we merge.

**Comment by daniwelter** [comment]
Pattern has been replaced in all instances where a format is available.
