### ISSUE TITLE
Making largest scale test sheet and files

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#510]
As a member of ingest infrastructure dev team, I need spreadsheets and data files to use for scale testing.

We need to make a 200,000 bundle sheet with as wide as possible metadata. This is twice as big as the largest example for phase 1. The 400,000 files will come to over 12TB so Parth needs to make a new ec2 for this. The file will be two FASTQ files duplicated with a loop.

- spreadsheet is done
- needs to pass validation
- need to generate datafiles

**Comment by malloryfreeberg** [comment]
@hewgreen is this ticket still useful? Or can we close it.

**Comment by malloryfreeberg** [comment]
Closing for now. If someone requests another scale test spreadsheet/data sets, we will make a new ticket.
