### ISSUE TITLE
Draft of HCA Metadata Implementation Guide document

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#513]
As a developer against the HCA Metadata Standard and bundle structure, I would like information about assumptions, high-level functionality, and key insights of both metadata and bundle structure in order to be able to code effectively against the HCA Metadata Standard.

Tasks:
- [ ] Draft outline for what should belong in the HCA Metadata Implementation Guide document
- [ ] Identify existing documentation relevant to the Guide
- [ ] Assign sections to be written by individual persons
- [ ] Each person draft their section
- [ ] Final review of draft among all interested parties
- [ ] Publish document to master branch of metadata-schema repo

**Comment by malloryfreeberg** [comment]
Tagging @lauraclarke @ttung @rolando-ebi @rdgoite @aaclan-ebi to help start gathering documents relevant to this issue.

**Comment by zperova** [comment]
Relevant to the Metadata standard and improvement of the Metadata section on the Data Browser
