### ISSUE TITLE
Build and validate schema documentation using a CI system

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/metadata-schema#523]
Currently, documentation extracted from the schema is generated by a git commit hook.  This often results in conflicts that need to be resolved.  Building derived files is normally done by a process that runs downstream from the repository.  With github, this is generally done as part of the of a continuous integration process.

Having a CI process for the metadata would also allow for validation of examples against the updated schema, help to ensure they are current.

**Comment by diekhans** [comment]
@daniwelter wrote:

There was a lot of debate on when/how to build the markdown docs and the current pre-commit Githook isn't necessarily the optimal solution. Just for context, the following elements influenced the decision:
- The metadata repo has a wide range of contributors with different levels of technical ability, so the markdown generation script needed to be easy to run
- Lots of commits means the script needs to run regularly in order for the markdown to stay consistent with the json schemas
- Markdown docs need to be checked into the repo
- Even minor changes in markdown docs can cause merge conflicts

Checking in docs built by a CI process is a non-trivial problem and as we had limited time to generate a solution, a pre-commit Githook was the best compromise to quickly and regularly build the docs without committers having to actively remember to run a script every time they commit a change. The hook also helps with markdown merge conflicts as the committer can be confident that as long as their branch is up-to-date, their docs will also be the "canonical" version, and they can therefore resolve any conflicts directly in their favour. Any incorrectly resolved conflicts will also be rectified at the next commit.

As I said, the precommit Githook isn't necessarily the best solution here but it was the best compromise at the time. I would be happy to revisit with better options if anyone has any suggestions. I am however closing the discussion here as it is OT for the PR - we can transfer comments to a ticket if anyone would like to discuss doc generation optimisation.

**Comment by zperova** [comment]
We think many of this has been done and we will review the process in a separate ticket.
