### ISSUE TITLE
Add new cell suspension field: Inferred cell type

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#524]
**For which schema is a change/update being suggested?**

I would like to request an update the the `cell_line.json` schema.

**What should the change/update be?**

The `cell_line.json` schema could possibly contain an `inferred_cell_type` field for capturing cell types discovered by the data generator post-analysis. Currently, the `selected_cell_type` field 

**What new field(s) need to be changed/added?**

* Field name: `inferred_cell_type`
* Field description: The cell type inferred based on an analysis.
* Required: no
* Example: pancreatic PP cell
* CV or enum: ontology (HCAO cell line ontology)

**Why is the change requested?**

Often, data generators will have done some analysis on their data prior to submission, and might have determined the cell type for their data. While this information will not be used by the HCA DCP analysis pipelines, it might be useful for data consumers to know what the original data generators thought their cell types were. This field might conflict with `selected_cell_type` or with results from how the DCP analyzes the data, so we should open this topic up for discussion.

**Comment by malloryfreeberg** [comment]
@daniwelter a topic for a tertiary portal metadata call?

**Comment by zperova** [comment]
There needs to be a clear distinction between `inferred_cell_type` and ` selected_cell_type` for the user when he/she searches for it in the browser.

**Comment by lauraclarke** [comment]
I am concerned about this field being added without any resolution to the discussion if we will take secondary analysis results from users

As pointed out by Zina this created a lot of complexity from a data browser display point of view and potentially from a user interpretation perspective. I would propose this remains in the icebox untill the policy question surrounding secondary analysis results is resolved

**Comment by claymfischer** [comment]
Annotations such as this are currently being explored in a proposal to the GG. We are documenting user stories about why this type of information is important for data generators to provide. 

If done, I agree that this needs to be very clearly distinct as user-generated supplementary analysis, and not a canonical annotation.

**Comment by lauraclarke** [comment]
Does the secondary analysis document exist somewhere, it would be great to review it?
