### ISSUE TITLE
Supplementary_links example update.

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#528]
**For which schema is a change/update being suggested?**

Project type schema

**What should the change/update be?**

The example for this field may not be appropriate:

```
        "supplementary_links": {
            "description": "External link(s) pointing to code, supplementary data files, or analysis files associated with the project which will not be uploaded.",
            "type": "array",
            "example": "https://github.com/czbiohub/tabula-muris",
            "items": {
                "type": "string"
            },
```

**Why is the change requested?**

Our UX designer pointed out that this was a poor example. Consider filling out the `guidelines` attribute to give more context for what to put here.

**Comment by hewgreen** [comment]
We should think about this in the context of the new style guide https://github.com/diekhans/metadata-schema/blob/mf-metadata-style-guide/docs/schema_style_guide.md

**Comment by malloryfreeberg** [comment]
Here is a second example that we could use:

`"https://www.ebi.ac.uk/gxa/sc/experiments/E-GEOD-106540/Results; https://github.com/czbiohub/tabula-muris"`

Where there are 2 examples, separated by a semicolon (as per the style guide).

**Comment by hewgreen** [comment]
Should we close this issue for now and await tickets for a more general overhaul which would include guidance rather than adding a temporary fix or should I make a PR?
