### ISSUE TITLE
Update all example spreadsheets in repo for F2F hackathon Sept 11-13, 2018

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#529]
This ticket it to make sure that all example spreadsheets are in the integration metadata-schema repo in preparation for the DCP F2F hackathon in Boston on Sep 11-13.

- [x] Confirm with @kbergin what data/spreadsheets are needed
- [x] Check that these spreadsheets are in infrastructure-testing-files in integration branch
- [x] Check that these spreadsheets upload/validate against schemas in integration branch
- [x] Update spreadsheets if they do no upload/validate
- [x] Make new "larger" 10X spreadsheet from ICA dataset
- [x] Make sure that updated spreadsheets are in integration

In the infrastructure-testing-files folder right now, we have the following:
- GBM SS2 DCP-wide integration test spreadsheet (1 bundle)
- GBM 10X DCP-wide integration test spreadsheet (1 bundle)
- GBM 100-cell (SS2) spreadsheet (100 bundles)
- GBM 200-cell (SS2) spreadsheet (200 bundles)
- GBM 400-cell (SS2) spreadsheet (400 bundles)
- GBM 1000-cell (SS2) spreadsheet (1k bundles)

Need to make and add to infrastructure-testing-files folder: 
- ICA larger 10X spreadsheet (32 bundles)

**Comment by kbergin** [comment]
Love seeing this ticket! The list of ones that currently exist seem like the appropriate ones to have for testing. Maybe a larger 10x bundle (vs an int sized one) would also be helpful, in case we have that pipeline in testing by then?

**Comment by malloryfreeberg** [comment]
Maybe @zperova can work on making a large 10X sheet. How many bundles were you thinking, @kbergin ? For SS2, 1 cell = 1 bundle, but for 10X we'll need to make sure that we have the appropriate number of cell suspensions/files (maybe throw in a technical replicate or two for fun?). How many 10X bundles/pipelines do you want for a "large" one?

**Comment by daniwelter** [comment]
@malloryfreeberg I started work on reducing the ICA dataset to a 10X test s/sheet - happy to coordinate with @zperova so she doesn't have to start from scratch.

**Comment by malloryfreeberg** [comment]
@daniwelter perfect. I think that would satisfy the last spreadsheet needed as per @kbergin 's response. I'll add it to the checklist above.

**Comment by malloryfreeberg** [comment]
I confirmed that all the spreadsheets (except @daniwelter 's new one) are in the repo.

**Comment by kbergin** [comment]
Amazing, thank you both so much!

**Comment by malloryfreeberg** [comment]
@daniwelter did you happen to make that subsetted 10X spreadsheet?

**Comment by malloryfreeberg** [comment]
@daniwelter has uploaded a 10X spreadsheet with 32 bundles into develop and integration that validates against the frozen schemas.
