### ISSUE TITLE
Add links to relevant OLS ontology pages.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#53]
In the descriptions of ontology fields, include a link to the relevant OLS ontology page. Suggest to submitter to access this link and choose an appropriate ontology for the field.

**Comment by JimKent** [comment]
Seems reasonable, at least to put in the suggested ontology name in.   URLs tend to be a bit more human than machine readable, so not sure about putting it in a description we're hoping to keep short.   If we can wrap the ontology name in a hyperlink when we display it to the user though it'd be ideal.
