### ISSUE TITLE
Create schema linter to verify against style guide

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/metadata-schema#537]
Create library and program to verify that the schema matches the style guide (linter).  This could be run as a commit hook to make sure updates conform to the specification.  It will also serve to help ensure the accuracy of the specification.  Known exceptions may be specified as a way to help track what doesn't conform.

Related to #419 and #523

Thanks to @TimothyTickle for the suggestion.

**Comment by malloryfreeberg** [comment]
@hewgreen to think/write out specific steps (issues) and link to this Epic.

**Comment by hewgreen** [comment]
Code in progress in branch mg-style_validator

**Comment by malloryfreeberg** [comment]
Linter features tracked [here](https://docs.google.com/document/d/1pg-YCBE9YGAEVVZQN6p3nKMghdjiUSd8i4mlnRheoUs/edit).

First draft of linter merged in to develop (#788).
