### ISSUE TITLE
Include a watchlist of "needed" metadata fields in the schema testing strategy

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#538]
As a developer against the HCA metadata schemas I would like you to include a watchlist of "needed" metadata fields in your testing strategy so I can be informed if you change a field which is needed for my own process/software

**Comment by lauraclarke** [comment]
This is a ticket stub for the idea that myself @tburdett @simonjupp and @morrisonnorman were kicking around after discussions with @mweiden 

The testing strategy for the metadata schemas should include a watchlist of fields which are important to downstream users

This list won't reflect a commitment to never change these fields but instead aims to raise awareness both if someone requests a change to one of these fields that their change will have downstream consequences but also flag changes to users of that field, if the change considered justified to improve the scientific value of the schemas and data or to fix a bug

This ticket needs more fleshing out

**Comment by mweiden** [comment]
@lauraclarke this could help. Let's also check in with the Arch group on this next week after the eng F2F. We might be able to come up with a solution that might address your concerns--wranglers not having to know about downstream systems and rapid schema evolution--even better.

**Comment by lauraclarke** [comment]
If there are orthogonal ways to protect against this that is great. Having something which is intrinsic to the metadata testing systems seems like a good plan though

**Comment by zperova** [comment]
Closing as no progress has been done on this.
