### ISSUE TITLE
Consider removing "related_projects" field from project.json

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#54]
As suggested by submitter, the definition of what counts as a "related project" is unclear. It is likely that related projects can be identified by querying the data store and do not necessarily need to be hard-coded by the submitter.

**Comment by JimKent** [comment]
I'm happy to leave this out myself.  There are fields in ArrayExpress and GEO that correspond to this.  They tend to be used for large projects which sometimes get broken into  of smaller projects that reference each other (or a parent) via this field.

**Comment by lauraclarke** [comment]
This was added as a suggestion from ArrayExpress.

I would be happy for it to be left out.

It would be interesting to do a query in ArrayExpress and see how often it is used if not often then the user is in the majority and the usefulness of the field is probably limited. If it is used a lot it would be good to see how it is used, if it is consistent and if we can improve our own documentation.

**Comment by daniwelter** [comment]
Is this still an ongoing issue? The field hasn't been removed yet.

**Comment by malloryfreeberg** [comment]
Along with the other opinions voiced here, I am in favor of removing the related_projects field from the schema. Querying on various facets will give us enough information about the "relatedness" of the projects.
