### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#540]
It would be good to clean up branches in the metadata-schema repo that are no longer being used for development prior to the pilot launch. The following branches we have are:

- `master` - Environment
- `develop` - Environment
- `staging` - Environment
- `mf-metadata-style-guide` - Open PR
- `integration` - Environment
- `dw_project_license` - Open PR
- `ws-10x` - DELETE? @willrockout 
- `new-bundle-examples` - DELETE? @simonjupp 
- `mf-new-brain-initiative-module` - Active (NeMO)
- `develop_will` - DELETE? @willrockout 

If you've been tagged, please determine if the branch can be deleted and then delete if yes.

**Comment by malloryfreeberg** [comment]
Pinging @simonjupp @willrockout

**Comment by willrockout** [comment]
@malloryfreeberg All done!
