### ISSUE TITLE
Decide if each donor field is necessary or not

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#55]
Specifically in donor.json, there are many fields that may not be useful for querying. We would also need to justify for each field why it is necessary to collect this information. Someone(s) should do a pass through all the field and decide which ones aren't necessary.

**Comment by malloryfreeberg** [comment]
Also, noted by user evaluation session, some "donor" fields don't apply to e.g. mouse. Also they don't consider a mouse a "donor" (can't give consent). Consider grouping donor fields so they can be appropriately given to different donor types.

**Comment by JimKent** [comment]
Which ones don't seem to be useful for queries?  They all look useful to me.

**Comment by malloryfreeberg** [comment]
Closing this ticket. We have moved various donor (now organism) fields to modules based on whether they are highly specialized.
