### ISSUE TITLE
Make publication field in cell_line.json a single object instead of an array of objects

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#557]
**For which schema is a change/update being suggested?**

I would like to request an update the the `cell_line.json` schema.

**What should the change/update be?**

Make the `cell_lines.publications` field a single `publication` object instead of an array of `publication` objects

Current:

```
        "publications": {
            "description": "One or more publications in which the cell line creation was cited.",
            "type": "array",
            "items": {
                "$ref": "module/project/publication.json"
            },
            "user_friendly": "Cell line publications"
        }
```

Suggested:

```
        "publication": {
            "description": "A publication in which the cell line creation was cited.",
            "type": "object",
            "$ref": "module/project/publication.json"
            "user_friendly": "Cell line publication"
        }
```
**What new field(s) need to be changed/added?**

No new fields

**Why is the change requested?**

Cell lines should only need 1 publication cited. Also, this is a temporary solution until a generic solution for importing arrays of objects with array fields can be implemented by the importer.

**Comment by malloryfreeberg** [comment]
@daniwelter does this change seem reasonable to you?

**Comment by daniwelter** [comment]
As long as we're confident that we won't get a dataset tomorrow which absolutely insist on providing multiple publications for a cell line, yes, this is absolutely reasonable.
