### ISSUE TITLE
Replace "body_part" in specimen_from_organism.json with meaningful field name

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#56]
The body_part field in specimen_from_organism.json doesn't really reflect what we want to capture. What we want is a more specific name for the part of the organ that was collected. For example, if organ="pancreas", we want to collect that the specific part of the pancreas that was collected is the "islet of Langerhans". Therefore, consider renaming body_part to "organ_part" or something similar. This field could also be linked to an ontology.

**Comment by dosumis** [comment]
I think this is the right thing to do, given the feedback from data submitters, but thought I'd should mention here that we discussed this previously and one objection to this change was that we may have cases where the biological sample is not an organ or organ_part - at least as many biologists will use this term.  Having said that - organ is used in many different ways, so I think we can get around this issue with a description that makes it clear we take a very broad view of what counts as an organ.

**Comment by JimKent** [comment]
There is a separate "organ" field.   The body_part is deliberately ambiguously named.  Past the organ level, what people do to isolate a sample is highly variable.  People can separate by tissue, by tissue layer,  and also by sorting.  The intent of the body_part is to encompass all of this in a single place.   It seems less of a problem to have a vague sounding name like "body_part" that is not misleading than to use a term like "organ" in a nonstandard way.

**Comment by malloryfreeberg** [comment]
Addressed in 3e7cc55

**Comment by lauraclarke** [comment]
I agree with Jim that body is better thatn organ, what about organism_part rather than body_part of organ_part

Then if it is a section of multiple layers that can be considered different "organs" no one feels the field isn't for them.

That being said, this is something it would be good to get user views on, not sure what the best approach for that is

**Comment by JimKent** [comment]
I could live with organism_part.  I don't like organ_part.  I still prefer body_part for being short and already in common English usage.
