### ISSUE TITLE
Enforce selection of foreign keys from primary keys in spreadsheet

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#57]
If possible in spreadsheets, write rules that enforce selection of foreign key from appropriate primary key field. For example, enforce that the `input_biomaterial_id` field in the specimen_from_organism tab must be filled with a value from the `biomaterial_id` field in the donor tab. 

This will be easier to implement in UI, but would be very useful for spreadsheets as well.

**Comment by lauraclarke** [comment]
I am going to guess this isn't a feature which is likely to be developed for the MVP. Can we move it to the ice box?

**Comment by malloryfreeberg** [comment]
Yes, it can be moved to icebox.

**Comment by malloryfreeberg** [comment]
Issue moved to [HumanCellAtlas/ingest-central #105](https://github.com/HumanCellAtlas/ingest-central/issues/105) via [**ZenHub**](https://www.zenhub.com/)
