### ISSUE TITLE
Add protocol_type field to imaging_protocol.json

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#572]
**Give the bug a title**

protocol_type is a required field but the field is not in the schema. Worryingly this passed validation.

We either need to remove this from the required fields list or add the field.

**Schema versions**

imaging_protocol.json

**Expected behavior**

Is protocol_type a duplication of assay_type? We record assay type for each target.

        "assay_type": {
            "description": "Type of assay used to detect target.",
            "type": "object",
            "$ref": "module/ontology/process_type_ontology.json",
            "example": "MERFISH, smFISH, immunofluorescence, fluorescent cell stain",
            "user_friendly": "Assay type"
        },

As we have this do we need protocol_type at the level of imaging_protocol.json?

**Comment by zperova** [comment]
There is no protocol_type in the original description of the imaging_protocol.json. So this must have migrated from copy-pasting during creating of the file?
https://docs.google.com/spreadsheets/d/1pQfWaywIK1e6YJFVdX5gFP7nwszD3Z6ZJppEVjbWA24/edit#gid=1087460193

**Comment by zperova** [comment]
@hewgreen @dosumis if no one disagrees I will remove it.

**Comment by malloryfreeberg** [comment]
Please remove it!

**Comment by hewgreen** [comment]
I agree remove it. This is a bad way to describe what I presume it was anyway and capturing this at a more granular level is likely to be better.
