### ISSUE TITLE
JSON validator failed to notice missing required field

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#576]
**To reproduce**

Issue #[572](https://github.com/HumanCellAtlas/metadata-schema/issues/572) outlines the problem. An attribute 'protocol_type' was listed int he required list in imaging_protocol.json but it doesn't exist in the schema. This JSON was considered valid.

I would expect this to be invalid JSON. We should look at our validator and see why this was missed.

Acceptance criteria: improved validator fails schema that have missing fields.

Note that issue 572 is likely to have this removed from the required list before this ticket is addressed. Either create a dummy JSON to simulate the error or use the corrupt version 8.0.2.

**Schema versions**

 "imaging_protocol": "8.0.2"

**Comment by malloryfreeberg** [comment]
Our current JSON validator uses `Draft4Validator` from [jsonschema](https://github.com/Julian/jsonschema), which may be contributing to why we don't get an error when we include a field in required list that isn't actually in the schema. Investigating whether this python package supports Draft-07 JSON yet.

**Comment by malloryfreeberg** [comment]
The current released version of `jsonschema` is 2.6.0 and **does not** support draft-07 validation. The most recent [tagged branch](https://github.com/Julian/jsonschema/releases/tag/v3.0.0a3) in the `jsonschema` repo (v3.0.0a3) **does** support draft-07 validation, but it's not been stably released. I haven't been able to figure out how to test this tagged branch in our `schemas_are_valid_json.py` script. Need help!

**Comment by malloryfreeberg** [comment]
@daniwelter I think I've reach the end of my ability to investigate this issue. If you have some bandwidth, could you take a look?

**Comment by daniwelter** [comment]
I've just tested this use case with the new javascript validator and it still doesn't catch this. Neither does the only draft-07 compatible online validator I could find.

**Comment by malloryfreeberg** [comment]
I wonder if it's time to make a git issue on the javascript validator project...

**Comment by claymfischer** [comment]
@malloryfreeberg I think you're right.

**Comment by daniwelter** [comment]
I've flagged this with the JSON schema development group as I'm unclear whether this is a validator implementation issue or whether it's a more fundamental issue with the schema spec. https://github.com/json-schema-org/json-schema-spec/issues/692

**Comment by daniwelter** [comment]
Somebody from the JSON schema team got back to me on the issue and suggested that this needs to be caught by a linter rather than encoded in the specification as this is an interaction between keywords and the schema can't capture every potential interaction of every combination of keywords.

**Comment by dosumis** [comment]
Should be easy enough to write a test for this using jpath

**Comment by dosumis** [comment]
Here's a gist showing how this can easily be tested using JPATH

https://gist.github.com/dosumis/2fc95a4d4b7aa2f0d5a9856a94d75696

**Comment by malloryfreeberg** [comment]
This bug will now be addressed by the new schema linter. The linter will perform a check that all fields listed as required are indeed in the schema.
