### ISSUE TITLE
Add `file_core.is_auxiliary`

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-schema#579]
**For which schema is a change/update being suggested?**

I would like to request an update the the `file_core.json` schema.

**What should the change/update be?**

Add a field to express that a data file is "auxiliary" in the sense that it is not useful in isolation, but only in the presence of another file.

**What new field(s) need to be changed/added?**

* Field name: "is_auxiliary"
* Boolean type
* Required: No

**Why is the change requested?**

Analysis bundles will soon contain expression matrices in the form of a [zarray](https://zarr.readthedocs.io/en/stable/spec/v2.html) store. These stores are essentially a collection of files, a main `.zarray` file and dozens of other files referenced in the `.zarray` file.

Each of these files will have to be described by metadata and linked to the analysis process that created them. That's the only way they can be placed together in a bundle. However, the data browser should only show a row for the `.zarray` file. Listing all files would clutter the UI significantly without gain in utility or expressiveness.

@tburdett @mckinsel @rexwangcc @dshiga @NoopDog

**Comment by malloryfreeberg** [comment]
@hannes-ucsc so I can understand the usage the better: is the intention that each analysis bundle submitted by an analysis pipeline to ingest will contain - in addition to the regular analysis files - a collection of 1 main zarray file and other files, and it is these (1 main zarray file and other files) files that will need to have the indication of being auxiliary or not? 

Will the "main zarray file and other files" be submitted using the `analysis_file.json` schema? If so, I propose putting the proposed `is_auxiliary` field in the `analysis_file.json` schema. Unless there is a reason that the field might ever be needed for other types of files like sequence data files, image files, etc.

**Comment by hewgreen** [comment]
I'd go even more granular Mallory.

I think imaging datasets have this same usecase with some added complexity. A metadata field that essentially toggles indexing doesn't sound optimal. It would be preferable to enhance our file typing. I've perviously advocated recording both file format (we have this) and a file content label as an enum (proposed new field for file_core). These aux zarr files are not unknown and we should avoid overloading that term but we should be able to tag them. As an example we could say format is `.zarray` file_label is `aux_zarr`. Then the datastore could be more specific about not indexing these file types. This mechanism would also be helpful elsewhere in imaging and supplementary files.

**Comment by malloryfreeberg** [comment]
@rexwangcc @hannes-ucsc If we are to add this field to the `analysis_file.json`, how do you all want to handle current analysis files that get submitted in the secondary bundle? For example, the bam and bai and log files. Should they also have this field? What should it be set to? I'm not sure how the Browser currently decides which of those files to display. Looks like only the BAM secondary files are being shown? How is this encoded?

Although this ticket might be a good idea, we are currently in a metadata freeze except for bug fixes and metadata needed to ingest datasets. I would consider this a feature request but happy to discuss when this change might be able to be incorporated into the metadata release process.

**Comment by hannes-ucsc** [comment]
> so I can understand the usage the better: is the intention that each analysis bundle submitted by an analysis pipeline to ingest will contain - in addition to the regular analysis files - a collection of 1 main zarray file and other files, and it is these (1 main zarray file and other files) files that will need to have the indication of being auxiliary or not?

What @rexwangcc said.

> Will the "main zarray file and other files" be submitted using the analysis_file.json schema? If so, I propose putting the proposed is_auxiliary field in the analysis_file.json schema. Unless there is a reason that the field might ever be needed for other types of files like sequence data files, image files, etc.

I think this might come in handy for imaging files, too.

At the very highest level, what is missing here is a way to express relationships between files. Orange and potentially others are in need of a mechanism to answer the following question: *In order to process file A which other auxiliary files do I also need?* Without this mechanism, only a heuristic can be used. In the example @rexwangcc gave, the heuristic would be to consider all files with the same prefix (`xxx` in that example). @tburdett mentioned that the relationship will be made evident by `links.json` which links those files to the same process. But this doesn't express the fact that I don't need the `.bam` when I'm interested only in the matrix files. Neither does that cover the case where there are two independent zarray stores in a single analysis bundle. 

Maybe we should simply add more edges to the graph via `links.json`. Edges that express relationships directly between files. As in "file `A` is useless without file `B`."

**Comment by hewgreen** [comment]
> the case where there are two independent zarray stores in a single analysis bundle

In the imaging case, spacetx own and control the metadata and linking of files. For spacetx format imaging data we've been told that pointing to their experiment.json (their highest level entity) is all the HCA metadata needs to do (we may mark the rest as auxiliary). But as Hannes points out, this would mean in a bundle with more than one experiment.json file you wouldn't know which aux files belonged to which experiment.json without looking in the experiment.json and finding out. DCP couldn't do this very reliably because we don't control the format. The knock on effect here would be that a user couldn't just download one experiment. Down the hierarchy they also have multiple FOV.json files which are manifests with pointers. At that granularity it is likely there will be more than one per bundle which gives us the same problem as Hannes mentions.

For matrix files we have more control of the format so could inspect the `.zarr!.zattrs` file but it would be nice to have some extra links so we didn't have to. Depending on consumer requirements we may need to do something similar for imaging but with the added worry that the format is not stable and third party. So a general mechanism would be great.

**Comment by malloryfreeberg** [comment]
Discussed on Metadata call 19/11/2018. Decided to make new ticket with specific use cases (e.g. zarr*, bam/bai). @hannes-ucsc

**Comment by hannes-ucsc** [comment]
Notes to self: BAI/BAM and imaging.

**Comment by hannes-ucsc** [comment]
Superseded by #623.
