### ISSUE TITLE
Remove well-related fields from cell_suspension.json

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#58]
Based on user feedback, it was suggested that well-related information would not be relevant for downstream users. Consider removing these fields altogether from cell_suspension.json. Perhaps they can be moved to a specific procedure's JSON schema, which would be a more appropriate place for them.

**Comment by JimKent** [comment]
Hmm.  It is helpful to know which samples came from the same plate to help look for batch related artifacts.
The well.quality is also helpful in knowing samples that should be rejected.  The well.cell_type currently is the only place we have to put the submitter's guess to cell type when we are importing data sets from GEO or ArrayExpress that are done well-by-well.

**Comment by malloryfreeberg** [comment]
I guess the term "well" is confusing here, at least for some of our users (any myself, admittedly). For example, a 10x group we talked to mentioned that they wanted to put in channel information (8 channels per 10x microfluidics chip) so that channel-based batch effects could be assessed. I guess channel information could be interpreted as "well" information, but this differs slightly from "well" information in other contexts, e.g. a fluidigm C1-based assay. I'm sure there are other well/channel/etc. types for other protocols that might not fit the current well.json schema.

Should we make well.json more flexible to accommodate all well/channel/etc.-type things? Or have separate well.json, channel.json, etc.? This discussion might benefit from speaking with someone who has experience using a variety of sequencing techs.

**Comment by JimKent** [comment]
I would very much want to see well and channel kept separate.  In the single cell world so far at least,
 in the Fluidigm and FACS sorter plate based techniques, we've just been seeing people try to get one cell per well while a channel processes lots of cells.   The channel tracking request is making me want to have a "tenX" module to put it in.

**Comment by daniwelter** [comment]
well-related information has been moved into its own module so this ticket can be closed after v5 release
