### ISSUE TITLE
In the JSON schema to spreadsheet converter, enforce enum fields.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#59]
It was suggested by a user that having enum fields in a drop-down menu would aid spreadsheet filling. @simonjupp and @daniwelter suggested that it is possible to implement autofilling of a drop-down menu from enum JSON field.

**Comment by lauraclarke** [comment]
@simonjupp @aaclan-ebi @rdgoite @daniwelter Was anything ever done about this, this issue is from a long time ago

If it wasn't done I am guessing that ingest-central or JIRA might be a better place for this than here?

**Comment by daniwelter** [comment]
Yes, this is not a metadata issue and should be moved.

**Comment by daniwelter** [comment]
Issue moved to [HumanCellAtlas/ingest-central #70](https://github.com/HumanCellAtlas/ingest-central/issues/70) via [**ZenHub**](https://www.zenhub.com/)
