### ISSUE TITLE
Move normothermic_regional_perfusion to death.json schema

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#590]
**For which schema is a change/update being suggested?**

I would like to request an update the the `donor_organism.json` and `death.json` schemas.

**What should the change/update be?**

The field `normothermic_regional_perfusion` should be moved from the `donor_organism.json` schema to the `death.json` schema as it is only relevant if the donor is deceased. Usually it is done prior to organ donation.

**What new field(s) need to be changed/added?**

No new fields requested.

**Why is the change requested?**

This field was added to the `donor_organism.json` schema based on requirements for the Tissue Sensitivity dataset, but as it only applies in cases where the donor is deceased, it should be moved to the `death.json` module.

**Comment by hewgreen** [comment]
PR: https://github.com/HumanCellAtlas/metadata-schema/pull/636
