### ISSUE TITLE
Add nominal_length and nominal_sdev to library_preparation_protocol.json

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#594]
**For which schema is a change/update being suggested?**

I would like to request an update the the `library_preparation_protocol.json` schema.

**What should the change/update be?**

I would like to add two new fields - `nominal_length` and `nominal_sdev` - to this schema to align with ENA standards and enable USI submissions to the archive. Open to alternative names for the fields, but it would be great if they were at least similar to the ENA fields to make it obvious they are representing the same value.

**What new field(s) need to be changed/added?**

Field 1:

* Field name: nominal_length
* Field description: Average (insert) size of the fragments being sequenced.
* Required: no
* Example: 250
* CV or enum: no

Field 2:

* Field name: nominal_sdev
* Field description: Standard deviation of the (insert) size of the fragments being sequenced.
* Required: no
* Example: 30
* CV or enum: no

**Why is the change requested?**

In the sequencingExperiment ENA metadata submitted via the USI, if the layout is paired, then the attributes NOMINAL_LENGTH and NOMINAL_SDEV are required. The HCA metadata standard should try to capture this metadata so it can be translated to ENA if needed (if `"paired_end": true`).

From Dave: 
> ENA require these fields for PAIRED layouts. Positive integers values should be fine, but present them as strings (i.e. "150" instead of 150)

Metadata appears in ENA Experiment XML like this:
```
               <LIBRARY_LAYOUT>
                   <PAIRED NOMINAL_LENGTH="250" NOMINAL_SDEV="30"/>
               </LIBRARY_LAYOUT>
```

Field definitions in ENA: 

>The attribute PAIRED NOMINAL_LENGTH is the average insert size. It is not the length of the reads. It is the average size of the fragments that are being sequenced.
>The attribute NOMINAL_SDEV is the standard deviation of the fragment lengths. This attribute is not mandatory so you can omit it if you do not have this detail.

**Comment by hewgreen** [comment]
PR https://github.com/HumanCellAtlas/metadata-schema/pull/635
