### ISSUE TITLE
Protocol accession regular expression

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#6]
The pattern associated with protocol seems to be found in many different places

https://github.com/HumanCellAtlas/metadata-schema/search?utf8=%E2%9C%93&q=%22pattern%22%3A+%22%5EP-....-.*%24%22%2C+&type=

It would be better to change this to a definition which could be referenced from anywhere using the file name?

Not sure what the right syntax is but presumably it would need something like 

      "protocol_access" : {
          "pattern": "^P-....-.*$", 
           "type": "string"
      },

Then if we need to change the pattern, we only need to change it in one place

**Comment by lauraclarke** [comment]
@malloryfreeberg I suspect this is now a non-issue. Please close it or update the issue with what ever the current state is

**Comment by malloryfreeberg** [comment]
This field has been removed in v5.0.0. It was determined to be a specific regex for protocols taken from ArrayExpress. We now have a more generic way to encode protocols, so this specific regex is not needed.
