### ISSUE TITLE
Include representation of an organ for datasets with stem cell derived cell lines.

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#606]
**What is the proposed name of the new schema?**
I would like to request a new field to represent an organ that stem cell derived cell lines model.
I can propose `model_organ` but this is open for suggestions.

**What field(s) should the new schema contain?**

* Field name: model_organ
* Field description: Organ for which this cell line is a model.
* Required: yes
* Example: brain
* CV or enum: yes, UBERON (same as `organoid.model_organ`)

**Why is the new schema needed?**

In case of datasets where the `biomaterial` in cell suspension tab was differentiated from embryonic stem cells (specific example: neuro_diff SS2 demo dataset) the modelled organ is not captured. The browser displays `embryo` as the organ (pulling it from the `donor_organism`) but should display `brain`as the cells are diffirentiated into inhibitory neurons.

There might be a different solution for this problem (displaying a correct organ in the browser, Issue https://github.com/HumanCellAtlas/data-browser/issues/338). Discussion is welcome.

**Comment by malloryfreeberg** [comment]
I'd like to prioritize this issue for GA, as it will greatly enhance the understandability of datasets for anyone looking at the Browser. Regardless of how the Browser decides to display this information, we are indeed lacking in capturing the organ/tissue that a cell line represents. e.g. cardiomyocytes representing heart or inhibitory neurons representing the brain.

The only other option I can think of is to infer the organ from looking at the cell line `cell_type` field, and whether the ontology for the field can be used to extrapolate the organ. @daniwelter is this a possible solution? 

Either way, I think I favor Zina's solution.

**Comment by daniwelter** [comment]
It might be possible to derive the organ from `cell_type` is the cell type is sufficiently well axiomatised in HCAO but it's not something I'd want to rely on. Furthermore, it would require some potentially more advanced ontology look-ups to work this out.

I think Zina's proposed solution is far more user-friendly and accessible. We could always (at some point in the future) implement a double-pronged approach where we capture `model_organ` AND derive the organ from the `cell_type` ontology term, then flag to the user if they don't match.

**Comment by malloryfreeberg** [comment]
Cool. I'll move this issue to the To do/Ready pipeline.
