### ISSUE TITLE
Communication with Matrix service on metadata requirements and strategy

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#608]
The Matrix service https://github.com/HumanCellAtlas/dcp-community/blob/master/charters/ExpressionMatrixService/charter.md provides metadata inside the delivered matrix files.

We need to understand what is the provenance of this metadata, how it is being presented and what the requirements users are

---

Two actions to start this process and understanding these interactions:

- [x] Invite matrix service reps to present how/what metadata they add to their files and how it is structured on Metadata call
- [x] Invite matrix services to regularly attend the Tertiary Portal/Analysis application metadata calls as we are currently assuming matrix files from the matrix service are likely to be a frequently accessed service by these downstream services

---

Next actions to continue this process:

**Comment by hewgreen** [comment]
I have met with Marcus from the matrix team and got a background of their thinking about metadata to date. They are currently importing analysis metadata and in the future they want to ensure they pull in relevant 'bundle metadata' to their expression files and provide a clear way for user to link back to the full bundle metadata.

The metadata team should now:
1. Engage with ux to discuss which fields are most relevant to users
2. Investigate a linking mechanism and make a proposal
3. Together with the matrix team we should produce instructions for users about how to access the rest fo the metadata.

**Comment by malloryfreeberg** [comment]
@hewgreen can you add a list of subtasks (with check boxes) in the main issue text under the "Next actions to continue this process" section? I want to make sure we have action items captured at the top of the ticket. Ty!
