### ISSUE TITLE
Update imaged_specimen according to the Schema Style Guide

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#611]
**For which schema is a change/update being suggested?**

I would like to request an update for the `imaged_specimen.json` schema.

**What should the change/update be?**

I would like to make the following changes:

- [x] move "Must be one of..." part of description in `overview_image` to guidelines
- [x] add second example to `overview_image`
- [x] change `overview_image` to `overview_images` since the field is an array
- [x] change `imaged_slice_thickness` to `slice_thickness` to remove redundant "imaged" word
- [x] add second example to `imaged_slice_thickness`

**Why is the change requested?**

As a consumer of the HCA metadata schemas, I would like to be sure that the metadata standards follow a set of consistent formatting and rules.

**Comment by zperova** [comment]
@hewgreen Do you agree with removing "imaged" word from `imaged_slice_thickness`? The initial idea was that `imaged_slice` is the `biomaterial` however we settled on the `imaged-specimen` instead.

**Comment by hewgreen** [comment]
Sounds good to me. I'd like to see if we can think of a principle that this highlights that we could add to our style guide?

**Comment by malloryfreeberg** [comment]
I think this follows the style guide:

> Unqualified field names should not contain context. Unqualified field names do not stand alone, meaning they are not accessed or used outside of their context (i.e. their schema). Therefore, additional context should be removed from unqualified field names unless there is justification for including it. For example:

So `imaged_specimen.imaged_slice_thickness` becomes `imaged_specimen.slice_thickness` which removed redundancy of the "imaged" word.
