### ISSUE TITLE
Broken internal link to "specifying schema urls" in the Overview of Metadata Structure document.

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/metadata-schema#614]
In this document the last TOC link is no longer valid:

https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/structure.md

This is causing link to also not work when this page is imported into the data portal.

https://dev.data.humancellatlas.org/learn/metadata/structure#specifying-schema-urls

Cheers,
D

**Comment by malloryfreeberg** [comment]
Good catch! Thanks @NoopDog .

This is now fixed in all environments.
