### ISSUE TITLE
insdc_experiment and insdc_run are per-sample features

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#62]
`insdc_experiment` and `insdc_run` fields are currently part of `seq.json`, but there should be one of each of these IDs for each sample, like for fastq file names. These fields should be moved to `file.json` when it gets created (not currently in version_4).

**Comment by lauraclarke** [comment]
insdc experiment ids are equivalent to sequencing libraries so probably belong associated with proceedure and insdc run ids are equivalent to sequencing lanes and sets of fastq files so probably belong on assay_data but I don't know how that impacts the json structure

**Comment by daniwelter** [comment]
This fields are part of sequencing_process.json in v5 pre-release. Is this an acceptable solution, in which case this ticket can be closed, or do we need to review again?

**Comment by malloryfreeberg** [comment]
I think `insdc_run` will need to go in the `sequence_file.json` schema so the IDs can be associated with the correct set of fastq files.
