### ISSUE TITLE
Update release_process.md to indicate that the process is done by Reviewer.

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#627]
**Description**

 

Clearly state that Reviewer should run the pre-release process and merge the PR.

**Acceptance Criteria**

 
*e.g.*:
 
- [ ] Add a line "Reviewer should run the pre-release process and merge the PR. The Committer should not merge their own PR." to the `Steps of the pre-release process`

**Comment by malloryfreeberg** [comment]
@zperova is this duplicated by #730?

**Comment by zperova** [comment]
@malloryfreeberg indeed. closing it now.
