### ISSUE TITLE
Should we mint IDs for datasets in the HCA?

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#630]
We should capture opinions, pro's and con's of minting new project IDs. As this proposal will have a wide reaching impact it should be drafted as an RFC.

Acceptance:

- [x] add use cases
- [x] engage with relevant parties and make a decision to solve use cases.
- [x] record the decision and rationale in git hub

**Comment by diekhans** [comment]
How would this differ from NCBI BioProjects?

**Comment by hewgreen** [comment]
Added use cases to main contributor use case doc. See 10C and 10E-G in https://docs.google.com/document/d/1g2twsC7a977o6CUyFTZUKzt4cbU50KIWbLAUy8J_4h0/edit#

**Comment by hewgreen** [comment]
@diekhans BioProject IDs solve many of the use cases around citation which is post ingest. Maybe we only need a more systematic and scalable way to use short names for internal use. If we do that and take this away from the contributor input, the Browser could then use the BioProject ID which would give them a shorter think to list nicely in a web table.

**Comment by malloryfreeberg** [comment]
Quoting @hewgreen:

> I think we were deciding against minting IDs formally because BioProjects could do this for us. Internally we may want to start assigning readable identifiers rather than the random short names we currently use and think about removing the field from use in the browser.

**Comment by lauraclarke** [comment]
Just to comment, are current arriving strategy means all project will get BioStudies ids first. As they are being submitted to the ENA they will also get Bioprojects but this isn't the primary study id from our perspective
