### ISSUE TITLE
Update organ_part text/ontology fields to arrays.

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/metadata-schema#648]
**For which schema is a change/update being suggested?**

I would like to request a change to the specimen_from_organism.json schema.

**What should the change/update be?**

I would like to update the organ part text and ontology fields to accept arrays.

**What new field(s) need to be changed/added?**

No new fields would need to be added just a type change from object to array.

**Why is the change requested?**

As a data generator, I want to be able to list out all the organ parts that I have pooled together so that data consumers can try an separate the cells into there respective parts.

**Comment by malloryfreeberg** [comment]
This proposal would change

```
        "organ_part": {
            "description": "A term for a specific part of the organ that the biomaterial came from.",
            "type": "object",
            "$ref": "module/ontology/organ_part_ontology.json",
            "example": "umbilical cord blood",
            "user_friendly": "Organ part"
        },
```

to 

```
        "organ_part": {
            "description": "A term for a specific part of the organ that the biomaterial came from.",
            "type": "array",
            "items": {
                "$ref": "module/ontology/organ_part_ontology.json",
	        },
            "user_friendly": "Organ part"
        },
```

Given that the field is now an array, according to the Style Guide the field name should be made plural: `organ_part` becomes `organ_parts`. Are we all ok with this change?

**Comment by zperova** [comment]
Yes.

**Comment by malloryfreeberg** [comment]
@willrockout can you remind me if there is a specific use case we've encountered already with preview, cbeta, or GA data that needs this change? If so, what is the use case (without naming names)?

This change will break the Browser which currently indexes on this field, so I want to be sure whether it's required prior to GA or can wait until after.

**Comment by zperova** [comment]
@malloryfreeberg that's where the sample consisted of mixed cells from cortex and hippocampus

**Comment by malloryfreeberg** [comment]
Ah, ok. I'll move this to To do/Ready, but we should maybe wait until after the F2F meeting to push this through as there are a few other Browser-breaking changes that we are pushing through this/next week.
