### ISSUE TITLE
Patch updates to organoid schema to adhere to Style Guide.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#652]
**For which schema is a change/update being suggested?**

I would like to request an update the the `organoid.json` schema.

**What should the change/update be?**

- [x] add user-friendly name to `biomaterial_core`
- [x] remove example from `genus_species` (example will live in the ontology module)
- [x] remove example from `model_for_organ` (example will live in the ontology module)
- [x] remove example from `model_organ_part` (example will live in the ontology module)
- [x] remove example from `organoid_age_unit` (example will live in the ontology module)
- [x] remove example from `organoid_size_unit` (example will live in the ontology module)
- [x] add a second example to `organoid_morphology`

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

Would like to adhere to Style Guide.

**Comment by malloryfreeberg** [comment]
@pnejad can you supply a second example for the `organoid_morphology` term, preferably an example that highlights the range of values that could be used for this field? The current example is:

```
"organoid_morphology": {
    "description": "General description of the organoid morphology.",
    "type": "string",
    "example": "Epithelial monolayer with budding crypt-like domains.",
    "user_frinedly": "Organoid morphology"
},
```

**Comment by pnejad** [comment]
@malloryfreeberg  From my experience, the most common way to describe organoid morphology is by their bud and crypt structures.

Here are some other examples from organoid publications:

- Polarized monolayer
- Bud structure
- Spheroid 
- Crypt-villus structures
- Optic cup structure

I find this [Science](http://science.sciencemag.org/content/345/6194/1247125) review on organoids very helpful. It breaks down organogenesis of different organs.
