### ISSUE TITLE
analysis_process mis-uses submittable type as module

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#664]
The property `outputs` references a submittable type as if it were a module. This causes issues with the new JSON Schema validator as the injected fields are treated as a separate submittable type, causing failures.

**Comment by malloryfreeberg** [comment]
Pinged data-pipelines-team channel regarding how best to address this bug.

**Comment by malloryfreeberg** [comment]
Slack (#data-pipelines-team) summary of issue: 

[Mallory]

> I have a question about reporting metadata for the `analysis_process`. Currently, for describing the output analysis files, the `analysis_process` JSON imports the exact metadata that is used to describe each file (and therefore duplicates it because this metadata is already being submitted alongside each output analysis file). Is reproducing this metadata in the `analysis_process` JSON necessary? It is possible to submit something else in the `outputs` field such as the output UUID? I ask because our metadata model currently does not support submittable type entities (e.g. analysis_process, analysis_file, the entities that ingest validates) importing other type entities. The metadata team would like to clean up the `analysis_process` schema so it adheres to the model.

> In the metadata, we have _Type_ entities, which can be thought of as the JSON documents that get submitted to ingest to validate.

![entity_inheritance_1](https://user-images.githubusercontent.com/10993501/53011478-5deae980-3438-11e9-91bd-a7d22b28f0b0.png)

> We also have _Module_ entities, which are groups of related fields that can be optionally imported into the _Type_ entities.

![entity_inheritance_2](https://user-images.githubusercontent.com/10993501/53011486-62af9d80-3438-11e9-979a-541af07af721.png)

> An experiment is described as a graph of _Type_ entities that connect to each other

![entity_inheritance_3](https://user-images.githubusercontent.com/10993501/53011510-6fcc8c80-3438-11e9-83ad-ba7b3106671e.png)

> With ingest validating a single JSON document per _Type_.  Optionally, the _Type_ entities might have one or more _Module_ entities included (and _Type_ entities also all have a _Core_ entity included, which aren’t in these figures).

![entity_inheritance_4](https://user-images.githubusercontent.com/10993501/53011536-8246c600-3438-11e9-9c80-42f748007beb.png)

> The issue with what green box supplies as their *Analysis process* JSON/entity is that it includes the *Analysis file* _Type_ entity once for each analysis file produced (`outputs` field). 

![entity_inheritance_5](https://user-images.githubusercontent.com/10993501/53011546-8a066a80-3438-11e9-87eb-710cbfdf3e69.png)

> Which ends up duplicating the *Analysis file* metadata and also violates the metadata model (includes a _Type_ importing another _Type_ when only _Module_ and _Core_ entities are allowed to be imported). So, my question is: Does the *Analysis process* that the pipelines submit to ingest _really_ need to include the *Analysis file* metadata in it? Is it used for anything?

[@rexwangcc]

> Following up on this, 2 pointers first:
> - The code we generate the analysis files: https://github.com/HumanCellAtlas/pipeline-tools/blob/75e4ced2a215a17f2ad6e265726ef0ebab4e9664/pipeline_tools/create_analysis_metadata.py#L130
> - The code we add the generated analysis files metadata to the analysis process: https://github.com/HumanCellAtlas/pipeline-tools/blob/75e4ced2a215a17f2ad6e265726ef0ebab4e9664/pipeline_tools/create_analysis_metadata.py#L70

> I think the question that
> > Does the *Analysis process* that the pipelines submit to ingest _really_ need to include the *Analysis file* metadata in it
> to me is more like a question to Ingest that does ingest have any other ways to link the analysis files to process other than this(showed in your diagram entity_inheritance_5)? If yes, we might be able to simplify the outputs field in `analysis_process` to only have links/names. Not sure if my understanding is correct tho.

[Mallory]

> I just briefly discussed with @rolando-ebi and @aaclan-ebi , who confirmed that ingest *does not* read the `analysis_process.outputs` field to link the analysis files to the analysis process. So, I believe that the `analysis_process.outputs` field is not needed at all in the `analysis_process.json` schema. I think the solution is for pipelines team to still to generate the individual `analysis_file.json` JSONs, one for each file, but should not need to also copy that metadata to the `analysis_process.json` JSON. I will make a ticket in the schema repo to suggest this change (removing `outputs` field from `analysis_process.json` schema) and tag appropriate people in pipelines and ingest team so we can coordinate this.

@justincc wondering if there is anything that ingest needs to do to accommodate this change? Or I can go ahead and make the schema change in coordination with pipelines team (so their code generates valid JSON).

**Comment by justincc** [comment]
Unless @rdgoite, @rolando-ebi or @aaclan-ebi want to immediately chip in with anything I say go ahead.

**Comment by rexwangcc** [comment]
@malloryfreeberg @justincc I forgot to mention it before, but we are also copying the `analysis_file` metadata to the `analysis_process.inputs`, since Ingest doesn't consume the `output`, I assume they don't use the `input` either?

**Comment by malloryfreeberg** [comment]
> @malloryfreeberg @justincc I forgot to mention it before, but we are also copying the `analysis_file` metadata to the `analysis_process.inputs`, since Ingest doesn't consume the `output`, I assume they don't use the `input` either?

@rexwangcc good catch. I'll confirm with the ingest devs tomorrow, but I think you are correct that the `inputs` field is also not needed in the `analysis_process.json` :)

**Comment by malloryfreeberg** [comment]
@aaclan-ebi and @rdgoite have confirmed removing `inputs` won't affect ingest's ability to derives links. So, I'll go ahead and remove both fields :)
