### ISSUE TITLE
Patch updates to project schema to adhere to Style Guide.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#682]
**For which schema is a change/update being suggested?**

I would like to request an update to the type `project.json` schema.

**What should the change/update be?**

- [x] add user-friendly name to `project_core` 
- [x] add second example to `supplementary_links`
- [x] move part of description to guidelines for `insdc_project`: "Accession can be from the DDBJ, NCBI, or EMBL-EBI and must start with DRP, SRP, or ERP."
- [x] move part of description to guidelines for `geo_series`: "Accession must start with GSE."
- [x] add guidelines for `array_express_investigation`: "Accession must start with E-."
- [x] move part of description to guidelines for `insdc_study`: "Accession can be from the DDBJ, NCBI, or EMBL-EBI and must start with PRJE, PRJN, or PRJD."
- [x] change user-friendly term for `funders` to "Funding sources(s)" to remove redundancy ("Project")

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

We would like to adhere to Style Guide.

**Comment by pnejad** [comment]
@malloryfreeberg  Here is another example:

http://celltag.org/
