### ISSUE TITLE
Patch updates to biomaterial_collection protocol schemas to adhere to Style Guide.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#687]
**For which schema is a change/update being suggested?**

I would like to request an update the the `aggregate_generation_protocol.json`, `collection_protocol.json`, `differentiation_protocol.json`, `dissociation_protocol.json`, `enrichment_protocol.json` , and `ipsc_induction_protocol.json` schema.

**What should the change/update be?**

- [x] aggregate_generation_protocol.json
    - [x] add user-friendly term to `protocol_core`
    - [x] fix typo in description for `aggregate_formation_method`
    - [x] add second example to `aggregate_cell_uniformity`
- [x] collection_protocol.json
    - [x] add user-friendly term to `protocol_core`
    - [x] reword collection_method description
    - [x] remove example from `collection_method` (example will live in the ontology module)
    - [x] add type to protocol_reagents.items
- [x] differentiation_protocol.json
    - [x] add user-friendly term to `protocol_core`
    - [x] remove "Differentiation" from beginning of description for 'differentiation_method` and `small_molecules`
    - [x] separate examples with semi colons
    - [x] add type to reagents.items
    - [x] add second example for `target_pathway`
- [x] dissociation_protocol.json
    - [x] add user-friendly term to `protocol_core`
    - [x] remove example from `dissociation_method` (example will live in the ontology module)
    - [x] add type to protocol_reagents.items
- [x] enrichment_protocol.json
    - [x] add user-friendly term to `protocol_core`
    - [x] change description for `markers` to "A list of markers used to enrich for or against certain cells."
    - [x] add guidelines for `markers` to indicate that markers should be space-delimited and include + or - depending on if the markers were enriched for or against. 
    - [x] add example to markers
    - [x] remove example from `enrichment_method` (example will live in the ontology module)
- [x] ipsc_induction_protocol.json
    - [x] add user-friendly term to `protocol_core`
    - [x] add examples to `ipsc_induction_method`
    - [x] add type to protocol_reagents.items
    - [x] fix typo in schema title
    - [x] add second example to `pluripotency_test`

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

We would like to adhere to Style Guide.

**Comment by diekhans** [comment]
Random_integer isn't a meanigful name.  Could you come up with a name that is fu ctionally meaningful?

**Comment by malloryfreeberg** [comment]
@pnejad can you please provide a second example for the `aggregate_cell_uniformity` field? The current one is "Mostly homogenous embryoid bodies of variable cell numbers" but I think it would be helpful to give a second example to illustrate the breadth of what types of values are valid for this field.

**Comment by diekhans** [comment]
Also, of the function is for a user-defined identifier, why limit it to a integer ?

**Comment by malloryfreeberg** [comment]
> Random_integer isn't a meanigful name

Are you referring to the template issue for requesting schema updates? When I made the template, I didn't intend it to have any biological meaning. In fact, I thought if it did have biological meaning, it might be confusing in case someone accidentally left the dummy text in. I can update the template to have biological meaning, if we think that would be helpful.

**Comment by diekhans** [comment]
ignore my random_integer comment; that is what I get for commenting on the phone while riding in a car.  I seems to misformatted it confused me (which is easy)
