### ISSUE TITLE
Multiple protocol json file types could be a problem given mixed protocols are likely

### ISSUE THREAD

**Issue by dosumis** [HumanCellAtlas/metadata-schema#69]
v5_prototype has multiple subschemas for protocol types, paralleling the subschemas for processes  types. 

See: https://github.com/HumanCellAtlas/metadata-schema/tree/v5_prototype/json_schema/types/protocol

Subschemas for process types make a lot of sense - different data fields will be relevant to different processes.  I'm worried that the multiple protocol subschemas could cause problems given that protocol documents are unlikely to respect the boundaries of any process typing system.   A single protocol doc might, for example have information about dissociation, enrichment and aliquot(ing).  Given this, wouldn't it be better to have a single protocol.json with a type field to allow typing using multiple terms from EFO?

**Comment by dosumis** [comment]
example mixed protocol

https://www.protocols.io/view/facs-sorting-and-genome-amplification-of-single-ce-kbzcsp6

**Comment by malloryfreeberg** [comment]
This issue has been addressed post-v5 with the implementation of "processes" that wrap one or more "protocols" and link biomaterials/files. Therefore, a user could declare that they did both a dissociation and an enrichment protocol to generate a cell suspension from a specimen. Both protocols could point to the same or different protocol documents/dois, but both would be wrapped as one "process" connecting the input and output biomaterials.
