### ISSUE TITLE
Using oneOf for Characteristics fields

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#7]
I noticed the characteristics_* fields are only validated as strings

I wonder if it would be better to use the anyOf tag and allow any type field

https://spacetelescope.github.io/understanding-json-schema/reference/combining.html

{
  "anyOf": [
    { "type": "string" },
    { "type": "number" }
  ]
}

**Comment by lauraclarke** [comment]
Given we are no longer using these I am assuming this is no longer an issue, please close it or update it  @daniwelter

**Comment by malloryfreeberg** [comment]
We no longer allow characteristics_* fields in v5.0.0. Instead, we've opted to use a flexible entity model whereby users can ask for new fields to be added to specialized modules if they need them.
