### ISSUE TITLE
"Warm and cold ischemia" suggested field

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#72]
Suggested field by user filling out spreadsheet, indicate whether ischemia is warm or cold.

**Comment by JimKent** [comment]
There is a death.cold_perfused field that was meant to address this issue.

**Comment by JimKent** [comment]
There's also state_of_specimen.ischemic_time.

**Comment by malloryfreeberg** [comment]
As of v4, death is a field (schema $ref) in donor.json, so the death.cold_perfused would apply to the whole donor. The user that suggested this field wanted to indicate warm vs cold ischemia at the level of the specimen - they actually added their own "warm or cold ischemia" column to the state_of_specimen tab next to the ischemic_time column.

Maybe we keep death.cold_perfused and add another field indicated warm or cold ischemia specifically to the state_of_specimen schema which currently has ischemic_time as a field.

**Comment by JimKent** [comment]
Ok.  I think I'd favor splitting the ischemic_time field into cold and warm ischemic times then, since they may have some of both.   If the body is cold perfused hopefully we would see it being all cold_ischemic_time, or just very short warm_ischemic_time

**Comment by malloryfreeberg** [comment]
Fixed in ed660130d107b4709fe230c2fe74d8378657e6dc
