### ISSUE TITLE
"Time of lysis" suggested field

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#73]
User suggests adding a "time of lysis" field for RNA/DNA work if tissue not fixed.

**Comment by JimKent** [comment]
state_of_specimen.json has a lot of stuff related to this in it, specifically ischemic_time and postmortem_interval

**Comment by malloryfreeberg** [comment]
Spoke with the user again and determined that the information they wanted to record could fit within the `state_of_specimen.postmortem_interval` field. They specifically wanted to record a time interval between death and sample processing if the tissue was not preserved. The description for this field is : "Duration of time, in seconds, between when death is declared and when the tissue is preserved or processed." which does indeed account for not preserving the tissue. 

We could potentially make this description clearer.
