### ISSUE TITLE
Add/Create a UUID for library_prep_id

### ISSUE THREAD

**Issue by willrockout** [HumanCellAtlas/metadata-schema#732]
**For which schema is a change/update being suggested?**

I would like a change to either sequence_file.json or links.json 

**What should the change/update be?**

I would like to either change the library_prep_id into a unqiue identifier or to create a uuid from the user provided library_prep_id.

**What new field(s) need to be changed/added?**

Field name: library_prep_uuid
Field description: A unique ID for the library preparation.
Required: No

**Why is the change requested?**

Consumers of data would like to have a field they can grab that will group a single sequencing run. This has been expressed by the organge box so they can add a display tab of a natural grouping of files. Currently the library_prep_id is a user provieded field that is only unique inside a project.

**Comment by diekhans** [comment]
@malloryfreeberg it would be good if the style guide addressed the naming of _id fields.  So far, there are no fields named _uuid, so I think it is problematic to add a field named library_prep_uuid.  Also, it most cases, the type and scope of the id field is not defined.

For instance, library_prep_id  has the description "A unique ID for the library preparation.", which I would assume is globally unique, but isn't.  I will start a ticket on this.

**Comment by malloryfreeberg** [comment]
@willrockout @diekhans I don't think we need any UUIDs in the metadata. Ingest generates and associates UUIDs with every entity that comes through the DCP, so this should be sufficient to distinguish between library preps for consumers. We don't actually need to display the UUID in the UI - we can use the user-supplied ID - but when data/metadata are downloaded, the globally unique UUIDs will be available.

**Comment by willrockout** [comment]
After a chat with Matt, I believe as Mallory said we don't need a new id field we can use a combination of the provided user-generated library_prep_id and the process uuids between a biomaterial and file/s to get the information needed for run and library groupings. I'm closing this issues as we've figured it is not needed.
