### ISSUE TITLE
Rename "organoid_type" field.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#736]
**For which schema is a change/update being suggested?**

I would like to request an update to the `organoid.json` schema.

**What should the change/update be?**

I would like to change the field name `organoid_type`. Having "organoid" at the start of the field name is redundant with the schema name and does not improve clarity of the field name. However, a field named "type" is not a good idea. "Type" is an overloaded term. Not sure what is a good alternative for the field name. 

`origin` has been suggested.

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

To adhere to Style Guide regarding fully qualified field names.

**Comment by willrockout** [comment]
@malloryfreeberg Would origin_type or source_type work? Or are we trying to avoid the word type altogether? @pnejad can you weigh in as well.

**Comment by willrockout** [comment]
@pnejad What is the reasoning behind this field? After discussing with @malloryfreeberg seems the information could be inferred from the provided biomaterials. 

ex.
* primary --> No cell line biomaterial provided
* immortalized, stem cell-derived, synthetic --> cell line provided and cell_line_type field gives this info.

**Comment by pnejad** [comment]
@willrockout  That is correct. It was added for search reasons and can be taken out now.

**Comment by malloryfreeberg** [comment]
Cool! So sounds like this field is no longer needed. @willrockout can you update the ticket to reflect Paris' comments and then move it to the to do/ready pipeline? Thanks!
