### ISSUE TITLE
Define feature list for linter to check

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#740]
**Description**

 

As a developer or user of the metadata schemas, I would like to know what standards the schemas are held to and checked for so that I can be sure that the schemas are of a high standard/quality.

Draft of feature list [here](https://docs.google.com/document/d/1pg-YCBE9YGAEVVZQN6p3nKMghdjiUSd8i4mlnRheoUs/edit#).

**Acceptance Criteria**

 
- [x] A draft document that lists and describes the schema features that are checked by the linter.
- [x] Review of document by metadata team.
- [x] ~A final document available in the repo.~

**Comment by malloryfreeberg** [comment]
I have put together a first draft of features that would be great if the linter could check. It is based on the [Schema Style Guide](https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/schema_style_guide.md) is available [here](https://docs.google.com/document/d/1pg-YCBE9YGAEVVZQN6p3nKMghdjiUSd8i4mlnRheoUs/edit#) (also linked in the ticket).

Some features are harder to implement to others, but we can iterate over and grow this list over time. 

Tagging @daniwelter @zperova @hewgreen @willrockout @cjvillar @pnejad @diekhans for reviews/additions/suggestions/etc.

**Comment by diekhans** [comment]
this looks like a great start!!

**Comment by malloryfreeberg** [comment]
Keeping this doc as a Google doc so we can add items and cross items off as they finish. Closing this ticket!
