### ISSUE TITLE
Adding "read length" field in sequencing schema

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#75]
User suggests adding field to capture intended read length of files. This might be helpful for doing sanity check on the raw data files to ensure that the reads we receive match what is expected from the sequencing run.

**Comment by daniwelter** [comment]
This has not yet been done - do we want to address or close the ticket?

**Comment by malloryfreeberg** [comment]
Pinged a few secondary analysis people to get their opinion. It's possible that a majority of users won't know or might ignore a read_length field, and it's not worth it to have this field in the schema. Curious what analysis folks think about it.

**Comment by jishuxu** [comment]
In the current pipeline, read length is not necessary but it will be useful for downstream data analysis. Alternatively, we can parse out the read length from alignment. I would say if it is not too much effort, we'd better just keep read length in schema.

**Comment by malloryfreeberg** [comment]
It's definitely no effort to add a read_length field :) Thanks for the feedback!

**Comment by lauraclarke** [comment]
One thing to consider (once everything is out and up and running) is the pipelines could provide this information to update any submission which doesn't already contain it or the fastq validation could fill it in @rdgoite @danielvaughan what do you think about fastq validation outputting it as a feature request for the backlog

**Comment by TimothyTickle** [comment]
I think the read_length is really important. Our current pipeline does not
leverage it but I would not be surprised if they did in the future. This
also could be important in looking at batch effects or if we need to make
pipelines around de novo assembly for instance.

I am a little fuzzy here but I believe the wet assay (kits) define the read
length and so, even if the person putting in the metadata does not know the
read length, they should/could know the kits used in assay development
which could auto-populate a good guess default. Interrogating that with a
pipeline could be useful for the running of the pipeline but may be
incorrect if, for instance, they demuxed the file wrong.
