### ISSUE TITLE
Create script to dump out all type URLs to file at staging -> prod release

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#765]
**Description**

As a metadata editor, I want to be able to run a script when releasing metadata schemas from staging to production that dumps the URLs for all type schemas into a file that can then be absorbed into the release notes. At the moment, the release notes (https://github.com/HumanCellAtlas/dcp/blob/prod/components.yml#L13) only contain a link to the `/latestSchemas` endpoint. A clear list of the latest type schemas would be more appropriate here. 

**Acceptance Criteria**

- [ ] A script that performs the task described above
- [ ] An output file that can be consumed by the release notes generator for the whole DCP
- [ ] Updates to the release process documentation to tell the release manager how to use this script

**Comment by zperova** [comment]
@ESapenaVentura @mshadbolt we have discussed this issue
