### ISSUE TITLE
Nuclear versus cellular RNA

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#77]
Currently in the seq schema there is a `molecule` tab that asks for what molecule is sequenced and the examples given are "polyA RNA", "total RNA", "genomic DNA". But where do we capture whether the RNA is cellular or nuclear? Should this information be included in the `molecule` field? Or made into a new field?

**Comment by dosumis** [comment]
Single nucleus RNAseq is an important component of HCA plans (see [white paper](https://www.humancellatlas.org/news/13) ) .  Important that this is very easy to distinguish from single cell RNAseq in metadata and not buried in some subfield.

**Comment by malloryfreeberg** [comment]
So this sounds like it should be two separate fields:
1. `molecule` (total RNA, polyA RNA, etc.)
1. `cellular_fraction` (nuclear, cellular, non-nuclear, etc.)

**Comment by dosumis** [comment]
Example paper: [Lake, B. B. et al. Neuronal subtypes and diversity revealed by single-nucleus RNA sequencing of the human brain. Science 352, 1586-1590, doi:10.1126/science.aaf1204 (2016).
3](http://science.sciencemag.org/content/352/6293/1586)
![image](https://user-images.githubusercontent.com/112839/33429740-f5eb8c58-d5c5-11e7-9d72-5e45625a8162.png)

**Comment by JimKent** [comment]
A cellular fraction field suits me.  It would definitely be better than overloading molecule.   In bulk RNA we get nuclear, membrane-bound, and ribosome-attached fractions, as well as whole cell,  and these may eventually be possible with single cells as well.

**Comment by daniwelter** [comment]
Is this use case addressed by the new nucleic_acid_source enum field in dissocation_process.json?

**Comment by malloryfreeberg** [comment]
[input_nucleic_acid_molecule](https://github.com/HumanCellAtlas/metadata-schema/blob/03a1be73b7c110f63768dd5480c9f6b087e7bcf7/json_schema/type/process/sequencing/library_preparation_process.json#L47) now describes the precise type of molecule that is sequenced and [nucleic_acid_source](https://github.com/HumanCellAtlas/metadata-schema/blob/03a1be73b7c110f63768dd5480c9f6b087e7bcf7/json_schema/type/process/biomaterial_collection/dissociation_process.json#L55) describes whether single cells, single nuclei, bulk cells, bulk nuclei, etc. were the source of the molecule. Currently the former is an ontology and the later is an enum. Closing this issue as it is solved.
