### ISSUE TITLE
Review all regex patterns for accessions

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#78]
For v5, double check all the regex for accessions. e.g. "SAMEA4437021" is given as example under ingest-broker repo as a biosample ID, but this is failing the regex for biosample ID given in the schema (`^SAM[N|E|D][0-9]+$`). The accession is valid, so the regex needs to be amended.

**Comment by tburdett** [comment]
This is a better biosamples accession regex: `^SAM(D|N|E([AG]?))[0-9]+$`

This is still not perfect - for example, NCBI sample accessions are zero padded, and this doesn't allow for that - but is correct and reasonably precise

**Comment by daniwelter** [comment]
This has been done
