### ISSUE TITLE
Comma instead of semicolon separating examples

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#784]
**Give the bug a title**

Comma instead of semicolon separating examples

**To reproduce**

 

- [ ] cell_line.json: Property `karyotype` might have multiple examples that aren't separated by a semicolon (sex chromosome complement of XY, del(2) (q11))
- [ ] cell_line.json: Property `supplier` might have multiple examples that aren't separated by a semicolon (HipSci, ATCC)
- [ ] supplementary_file.json: Property `file_description` might have multiple examples that aren't separated by a semicolon (Protocol for FACS enrichment, Image of spleen sample collection location)
- [ ] reference_file.json: Property `ncbi_taxon_id` might have multiple examples that aren't separated by a semicolon (9606, 10090)
- [ ] sequencing_protocol.json: Property `local_machine_name` might have multiple examples that aren't separated by a semicolon (Machine1, HSMA-20)
- [ ] imaging_protocol.json: `microscope_setup_description` example has non-ascii character
- [ ] channel.json: Property `channel_id` might have multiple examples that aren't separated by a semicolon (1, A)
- [ ] target.json: Property `assay_type` might have multiple examples that aren't separated by a semicolon (MERFISH, smFISH, immunofluorescence, fluorescent cell stain)
- [ ] target.json: Property `molecule_name` might have multiple examples that aren't separated by a semicolon (ACTA1, cFos)
- [ ] target.json: Property `channel_id` might have multiple examples that aren't separated by a semicolon (1, A)
- [ ] target.json: Property `molecule_id` might have multiple examples that aren't separated by a semicolon (CHEBI:85345, ensembl_9606)
- [ ] imaged_specimen.json: Property `overview_images` might have multiple examples that aren't separated by a semicolon (my_image_file.jpg, overview_image.tiff)

**Schema versions**

 
Too many to list

**Observed behavior**

Examples separated by comma.

**Expected behavior**

 
Examples separated by semicolon.

**Screenshots or Messages**

Caught by linter :D

**Comment by daniwelter** [comment]
@malloryfreeberg re non-ASCII character example - that same example has several semi-colons, not just as a separator. Do we anticipate tokenising examples on semi-colons because if so, this would break.

**Comment by malloryfreeberg** [comment]
I'll let @zperova confirm on this field, but I think we should be strict about using semicolon ONLY for separating examples. In which case, we'll need to re-work the examples for this field.

**Comment by malloryfreeberg** [comment]
But getting the non-ascii char in there is key now, as it breaks the linter :)
