### ISSUE TITLE
Coping with multiple donors in one scRNAseq

### ISSUE THREAD

**Issue by dosumis** [HumanCellAtlas/metadata-schema#79]
From the HCA white paper: "When possible, cells from multiple individuals will be mixed in a single assay, and then distinguished based on the genetic differences, reducing batch effects and costs, and streamlining the process."

We need to work out how best to represent cases like this in the metadata schema.

https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/sample_bundle.json allows multiple instance of the relationship sample derived_from sample to be recorded. A list of (derivation) protocols (presumably extending to processes in v5) may be associated with each relationship.  

This *could* be extended to cope with mixed samples by making 'derived_from' into an array.  This has the problem that all processes/protocols recorded must apply to all samples.  The safest way to use this pattern is probably to have sample pooling be a derivation step, and, by convention, only record multiple samples in the derived_from field for cases of pooling.

**Comment by lauraclarke** [comment]
@malloryfreeberg @willrockout @pnejad @cjvillar Is this a reality now? otherwise we can move it to the icebox

**Comment by malloryfreeberg** [comment]
Yes, with the new metadata entity model introduced to schemas (all schemas v5+.*.*), the functionality David describes can be obtained. This issue can be closed.
