### ISSUE TITLE
Spreadsheet directory

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#8]
@claymfischer I was wondering how you created the spreadsheet directory. 

It feels like it will create a maintenance burden

Would we be better adding a python or another language script which can convert the schemas into tsvs without actually committing them and needing to keep them inline

**Comment by claymfischer** [comment]
@lauraclarke The Data Store folks requested I have TSVs for the first freeze. Fortunately I have a python script to make TSVs from Google Sheets for me, only takes a second. 

Jeremy Freeman and I talked a bit about how to handle the TSVs moving forward. One thought we had was to use the python script to monitor the metadata spreadsheet (whichever it may be) and look for diffs, then save and timestamp the diffs for possible versioning. We could then choose one or more of the versions as a named version to commit to git.

**Comment by lauraclarke** [comment]
It would be good to talk through that process. I worry if we keep about more than one text representation of the schema that it will get challenging to keep them inline.

I would have thought that better viewing tools or editing tools are less risky (though of course will take slightly longer to get up and  running)

**Comment by lauraclarke** [comment]
I certainly don't want any automated changes/new versions due to diffs between different text versions, that would negate the purpose of the review process.

**Comment by claymfischer** [comment]
Definitely, this is a big topic we will discuss in person. Usings diffs was just a thought in how to track changes over time, and then it's likely a metadata group will decide on specific versions. 

I put these here because the Data Store requested them with the freeze.

**Comment by lauraclarke** [comment]
Certainly putting them in for the data store is fine now. I am mostly thinking about a longer term view  

Discussing this in person will be great as I am struggling to see how this tallies with the life cycle proposal where each PR change is reviewed and accepted(or not) rather than an accumulation over time.

**Comment by lauraclarke** [comment]
I am closing this issue now and I am sure we can come up with a plan once we are all in the same place.
