### ISSUE TITLE
Design principles document requires permission to view

### ISSUE THREAD

**Issue by jonathancasper** [HumanCellAtlas/metadata-schema#80]
The root level README.md links to a design principles Google Doc.  I can't view that document - it just says that I need permission.  Either the permissions need to be fixed so that it's publicly viewable, or the design principles should just be included in the repository.

**Comment by malloryfreeberg** [comment]
@samanthachui Do you know who would have permission to change the permissions on the Google Drive docs? I think permission can be set for the highest "HCA" directory to "anyone with link can view" and then that should propagate down to all documents. Thanks.

**Comment by lauraclarke** [comment]
This should be fixed now, please close the issue if it is

**Comment by malloryfreeberg** [comment]
I have checked viewing the design principles doc on a different account, and I am able to view it. So, hopefully the permissions are fixed globally.

**Comment by jonathancasper** [comment]
Thank you, sorry about that - I've been out sick.  It works for me now as well!
