### ISSUE TITLE
Height in cm instead of m

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#81]
User suggests recording height in centimeters instead of meters as this is how it typically comes from the clinic.

**Comment by lauraclarke** [comment]
Is there a way to make this a user interface issue or allow either unit?

**Comment by claymfischer** [comment]
I'm not sure adding the complication of selecting a unit is worth the effort. It's a simple division or multiplication.

**Comment by lauraclarke** [comment]
Whichever unit we pick, some people will put in the wrong one as different people will get different values

If the schema only allows one unit then the validation service will need to be made aware and able to suggest someone has given the wrong value (say for human numbers less than 30 if the unit is cm or numbers greater than 3 if the unit is metres) as that doesn't sound like a check which can be easily encoded in the JSON schema doc I wonder if a UI trick which assesses the number and asks if the unit is correct is a better solution than forcing one unit or the other

**Comment by JimKent** [comment]
In the clinics in the metrically challenged US,  it tends to come in feet and inches.  I believe the BMI calculations use meters (and kilograms).  In the UK when people are talking about height what units do they typically use?  Weight I know is stone, but I'm not suggesting we convert to that.

**Comment by lauraclarke** [comment]
I can only comment as a patient and when I am at clinic at the hospital I am given my weight in kilograms and my height in metres 

I suspect different people will get different things depending on the country, it might be best to ask people to provide a number and assert a unit and do a check on that basis so large numbers that aren't cms would be a problem small floating point numbers that weren't metres. I don't know if that is practical from an implementation perspective or how we would expect feet and inches to be input in this scenario

**Comment by JimKent** [comment]
Thanks for your perspective Laura.  Given this I'd favor sticking with meters.  It'll be a conversion for some, but I'd favor this rather than having a separate unit field, that then the people writing scripts against the metadata would have to deal with.

**Comment by malloryfreeberg** [comment]
I'm certainly in favor of not having separate value+units fields in this case. But I have two additional arguments in favor of having cm be the unit on this field. One reason is for cases where a human donor is an infant/child, for whom I think (correct me if I'm wrong) height is typically given in cm. The other reason is for cases where the donor is a mouse, and if the height is relevant, will likely be recorded in cm. Personally, I favor working with whole number values over decimals, but I can't give a rational reason for this.

With regard to validating values in the schema, as of v4.2.0, a sanity check on the height number entered cannot be directly encoded in the schema itself as we changed the field type from number to string+regex to allow ingest of ranges of values, e.g. 1.75-1.8 or 175-180 should be allowable as a value. The validation would have to happen outside of the schema, and I agree it would be great if this could be incorporated into the UI.

**Comment by malloryfreeberg** [comment]
We have made two fields - height and height_unit - to accommodate users having this info in different unites. Fixed with #126

**Comment by daniwelter** [comment]
height_unit is now also an ontology field so values are validated against acceptable values from the unit ontology
