### ISSUE TITLE
Add codeword field to targets.json

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#814]
**For which schema is a change/update being suggested?**

We should add a field to targets.json to include the codeword. This is a list of channels indexed by hybridisation round that corresponds to the signal for a particular target/probe.

**What new field(s) need to be changed/added?**
Should be **Not required**

Add 'codeword'
Array (separator is ||)
Example A||T||C||G||C||G

or

Add 'codeword'
String (non-standard field separator)
Example ATCGCG

The latter option is ok for nucleotide specified channels but would be a problem if channel names were more convoluted. This is as a contributor has previously provided this field.

**Why is the change requested?**

This information was provided by a submitter and is very concise for image based seq experiments where channels are often A,T,G and C. Here an example of a codeword is ATCGCG meaning that detection of the probe relies on signal from A in hybridisation round 1, T in hybridisation round 2 etc...

This reflects the spacetx codebook and allows decoding from the metadata and is easy for users to provide as their probe sets are often designed in a tabular format anyway.

**Comment by lauraclarke** [comment]
codeword feels like a very generic term. Is there a more specific term which wouldn't be so opaque to outsiders from the field?

**Comment by joshmoore** [comment]
@hewgreen : do you have (pseudo)code for translating between spacetx and HCA json?

**Comment by dosumis** [comment]
I thought the aim was to leave this to the SpaceTx codebook as it is not of any interest outside of analysis.

**Comment by zperova** [comment]
@lauraclarke I am afraid there is no specific term for this. The data contributors called this column `code` - I am assuming to differentiate from `barcode`. We decided to change it to `codeword` to differentiate from `codebook` (used in MERFISH) that we are not collecting in the HCA metadata. 
This is a contributor provided field. I imagine this field (and some others) will need to be reconsidered once we get several datasets in.

**Comment by hewgreen** [comment]
@joshmoore not right now but I was loosely thinking this could enable that sort of use case.

@dosumis We did say that. We weren't explicitly modelling hybridisation round (like we do for channel and probe/target) and codeword essentially does that. But out of the two datasets we have metadata for so far (both in-situ sequencing FISH) contributors have added this information into the sheet anyway. In addition, for in situ sequencing we must consider probe sequence and the detection sequence separately. If the implementation here works well we will also add clarity about what belongs in each field as both contributors used the current fields differently.

**Comment by lauraclarke** [comment]
Can I just confirm the full definition for this term? I am struggling with the lack of specificity in the name and following a poor word choice made by another group without some consideration feels like a bad choice

**Comment by ambrosejcarr** [comment]
I suspect @joshmoore was asking because if you were able to provide pseudocode to convert from the spaceTx codebook, that would help us understand what you're trying to represent here and provide feedback. I'm a bit lost.

**Comment by malloryfreeberg** [comment]
Moving this issue to the Icebox. Currently unclear how to resolve this. Requires more research and is not necessary to have this done now.

**Comment by ESapenaVentura** [comment]
targets.json was deprecated
