### ISSUE TITLE
Generate data consumer vignette for metadata fields of common interest

### ISSUE THREAD

**Issue by daniwelter** [HumanCellAtlas/metadata-schema#826]
**Description**

During the last round of user feedback, it became clear that many users either can't find the HCA metadata at all or don't understand how to interact with it once they have downloaded it. We will generate a data consumer vignette in the form of a jupyter notebook to guide data consumers through a standard workflow of downloading some metadata and extracting relevant metadata fields from the JSON document. We will also produce a list of metadata fields that may be considered to be of most interest to the average data consumer interacting with HCA data.

**Stakeholders**

- Metadata team: will take point on drafting the overall jupyter notebook
- Datastore team: will provide advice on the best/most efficient way to download metadata from the datastore
- Matrix service team: will share their experience on identifying relevant metadata to help generate the list of metadata fields of primary interest

**Acceptance Criteria**

- [ ] A list of the main metadata fields most likely to be of interest to a data consumer downloading HCA metadata
- [ ] One or more jupyter notebooks with a step-by-step example of how to traverse downloaded HCA metadata json to extract the desired metadata fields

**Comment by daniwelter** [comment]
RFC now open for comments 
https://docs.google.com/document/d/1-HSIwZKOabjk9Ziee8WD_67tbdyFzIVfDQESzqVqm3k/edit#heading=h.xe1eqwz3nqmr

**Comment by daniwelter** [comment]
Proposed fields to include in the vignette:
- relevant entity IDs
- species
- sex
- development stage
- organ/organ part/ model organ
- diseases
- library construction method
- sequencing method
- cell count

**Comment by daniwelter** [comment]
A first pass of this is done: https://github.com/HumanCellAtlas/data-consumer-vignettes/tree/metadata_vignette/tasks/Explore%20metadata

The fields are currently entirely hard coded so the vignette will break if there are field changes.

**Comment by zperova** [comment]
@daniwelter the link for the notebook doesn't work

**Comment by daniwelter** [comment]
Removing myself from this ticket as there is a new vignettes & tutorials plan that came out of the last DCP meeting.
