### ISSUE TITLE
Add /health endpoint for https://schema.humancellatlas.org

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#828]
To conform with DCP operational policies, all components must have a `/health` endpoint that can be checked to see if the component is up.  https://schema.humancellatlas.org needs this.

**Comment by malloryfreeberg** [comment]
@lauraclarke @morrisonnorman @diekhans who should be responsible for this?

**Comment by lauraclarke** [comment]
Who is responsible for the web service in the first place? who set it up and runs it?

**Comment by danielvaughan** [comment]
That should be easy. You could just upload a text file named health with the content OK I would have thought.

**Comment by malloryfreeberg** [comment]
@danielvaughan sometime can you help me to set this up?

**Comment by danielvaughan** [comment]
@aaclan-ebi has given it a go. Need to wait for the cache to expire

**Comment by justincc** [comment]
Okay, it looks like this works but is not the end solution since it would disappear if the bucket needs to be rebuilt. A ticket for that work will be linked from ingest-central shortly.

Second, @sampierson where are the requirements for health endpoints documented?

**Comment by justincc** [comment]
This appears to be an ingest dev responsibility

**Comment by justincc** [comment]
[The documentation that exists for this requirement](https://humancellatlas.slack.com/archives/C6SGU0R3J/p1550674524000900)

**Comment by justincc** [comment]
[Ingest ticket #309](https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/ingest-central/309)

**Comment by justincc** [comment]
We're taking responsibility for this @malloryfreeberg

**Comment by lauraclarke** [comment]
@justincc can this ticket now be closed due to the needed work now being reflected in ingest-central?

**Comment by sampierson** [comment]
Actually, please leave this open until the work is completed by the Ingest team.  The tools I have built for tracking GA requirements aren't smart enough to be able to say "yes this is a metadata project requirement but is being implemented by and tracked by the ingest team".

**Comment by sampierson** [comment]
Nevermind.  I see this is implemented enough for GA.
