### ISSUE TITLE
Rename "donor" to more generic (e.g. "organism")

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#83]
Based on user feedback, some projects use non-human subjects (e.g. mouse, dog), in which case the concept of a "donor" does not apply. Some users were very hesitant to put non-human subjects in the "donor" tab.

Suggest renaming "donor" to something more generic. For example, "organism". Other suggestions?

**Comment by lauraclarke** [comment]
Is there a way to have differential requirements across different species?

**Comment by malloryfreeberg** [comment]
Re-opening this issue as there is now more discussion going on about the use of donor versus organism. Below are quotes from pilot users taken during user experience evaluation sessions and notes from the Boston metadata meeting specifically centered on metadata terms which led to the decision to replace donor with organism as the entity name.

1. Quote from pilot user who has both human and mouse data: "Donor is for the human samples, right? ... [A mouse is] an organism, but not a donor. At least not a voluntary donor."

2. Scribe notes from Boston metadata meeting: "The HCA considered Donor to be the whole organism. Most data contributors put their "specimen" under "donor" and not "specimen from organism". Why? This is because the term "donor" was confusing."

3. Scribe notes from Boston metadata meeting: Data generators thought "Immune cells, brain tissue" were "donor" type samples. They should be "specimen from organism" types.

Another suggested term instead of donor was "individual", but "organism" was chosen instead because even the term "individual" has some suggestion of person-hood.

**Comment by malloryfreeberg** [comment]
Also copying a relevant, recent Slack conversation here between myself and @pnejad:

"Could you explain the reasoning behind not using the term donor?"

"So, given that we are expecting to receive non-human samples, we got some feedback from users that the term "donor" implies a human giving consent, which might not always be the case. So, we switched to the more neutral and general "organism" which removes a sense of the individual giving consent (which non-humans can not give) and also makes clear that this schema is for the "whole individual"."

"In regards to donor and consent, wouldn't the non-consent issue also apply to samples from embryos, fetuses and children? Other species can't consent to their samples being donated to research, but likewise some human samples also don’t have consent from donor."

"Yup! There are many instances where the idea of "consent" doesn’t apply, which is why we decided to drop donor in favor of organism."

**Comment by malloryfreeberg** [comment]
Another point to consider brought up by @claymfischer:

"donor makes more sense than organism for the people we have been talking with. If donor is really unacceptable, we would like to consider a source id field. We understand that donor doesn't feel right to some due to not giving consent, but human donors don't always have the agency to consent either (embryonic stem cells, children under 18, cell lines such as HeLa). We do feel that donors have contributed to science and we should respect that by using the term donor."

**Comment by malloryfreeberg** [comment]
A point brought up by Gabby:

"I appreciate Donor might be perfect for the occasions when the data is ideal scenario - coming from Human donors. Do we think this is the primary (95%) type of data coming to the Atlas?

Considering we have spoken at least at this point to teams who are going to have data from mixed origin, or from other organisms, we need to have the option for them to recognise something else as a name, like "organism". Donor wouldn’t be suitable for their experiments, and neither would fields under Donor that have something saying "mouse strain".

As pointed out in the Metadata evaluation report - there needs to be a way to cater for different types of users to recognise their type of organism, Human or Mouse, e.g.

In my opinion, as a word being shown to users, it could say Donor/Organism or Donor, if somebody has selected Human; and Organism, maybe after a selection they have made for other species?"

**Comment by JimKent** [comment]
A problem with organism is that it is synonymous with species in many
usages.  When you say "what organism" you are not distinguishing between
individuals, but between species most often.

**Comment by lauraclarke** [comment]
While I take your point Jim that organism is frequently used as a synonym to species I think given the context in which is being presented here I think the risk of that sort of misinterpretation is quite low.

Thinking  about alternatives

We could add whole_ in front of organism, making it clearer we mean organism in the singular rather than the plural

We could change to something like individual rather than organism or donor, this is a good singular non specific noun but I do still worry it isn't really a term that gets used for non human organisms

Anything else?

**Comment by tburdett** [comment]
I like @lauraclarke's earlier suggestion about the possibility of having different requirements across different species.  So 'donor' for human data, 'individual' or something else for other species.  Like @JimKent I don't really like 'organism' as almost every other database I know uses this synonymously with species/taxonomy... I'd expect this to confuse people more than donor!

**Comment by gabsie** [comment]
On the UI specifically, we were thinking to ask the question about species, and then based on that, have the spreadsheet say Donor, if "Homo Sapiens only" has been selected.

**Comment by lauraclarke** [comment]
I agree that having the UI tailor the language depending on the user is the  best solution

We still need a general name for the type through which is agnostic to the specific context

We could decide that as in the majority of cases donor is correct so we use donor though I will note it wasn't just scientists with non human samples who seemed confused, the name donor was also attributed to organ donations as well as humans by the people working in a clinical setting too

**Comment by malloryfreeberg** [comment]
**Proposal**: Rename `organism.json` to `donor_organism.json` with the understanding that "donor_organism" can be translated into alternative phrases like "donor" or "mouse" or w/e in the UI, in spreadsheets, and other user-friendly interfaces. It seems there will never be a 100% consensus, so my hope is that this compromise is at least tolerable by a majority of invested parties.
