### ISSUE TITLE
Add "administrator" value to project_role enum.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#845]
**For which schema is a change/update being suggested?**

I would like to request an update to the `contact.json` schema.

**What should the change/update be?**

I would like to add a new value to the enum for the `project_role` field. A data contributor wants to add a primary contact (execofficeuk@humancellatlas.org) that serves an administrative role rather than a single person who contributed to the project. Possible values for this could be:
- administrator
- ~executive~
- ~any other ideas?~

Seems the consensus is "administrator".

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

Data contributors need to be able to enter contact information for an administrative or executive office that handles correspondence for a project.

**Comment by malloryfreeberg** [comment]
@hewgreen @zperova @daniwelter @willrockout @cjvillar @pnejad @morrisonnorman @diekhans @claymfischer any thoughts?

**Comment by daniwelter** [comment]
Looking at the other available options in the enum at the moment, a more administrative style role may not be a bad idea. I prefer `administrator` to `executive`. Alternatively, there's already an `other` option on the list that could be used for non-scientific roles.

**Comment by claymfischer** [comment]
It seems a reasonable role that we will encounter with frequency. I agree with @daniwelter about a preference for `administrator`.

**Comment by malloryfreeberg** [comment]
Great! Seems that "administrator" is the best option, so we'll go ahead with that.
