### ISSUE TITLE
Map attributes across single cell RNA seq archives.

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#848]
Produce a spreadsheet with all by all attribute comparison between HCA and ArrayExpress metadata.

**Description**

The metadata team needs to understand how attributes in our schema align with other resources. Initially we will map to ArrayExpress using work already done by Robert Petryszak.

If possible we could extend this analysis to include mapping to the following:

- SCEA/ArrayExpress
- NeMo
- GEO/SRA
- CIRM

**Acceptance Criteria**

- [x] Make a table of attributes and map usage across schemas.
- [x] Add frequency of use information covered in ticket https://github.com/HumanCellAtlas/metadata-schema/issues/847

Optional tasks for future work:
- [ ] Categories attributes based on MINSEQE definitions.
- [ ] Assessment of how long it will take to include the other archives/projects.

**Comment by hewgreen** [comment]
https://docs.google.com/spreadsheets/d/1vytO_c0R9-NZ2Qge2UVq90955HKm81vSd4tcL0Z2BNg/edit?ts=5c80ee4d#gid=0

**Comment by hewgreen** [comment]
Mapping of attributes and attribute counting is done. Further support will be required to complete the paper.

**Comment by lauraclarke** [comment]
What further support is needed?

**Comment by hewgreen** [comment]
1. Add some implementation detail about HCA metadata to the paper (Matt)
2. Add [interoperability context](https://wellcome.figshare.com/articles/Review_Interoperability_standards/4055496) of this work to intro or conclusion (Norman)
3. CIRM may want to align their metadata (undecided)
4. We may want to do more quantitative analysis and a like for like comparison of metadata usage (undecided)
5. We may want to align metadata to other MI standards to reduce overlap (undecided)
