### ISSUE TITLE
Add some dev facing docs for using ontologies

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#856]
Add documentation to address the following use cases:

1. As a developer against the HCA metadata, I would like to be able to convert an ontology curie to a url so I can provide a link to my users to the ontology entry.
1. As a contributor of HCA metadata, I would like to know what the acceptable terms are for a specific curie so that I can select the best term.
1. As a consumer of the HCA metadata, I would like to know why there is no prod deployment of the HCAO.
1. How you might automate the `rdfs:subClassOf` -> `descendants` mapping?

Discussion in slack gave the following explanation from Tony:

e.g. for "HANCESTRO:0004"

use API link `http://ontology.staging.data.humancellatlas.org/api/ontologies/hancestro/terms?short_form=HANCESTRO_0004`

The set of allowed values is informed by this attribute:
"relations": ["rdfs:subClassOf"]

Given that, you can follow the `_links.descendants.href` URL from the above API endpoint to get the allowed values, i.e.

http://ontology.staging.data.humancellatlas.org/api/ontologies/hancestro/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHANCESTRO_0004/descendants

**Comment by zperova** [comment]
could be related to the ols api library @ESapenaVentura
