### ISSUE TITLE
Alerts are sent to dev/ops team for a component when it is down/unhealthy

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#859]
As a developer/operator of the DCP
when a component is down or unhealthy
I should receive an alert

Our current alert mechanism is to send messages to an appropriate Slack channel.
I believe @mweiden's status dashboard does this.  You just need to tell it where to look.

**Comment by mweiden** [comment]
Yes, this is currently in place:

* Health check - https://github.com/HumanCellAtlas/dcp-monitoring/blob/master/terraform/modules/singleton-health-checks/metadata-schema.tf
* Alert - https://github.com/HumanCellAtlas/dcp-monitoring/blob/0cf3f76c8baa7d1fb0c9e94ac926ec5ad1f870be/terraform/modules/singleton-alerts/metadata-schema.tf

I will close this ticket now. If you would like changes to the alert open up a ticket in `dcp-monitoring`, ping me, and I can help walk you through the process.

**Comment by malloryfreeberg** [comment]
@mweiden is the Alert meant to be an internal alert? Or an alert that should go out to non-DCP people as well?

If the former, I'll open a ticket in dcp-monitoring to sent the alert to #hca-metadata-int. Thanks for setting this up!

**Comment by mweiden** [comment]
@malloryfreeberg this information is already public and I think it's best we keep it that way for transparency to users/devs: https://humancellatlas.github.io/projects/metadata-schema/
