### ISSUE TITLE
Operator Documentation (RunBooks)

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#860]
Internal.

Runbook should detail how to deploy the component.
Runbook should detail how to roll-back a deployment.
Runbook should provide guidance on how to diagnose / resolve common problems.

Create your RunBook on allspark.dev.data.humancellatlas.org
Put a link to it in this page: https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/home

Examples:

https://github.com/HumanCellAtlas/ingest-central/blob/master/release-manager-playbook.md

[SOP: Releasing new Versions of DCP Software](https://docs.google.com/document/d/1HbSWuIABaavaHpCwaO0peA_uwTW5wBCdRnYoz7ZVQuQ/edit?ts=5b0d7550#heading=h.yw6cvy5vlmbu)

[Playbook template in doc form](https://docs.google.com/document/d/1EPcN1tEIwMuzRXj8JPARd-Vgnc3sXJvwQOEcVWkVaYc/edit)

**Comment by rhiananthony** [comment]
This is a Q3 priority, can we please set a milestone (Q3 milestone 3?) and set an owner?

**Comment by stahiri** [comment]
This work has shifted to Q4 as carryover MUST HAVE work. I've updated release and milestone for this but it needs an owner. @diekhans or @morrisonnorman, can you assign the appropriate owner?

**Comment by diekhans** [comment]
@zperova will update current SOP at
[https://docs.google.com/document/d/1gNq5I42xY5ie8jqENSVEswn3NXHKUYgrfFgwMK_Vh8A/edit](https://docs.google.com/document/d/1gNq5I42xY5ie8jqENSVEswn3NXHKUYgrfFgwMK_Vh8A/edit)

@diekhans will put this in the wiki

**Comment by stahiri** [comment]
Thanks for the update @diekhans!

**Comment by stahiri** [comment]
@diekhans it looks like the Metadata Schema Publisher runbook has been published to the wiki (https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/Metadata%20Schema%20Publisher) so I believe this ticket can be closed.
