### ISSUE TITLE
Big Red Button

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#861]
As the operations team, I need a way to stop production should something be going extremely wrong, i.e. abuse of the system, security breach

Tony Tung is a great resource for this

- [x] ingest
- [x] data store
- [x] upload
- [ ] Data browser
- [ ] Data portal
- [x] secondary analysis
- [ ] operations runbook for pushing the big red button

Post Pilot:
- [ ] matrix service

**Comment by malloryfreeberg** [comment]
@justincc

**Comment by daniwelter** [comment]
Is this issue relevant for the metadata component?
