### ISSUE TITLE
Move all services to GitLab deployments

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#862]
Brian H has been volunteered to track this effort. 

AC:
Production deployments in gitlab

- [ ] Ingestion service deployments
- [x] Upload service deployments
- [x] Secondary Analysis service deployments
- [x] Data Storage service deployments
- [x] Matrix service deployments
- [ ] Data browser service deployments
- [x] Data portal service deployments

**Comment by daniwelter** [comment]
Is this issue relevant for the metadata component?

**Comment by stahiri** [comment]
Closing this ticket for metadata schema
