### ISSUE TITLE
Track financial details, including the total spend incurred by usage of the DCP in production conditions

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#863]
We need to monitor our spending and find ways to improve where possible.

Coverage is required In both AWS and GCP.  Need to be able to break spend down by DCP component, and by service type (bucket storage, compute, batch, etc).

In AWS I believe this requires we tag each of our resources and then use their finance tools to mine those tags and aggregate costs.  Not sure how this works in GCP.

Step 1 = research the different mechanisms in AWS / GCP.
Step 2 = design tagging strategy, detail it in the dcp repo ticket #78 (https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/78)
Step 3 = ping component teams to implement their part
Step 4 = ensure platform-wide tools work as advertised

**Comment by zperova** [comment]
@sampierson this doesn't look like a metadata repo issue.
