### ISSUE TITLE
Ensure secrets do not leak into source code

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#864]
Verify that all developers are using Git Secrets.

https://github.com/awslabs/git-secrets
https://cloud.google.com/blog/products/gcp/help-keep-your-google-cloud-service-account-keys-safe
https://docs.google.com/document/d/1_7deaZd2XbjUetVJs8EsQg6JbW_MEX2iFgXpnR_PyYs/edit#heading=h.4f1e34ah25ia

**Comment by malloryfreeberg** [comment]
If you are listed below, please confirm (by checking the box below by your name) that you have installed GitSecrets. If you don't have Git Secrets installed, please do by **Monday March 25** 
by following the instructions posted in the ticket. 

- [ ] @hewgreen 
- [ ] @zperova 
- [ ] @daniwelter 
- [ ] @simonjupp 
- [ ] @diekhans 
- [ ] @willrockout 
- [ ] @cjvillar 
- [ ] @pnejad 
- [ ] @malloryfreeberg

**Comment by malloryfreeberg** [comment]
If you are listed below, you are a member of the metadata-updates team in the Human Cell Atlas organization which means you have commit privileges in the metadata-schema repo. As per this issue, please confirm - by checking the box below next to your name - that you have installed GitSecrets by **Friday April 19**.

If you don't have Git Secrets installed but would like to commit to this repo, please follow the instructions posted in the ticket to install it by **Friday April 19** and confirm installation by checking the box below next to your name.

If you don't want to commit to this repo, please let us know in the ticket. You will be removed from the metadata-updates team, but you will still be able to view the repo, create tickets, and provide comments on issues and PRs. You can also be added back to the team - provided you have installed GitSecrets - anytime in the future.

### Anyone who hasn't confirmed they have installed GitSecrets by Friday April 19 will be removed from the metadata-updates team.

- [ ] @simonjupp 
- [ ] @diekhans 
- [ ] @cjvillar 
- [ ] @pnejad 
- [ ] @ESapenaVentura 
- [ ] @claymfischer 
- [ ] @dosumis 
- [ ] @JimKent 
- [ ] @joshmoore 
- [ ] @justincc 
- [ ] @lauraclarke 
- [ ] @morrisonnorman

**Comment by daniwelter** [comment]
@malloryfreeberg I'm not on this list but I do have commit privileges to the repo and have installed git secrets.

**Comment by justincc** [comment]
Please remove me from this repo

**Comment by diekhans** [comment]
@sampierson is there a script to actually add git secrets?  The cited document doesn't allow copy/paste or save, so one it forced to type in 6 commands by hand.  Seems like a sure way for people to get it wrong.

**Comment by malloryfreeberg** [comment]
@dosumis  - removing you from the list of approved committers to the schema repo. If you would like to be added back, please install git-secrets as per the instructions above and let me know :)

**Comment by malloryfreeberg** [comment]
@diekhans here is the list of secrets/patterns I installed, based on the google doc linked to in the ticket and adding a couple based on secrets that have accidentally been committed to the wrangler repo previously:

```
cd metadata-schema/
git secrets --add --literal 'private_key'
git secrets --add --literal 'client_email'
git secrets --add --literal 'client_id'
git secrets --add --literal 'notification_token'
git secrets --add --literal 'api_key'
git secrets --add --literal 'api-key'
```

Feel free to copy/paste these if you haven't already :)

**Comment by malloryfreeberg** [comment]
@JimKent  - removing you from the list of approved committers to the schema repo. If you would like to be added back, please install git-secrets as per the instructions above and let me know :)
