### ISSUE TITLE
A developer onboarding and offboarding process is followed

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#865]
As a DCP stakeholder
I want an onboarding and off-boarding process to be followed for developers
so we maintain the integrity of the DCP source code when people leave the team.

We need to follow an onboarding and off-boarding process both:
- at the DCP level - that addresses things such as GitHub organization access and PaaS access
- and at the component/ team level, that addresses specific needs for that component

Onboarding and offboarding documents should be linked to from the [DCP Ops Wiki Home](https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/home)

**Comment by malloryfreeberg** [comment]
@hewgreen given that you are in the process of being off-boarded, maybe we can use the doc you have written for yourself as a starting point for developing metadata-team and wrangler-team off-boarding documentation?

@ESapenaVentura given that you are in the process of being on-boarded, maybe we can use the docs/tickets we've put together as a starting point for developing metadata-team and wrangler-team off-boarding documentation?

**Comment by ESapenaVentura** [comment]
@malloryfreeberg seems like a good idea. When I have some free time I can try and gather all the docs/tickets that you have given me up to this point. They could be potentially useful for a hypothetical future wrangler.

**Comment by lauraclarke** [comment]
@ESapenaVentura you could potentially create a template issue for onboarding a new wrangler to capture the standard tasks and help you learn how to build issue templates

**Comment by ESapenaVentura** [comment]
Seems like a good idea! We can talk tomorrow about it
