### ISSUE TITLE
3rd party libraries in use are tracked and analyzed for security risk

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#869]
DevSecOps team needs to tell us what tools to use to do this.
Then we will update all the component team tickets with that information.

**Comment by stahiri** [comment]
Per #308, DevSecOps recommendation is for everyone to use the same tool. Both Snyk and SourceClear are good options here. Prior recommendation from the team is to start with Snyk since it's open source (SourceClear requires procurement).

**Comment by stahiri** [comment]
Snyk has been implemented across the humancellatlas GitHub org
