### ISSUE TITLE
Please consider just a single cell_line module

### ISSUE THREAD

**Issue by JimKent** [HumanCellAtlas/metadata-schema#87]
In the interest of brevity and simplicity of data modeling, could we merge immortal_cell_line and primary_cell_line, and have a field in the merged module, called simply cell_line, to distinguish the two?  The two share most fields.   The primary_cell_line is lacking catalog number, but you can buy primary cell lines at many places including ATCC.

**Comment by claymfischer** [comment]
I like this solution.

**Comment by lauraclarke** [comment]
We certainly want to reduce the number of duplicated fields where possible. It would be good to understand the value of the two files if the fields are almost all the same.

Is this due to the differential requirements between the two types? is there another way to model that?

**Comment by JimKent** [comment]
I think this is one of those messes that can only happen when multiple people work on something.  You, I, and David O-S all played a role.   

My role was a field, sample.culture_type, which I took from both ArrayExpress and GEO.  It was an enum with three values: "primary culture" "cell line" and "tissue."   Your role was to create a cell_line module that was quite detailed in v4.  David's role was deciding if there was a cell_line module,   there should be modules for "primary culture" and "tissue" as well, and then later "organoid" too.   Then David renamed "primary_culture" and "cell_line" became for reasons of consistency and/or clarity to "primary_cell_line" and "immortal_cell_line."

Perhaps you could ask David if he sees a problem with the single cell_line module?

**Comment by malloryfreeberg** [comment]
We have merged these in v5.0.0 into a single schema `cell_line.json` with a field `cell_line_type` that can be used to declare whether the cell line is primary, immortalized, stem cell-derived, or synthetic. Additional types can be added to the enum for this field as needed.

**Comment by malloryfreeberg** [comment]
Addressed in 09089de0981d150d78ea2de7a39ab87dfe2a45fd.
