### ISSUE TITLE
Define way to indicate confidence level of metadata fields.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#870]
**Description**

 

As a data consumers who downloads and uses data from the DSS, I would like to have an idea of how confident I can be in the correctness of metadata fields in order to be able to process, analyze, and interpret the data to my standard.

**Acceptance Criteria**

  
- [ ] TBD

**Comment by malloryfreeberg** [comment]
@mckinsel I started a stub issue for you here and filled out a generic use case. Could you please review and update as appropriate? And even start to list some acceptance criteria that would satisfy your needs. Thanks!

**Comment by lauraclarke** [comment]
It would be good to make sure we define "correctness" well or choose a better word. I am assuming this isn't about individual fields being right or wrong, that we can't know, we have to assume we have been given the right values by submitters but how complete for optional but valuable fields the metadata is

**Comment by malloryfreeberg** [comment]
I think there might be two uses for "confidence" here.

The first use is, as you state, how confident a consumer can be that an optional field is filled in.

The other use is actually about individual fields being right or wrong. One of @mckinsel 's key examples is the `strand` field. There is only one correct answer for `strand` for a given experiment type. 10x 3' v2 I believe sequences the "first" strand (nice illustration [here](https://teichlab.github.io/scg_lib_structs/methods_html/10xChromium3.html)). However, currently in production is a mix of strandedness values for various 10x experiments, mostly due to many scientists not really knowing what to fill for the field and also due to lack of consensus of wranglers and tools that allow us to programmatically check this type of validation. So, until we have semantic validation tools (see some discussion in [this thread](https://github.com/HumanCellAtlas/metadata-schema/issues/539#issuecomment-463728467) about this topic), there might be some fields that consumers can't 100% rely on being accurate. Wranglers can improve this confidence by manually validating these types of field, but wranglers are not infallible. 

It would be great to get some help filling out this ticket from data consumer experiences. Maybe @adriennes or @gabsie might have some specific examples that came out of beta1 (or from beta2 in the future).

**Comment by lauraclarke** [comment]
Just to reiterate what I have just discussed with @malloryfreeberg 

We have to be very careful with correctness, we only knew that the value @mckinsel pointed us too was wrong because he pointed it out. I think we need to maintain the idea that the value we are given by the submitter is the correct value unless it fails our validation because the validation infrastructure to assume anything else is just too complex for us to support.

If we then post-hoc learn that a field has a limited set of values which aren't always being used we should fix our validation (or in this case add a way to validate) to make sure the error doesn't occur again

@gabsie @adriennes I do wonder if there is any sensible way for a contributor to be able to express uncertainty about what they put it, so if they don't know the right answer for a required field they can flag that this term was a guess? is that even a good idea?

**Comment by claymfischer** [comment]
I am quite wary of this. My concern is that it will be increasing complexity in something already complex, solving a problem we don't currently have, and enabling confidence where I am not sure we should.

**Comment by malloryfreeberg** [comment]
>  I think we need to maintain the idea that the value we are given by the submitter is the correct value unless it fails our validation because the validation infrastructure to assume anything else is just too complex for us to support.

I agree with this point. 

Besides validating that the JSON document adheres to the schema, we don't do any semantic validation. For example, it is known that if an experiment follows the standard 10x 3' v2 protocol, they they have sequenced the first strand of cDNA. If a contributor submits data from a standard 10x experiment and puts in "second" or "unstranded" for the strand field, we should flag this and suggest they they change it. Strandedness is something many people don't know, and they might be inclined to guess (it's a required field). We currently don't have the tooling in place to semantically catch/check this.

Instead of indicating how often we expect fields in the schema to be filled in "correctly", perhaps we can indicate directly whether the system has semantic validation in place for a field. For example, we could indicate for "strand" that "This field has been semantically validated by the DCP." which might give data consumers more confidence that the field is reliable. 

We have an open issue for another field that needs additional semantic validation, a field that is required for us to ingest one of the current datasets being wrangled. https://github.com/HumanCellAtlas/metadata-schema/issues/539#issuecomment-463777454

**Comment by lauraclarke** [comment]
I like this idea @malloryfreeberg I also think it is easier to implement and has lower social consequences for submitters than asking them to express certainty in the values they give us

**Comment by malloryfreeberg** [comment]
@diekhans had a good suggestion for ordering of validation types post-import https://github.com/HumanCellAtlas/metadata-schema/issues/539#issuecomment-463728467

1. syntax validation (check JSON conforms to schema)
1. correction/repair/consistency
1. semantic validation (see that fields make sense together)

e.g. if `library_construction_method` == "10x 3' v2 sequencing" then `strand` should be "first".

**Comment by lauraclarke** [comment]
That makes a lot of sense, from a time and complexity perspective we might need to implement at least some bits of semantic validation and run in the absence of a repair UI as otherwise it is going to get very frustrating from a user perspective, unless the repair being referred to is automated

**Comment by malloryfreeberg** [comment]
I think the "awesome" goal is for repair to be automated. There are some incremental repairs goals that could be implemented sooner, for example if a user puts "M" in the `sex` field, we could repair that to "male" in order to pass validation. I imagine this would happen programmatically in the background. Other repairs will be trickier and require opt-in from submitters in the UI. I'm thinking a lot of the ontology work fits in this category. 

But I agree, there are small bits of both correction and semantic validation that would go a long way to helping wranglers now and be a test for the fully awesome version of these features.

**Comment by daniwelter** [comment]
+1 on automatic enum/ontology-based standardisation of free-text values. I'm in the middle of reviewing all ontology mappings from all the current datasets and we have various cases of the same field value being spelt in different ways in the free-text field (eg 10X v2 sequencing v 10x v2 v 10x_v2)

**Comment by diekhans** [comment]
I created an issue to collect issues related to the need for
semantic validation:

   https://github.com/HumanCellAtlas/metadata-schema/issues/889

I like the two issues mentioned here, please to add any other you think might
be related.

**Comment by zperova** [comment]
Need to review with a potential of closing @lauraclarke
