### ISSUE TITLE
Include versions with accession fields.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#877]
**For which schema is a change/update being suggested?**

I would like to request an update to schemas that have accession fields.

**What should the change/update be?**

I would like to be able to capture version information for fields that are accessions. This could potentially be implemented as new fields. 

**What new field(s) need to be changed/added?**

*e.g.* field for indicating version of an INSDC run accession:
* Field name: insdc_run_accession_version
* Field description: Version of the INSDC run accession.
* Field type: string
* Required: no
* Examples: ?
* CV or enum: no

**Why is the change requested?**

As per @diekhans discussion from [this PR](https://github.com/HumanCellAtlas/metadata-schema/pull/839).

This ticket needs further discussion and refinement.

**Comment by zperova** [comment]
@diekhans none of our accessions have versions. is this relevant?
