### ISSUE TITLE
Support for semantic validation of metadata

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/metadata-schema#889]
This ticket serves as a place to define the needs of semantic validation of metadata that goes beyond the syntactic validation of JSON schema.  This includes detailed value , cross field, and cross-entity validation.  Please link tickets that relate to or would be address by sematic validation.

**Comment by diekhans** [comment]
Related issues:
- #539 Values entered as dates only should be valid in date-time typed fields 
- #870 Define way to indicate confidence level of metadata fields.

**Comment by ESapenaVentura** [comment]
I think this is obsolete (We can currently check datasets with the ingest-graph-validator)
