### ISSUE TITLE
Increasing max ischemic_time value

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#89]
We have data from a group specifically interested in looking at cells up to 72h ischemia. Converted to seconds this is 259200 seconds, which doesn't validate against the current maximum level set for the ischemic_time field (100000 seconds).

```
        "ischemic_time": {
            "minimum": 0, 
            "type": "integer", 
            "description": "Duration of time, in seconds, that the body part had insufficient blood supply.", 
            "maximum": 100000
        }, 
```

What was the motivation behind choosing this maximum value? I suggest increasing to accommodate this use case.

I'm happy to make the change, which will then necessitate a minor release v4.3.0.

**Comment by dosumis** [comment]
I'd increase.  I guess the original value was added because experiments to look at degredation of sample due to ischemia were not anticipated.
