### ISSUE TITLE
Write up RFC for Library Prep entity

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#892]
**Description of the task:**

Write up an internal RFC (to be turned into a DCP-wide RFC) for adding a Library Preparation biomaterial entity to the HCA metadata model. RFC should synthesize discussions and opinions from this [doc](https://docs.google.com/document/d/15-UkjbAlGDGhOPw1Zu09YdoaGw2Zeq5Y3uDlGsrz6pw/edit#heading=h.zu8c32dxlj1).

**Acceptance criteria for the task:**

- [x] Internal RFC document written.
- [x] Internal RFC document circulated within metadata team for feedback.
- [x] DCP RFC document made in dcp-community repo.

**Comment by hewgreen** [comment]
Internal doc here https://docs.google.com/document/d/15-UkjbAlGDGhOPw1Zu09YdoaGw2Zeq5Y3uDlGsrz6pw/edit#

**Comment by hewgreen** [comment]
Internal doc here https://docs.google.com/document/d/15-UkjbAlGDGhOPw1Zu09YdoaGw2Zeq5Y3uDlGsrz6pw/edit#

**Comment by lauraclarke** [comment]
@hewgreen what state is this currently in?

**Comment by malloryfreeberg** [comment]
Updating this ticket with the current Library preparation RFC doc: [Google doc](https://docs.google.com/document/d/1PdJAd4q775jwnDoavJE_7XajXm0e7a5SGvP2k7DRJHc/edit?pli=1#)

Has been presented internally. Am reaching out to specific individuals in the DCP for targeted feedback.

**Comment by malloryfreeberg** [comment]
RFC is now in GH [here](https://github.com/HumanCellAtlas/dcp-community/blob/mfreeberg-rfc-library-preparation/rfcs/text/0000-rfc-library-preparation.md).

**Comment by malloryfreeberg** [comment]
Closing this issue as the acceptance criteria have been met.
