### ISSUE TITLE
Provide mechanism to provide a context-specific human readable property name

### ISSUE THREAD

**Issue by simonjupp** [HumanCellAtlas/metadata-schema#899]
There's a requirement to provide human readable names for property names when presenting the metadata schema to consumers (DataBiosphere/azul#784). Some property names come from shared modules or core schemas e.g. `biomaterial_id` has a user friendly name of “Biomaterial ID”. 

If human readable labels alone are used to present metadata with multiple biomaterial types then you'll have multiple columns called "Biomaterial ID" with no way to distinguish between them. Ideally, we would like to present a unique name e.g. in a donor context provide a human readable name of "Donor ID". 

We've discussed a few options in the past:
1. Add an additional unique property name that incorporates the schema name. e.g. `"Biomaterial ID (donor_organsm.biomaterial.core.biomaterial_id)"`. This is what the ingest spreadsheet templates currently have, although the unique field names are in a hidden row that is needed to interpret the spreadsheet. 
2. Use the `SchemaTemplate` accessor library to generate a context specific human readable name on the fly e.g. by concatenating user friendly names to generate labels like "Donor Biomaterial ID"  when biomaterial id is referenced from the donor schema. 
3. Dereference all the imported schema as publishing time to produce single schemas for each submittable type (we've been called this demodularisation). This would give us a step in the schema release process to generate appropriate human readable names and have these live in the released schemas and accessible to downstream application. We have a draft RFC for this here https://github.com/HumanCellAtlas/dcp-community/blob/rfc-metadata-schema-simplification/rfcs/text/0000-metadata-schema-usability.md

This is related to HumanCellAtlas/ingest-central#211

**Comment by zperova** [comment]
This needs review @zperova
