### ISSUE TITLE
Extend set of sample types & implement subschema pattern for each.

### ISSUE THREAD

**Issue by dosumis** [HumanCellAtlas/metadata-schema#9]
- [x] Extend set of sample types (from current set specified in culture-type field) into something more general.  New types will include one for donor and one for organoid. 
- [x] Implement JSON pattern in which each sample type has its own subschema.  Most fields for each type will live in these subschemas.

(This is an action item from CZI meeting (Oct 2-4 2017)

**Comment by dosumis** [comment]
A gist, sketching out how JSON could be structured to achieve this, can be found here:

https://gist.github.com/dosumis/239c6337325be70711cc00a0dd8007d9

**Comment by dosumis** [comment]
CC @lauraclarke

**Comment by malloryfreeberg** [comment]
This has been addressed since v4.0.0. And we have the ability to add new subschemas as needed.
