### ISSUE TITLE
Ontologize select metadata fields.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#900]
**For which schema is a change/update being suggested?**

I would like to request an update to multiple schemas.

**What should the change/update be?**

I would like to make some fields ontologies.

- [ ] `cell_line.type`
- [ ] `cell_line.name` (don't have this field now, but maybe add to cell line schema #756 )
- [x] `contact.project_role` (#894)
- [ ] `file.format` (#812)

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

Maintaining these fields with ontologies is more stable than maintaining an internal enum.

**Comment by zperova** [comment]
@zperova split this into separate tickets

**Comment by lauraclarke** [comment]
@zperova did you split this into separate tickets and add them to? https://docs.google.com/spreadsheets/d/1B52QjioJ7CzOLXFIcB-Q8mfjiFSH0jzbfdNs_nce3P4/edit#gid=0

It would be good to consider if these changes are needed

**Comment by zperova** [comment]
Closing this issue as has been split into separate tickets:
https://github.com/HumanCellAtlas/metadata-schema/issues/1172
https://github.com/HumanCellAtlas/metadata-schema/issues/756
https://github.com/HumanCellAtlas/metadata-schema/issues/894
https://github.com/HumanCellAtlas/metadata-schema/issues/812
