### ISSUE TITLE
Rename `donor_organism` to `donor`

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-schema#905]
Apologies for not following the template but this one is easily explained.

There currently is only one entity type with `donor` in its name. Unless we expect another type of `donor`, say `donor_cell`, it would make sense to shorten the name because it turns out that we frequently need to qualify metadata properties fully—in TSV headers, for example. These fully-qualified metadata property references tend to be long.

It may also be worth noting that we colloquially use the shortened term.

**Comment by malloryfreeberg** [comment]
Thanks for the schema update request!

A similar ticket already exists: #386

I will close this ticket and transfer your usability comment to the older ticket, if that's ok?

**Comment by hannes-ucsc** [comment]
Duplicates #386.
