### ISSUE TITLE
Rename `specimen_from_organism` to `specimen`

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-schema#906]
Apologies for not following the template but this one is easily explained.

There currently is only one kind of `specimen` mentioned the schema. Unless we expect another type of `specimen`, it would make sense to shorten the name because it turns out that we frequently need to qualify metadata properties fully—in TSV headers, for example. These fully-qualified metadata property references tend to be long.

It may also be worth noting that we colloquially use the shortened term in conversation.

**Comment by malloryfreeberg** [comment]
Thanks for suggesting a schema update!

A similar issue already exists: #389 

I'll close this issue and post your comment on the existing issue, if that's ok?

**Comment by hannes-ucsc** [comment]
Duplicates #389.
