### ISSUE TITLE
Fix enum for storage_method for preservation_storage.json

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/metadata-schema#916]
**For which schema is a change/update being suggested?**

I would like to request an update to the `preservation_storage.json` schema.

**What should the change/update be?**

I would like to fix enum for storage_method:
frozen at -70C to frozen at -80C

**Why is the change requested?**

Freezing at -80C is a conventional storage method.

**Comment by malloryfreeberg** [comment]
Can we add "frozen at -80C" instead of replace what's there? Unless you want to check that no current datasets use "frozen at -70C". If so, that dataset will not validate against the schema change.

**Comment by malloryfreeberg** [comment]
Also, removing a value from an enum is a major version change. Adding is only a minor version change :)

**Comment by zperova** [comment]
@malloryfreeberg sure, I can add instead. Maybe specific protocol, or rather poorly working freezer :) This brings me to a question, how do contributor's know that this is an enum? i understand in the future this will be incorporated in the spreadsheet, but i think it makes sense to add all the values for enums in the spreadsheet to the Spreadsheet guide.

**Comment by malloryfreeberg** [comment]
@zperova if you haven't started this update, maybe we can give it to @ESapenaVentura ?

**Comment by zperova** [comment]
Sure. @ESapenaVentura feel free to reassign this issue and go ahead.

**Comment by ESapenaVentura** [comment]
@malloryfreeberg @zperova Ok, I can try!
