### ISSUE TITLE
timecourse module add to cell line biomaterial

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/metadata-schema#917]
We have now added differentiated cell line entities to the neuronal diff dataset. We have the timecourse information on cell suspension but it would be nice to record this on the cell line entity. We should add this as an optional module to the cell line entity.

**Comment by malloryfreeberg** [comment]
Will pull this into the sprint so we don't block ingestion.

**Comment by ESapenaVentura** [comment]
Done!
