### ISSUE TITLE
Require 2FA in all Github and GitLab repos

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#919]
As a DCP stakeholder, I want all developer accounts to be secured with 2FA, so that a compromised password alone won't allow malicious actors to inject malware into the DCP codebase.

It would be nice if we could just turn on the _"everybody in this organization must have 2FA set up"_ GitHub feature, but we cannot, as there are many members of the organization peripherally attached to the HCA (Jamboree attendees) that don't have 2FA set up, and that we cannot contact and don't want to alienate by kicking them out of the org.

So an alternate strategy was devised to secure all the DCP component repos:

A transitional group has been created: "HCA" that contains all HCA members and  has write access to all repos.

Each component team must now:
* create or add their developers to a different group
* give that group write-access to their repo(s)
* remove write access from the "HCA" team

I'm going to create a ticket in all DCP component repos for this.  My apologies if you have already completed this work.  Just close the ticket for your team if you have.

**Comment by malloryfreeberg** [comment]
- All the metadata team developers are part of the metadata-updates GitHub team.
- The metadata-updates team has write-access to the metadata-schema repo.
- I don't see that the "HCA" team has write-access to the metadata-schema repo. @stahiri or @sampierson is this enough to confirm that this item is done?

**Comment by stahiri** [comment]
Yes; looks like this meets all of the requirements. Can you confirm that the metadata-updates team is the only group with write access to the metadata-schema repo?

**Comment by malloryfreeberg** [comment]
@stahiri thanks! Can confirm:

![Screen Shot 2019-05-13 at 14 32 35](https://user-images.githubusercontent.com/10993501/57625565-05853d00-758c-11e9-8962-f438bc240c97.png)

**Comment by malloryfreeberg** [comment]
Closing as this appears to be done.
