### ISSUE TITLE
Components SHOULD implement Level 2 Health Checks

### ISSUE THREAD

**Issue by sampierson** [HumanCellAtlas/metadata-schema#922]
_The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in RFC 2119._

**As a DCP Operator,
I want to know not only that a component is up, but that it is nominally functional,
so that we may take action if necessary to remedy the situation.**

Most components currently only have what we will call a "Level 1" Health Check in place.  They have a `/heath` endpoint that will respond if the REST API part of the service is available, but it indicates no more than the REST API part of the service is functioning.

A "Level 2" health check tests other parts of the component service and its internal dependencies, to give a clearer indication that the entire component is healthy.

I suspect that it is unlikely that these checks can be completed in real time (i.e. please don't block for ages when `/health` is polled), and that the `/health` endpoint will be reporting results of the last time that periodic health checks ran in the background.

This ticket was created at the request of the Tech Arch committee, 2019/03/22 meeting.

**Comment by daniwelter** [comment]
Is this issue relevant for the metadata component? Metadata itself does not have a live component - there is the metadata schema server but that is under the preview of a separate repo, not directly linked to or deployed from the metadata repo.

**Comment by rexwangcc** [comment]
where is the separate repo? Could you provide a pointer here 😺

**Comment by mweiden** [comment]
To my understanding, the metadata-schema is served directly by a CDN, so this may not be relevant. Closing.
