### ISSUE TITLE
Change `enrichment_method ` to `method`, `min_size_selected` to `minimum_size`, `max_size_selected` to `maximum_size`

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#925]
**For which schema is a change/update being suggested?**

I would like to request an update to the `enrichment_protocol.json` schema.

**What should the change/update be?**

- [ ] change `enrichment_method ` to `method`  to remove redundancy ("enrichment")
- [ ] change `min_size_selected` to `minimum_size`
- [ ] change `max_size_selected` to `maximum_size`

**What new field(s) need to be changed/added?**

Above.

**Why is the change requested?**

Adhere to Style Guide.

**Comment by malloryfreeberg** [comment]
@ESapenaVentura can you take this issue?

**Comment by ESapenaVentura** [comment]
@malloryfreeberg Yes, of course!
