### ISSUE TITLE
Change `contact_name` to `name`

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#927]
**For which schema is a change/update being suggested?**

I would like to request an update to the `contact.json` schema.

**What should the change/update be?**

- [x] change `contact_name` to `name` to remove redundant word (contact)

**What new field(s) need to be changed/added?**

Above.

**Why is the change requested?**

Adhere to Style Guide.

    Ping Marcus, Brian, Hannes, Dave

**Comment by cjvillar** [comment]
Done.
