### ISSUE TITLE
Change `biosd_biomaterial` to `biosamples_accession`, `insdc_biomaterial` to `insdc_sample_accession`

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#929]
**For which schema is a change/update being suggested?**

I would like to request an update to the `biomaterial_core.json` schema.

**What should the change/update be?**

- [x] change `biosd_biomaterial` to `biosamples_accession` to be more precise about what the field is
- [x] change `insdc_biomaterial` to `insdc_sample_accession` to be more precise about what the field is

**What new field(s) need to be changed/added?**

Above.

**Why is the change requested?**

Adhere to Style Guide.

    Ping Alegria

**Comment by ESapenaVentura** [comment]
Already merged.
