### ISSUE TITLE
Change protocol and process `type` fields.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#931]
**For which schema is a change/update being suggested?**

I would like to request an update to multiple schemas (see below).

**What should the change/update be?**

- [x] analysis_protocol.json
    - [x] change `protocol_type` to `type` (actually to something else that is more descriptive than 
- [x] protocol.json
    - [x] change `protocol_type` to `type` to remove redundancy ("protocol")
- [x] process.json
    - [x] change `process_type ` to `type` to remove redundancy ("process")
- [x] analysis_process.json
    - [x] change `process_type ` to `type` to remove redundancy ("process")

**What new field(s) need to be changed/added?**

Above.

**Why is the change requested?**

Adhere to Style Guide.

    Ping Marcus, Brian, Saman when PR is made

**Comment by malloryfreeberg** [comment]
@ESapenaVentura can you take this one?

**Comment by ESapenaVentura** [comment]
@malloryfreeberg More than glad to take it!

**Comment by cjvillar** [comment]
Merged change, closing ticket.
