### ISSUE TITLE
Change cell_line_type to type

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#935]
**For which schema is a change/update being suggested?**

I would like to request an update to the `cell_line.json` schema.

**What should the change/update be?**

- [x] change cell_line_type to type (maybe need a better word than "type") to remove redundancy (cell_line)

**What new field(s) need to be changed/added?**

Above.

**Why is the change requested?**

Adhere to Style Guide.

**Comment by ESapenaVentura** [comment]
Pull request linked to this issue already merged with develop.
