### ISSUE TITLE
Capture appropriate alerts and audit trails so we can handle detected attacks and understand the consequences of emergent threats and breaches

### ISSUE THREAD

**Issue by stahiri** [HumanCellAtlas/metadata-schema#951]
As specified in the [Q2 Roadmap] (https://docs.google.com/spreadsheets/d/1iAL2JR3ndgMmYwojUU0kU8Pm7B7ycRLt_973seREd3M/edit#gid=1107068822&range=C10).

We need appropriate alerts and audit trails so we can learn about and appropriately handle detected attacks and understand the consequences of emergent threats and breaches. This includes being able to know when an attack is taking place and being able to see in the logs what the attack entailed (what attacker accessed, changed, etc.).

__Deliverable__: 
Ensure each component captures audit logs for the following types of events (as appropriate):
• Server alerts and error messages
• User log-on and log-off (successful or unsuccessful)
• System administration activities
• Modification of privileges and access
• Modifications to the application
• Application alerts and error messages
• Configuration changes
• Account creation, modification, or deletion

**Comment by daniwelter** [comment]
Is this issue relevant for the metadata component?

**Comment by stahiri** [comment]
We want to be able to capture any changes to metadata schemas, as well, which I would consider a configuration change.

**Comment by malloryfreeberg** [comment]
@stahiri  I don’t really know what needs to be done for the metadata-schema ticket (might need some engineering help), or where it lies in our priorities (@lauraclarke ? @morrisonnorman ? @justincc ?) I can at least bring the ticket into our current sprint.

**Comment by stahiri** [comment]
So this is admittedly less concerning for metadata-schema, but we (1) want to have the same level of auditing across the DCP and (2) want to be able to log any relevant events so those can be monitored for malicious activity. For example, if a malicious user came in and wanted to be simply mean, they could change the schema or configuration of the project. We would want to be able to look at logs and see who made the changes. 

Please be sure all of the events mentioned in the description, relevant to metadata-schema, are being logged and that those logs are being stored somewhere. I'd be happy to talk if there are still questions!

**Comment by zperova** [comment]
@stahiri thanks for the explanation. I understand the concern of malicious activity. Could you also clarify what do you mean by "logged and that those logs are being stored somewhere" and how that can be achieved?

**Comment by malloryfreeberg** [comment]
So talking a bit more with the ingest developers, I think there are two points of auditing/logging we need.

1. **GitHub repository** - the metadata-schema repository is where all the schema changes happen. By nature of being on GitHub, it is sufficient to have the trail of commit statements to log/monitor who is making changes to the metadata?
1. **s3 bucket hosting schemas** - the schemas are published to an s3 bucket which is where the DCP software gets them from to use them. I'm guessing we need to confirm that there is a security layer of this bucket? Maybe AWS does this automatically and the logs are maintained by Cloudwatch? 

We can discuss with @lauraclarke @morrisonnorman and @justincc about who should own this, but do GitHub commit statements and AWS Cloudwatch logs satisfy the requirements @stahiri ?

**Comment by stahiri** [comment]
Hi @malloryfreeberg --- yes, commit statements and cloudwatch logs will likely satisfy these requirements. I understand that cloudwatch is configurable, so we'll just want to ensure that it's capturing the applicable logs noted in the ticket description.

Any luck on identifying an owner for this task? Could this also be assigned a milestone (I'm guessing Sprint 3 is the appropriate one)?

**Comment by malloryfreeberg** [comment]
@stahiri thanks for the clarification!

We haven't yet discussed ownership. There's been a lot of people on holiday recently. We will put this ticket in our next sprint (11-25 June) and we will aim for it to be addressed by the end of the sprint.

pinging @morrisonnorman @lauraclarke @justincc

**Comment by lauraclarke** [comment]
@stahiri @diekhans our metadata tech-lead is happy to also take on security responsibility

**Comment by diekhans** [comment]
As the metadata schema has no system run time component, these security issues don't apply.
