### ISSUE TITLE
Add Descriptions to any field that does not have one

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/metadata-schema#955]
For the Input parameters and workflow tasks on the Analysis Process type can we get the definitions filled out? Since they are missing in the JSON Schema we do not have any text to display for several fields in the Metadata Dictionary

See

https://dev.data.humancellatlas.org/metadata/dictionary/process/analysis/analysis_process#analysis-process-inputs-checksum

and

https://dev.data.humancellatlas.org/metadata/dictionary/process/analysis/analysis_process#analysis-process-tasks-disk-size

Would be great if all fields had a definition. 

Thanks!
D

**Comment by malloryfreeberg** [comment]
Great catch, @NoopDog !

@samanehsan @rexwangcc @kbergin - I took a look at the fields in the analysis_process.json schema, and I don't think I know precisely what the fields represent enough to get the definitions correct. For example, I can guess that the `cpus` field captures some count of CPU usage, but I don't know exactly what the count is (average? total? for the whole workflow? calculated how?).

So, I would greatly appreciate some help with addressing this ticket! The schema update team is happy to do all the reviewing/merging, but it's probably best if someone from pipelines team provides the actual field definitions. 

To officially adhere to the [Style Guide](https://github.com/HumanCellAtlas/metadata-schema/blob/develop/docs/schema_style_guide.md#required-field-attributes), all these fields actually need both definitions and user-friendly names. Most also could use examples. The schema update team would be happy to help with user-friendly names and examples (we can probably grab examples from the integration tests). 

**How would you all like to proceed?** One option is for the schema update team to make a branch  and start updating the bits we can to bring the schema up the Style Guide standards. Then we'd ask the pipelines team to add the descriptions. How does this sound? Is there another approach that you think would be easier? These are all patch changes, so they wouldn't have negative impact on any other DCP components :)

**Comment by malloryfreeberg** [comment]
@samanehsan @rexwangcc @kbergin

I'll take a stab at doing these updates, and I'll request your review/help for the remaining bits :)

**Comment by kbergin** [comment]
Adding in Janki, sorry for the delay in response, Mallory. @jkaneria
