### ISSUE TITLE
Schema linter shows Errors and Warnings separately. Fails if any Errors.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#959]
**Description**

 

As a DCP member who updates the metadata schemas, I would like to know whether the updates I did result in deal-breaking violations of the Style Guide (errors that need to be fixed before committing) or result in undesirable but acceptable violations of the Style Guide (warnings that _should_ be fixed but are OK to commit).

**Acceptance Criteria**

  
- [x] Output of running the schema linter: passes if no warnings or errors, passes if warnings but no errors, and fails if any errors. 
- [x] Warnings and errors describe what the violation is.

**Comment by ESapenaVentura** [comment]
Done!
