### ISSUE TITLE
Nit on "?" for boolean fields friendly name. 

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/metadata-schema#963]
We are not yet consistent on using the "?" character at the end of the friendly name for boolean fields.

For example

`Drop uniformity` in 10x Specific Module vs "Paired end?` in Protocol/Sequencing Protocol.

Requesting that we are consistent in the naming with my personal preference being to drop the question mark.

**Comment by ESapenaVentura** [comment]
+1 on dropping the question mark. I think we should tend to avoid punctuation on names as much as possible (Even if it's a "friendly name")

**Comment by malloryfreeberg** [comment]
@ESapenaVentura @daniwelter @cjvillar @willrockout @pnejad @zperova @hewgreen 

Please react to this comment with a
- 👍  if you'd like to _remove_ all question marks from boolean fields
-  👎  if you'd like to _keep_ all questions marks for boolean fields. 

Get your votes in by **Tuesday Apr 30**.

**Comment by ESapenaVentura** [comment]
@malloryfreeberg @NoopDog Since it's already almost May 2, are we going to try to push this change, or are we going to wait until re-ingestion?

**Comment by malloryfreeberg** [comment]
> @malloryfreeberg @NoopDog Since it's already almost May 2, are we going to try to push this change, or are we going to wait until re-ingestion?

We can make this change and push to develop, but we will not be promoting anything further than to dev until the end of Q2. This schema change doesn't affect functionality of ingesting/storing/processing data.

**Comment by ESapenaVentura** [comment]
> > @malloryfreeberg @NoopDog Since it's already almost May 2, are we going to try to push this change, or are we going to wait until re-ingestion?
> 
> We can make this change and push to develop, but we will not be promoting anything further than to dev until the end of Q2. This schema change doesn't affect functionality of ingesting/storing/processing data.

👍 I'll do it tomorrow morning (Unless anyone wants to do it earlier than that)

**Comment by ESapenaVentura** [comment]
While working on this, I have noticed that we have several fields that are booleans (We expect a yes or no) but are treated like enums. An example would be in the `module/protocol/target.json`, where the property `multiplexed` is an enum. 

I think we should change them to booleans. What do you guys think?

**Comment by zperova** [comment]
@ESapenaVentura we have a number of cases where value had to be added (such as "unspecified" or "unknown", for example). This is only possible to do with an enum. Changing a type of field is a major change, and would be not the most rational solution to go back in case we need to add extra value. 
as for the target.json - this schema should be deprecated.

**Comment by malloryfreeberg** [comment]
I think this is a good idea to try to standardize our usage. I would say that we should only use boolean when there are absolutely no other possible answers. For example, the `is_living` field is an enum because it can be "yes", "no", or "unknown". 

Let's keep this ticket to address the user-friendly field names, and @ESapenaVentura can you make a new ticket to address reviewing and standardizing enum vs. boolean fields?

**Comment by ESapenaVentura** [comment]
> @ESapenaVentura we have a number of cases where value had to be added (such as "unspecified" or "unknown", for example). This is only possible to do with an enum. Changing a type of field is a major change, and would be not the most rational solution to go back in case we need to add extra value.
> as for the target.json - this schema should be deprecated.

Actually, in the 2 schemas that I've found it, it only accepted `yes` or `no`, so it would be a minor change (if it only accepts those 2 values, which are actually boolean values, doesn't break backwards compatibility).

Anyways, what I'm most concerned of is if I should update these values for this ticket. They have the "?" at the end of the friendly name, but they are not "strictly" boolean fields (Even though we are going to change them)
