### ISSUE TITLE
Automatically generate example metadata JSON

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#964]
**Description**

 

As a DCP member who depends on metadata schemas, I would like to have access to example metadata JSON that is valid against the current schema for a given environment so that I can validate new features that I am developing.

**Acceptance Criteria**

  
- [ ] A set of example JSON documents in the metadata-schema repo that cover the breadth of schemas and fields
- [ ] Code that generates example JSON documents automatically from the schema and commits them to the repo

**Comment by zperova** [comment]
need to revisit in November @lauraclarke

**Comment by ESapenaVentura** [comment]
In a very convoluted way, this ticket has been accomplished with the [schema-test-data](https://github.com/HumanCellAtlas/schema-test-data/) repository
