### ISSUE TITLE
Requirements gathering for property_migrations auto-update.

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#965]
**Description**

 

As a data wrangler and a recurring user of the metadata repo, it would be of help to dispose of a tool to assist us on filling up some error-prone fields, like the `property_migrations.json` schema. This tool would also assist people with less programming experience, and speed up the process of making major changes to the metadata schema.

**Acceptance Criteria**

 

- [ ] Completing a [requirements gathering doc](https://docs.google.com/document/d/1T8VjaWt2Je78G0IoayVxKDq9ZAXw2lOrCa3pEqtC1qc/edit?usp=sharing) with all the needs from the HCA-DCP community.
- [ ] Issuing the proper tickets for all the points discussed inside the doc.

**Comment by ESapenaVentura** [comment]
@HumanCellAtlas/wranglers Pinging the wrangling team to make sure everyone knows about this. There is no hurry, but I'd like to work on this ASAP, so I'd like to set a deadline for this friday (03/05) to begin working on this.

**Comment by malloryfreeberg** [comment]
@ESapenaVentura I've commented what I can right now. Excited to see what you can do in the next iteration!

**Comment by malloryfreeberg** [comment]
@ESapenaVentura are you working on this in the current spring? If not, can you put this ticket back in the product backlog?

**Comment by ESapenaVentura** [comment]
Moved it to product backlog! I'm currently more focused on e-mails and wrangling. Will come back with this when I talk with Simon (prob next sprint)

**Comment by zperova** [comment]
@ESapenaVentura probably next sprint? ;)

**Comment by ESapenaVentura** [comment]
This will be worked on with a different approach once we support schema migration
