### ISSUE TITLE
Change format of date and date-time fields to allow partial values.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#966]
**For which schema is a change/update being suggested?**

I would like to request an update to multiple schema (below).

**What should the change/update be?**

I would like to change the format of the following `date` and `date-time` fields to alternatively allow partial date and time values using a JSON pattern. Description of the approach is [here](https://github.com/HumanCellAtlas/metadata-schema/issues/539#issuecomment-465535372) and summarized as:

We could change the affected metadata schema properties to use the `oneOf` keyword and allow both a full date/date-time (as appropriate) and a reduced field matching a defined regex pattern. For example:

```
"time_of_death": {
      "description": "Date and time when death was declared.",
      "type": "string",
      "user_friendly": "Time of death",
      "example": "2016-01-21T00:00:00Z; 2016-03",
      "guidelines": "Enter the date and time in date-time format: yyyy-mm-ddThh:mm:ssZ. Supplying partial date is allowed."
      "oneOf": [
         {
            "format": "date-time"
         },
         {
            "pattern": "^((19|20)\\d\\d){1}([- \\./][01]\\d){0,1}([- \\./][0-3]\\d){0,1}$",
         }
      ]
 }
```

Suggested fields to change:

cell_line.json
- [x] `date_established`: YYYY, YYYY-MM, YYYY-MM-DD

death.json
- [x] `time_of_death`: YYYY, YYYY-MM, YYYY-MM-DD, date-time

specimen_from_organism.json
- [x] `collection_time`: YYYY, YYYY-MM, YYYY-MM-DD, date-time

purchased_reagents.json
- [x] `expiry_date`: YYYY, YYYY-MM, YYYY-MM-DD

analysis_process.json*
- [x] `start_time`: date-time
- [x] `stop_time`: date-time
- [x] `timestamp_start_utc`: date-time
- [x] `timestamp_stop_utc`: date-time

provenance.json*
- [x] `submission_date`: date-time
- [x] `update_date`: date-time

*Fields in analysis_process.json and provenance.json schema are programmatically derived/entered, so these might be OK staying as strict `date-time` format. All other fields listed are supplied by data contributors and are at risk of being submitted as partial values.

**What new field(s) need to be changed/added?**

No new fields.

**Why is the change requested?**

For an example dataset given to us with time_of_death information, only the death year-month was recorded and thus a dummy "00T00:00:00Z" bit had to be added to the end of the date to be valid against the JSON date-time format. Expecting users to do this is not appropriate and might not fit the ethical standards for the data.

collection_time might also have some ethical restrictions in cases where a specimen was collected from a dead donor, and the specimen collection_time was recorded (thus potentially identifying the donor).

For date_established, we want to be sure that we are expecting a date if the word "date" is in the field name and a time if the word "time" is in the field name.

Replaces https://github.com/HumanCellAtlas/metadata-schema/issues/539

**Comment by malloryfreeberg** [comment]
@daniwelter @zperova @hewgreen @ESapenaVentura @willrockout @cjvillar @pnejad What do you all think of this change? Especially @willrockout in regards to your recent start/end time PR (https://github.com/HumanCellAtlas/metadata-schema/pull/962)

**Comment by ESapenaVentura** [comment]
I am all onboard with the idea of a reduced date! 

Maybe I'm being a little picky, but are we restricting reduced dates to the format "year-month"? Should we also consider other dates? (e.g., year-month-day, just year, or even year-month-day-hour). And, in case we accept more, we should also try to impose a limit on these, or we'll end up with either a long RegEx (In case we squeeze all in one pattern) or a long list (In case we add one pattern per case use). That's also another thing to discuss, the way we would implement more use cases.

What do you guys think?

**Comment by cjvillar** [comment]
Idk, if we should accept more (month/day/year) it would be convenient but the devs might hate us.

**Comment by daniwelter** [comment]
I don't think we should necessarily use the same pattern for all of the affected fields. Different fields have different requirements and this should be reflected in the regex pattern. The general approach of oneOf applies to all the schemas though. It should even be possible to use more than 2 options with oneOf.

**Comment by zperova** [comment]
I agree with @daniwelter that we should not limit ourselves to one regex pattern as different fields have different requirements.

**Comment by malloryfreeberg** [comment]
@ESapenaVentura @cjvillar @daniwelter @zperova 

I updated the ticket with possible valid values (either a regex format or a JSON type) for each field. Thoughts?

**Comment by ESapenaVentura** [comment]
@malloryfreeberg LGTM!

**Comment by malloryfreeberg** [comment]
The following pattern is in correct JSON regex format and also allows slashes (/) in dates:

`^((19|20)\\d\\d){1}([- \\./][01]\\d){0,1}([- \\./][0-3]\\d){0,1}$`
