### ISSUE TITLE
Ensure we capture ATAC-Seq metadata

### ISSUE THREAD

**Issue by ESapenaVentura** [HumanCellAtlas/metadata-schema#973]
Since we are probably getting ATAC-Seq data in the future, we need to be sure that we are able to capture metadata for this experiments.

Understanding metadata requirements:

- [x] Present the technique to the team. There are some notes [here](https://docs.google.com/document/d/1dL8zo3ORjXG-eckR-0Kk4vSZokeODP2PsC3yV3sATVw/edit#heading=h.gjdgxs)
- [x] Gather information from the pipelines team (Meeting this Thursday with Nick Barkas)
- [ ] Try to get data / metadata (In progress)

Once this is all done, which should be easy to get for this sprint (Except for the data, ~~that should wait until re-ingestion~~ that is going to take a while, since the 2 possible datasets in ArrayExpress are invalid for the DCP), the next requirement will be to create the necessary tickets to make sure our schemas can collect the essential data.

The pipeline team (Represented by Nick Barkas) suggest that no additional metadata field is required for the pipeline implementation. Nonetheless, they asked about a conditional validation on the json schema, as this technique is pretty wide (It's actually a set of techniques that only share the transposition with Tn5). Depending on the approach used, there might be some needs (e.g., with 10x the barcoding is pretty standard, but might need a list of barcodes for "custom" approaches or other experiments). As so, it was proposed that there is some kind of "conditional validation" that checks which kind of ATAQ-Seq data we're getting. Last request was for us to discuss on what kind of ATAQ-Seq data are we going to get in the future.

- [ ] Propose metadata schema changes

Edit 14/05: Added information about meeting with Nick Barkas
Edit 17/05: Added metadata gathering updates

**Comment by ESapenaVentura** [comment]
@malloryfreeberg @zperova @daniwelter Everything alright?

**Comment by malloryfreeberg** [comment]
Looks good!

When you discuss with Nick, it would be good to think of requirements both from the data processing pipelines perspective but also from the tertiary analysis perspective.

**Comment by ESapenaVentura** [comment]
Closing it until we get ATAC-Seq data

**Comment by ESapenaVentura** [comment]
When we prioritise this we should take a look at https://docs.google.com/document/d/1VG7jxwhpKyRQGcyVz1BfudGaOPcAB5NC868FzFLeVBM/edit#heading=h.gjdgxs

(HTAN metadata for ATAC-Seq)
