### ISSUE TITLE
Support for inDrop data

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/metadata-schema#979]
This Epic will track tickets related to supporting inDrop data.

**Comment by malloryfreeberg** [comment]
From @barkasn
There is currently an inDrop dataset in the dss, but there is no information on which version of the inDrop protocol was used. Is there a way to find this out? Also, how do you capture information about the inDrop protocol, and any customizations, in the metadata?

From @malloryfreeberg
Regarding inDrop version information, we don't separately capture version information for any protocols right now in the metadata. There are a few potential solutions for this. 1) We add a new `protocol_version` field (or similar) to capture this value (for inDrop and all techs). 2) We expand the ontology for the `library_construction_approach` field and add explicit inDrop+version ontology terms (like we have a "10x v2 sequencing" term).

Any additional protocol information not explicitly modelled by the metadata can optionally be captured via a DOI to a published paper about the protocol, a protocols.io DOI, or an uploaded protocol document (e.g. PDF). We don’t currently capture customizations in a _structured_ way, although we have a free text `deviation_from_protocol` field in the `process.json` schema that can be used to record customizations.

https://github.com/HumanCellAtlas/metadata-schema/blob/ec5f13c8278be46d2ac943ee43bf5f360eb54c01/json_schema/type/process/process.json#L63-L68

It would be great to get a list of requirements for processing inDrop data. Is this something that is currently being worked on by the pipelines team? I can make a schema repo ticket about supporting inDrop data.

I believe @pnejad wrangled the current inDrop dataset in the DSS, so she might be able to reach back out to the lab to get additional inDrop version info

From @barkasn
Thank you for your detailed answer. I'm currently scoping the required changes for inDrop, prioritization will depend on the amount of data coming and level of challenge. The inDrop protocol is really a collection of protocols, at least 3 of which are semi-standardized in terms of read structure (V1,V2,V3). I say semi-standardized because there might be different variants of V3 (tbc). It is critical to know what type of data the experimenters are submitting so that we can process it correctly.
happy to talk if it will help with clarifying the requirements. The issue of semi-standardized protocols will come up over and over again because the same problem exists with many different data modalities

From @malloryfreeberg
Having a chat will be very helpful, perhaps on a metadata call? Is the main concern the barcodes being used? We do currently have fields to capture barcode information

From @barkasn 
The cell barcoding and the read structure is the concern as they can vary. Are you referring to cell barcodes or library barcodes in the metadata?

V1 V2 and V3 should be standardized (but also there might be some confusion in the community about which version is which), so we should provide some clarification to submitters so they know what the version they are submitting as mean in term of read structure (and can check they it matches their protocol).

From @malloryfreeberg 
We have 4 "barcode" fields (which read it’s in, the length of the barcode, the 0-based offset of start of barcode in read, and the name of a file containing legitimate barcode sequences). We can capture these 4 fields for both cell barcodes and UMI barcodes.

https://github.com/HumanCellAtlas/metadata-schema/blob/ec5f13c8278be46d2ac943ee43bf5f360eb54c01/json_schema/module/process/sequencing/barcode.json#L25-L60

We don’t explicitly capture library barcodes because we require contributors to already demux by library prior to giving us reads. Is this what you mean by structure? Indicating which read the barcode is in, the length of the barcode, and the position/offset?

From @barkasn
Yes that's exactly the type of information we want. However, it gets more complicated! Some protocols, inDrop included, have variable length barcodes which means that the second barcode starts after a fixed length linker sequence. Also in some cases the barcodes are drawn from a fixed pool of barcodes ('whitelist'). In some cases users may customize this list, or there will be no fixed list. In some protocols it gets even more complicated, with half the barcode (or umi) in one read and the other half in another. I think we should confine ourselves to scenarios where the protocols follow a set arrangement and no customizations are allowed, but keep in mind we may need a way to extend to customizations in the future.

**Comment by ESapenaVentura** [comment]
Ticket superseeded by https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/349
