### ISSUE TITLE
Add user_friendly name to provenance wherever it is used

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/metadata-schema#989]
Other modules have a user_friendly name where they are used but provenance does not. For example see cell_line.json

No user_friendly:
```
"provenance" : {
            "description": "Provenance information provided by the system.",
            "type": "object",
            "$ref": "system/provenance.json"
        },
```
has user friendly

```
biomaterial_core" : {
            "description": "Core biomaterial-level information.",
            "type": "object",
            "$ref": "core/biomaterial/biomaterial_core.json",
            "user_friendly": "Biomaterial core"
        },
```

When displaying the field in the types the data portal is looking for a user_friendly name and when it cant find one defaults to the field name which looks funny as its lower case.  Would be nice if we can just always have a user friendly for all fields in case they are displayed at some point.

**Comment by diekhans** [comment]
@NoopDog, if you want to make a pull request with suggested descriptions, that would short-circuit this boiling up to the top of someone's queue.

**Comment by malloryfreeberg** [comment]
@ESapenaVentura could you take this one for this sprint? Specifically, the following comes out of the linter:

```
provenance.json: Keyword `user_friendly` missing from property `submission_date`.
provenance.json: Keyword `user_friendly` missing from property `update_date`.
provenance.json: Keyword `user_friendly` missing from property `accession`.
provenance.json: Keyword `user_friendly` missing from property `submitter_id`.
provenance.json: Keyword `user_friendly` missing from property `document_id`.
provenance.json: Keyword `user_friendly` missing from property `updater_id`.
```

**Comment by ESapenaVentura** [comment]
Ok! 👍

**Comment by malloryfreeberg** [comment]
@NoopDog this should bubble up to master/prod in a few weeks.
