### ISSUE TITLE
Do a top-down review of metadata entity names and structure.

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/metadata-schema#994]
There appear to be some issues where the metadata entity names and/or structure is confusing and/or is a less than ideal model of the underlying data.  The goal of this ticket is to collect problems that need to be examined and then do a top-down, user-centric review of the metadata as a whole and propose changes if any are deemed important enough.

**Comment by diekhans** [comment]
Existing tickets:

- [Rename entity specimen_from_organism to body_part #389](https://github.com/HumanCellAtlas/metadata-schema/issues/389)
- [Rename entity donor_organism to donor or individual #386](https://github.com/HumanCellAtlas/metadata-schema/issues/386)

**Comment by zperova** [comment]
This is also related: https://github.com/HumanCellAtlas/metadata-schema/issues/991

**Comment by malloryfreeberg** [comment]
Let's make this an epic and formally link the tickets. Then we can link this epic to one of the DCP-wide epics for improving user understandability of the metadata (or something similar).

**Comment by ESapenaVentura** [comment]
@clairerye I think we can close most of these epics, but let me know if you think we need to retake some
