### ISSUE TITLE
Source file as missing for documentation images

### ISSUE THREAD

**Issue by diekhans** [HumanCellAtlas/metadata-schema#995]
There are no source files for the images in metadata-schema/docs/images/,
making it impossible to modify the images.  It would be good to get them in there before they are lost.

Also, line drawings are better as PNGs.  JPEG is designed for photographs.

**Comment by malloryfreeberg** [comment]
I can put the images in as png. I think those render in markdown, too. And I can put the omnigraffle files in, as well, but I don't know how many people are able to open omnigraffle files.

**Comment by diekhans** [comment]
yes, PNG works fine with markdown.

Having the source in a priority format is better than not having
it at all. All you to have is a friend that can open
it ;-)  Omnigraffle is really good.
