### ISSUE TITLE
Add project-level DOI field

### ISSUE THREAD

**Issue by lauraclarke** [HumanCellAtlas/metadata-schema#997]
The project needs a new optional field to store the project DOI. This DOI will be assigned by Biostudies

In future, this may become a required field but right now it is best to start as optional for a number of reasons

* Field name: biostudies_doi
* Field description: A DOI as assigned by the Biostudies database for this project
* Field type: string (not sure if this needs to be string or url)
* Required: no
* Examples: https://doi.org/10.6084/m9.figshare.8179490.v2

Note this example is from figshare so doesn't reflect what our DOIs will look

* CV or enum: no

This is needed as DOIs are going to be assigned to facilitate the citability of our datasets by providing permanent URLs which point to records about each HCA project and these DOIs need to be displayed in the data browser

**Comment by diekhans** [comment]
This is great. The DOIs are versioned, correct?

**Comment by lauraclarke** [comment]
We need to discuss with Biostudies about how they assign DOIs but that is certainly possible.

**Comment by diekhans** [comment]
Count me in to help with this.  I have made too many mistakes in the past
by losing versions...

**Comment by diekhans** [comment]
> We need to discuss with Biostudies about how they assign DOIs but that is certainly possible.

Another option is to assign a unique DOI per release version and no DOI on intermediate versions between release. We would fail on FAIR is we had a DOI that applied to multiple versions of a project.

**Comment by lauraclarke** [comment]
Looking at how both Figshare and Zenodo do DOIs as the group minting DOIs controls everything after the prefix you can have a main DOI which points to the most recent version and then versioned URLs which point to specific versions and this works out fine and is a pragmatic solution to remaining FAIR while enabling tracking of individual versions.

We should remember that most projects will never be updated and we shouldn't overthink a solution to a relatively rare problem

This is an example https://figshare.com/articles/Attraction_of_males_to_females_in_the_fourth_larval_stage_L4_or_as_adults/1597650

So 

https://doi.org/10.6084/m9.figshare.1597650.v2

points to the specific v2

https://doi.org/10.6084/m9.figshare.1597650

points to the main version

https://doi.org/10.6084/m9.figshare.1597650.v1

points to the old version

**Comment by diekhans** [comment]
This approach to versioning is idea., Striping off the version
gives you the canonical one is the way most bio-data versions
work.

I don't think this is overthinking; it is simple and straight
forward and doesn't require special cases if a project does
change.

**Comment by lauraclarke** [comment]
Sounds like we are in agreement then.

**Comment by malloryfreeberg** [comment]
So it sounds like we are all in agreement <3 about having a DOI.

I want to clarify that, although this DOI is being assigned by BioStudies, we probably don't need to indicate that in the field name. It also means that if in the future we move to a DOI that isn't supplied by  BioStudies, we won't have to change the field name. 

I also want to clarify whether we want the field to capture just the DOI (my vote) or a url. E.g. `10.6084/m9.figshare.8179490.v2` (DOI) versus `https://doi.org/10.6084/m9.figshare.8179490.v2` (url resolving the DOI). I vote for capturing just the DOI as it can later be formatted to be a url or copy/pasted into search engines etc.

Given the above, I propose the following:

* Field name: doi
* Field description: A DOI for this project
* Field type: string (with regex pattern)
* Required: no
* Examples: 10.6084/m9.figshare.8179490.v2; 10.6084/m9.figshare.8179490 (will need to get BioStudies examples here)
* CV or enum: no

What are everyone's thoughts @HumanCellAtlas/metadata-updates ?

**Comment by diekhans** [comment]
Absolutely; once a DOI  is assigned, how it is assigned is not relevant!

**Comment by malloryfreeberg** [comment]
@lauraclarke where could I lookup what Biostudies-minted DOIs look like? I don't actually see any DOIs in Biostudies entries, so I don't know what an example might look like.

**Comment by lauraclarke** [comment]
Sorry for not responding sooner but the reason I proposed BioStudies DOI was because this field would be specifically used for DOIs assigned by BioStudies. If HCA starts assigning their own DOIs then another field would be used just as another field is used for publication DOIs.

Can someone explain why a straight DOI field is better when there can be multiple sources of DOIs which resolve to multiple different locations

**Comment by malloryfreeberg** [comment]
In the case of the publication DOI, the reason that it is a separate field is that the DOI is pointing to a separate entity (pointing to a publication, not the dataset in the HCA). 

We don't need to worry about clashes of field names because the fully qualified field name for a publication doi is `project.publication.doi` and the proposed field here would be `project.doi`.

For published protocols, the DOI field is `protocol.protocol_core.publication_doi` and for protocols in protocols.io the DOI field is `protocol.protocol_core.publication_doi`. We need separate identifying fields for these two because 1) they exist in the same schema and 2) they point to different objects (one a publication and one an entry in protocols.io).

I don't think you need to know who assigned/generated the DOI in order to be able to resolve it. That information is contained in the DOI. For example, DOIs assigned to publications in Science (e.g. `10.1126/science.aax9181`) contain `science` in them. DOIs assigned to objects in Zenodo (e.g. `10.5281/zenodo.826906`) contain `zenodo` in them. 

If we think an HCA project might someday have more than 1 project/dataset-level DOI that points to the dataset (not a publication or protocol), then we could make this field an array. We risk being overmodeled, I think, if we make a separate field for DOIs that are generated by different sources. @lauraclarke are you happy for this field to be an array of DOIs to support the use case of there being more than 1 DOI assigned to the HCA dataset?

**Comment by ESapenaVentura** [comment]
> for protocols in protocols.io the DOI field is `protocol.protocol_core.publication_doi`

I think you're referring to `protocol.protocol_core.protocols_io_doi`

**Comment by zperova** [comment]
@lauraclarke Do we know when will Biostudies start assigning DOIs or who can provide some insight on that?

**Comment by malloryfreeberg** [comment]
Copying @lauraclarke 's comment from the PR: 

https://github.com/HumanCellAtlas/metadata-schema/pull/1013#issuecomment-500436431

So I would leave this ticket on hold for now as there is an open question if Biostudies is the right solution for DOI assignment being discussed between @morrisonnorman @theathorn and @briandoconnor. I suspect some UX research will be needed before an answer is reached.

Back to the original question. I specified biostudies_doi so there would be no surprise about the fact the DOI resolved to a biostudies location and not somewhere within the HCA web space just as we are specific about the publication DOI or the protocol DOI I would like to be specific about the biostudies DOI so there are no surprises for users

**Comment by malloryfreeberg** [comment]
From @diekhans 
> DOIs are intended to be globally unique and resolvable.  This is
achieved by registrant being the prefix of the DOI.  Specifying
the registrant in the field name is redundant.

> I also find it confusing, as DOIs themselves answer the question
of where it resolves.

> What type of resource a DOI resolves to is defined by the type
of record containing the DOI.  A publication doi should be in a
record about publications.  There is no need for redundant within
the field name.
